### ISSUE TITLE
Windows 10 : getting error while configuring detekt plugin

### ISSUE THREAD

**Issue by pravinsk21** [arturbosch/detekt#1019]
I am getting below error after running below command on Windows 10 : 

java -jar detekt-cli/build/libs/detekt-cli-1.0.0.RC8-all.jar -p /home/artur/Repos/detekt -c /home/artur/Repos/detekt/default-detekt-config.yml -f ".*/test/.*" --parallel

Error :
The following option is required: [--input | -i]
Usage: main class

Appreciate your help. Thanks

**Comment by schalkms** [comment]
You have to specify the input path which detekt should analyse for you.
Further information can be found under the cli usage section
https://arturbosch.github.io/detekt/cli.html

If you need further assistance feel free to reopen this issue.

**Comment by pravinsk21** [comment]
Thank You @schalkms. Can you please give one example ? it will be great help.

**Comment by schalkms** [comment]
Sure
-home/artur/repos/your_repo

Your_repo contains your Kotlin project/files

**Comment by pravinsk21** [comment]
Thanks. let me try out.

**Comment by pravinsk21** [comment]
Hi @schalkms. I am still getting same error.  basically I am trying to integrate detekt plugin to Sonarqube.

**Comment by schalkms** [comment]
There is a separate detekt plugin for sonarqube available.
https://github.com/arturbosch/sonar-kotlin/

**Comment by pravinsk21** [comment]
@schalkms. Thanks.
