### ISSUE TITLE
How to run "autoCorrect"

### ISSUE THREAD

**Issue by fabriciorissetto** [arturbosch/detekt#1021]
Hi, it may be a stupid question, but I'm not finding in documentation how to run the "autoCorrect" feature.

I already have the property `autoCorrect: true` in the config.yml file, and the file is being tracked by the command `gradle detektCheck` successfully. But it seems this command doesn't fix the issues. 

Am I missing something here? Thanks in advance.

**Comment by Mygod** [comment]
You missed the plugin. It confused the hell outta me too. Try `-p /path/to/detekt/detekt-formatting/build/libs/detekt-formatting-1.0.0.RC8.jar` or see #925.

**Comment by fabriciorissetto** [comment]
Thanks @Mygod :+1:  

I will describe what I did here, in case it can help someone else. 

### 1. Added detekt formatting plugin in my root `build.gradle`:
```
// ...

plugins {
    id "io.gitlab.arturbosch.detekt" version "1.0.0.RC8"
}

dependencies { 
    detekt "io.gitlab.arturbosch.detekt:detekt-formatting:$detektVersion"
}

detekt {
    version = "$detektVersion"
    defaultProfile {
        input = file("../")
        config = file("../detekt-config.yml")
        filters = ".*/resources/.*,.*/build/.*"
    }
}
```

### 2. Then just:
```shell
gradle detektCheck
```

**Comment by schalkms** [comment]
@Mygod thanks for helping out!
@arturbosch maybe this should be included in the documentation?
