### ISSUE TITLE
TooGenericExceptionCaught should not be reported if the name is ignored

### ISSUE THREAD

**Issue by vanniktech** [arturbosch/detekt#1056]
Catching an `Exception` is sometimes necessary. In cases it is named like `ignored` or `expected` it should not be flagged since the developer made an explicit decision about this.

I believe some rules are already honoring the names of accepted exception variable names. If not we should sync them and make it the default.

**Comment by schalkms** [comment]
True. The `EmptyCatchBlock` rule handles this case.
I'll start working on that tomorrow.
