### ISSUE TITLE
Forbid usage of Void

### ISSUE THREAD

**Issue by egor-n** [arturbosch/detekt#1058]
Detekt should warn about using [`Void`](https://docs.oracle.com/javase/7/docs/api/java/lang/Void.html) since Kotlin has [`Unit`](https://kotlinlang.org/api/latest/jvm/stdlib/kotlin/-unit/index.html) instead.

Although, maybe `java.lang.Void::class` should be allowed.

**Comment by schalkms** [comment]
Good point. This might be called `OptionalVoid` to be in line with the existing rule.

**Comment by egor-n** [comment]
I'll take a stab at it.

**Comment by schalkms** [comment]
@egor-n cool! You might want to take a look at #1034

**Comment by egor-n** [comment]
@schalkms I have opened #1059. I don't think this rule falls into the Optional* set. Usage of `Void` doesn't seem optional to me.

**Comment by schalkms** [comment]
I agree @egor-n
