### ISSUE TITLE
Juggling between `CollapsibleIfStatements` and `ComplexCondition`

### ISSUE THREAD

**Issue by xgouchet** [arturbosch/detekt#1063]
## Expected Behavior
I have a kotlin code lookin like this : 
```kotlin
    if (Fabric.isInitialized()) {
        if (this.isBadRequest()
                || this.isUnauthorized()
                || this.isForbidden()
                || messageRes == R.string.common_error_unknown) {
            Crashlytics.logException(this)
        }
    }
```

When I run **detekt**, I get a  `CollapsibleIfStatements`, which is normal I guess. But if I collapse the two if statements, I get a `ComplexCondition` : 

```kotlin
    if (Fabric.isInitialized()
            && (this.isBadRequest()
                    || this.isUnauthorized()
                    || this.isForbidden()
                    || messageRes == R.string.common_error_unknown)) {
        Crashlytics.logException(this)
    }
```

Is there a way to configure the `CollapsibleIfStatements` to understand that collapsing will conflict with another solution ? 

## Context
Right now, I'll stick to the first version, with a `@Suppress` to avoid this error, and I'd totally understand if this was too much of an edge case.

**Comment by schalkms** [comment]
I wouldn't worry about it. Supressing or ignoring is in this case fine. If possible you can refactor the condition, so that the warning disappears.

**Comment by vanniktech** [comment]
One could also extract those conditions into separate functions which then wouldn't trigger anything.
