### ISSUE TITLE
Unknown exception thrown when running detekt

### ISSUE THREAD

**Issue by pavlospt** [arturbosch/detekt#1064]
## Expected Behavior
Expected detekt to finish without any exceptions thrown

## Current Behavior
Currently when running detekt, after enabling a rule, not sure which one, we get the following exception stacktrace:
```java
Analyzing '/path/to/the/file.kt' led to an exception.
Running detekt 'unknown' on Java '1.8.0_131-b11' on OS 'Mac OS X'.
Please create an issue and report this exception.
java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:273)
java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:280)
java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1592)
java.util.concurrent.CompletableFuture$AsyncSupply.exec(CompletableFuture.java:1582)
java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)
```
The exception above is the result of enabling one of the latest rules we enabled, will probably do a `git bisect` to find which one, but I am reporting it in case you already know what is wrong so that I could resolve it sooner :D 

Before enabling that rule it was running without exxceptions being produced.

## Steps to Reproduce (for bugs)
Not sure on that one, I am still trying to figure out the exact repro flow.

## Context
We are incrementally enabling more and more detekt rules and one of those caused the above exception.

## Your Environment
* Version used: 1.0.0.RC8
* Operating System and version: macOS Sierra (10.12)
* Link to your project: It's a private project.

**Comment by pavlospt** [comment]
Update: I tried to manually disable every rule that we have introduced in the branch that it stopped working and had no luck. Also tried reverting to RC07-2 and it was not resolved either. LMK if I need to provide any more info!

**Comment by arturbosch** [comment]
Do you have to stau at a beta version of jdk8 ? -> '1.8.0_131-b11'.
In `detekt-core` we leverage the CompletableFuture Api from java which should be fine.
Maybe an error in beta version of jdku8. Can you upgrade and test with a recent jdk8 please?

**Comment by pavlospt** [comment]
I tried upgrading but the Java client did not show any available update for macOS. Is there another way to check that?

**Comment by pavlospt** [comment]
It keeps on crashing even o JDK 10.
```
Running detekt 'unknown' on Java '10.0.2+13' on OS 'Mac OS X'.
```

**Comment by arturbosch** [comment]
Just tested it with java 10u23-openjdk with sdkman. Worked.
Which rules have you enabled lately, which may cause this error?
Is this the whole stacktrace? Because it does not show any detekt related stack traces.

**Comment by pavlospt** [comment]
Unfortunately this is the only stacktrace. Also as I said before i tried disabling all rules after bumping to rc08 but did not work...will try some older rules to see if it is resolved.

**Comment by pavlospt** [comment]
### Update

So, I ran a `git bisect` to find the offending commit and ended up finding that it was when we enabled `LateinitUsage` rule. But just disabling it was not enough. I noticed that turning `active: false` instead of true would still cause a crash on some files. 

The thing though was that we have modified the rest of `LateinitUsage` rule's properties like the following: 

```
LateinitUsage:
    active: false
    excludeAnnotatedProperties: ""
    ignoreOnClassesPattern: "*Fragment"
```
After removing `*Fragment` I found that it was no longer crashing. I am not sure why it would crash when it is disabled, but will definitely do a check on the code of that rule and let you know if I find something.

**Comment by arturbosch** [comment]
Wow, that's actually scary :D. We create every rule upfront, filter the active ones and throw inactive ones away. Therefore we also initialize everything... 
The design decision is here:
```kotlin
interface RuleSetProvider {
    	fun instance(config: Config): RuleSet
}
```
Every provider creates it's own `RuleSet` and inits all rules.
Every `Rule` must have an ID which is used for filtering and which is created on object construction.

1. solution would be to lazily instantiate all rules by kind of static ids and reflection or factory methods with a DI framework -> much rework, idk if it is worth it as our "garbage" creation is cheap + a detekt run does not live long
or 2. solution create a `by regex` delegation function which lazily instantiates and evaluates regexes. This could be a function inside the `Rule` class.

**Comment by pavlospt** [comment]
@arturbosch solution number 2 sounds a lot more easy to remember and use :)

**Comment by pavlospt** [comment]
@arturbosch shall this be closed once a release containing the fix is out?

**Comment by pavlospt** [comment]
I am closing this issue since the fix has been merged into `master`. :)
