### ISSUE TITLE
visit(root: KtFile) should be effectively final 

### ISSUE THREAD

**Issue by arturbosch** [arturbosch/detekt#107]
When overriding this method in a custom rule the ifActive gets abandoned.

**Comment by Mauin** [comment]
The current state in #196 introduces `visit(root: KtFile)` and `visitFile(root: KtFile)`. The `visitFile` method contains the `ifActive` check and cannot be overridden. Only the `visit` method can be overridden which then contains the custom rule logic.

**Comment by arturbosch** [comment]
Make sure to mark this issue as closed in the PR later :)
