### ISSUE TITLE
Search is not working on website

### ISSUE THREAD

**Issue by bagage** [arturbosch/detekt#1077]
## Expected Behavior
When searching `ImportOrdering` it should return https://arturbosch.github.io/detekt/formatting.html#importordering

## Current Behavior
When searching `ImportOrdering` on website, it says `No results found.` 

![image](https://user-images.githubusercontent.com/1451988/44907665-01283500-ad19-11e8-8a69-faf35614874e.png)

## Steps to Reproduce (for bugs)
1. Go to https://arturbosch.github.io/detekt
2. In top right searchbar, type `ImportOrdering`

## Context
Trying to tweak my configuration file by searching what rules are for. Have to search them on github for now.

ps: it would also be great if you could add website URL directly in github project description, eg here:

![image](https://user-images.githubusercontent.com/1451988/44907777-6845e980-ad19-11e8-9c31-4f2d87b8e719.png)

For instance: 

![image](https://user-images.githubusercontent.com/1451988/44907788-73991500-ad19-11e8-94ea-78cc52efc718.png)

**Comment by schalkms** [comment]
I also stumbled upon this one. It's bizarre that there's no full text search on the website.
Is there anything we could do about this one?

**Comment by arturbosch** [comment]
I'm no frontend guy, so picking up a jekyll template was the easiest part. Dunno actually.
I think the search works with `tag`s so adding a tag for each rule could be a quick hack for this :/

**Comment by schalkms** [comment]
@arturbosch I researched a bit. It looks to me that Jekyll doesn't support a full text search without any plugins or scripts. Google yields some information when searching for this information.
As a result I'll close this. It's faster to search after a rule with Google, since the indices for the homepage work very well.
