### ISSUE TITLE
Suppress for TooManyFunctions is not considered in detekt

### ISSUE THREAD

**Issue by xMickeymikex** [arturbosch/detekt#108]
Hey,

I have recently encountered a problem with Suppress annotation for TooManyFunctions, as i cannot apply it to any class. 

Example:

`@Suppress("TooManyFunctions")`
`interface Example {`
`    .`
`    .`
`    .`
`    fun manyFunctions()`
`}`

**Comment by arturbosch** [comment]
Your right, will fix this for M12, thx!

As a workaround you can use `@file:Suppress("TooManyFunctions")`.
