### ISSUE TITLE
Cases files are super rigorous to work with

### ISSUE THREAD

**Issue by vanniktech** [arturbosch/detekt#1089]
It's so hard to read the unit tests. I'm opening one and need to tangle my way down on so many files without proper IDE support.

```kotlin
val path = Case.UnnecessaryAbstractClassPositive.path()
val findings = subject.lint(path)
```

I can click on `UnnecessaryAbstractClassPositive` which is fine. Then I'm seeing okay I need to go there `/cases/UnnecessaryAbstractClassPositive.kt`. This I can't click with the IDE and need to manually go down.

To make things worse there are two `UnnecessaryAbstractClassPositive.kt` classes.

```
./detekt-rules/src/test/resources/cases/UnnecessaryAbstractClassPositive.kt
./detekt-rules/build/resources/test/cases/UnnecessaryAbstractClassPositive.kt
```

Luckily they are the same though. By the time I'm at the case file I've already lost what I wanted to look up.

Even worse is the fact that a single unit test often checks everything. Some are split up between Positive and Negative although it does not make much of a difference.

Some of the Postive files then help themselves with comments like `// violation: no abstract members`. I don't know whether I can rely on them or not since sometimes they are present sometimes not and I would not expect them to be updated when tweaking a rule. Those things slip understandably in PR reviews.

What I propose instead is to have everything in one file and only one violation being tested at a time. With Android Lint this looks like this:

```kotlin
lint()
    .files(xml("res/layout/ids.xml", """
      <TextView
          xmlns:android="http://schemas.android.com/apk/res/android"
          android:paddingTop="16dp"
          android:paddingBottom="16dp"
          android:paddingStart="16dp"
          android:paddingEnd="16dp"/>""").indented())
    .issues(ISSUE_SUPERFLUOUS_PADDING_DECLARATION)
    .run()
    .expect("""
      |res/layout/ids.xml:1: Warning: Should be using padding instead. [SuperfluousPaddingDeclaration]
      |<TextView
      |^
      |0 errors, 1 warnings""".trimMargin())
```

or 

```kotlin
lint()
    .files(xml("res/layout/ids.xml", """
      <TextView
          xmlns:android="http://schemas.android.com/apk/res/android"
          android:paddingTop="8dp"
          android:paddingBottom="16dp"
          android:paddingStart="16dp"
          android:paddingEnd="16dp"/>""").indented())
    .issues(ISSUE_SUPERFLUOUS_PADDING_DECLARATION)
    .run()
    .expectClean()
```

It's a bit more verbose and we probably don't need a full testing support like there is in Lint. However, it's very clear why and where things are failing and you have everything inside your Junit4 `@Test` method or in your `it` when using Spek.

Bonus points are:

- That we can probably find a way to test out where exactly it's being reported (either by using `^` or `~~~~~~` for longer flags.
- We can also assert our error messages. We had a lot of typos there in the past.
- Tests get decoupled and we can give them better descriptions
- It's easier for everyone to read the tests and adjust it for future changes
- Proper IDE support

**Comment by vanniktech** [comment]
Also for `MaxLineLength` there are two files. One being the case and the other being the actual rule where it's implemented. This is confusing too.

**Comment by schalkms** [comment]
There has been a discussion in another issue about this. I agree that the next steps should be to test exactly 1 violation in 1 test case. Moving the test cases into a separate .kt file was IMHO the right decision, because there were syntactical and semantic issues with test code. (e.g. code was invalid Kotlin code and thus not compiling at all). Splitting the test code in positive and negative cases was necessary to prevent flagging valid code while still reporting the right number of violations. After testing just 1 thing this does no longer apply.
I don't like to have all test code contained in Kotlin strings. Kotlin's String capabilities are good, but do not prevent the developer from writing invalid source code, which I think is the biggest disadvantage with this approach.
As I see it there is room for improvement regarding test descriptions. Your approach would improve that for sure.

**Comment by schalkms** [comment]
> Can't we use the @LANGUAGE("kotlin") annotation construct? That should highlight Kotlin code.

Of course. However, this only provides syntax highlighting in IntelliJ only. The code should be compiled by the Kotlin compiler and verified. In Java this is possible with the [Java Compiler API](http://docs.oracle.com/javase/8/docs/api/javax/tools/JavaCompiler.html)
