### ISSUE TITLE
Renaming rule names for 1.0.0

### ISSUE THREAD

**Issue by arturbosch** [arturbosch/detekt#109]
Tell me your renaming suggestions!!

So far renamed:
- NoDocOverPublicClass -> UndocumentedPublicClass
- NoDocOverPublicMethod -> UndocumentedPublicFunction

**Comment by Mauin** [comment]
Hasn't this already been done with the commits above?

**Comment by arturbosch** [comment]
Just for two rules. I want finalize all rule names for 1.0.0 ^^

**Comment by vanniktech** [comment]
Also one potential candidate for a rename is the property `values` in `ForbiddenComment`.

**Comment by arturbosch** [comment]
- CommentOverPrivateMethod -> DocumentedPrivateFunction
- CommentOverPrivateClass -> DocumentedPrivateProperty

**Comment by andrejp88** [comment]
`exceptions` in `TooGenericExceptionCaught` and `TooGenericExceptionThrown` confused me a bit at first (are they the names of forbidden exceptions, or are they exceptions to the rule (i.e. not forbidden)?). Maybe renaming it to `throwable` or something similar would make it clearer.

**Comment by arturbosch** [comment]
No more renaming suggestions so closing this.
