### ISSUE TITLE
Issue descriptions for each rule (also displayed in `Detekt way` - sonar plugin)

### ISSUE THREAD

**Issue by arturbosch** [arturbosch/detekt#110]

**Comment by Mauin** [comment]
Does this reference adding some meaningful description to each `Issue` where right now mostly empty Strings are passed?

**Comment by arturbosch** [comment]
Yes exactly that. This, more documentation and windows support are missing for the release candidate phase :)

**Comment by Mauin** [comment]
I started yesterday adding some basic descriptions to some of the rules. I might continue this evening and push them as one PR if that's okay for you? I can also create a first PR for only some of them and open a later PR for the rest.

**Comment by arturbosch** [comment]
That's awesome! Yeah, I would prefer smaller PR's so we can check the descriptions for each rule set individually?

I'm trying to fix the last sonar issue I'm having -> saving the findings ... No one at Stackoverflow or Sonar google groups seems now something about (no answers) ... :( ... after that the descriptions are next priority :)

**Comment by arturbosch** [comment]
@Mauin there is your description! ;)

![sonar-descriptions](https://user-images.githubusercontent.com/20924106/27639846-cda18f22-5c17-11e7-8020-b40d8a4208e2.png)

**Comment by arturbosch** [comment]
I will close this for now. The sonar-plugin users (me :D) will tell us if something needs a rework %%
