### ISSUE TITLE
Rename plain report to txt report

### ISSUE THREAD

**Issue by vanniktech** [arturbosch/detekt#1111]
Makes more sense to use `txt` so it's symmetric with the file ending. `xml` and `html`.

**Comment by vanniktech** [comment]
Got the lucky number here!

**Comment by arturbosch** [comment]
Yes and maybe rework it so the parts are separated with \s and are easier parsable for whoever wants to do it ^^

**Comment by arturbosch** [comment]
Rebased and merged this manually, thanks!
