### ISSUE TITLE
CliArgs Documentation improvements examples

### ISSUE THREAD

**Issue by vanniktech** [arturbosch/detekt#1113]
The documentation for https://github.com/arturbosch/detekt/blob/master/detekt-cli/src/main/kotlin/io/gitlab/arturbosch/detekt/cli/CliArgs.kt isn't really that great.

Especially for the `--report`  argument as it talks about `report-id` but it's not defined what types of reports are supported.

**Comment by 3flex** [comment]
Is this fixed with #1225? If not what else needs updating?

**Comment by vanniktech** [comment]
Yup. For some reason issues like this never get closed when the PR is merged.
