### ISSUE TITLE
MagicNumber regression with RC9 in Annotation methods

### ISSUE THREAD

**Issue by vanniktech** [arturbosch/detekt#1115]
The following code gets flagged with RC9:

```kotlin
@JvmStatic fun setCustomDimension(@IntRange(from = 0, to = 19) index: Int, value: String?) {
```

The `19` is the problem here although it should not since it's using an annotation method as a reference point.

**Comment by arturbosch** [comment]
Are you sure you set `"ignoreNamedArgument" to "true"`?
I've added this test case and it gets only flagged if the ignore property is not set.

**Comment by vanniktech** [comment]
I'm using failFast and nothing else. I'm surprised the behavior changed between the rcs though. Shouldn't `ignoreNamedArgument` be set to true as a default anyways?

**Comment by vanniktech** [comment]
No worries. Can we just go to `RC10` instead of `RC9.2`? Doing semantic version checks is already hard with Detekt versioning and the `.2` just makes it worse.

**Comment by vanniktech** [comment]
Argh. I was too late.

**Comment by arturbosch** [comment]
:D oh noes :X
