### ISSUE TITLE
Documented version not available in gradle plugins

### ISSUE THREAD

**Issue by thadcodes** [arturbosch/detekt#1117]
It looks like all the documentation on the site is for the new API with RC9, but the only versions available on https://plugins.gradle.org/plugin/io.gitlab.arturbosch.detekt are M8 and below.  It does have a beta-5 but I can't seem to find anything if those two are the same.  Is this pending/planned to be published or intentional?

**Comment by Mauin** [comment]
It does seem like RC9 did not get published to the Gradle Plugin portal correctly. @arturbosch can you take a look?

**Comment by arturbosch** [comment]
Ups, now it should be up and usable :).

**Comment by thadcodes** [comment]
It looks like it's directing to the wrong URL for download of RC9.  It's directing to https://repo.jfrog.org/artifactory/libs-release-bintray/io/gitlab/arturbosch/detekt/io.gitlab.arturbosch.detekt.gradle.plugin/1.0.0.RC9/io.gitlab.arturbosch.detekt.gradle.plugin-1.0.0.RC9.jar?referrer which 404s, when it looks like it's really supposed to be hosted at https://repo.jfrog.org/artifactory/libs-release-bintray/io/gitlab/arturbosch/detekt/detekt-gradle-plugin/1.0.0.RC9/detekt-gradle-plugin-1.0.0.RC9.jar  Is it possible there was an error in how it posted up to the gradle plugin repo?

**Comment by arturbosch** [comment]
Where does the first link come from? Within gradle build scripts RC9 gets resolved

**Comment by thadcodes** [comment]
I'm not sure, I've not been able to reproduce it since so it maybe was a bug that was resolved somewhere
