### ISSUE TITLE
FunctionNaming should exclude overridden functions

### ISSUE THREAD

**Issue by scottkennedy** [arturbosch/detekt#1120]
## Expected Behavior
If I override a function, it should not trigger a naming warning, because I have no control over the name.

## Current Behavior
It triggers the rule and prints a warning.

**Comment by arturbosch** [comment]
I think this should be configurable via property and also apply to PropertyNaming.

**Comment by Mauin** [comment]
Good point. This could either be a configuration option that is enabled by default or it could just be encoded into the rule itself that we always ignore overridden functions.

**Comment by schalkms** [comment]
I agree with @Mauin that this should be the default behavior.
