### ISSUE TITLE
HTML report created at the wrong place

### ISSUE THREAD

**Issue by Tolriq** [arturbosch/detekt#1123]
RC9 / Windows 10 / Gradle 4.10.1

```
subprojects {
    apply plugin: 'io.gitlab.arturbosch.detekt'
    detekt {
        reports {
             html.enabled = true
        }
     }
}
```

Will create the html reports as "D" at the root of each module.
But will correctly create the detekt folder at build/reports/detekt

adding a destination for example:
```
destination = file("build/reports/failfast.html")
```

Does not change the behavior and the D files are still created (but no more the folder in reports)

**Comment by marschwar** [comment]
That is very weird. Could you please enable debug, rerun the task and provide the logged call of the cli. What do you mean with `"D"`? Is that the name of the html file?

```
	detekt {
		debug = true
	}
```

**Comment by Tolriq** [comment]
[--input, D:\_Gradle\xxx\xxx\src\main\java, --filters, .*/resources/.*,.*/build/.*, --config, D:\_Gradle\xxx\detek
t-config.yml, --report, html:D:\_Gradle\xxx\xxx\build\reports\detekt\detekt.html, --debug]

The file is named D :)

But D is the drive now that I see the command like I guess using : as a separator is an issue. Should probably add "" around the path to avoid the issue

Pretty sure https://github.com/arturbosch/detekt/issues/1141 is the same issue but the guy have the code on C: :)

**Comment by schalkms** [comment]
Thanks for investigating this, guys! This looks like a duplicate then.
