### ISSUE TITLE
Sample / demo code?

### ISSUE THREAD

**Issue by bagage** [arturbosch/detekt#1140]
## Context

I'm trying to migrate my application from detekt RC8 to RC9, but `detektCheck` is gone in flavor of incremental build system and it seems it doesn't run at all on my setup. I'm not familiar with gradle, so I don't know where to look at yet.

It'd be great IMO to have a simple hello world application (with error in it? ;)), on a separate repository (KISS), with detekt already configured, so one can test detekt and/or compare a working example with a real application to figure out what the problem(s) is(are).

For instance I struggled some time figuring out that gradle must be upgraded as well (even if this was fixed in #1136).

**Comment by schalkms** [comment]
Thanks for your feedback. I like the idea. I also think a simple hello world project would be beneficial for detekt's users.
There is a migration guide specially for RC9 which also shows some demo code [here](https://arturbosch.github.io/detekt/changelog.html#rc9). This might help you to get started.

**Comment by bagage** [comment]
Hey @schalkms, indeed the migration guide has useful information in it but I still had some issues and miscomprehension that I finally managed to fix.

Mainly: **detektCheck** is replaced by **detekt**, it is not run automatically with **build** task as I thought it would. I did not see mention of this in migration guide though neither Readme. Everything works well now! Awesome incremental build!

**Comment by schalkms** [comment]
Thanks for the encouraging feedback! Your suggestions will be addressed in the upcoming releases. I'm closing this for now. If you have any further questions please open a new issue.

**Comment by arturbosch** [comment]
Should we reopen this and actually create some sample projects, one for each gradle build type and one for the maven plugin https://github.com/Ozsie/detekt-maven-plugin ?
