### ISSUE TITLE
Referring to custom detekt.yml config results in InvalidPathExceptionon Windows

### ISSUE THREAD

**Issue by sschuberth** [arturbosch/detekt#115]
As started to discuss [here](https://github.com/arturbosch/detekt/issues/104#issuecomment-310600920), M12 results in

```
:detektCheckException in thread "main" java.nio.file.InvalidPathException: Illegal char <:> at index 51:
C:\Users\sebastian\Development\project\detekt.yml,C:\Users\sebastian\Development\project\detekt.yml
```

when using

```
detekt {
    profile('main') {
        config = "${new File(project.projectDir, "detekt.yml")}"
    }
}
```

on Windows.

**Comment by arturbosch** [comment]
Appveyor up and running. Resolved all Path problems. detekt is now buildable on Windows. The cli still has some trouble with paths in the parameters. Will keep you updated!

**Comment by arturbosch** [comment]
M12.2 is up, tell me if it works now for you :)

**Comment by sschuberth** [comment]
Does not work :-( I get

```
:detektCheck
The following option is required: [--project | -p]

Usage: detekt [options]
  Options:
    --baseline, -b
      Treats current analysis findings as a smell baseline for further detekt
      runs. If a baseline xml file exists, only new code smells not in the
      baseline are printed in the console.
      Default: false
...
```

**Comment by arturbosch** [comment]
Did you use `input = project.projectDir` or something?

```
detekt {
    profile('main') {
        config = "${new File(project.projectDir, "detekt.yml")}"
    }
}
```
Profiles now need the input parameter. The fallbackProfile has the default input configured

**Comment by arturbosch** [comment]
Basically detekt says that `--project` is missing which is `input` in gradle ... and yeah naming sucks :O

**Comment by sschuberth** [comment]
> Did you use `input = project.projectDir` or something?

No, I didn't, mainly because it is said that [input is pre configured to 'project.projectDir.absolutePath'](https://github.com/arturbosch/detekt#closure). But even after setting `input` like in the example to `input = "$input/src/main/kotlin"` I get

```
:detektCheck
Provided path 'null/src/main/kotlin' does not exist!

Usage: detekt [options]
  Options:
    --baseline, -b
...
```

What finally did work is to be explicit and use `input = "${project.projectDir}/src/main/kotlin"` like you suggested in your comment.

So, bottom line, this particular issue is fixed, so I'll close it. Thanks!

**Comment by arturbosch** [comment]
Just for documentation: `"${project.projectDir}/src/main/kotlin"` is the way to go, the `new File..`-stuff was an idea how it maybe could work ^^
