### ISSUE TITLE
Make `config` property in `Rule` effectively private

### ISSUE THREAD

**Issue by Mauin** [arturbosch/detekt#1153]
As `config` is usable in every single `Rule` class due to it being protected it is easy to use it directly, which can lead to issues similar to the one described in #1122.

`config` should be effectively private or at least very hard to use compared to the `valueOrDefault`/`valueOrNull` functions defined in `ConfigAware` to prevent similar issues in the future.

**Comment by arturbosch** [comment]
I will rename the property to `ruleSetConfig`. We can't make interface properties private or internal unfortunately.
