### ISSUE TITLE
In Travis CI: "0 kotlin files were analyzed."

### ISSUE THREAD

**Issue by 3flex** [arturbosch/detekt#1158]
## Expected Behavior
detekt Gradle plugin analyzes files during CI.

## Current Behavior
detekt Gradle plugin does not analyze any files during CI.

## Steps to Reproduce (for bugs)
View the Travis build log for master branch (https://travis-ci.org/arturbosch/detekt/jobs/432263468 at time of writing). See "0 kotlin files were analyzed." multiple times in the logs.

## Context
N/A

## Your Environment
N/A - build running in CI environment

**Comment by 3flex** [comment]
On closer inspection, looks like this is on Travis only, not AppVeyor... may be a *nix vs Windows issue with detekt itself?

**Comment by Mauin** [comment]
Just to clarify: This does not just affect `master` builds but pretty much every build on travis it seems. I cannot repro this locally.

**Comment by 3flex** [comment]
Simple when you know what to look for...

The filters set when Travis build runs is include `.*/build/*.`. Travis checks out the build at `/home/travis/build/arturbosch/detekt`. Since `/build/` is in the full file path, all Kotlin files under the project path are filtered out, so nothing gets scanned.

I'd say the root cause is that though the detekt is run from working directory `/home/travis/build/arturbosch/detekt`, and expectation is that it's filtering based on the relative path in that working directory it's actually filtering the absolute file path.

**Comment by Mauin** [comment]
Oh. Right... You want to submit a fix for this? 
Probably simply changing it to `detekt/.*/build/.*` or similar

**Comment by 3flex** [comment]
Can do for Travis, yeah. But I'm also going to open a new issue to see if behaviour should change - I'm surprised that it's not just the relative path where the filter applies.

**Comment by Mauin** [comment]
True, that would be the overall better fix for it. Which makes me wonder. Did _we_ change this behavior at some point? (absolute vs relative path considered for excluding paths)

Or did Travis change the directory projects get cloned into...?

**Comment by 3flex** [comment]
Do you want to close this in favour of a proper fix for #1212, or implement a workaround?

I'm inclined to close this since root cause is identified and an issue opened to track the issue. AppVeyor appears to run detekt just fine as part of the build so any non-compliant code will still fail CI.

**Comment by Mauin** [comment]
👍 Thanks for opening the concrete issue. We should definitely fix this properly.
