### ISSUE TITLE
Gradle Plugin Portal "latest" version incorrect

### ISSUE THREAD

**Issue by 3flex** [arturbosch/detekt#1159]
## Expected Behavior
Visting https://plugins.gradle.org/plugin/io.gitlab.arturbosch.detekt will show `1.0.0.RC9.2`, released September 23, 2018 as being latest version.

## Current Behavior
Visting https://plugins.gradle.org/plugin/io.gitlab.arturbosch.detekt shows `1.0.0-rework-beta5`, September 8, 2018 as being latest version.

## Steps to Reproduce (for bugs)
See above.

## Context
The plugin portal should show the latest released version number as the "latest" release.

This has happened because "rc" and "rework" are both considered "qualifiers" for version releases. "rc" is a recognized qualifier and "rework" is an unrecognized qualifier. Unrecognized qualifiers are considered after recognized qualifiers, so as far as Gradle Plugin Portal is concerned the "rework" versions have a higher version than the "rc" versions, so they will always appear as the latest versions.

Due to version ordering rules in Maven repositories this also means the "1.0.0-rework" versions will be considered a higher version than "1.0.0", so options are either to take down any published "rework" versions, or have "1.0.1" be the first "final" version.

## Your Environment
N/A

**Comment by arturbosch** [comment]
Thanks for the issue analysis, I wrote to the gradle support team to get the `rework-beta` versions removed.

**Comment by 3flex** [comment]
That was quick - the rework versions have been taken down.
