### ISSUE TITLE
SNAPSHOT builds don't appear on Bintray

### ISSUE THREAD

**Issue by 3flex** [arturbosch/detekt#1160]
## Expected Behavior
Since #1088 was merged, expect that SNAPSHOT releases are pushed to Bintray.

## Current Behavior
SNAPSHOT releases not published anywhere. Viewing https://bintray.com/arturbosch/code-analysis/detekt only shows the versions that were specifically tagged.

## Steps to Reproduce (for bugs)
See above.

## Context
SNAPSHOT releases make it easy to test the latest build from master branch.

Bintray may not actually support SNAPSHOT releases, according to https://github.com/bintray/gradle-bintray-plugin/issues/191

Instead, should publish snapshots to [Jfrog's Artifactory](https://jfrog.com/artifactory/) or Sonatype's snapshots repository or similar.

## Your Environment
N/A

**Comment by CristianGM** [comment]
`/home/travis/.travis/job_stages: line 104: .buildscript/deploy_snapshot.sh: Permission denied`

**Comment by vanniktech** [comment]
Also nothing on Sonatype. https://oss.sonatype.org/content/repositories/snapshots/io/gitlab/arturbosch/detekt/detekt-cli/

**Comment by lskillen** [comment]
@3flex @arturbosch Hey, please feel free to consider [Cloudsmith](https://cloudsmith.io) for snapshot releases. :-)

It's commercial, but offers generous free tiers and is also completely free for open-source (with 100GB of storage, and 1TB of bandwidth). Snapshots are fully supported for the Maven-style repositories, so you could dual release; JCenter/OSSRH for stable releases, and Cloudsmith for snapshots. Worth considering.

*Full disclosure*: I work for Cloudsmith and may be biased (but only very _slightly_, honest!)

**Comment by schalkms** [comment]
Is this still relevant in version 1.0.0?
