### ISSUE TITLE
Detekt Gradle Plugin Configurations

### ISSUE THREAD

**Issue by Mauin** [arturbosch/detekt#1162]
Continuing the discussion in #1147 

FindBugs defines two configurations:
 - `findbugs` which is used to define which version of FindBugs will be used.
 - `findbugsPlugins` which is used to define additional FindBugs rules that will be used.

After the changes in #1147 the Detekt Gradle Plugin also defines two configurations:
 - `detekt` which is used to define additional Detekt rules to be used (formatting, custom 3rd party rules)
 - `detektInternal` which is used to define which version of the Detekt CLI will be used.

This means detekt kind of inverts the configurations that FindBugs uses.
However changing our configurations will require a breaking API change which will break all builds that currently define a `detekt` dependency for additional rules as they would overwrite the default CLI dependency that we add in the Plugin (identically to the issue in #1143). 

All detekt users would have to change their additional rules to define them as `detektPlugins` dependencies. The `detekt`  configuration could then be used to define which version of the CLI dependency the Plugin will use (similar/identical to the `toolVersion` property in the `detekt` extension.

I'm unsure how to proceed however this is something we should do before v1 _if_ we want to do it.

**Comment by 3flex** [comment]
Thanks, appreciate you reviewing this. Changing behaviour will only break for anyone who switched to RC9.2 and changed their config based on #1147 fix, so probably not many people.

For anyone on earlier version it's required to set the detekt-cli dependency _in addition_ to the extra rules for the config to work:

```
dependencies {
    detekt("io.gitlab.arturbosch.detekt:detekt-formatting:${detektVersion}")
    detekt("io.gitlab.arturbosch.detekt:detekt-cli:${detektVersion}")
}
```

Before RC9.2 the above will work. If adding detektPlugins config as I'd proposed that will continue to work. Only those who have moved to RC9.2 and changed their config and removed explicit dependency on detekt-cli find their build broken again, but commenting on #1147 and #1143 and updating docs to describe usage of detektPlugins should be enough to notify users of updated usage. So it's not a breaking change for all users but only for those on RC9.2 who added plugins. I don't think the impact is that bad yet.

**Comment by Mauin** [comment]
However we would still have a default dependency on detekt CLI. Similar to FindBugs which does the same. So the main change will be that people will need to replace `detekt` dependencies with `detektPlugins`

**Comment by arturbosch** [comment]
Actually I like having just `detekt` more, but I would also go with the gradle convention if other plugins to it that way. Also `detektPlugins` has plugins in the name which makes things clearer.
@Mauin you have time to provide this as a PR? We could release a RC9.3 soon ^^

**Comment by Mauin** [comment]
Yeah I can look into it tomorrow.
