### ISSUE TITLE
Add *Lint-style configuration

### ISSUE THREAD

**Issue by deeprim** [arturbosch/detekt#1165]
Add ability to configure `detekt` in ES\TS\Etc\lint style, e.g.:

```yml
ui/
  main/ # ui classes
  .detekt.yml # contains ui specific rules
core/
  main/ # core classes
  .detekt.yml # contains core specific rules
.detekt.yml # root configuration
```

With the structure above, detekt upon its execution within `ui` module will take "root" config, merge ui/.detekt.yml in it (the ui version takes higher priority, i.e. *substitutes* corresponding rule from "root")

The same for "core" module

**Comment by schalkms** [comment]
Detekt is per se no linter. I don't think that this provides value to a static code analyzer.
Since no one upvoted this and because of many more features on the roadmap, I consider to close this issue.
