### ISSUE TITLE
Improve rules introspection capabilities

### ISSUE THREAD

**Issue by deeprim** [arturbosch/detekt#1166]
The below is required by [Add code assisting features for detekt configuration files](https://github.com/arturbosch/detekt-intellij-plugin/issues/16)

---

In order for tooling (IntelliJ IDEA) to be able to pick up rules configuration, following information is required for each property a rule may have: 

* Name
* Type (boolean, int, string, antpath, regex, more?)
-- int: may have `min`, `max`, `range` constaint
-- string: may have possible values enumerated
-- antpath: may have possible values enumerated
-- regex: may have possible values enumerated
* Description (optional)
* Constraints (optional) depending on the type

Proposed DSL:

```kotlin

class MyCustomRule : Rule() {

    // the rule's body

    companion object : RuleProperties() {
        override val properties = properties {
            boolean(
                    name = "boolean-property",
                    default = false,
                    description = "The property's description that really helps to understand it's purpose"
            )

            integer(
                    name = "threshold",
                    default = 10,
                    constraint = IntegerConstraint.Range(10, 50),
                    description = "The threshold's description"
            )
        }
    }
}

**Comment by arturbosch** [comment]
Hm, wouldnt parsing the KDoc of the rules work too for this? Maybe this an additional type specifier ...

**Comment by deeprim** [comment]
Parsing KDoc doesn't seems to be a reliable solution as small errata in KDoc may break stuff.
Additionally, such thing as constraints may help to improve editing experience (validate the value of property itself), how one would express that via KDoc?

**Comment by deeprim** [comment]
Hi @arturbosch,
Did you mean using `detekt-generator` module? Judging from the source, it might be used
We could create an additional gradle task that will create some rule descriptor file that might be used to retrieve all rule related metadata within IntelliJ Plugin
What do think?

**Comment by schalkms** [comment]
We might have a (Kotlin) DSL instead of the yaml for configuring detekt's rules. I also think we have an issue open somewhere. 
Furthermore, we don't need to track this in both of detekt's repositories, so I'll close this.
