### ISSUE TITLE
Publish cli-all

### ISSUE THREAD

**Issue by marianosimone** [arturbosch/detekt#1168]
To run detekt from cli, the only way right now is to build detekt to generate the `cli-all` jar.

It would be nice to publish it, to make it easier for people to use the cli version without having to build it themselves

**Comment by arturbosch** [comment]
github release plugin could upload the built cli.jar ^^

**Comment by marianosimone** [comment]
Interestingly enough, the one for [RC10](https://github.com/arturbosch/detekt/releases/tag/RC10) was released, but not the one for [11](https://github.com/arturbosch/detekt/releases/tag/1.0.0-RC11) 😕

**Comment by arturbosch** [comment]
Memo: https://github.com/BreadMoirai/github-release-gradle-plugin

**Comment by artem-zinnatullin** [comment]
Posted patch to publish to jcenter too https://github.com/arturbosch/detekt/pull/1453

Reasoning: many companies use maven repo proxies, it's an established practice (Artifactory, Nexus, etc). One can proxy GitHub releases too, but it's more manual work usually, although I like that it gets published there.

**Comment by artem-zinnatullin** [comment]
Looks like we're good! https://jcenter.bintray.com/io/gitlab/arturbosch/detekt/detekt-cli/1.0.0-RC13/:detekt-cli-1.0.0-RC13-all.jar
