### ISSUE TITLE
Sample Projects + Documentation

### ISSUE THREAD

**Issue by schalkms** [arturbosch/detekt#1169]
As mentioned in #1140 detekt should have a sample project for the following project types. The sample project should also be visible in the documentation on detekt's website to make it easier for a user to get familiar with detekt.

- [ ] one for each gradle build type 
- [ ] one for the maven plugin
- [ ] maybe move detekt-extension-example to sample repo
- [x] ~~detekt-watcher setup~~

**Comment by 3flex** [comment]
Now 1.0.0 is out this would be a good time to revisit this.

However, I worry that adding examples for Maven or Gradle builds as their own projects adds too much overhead for the project. If users aren't familiar with the build tools they should learn how to use them (I don't mean to be rude, but I don't think it's the detekt project's job). If they know how to use the build tools but can't set them up to use detekt when using our docs then docs can be updated.

We have the sample extension project which is good and specific to this project and should remain but I don't see much value in the others.

**Comment by schalkms** [comment]
> If they know how to use the build tools but can't set them up to use detekt when using our docs then docs can be updated.

> We have the sample extension project which is good and specific to this project and should remain but I don't see much value in the others.

I agree with both statements. Maintaining all this sample projects also requires some effort, which I would rather invest in the documentation on the home page.

I updated my initial post, because the watcher project got removed in RC15.

Unless @arturbosch has an objection against this, I'd favor to close this issue.

**Comment by arturbosch** [comment]
@schalkms @3flex I agree with you both.
We have linked to some gradle build files and sonar-kotlin (which uses maven) in the README file.
This should be enough.
