### ISSUE TITLE
Choose single assertion library and test engine

### ISSUE THREAD

**Issue by 3flex** [arturbosch/detekt#1170]
## Expected Behavior
Project uses a single assertion library and a single JUnit test engine.

## Current Behavior
Assertion libraries in use:
* kotlin-test
* AssertJ
* JUnit Jupiter

Both JUnit and Spek are used as test engines.

## Context
It's easier to contribute when a single assertion library and a single test engine is used across the project. Tests will complete more quickly on first run and in CI (fewer dependencies to pull) and may execute more quickly as well.

### ~~Assertions~~
~~Jupiter can be removed easily - it's only used in a single test (possibly by accident?). kotlin-test's assertions are very basic and would be easy to replace with AssertJ. It would be cumbersome to go the other way, as kotlin-test doesn't have a fluent API.~~

~~Propose using only AssertJ for assertions.~~ DONE!

### Test Engine
The project uses Spek much more than JUnit. However, Spek 2 is on the horizon (now at RC1). If migrating to Spek 2, majority of Spek tests would need to be modified to take advantage of improvements. JUnit is better supported both by maintainers and with external libraries and has better IntelliJ integration, though migrating to Spek 2 would be simpler.

Propose selecting either JUnit or Spek as the preferred test engine, and migrate tests accordingly (though if Spek is chosen, first migrate the JUnit tests to Spek 1, and handle Spek 2 migration separately if desired).

**Comment by arturbosch** [comment]
As you said, I'd go with spek2 after migrating everything to spek1 from junit5.
I've started using spek1 2 years ago but had to switch to junit5 for a while as there were some bugs/breaking things in the intellij plugin.
