### ISSUE TITLE
Detekt should not use PathSensitivity.ABSOLUTE for Detekt task

### ISSUE THREAD

**Issue by JLLeitschuh** [arturbosch/detekt#1178]
Doing so makes the `Detekt` task impossible to use the build cache cross system.

The build cache will be invalid when you have a CI system populate the cache and a different developer tries to use it.

This is one examples of many:
https://github.com/arturbosch/detekt/blob/15e3c800a6b19f3a8ba1c69c81a3ca59d3e17bcd/detekt-gradle-plugin/src/main/kotlin/io/gitlab/arturbosch/detekt/Detekt.kt#L68-L71

**Comment by Mauin** [comment]
Would you propose to change this to `RELATIVE` then?

**Comment by JLLeitschuh** [comment]
Correct. I would, sorry, I should have stated that in the original issue.

**Comment by vanniktech** [comment]
Out of curiosity what's the default?

**Comment by JLLeitschuh** [comment]
@vanniktech Good question. PR opened to improve the documentation:
https://github.com/gradle/gradle/pull/6983

**Comment by Mauin** [comment]
Looking at the Gradle tasks defined by Checkstyle and PMD they also set `PathSensitivity.RELATIVE` for config files mostly.
