### ISSUE TITLE
Gradle plugin: create task per source set

### ISSUE THREAD

**Issue by 3flex** [arturbosch/detekt#1198]
## Expected Behavior
Plugin creates detekt task for each source set in a Gradle project.

## Current Behavior
Plugin creates single detekt task per Gradle project.

## Context
Required for #485 (which I will update and integrate with the Gradle plugin).

To enable type and symbol resolution when detekt runs as part of the Gradle plugin, detekt must be aware of the compilation classpath. If detekt can't access the complete classpath that's used for compilation it's not possible to resolve all types and symbols unless classpaths are setup manually on each detekt task which isn't practical for users and highly error prone.

Additionally the detekt task for a source set should by default scan the source files in the sourceset. The current default for detekt is to scan `src/main/java` and `src/main/kotlin`. This will fail for tasks which are created for other sourcesets (e.g. "test") since the source files for those would typically be a combination of `src/main/java`, `src/test/java`, `src/main/kotlin` and `src/test/kotlin`.

This also affects how reports will be configured, because they will necessarily have to be created per task. If the report filename is set using the extension (i.e. `detekt.reports.xml.destination =`) a report generated for one detekt task would be overwritten by the next detekt task in the same project because the destination file path would be the same. Instead, the report directory must be set on the extension and the destination path on the task.

It should be possible to minimise disruption by creating source set tasks like "detektMain" and "detektTest" which use the new behaviour for reporting DSL and keep the current "detekt" task as is but with a deprecation message.

Then suggest that prior to 1.0 release, update the "detekt" task so it depends on all configured detekt tasks (detektMain, detektTest etc) and remove the reporting config from the extension (with exception of reportsDir provided by CodeQualityExtension).

**Comment by Mauin** [comment]
This seems similar to #540 which describes the same. Overall I agree with adding a task per sourceSet (while keeping one "global" `detekt` task). 

For the reports issue we could either suffix the report name with the sourceSet name or merge instead of overwrite the reports if multiple exist. But that would probably be quite tricky.

**Comment by marschwar** [comment]
Using a suffix or change the report directory for each task could easily be done. Does that imply the same config is used for all such tasks? 

From reading #485 I did not quite get what is expected to be passed to the cli. Is it `--input src/main/java;src/main/kotlin` as well as the `--classpath`? Must the classpath contain all the compile time dependencies of the project?

**Comment by Mauin** [comment]
I was looking into this earlier today and can upload a first snapshot of
the changes tomorrow.
