### ISSUE TITLE
Use Android Lint API

### ISSUE THREAD

**Issue by vanniktech** [arturbosch/detekt#1200]
Gotten this crazy idea for a while and wanted to get some input. Also talked with @Mauin about this and he's not opposed to the idea.

Detekt rules could be written on top of the Android Lint API. Some benefits:

- Java and Kotlin support
- Type resolution is a thing and much more
- Proper testing support / API (#1089)
- Built-in support with IntelliJ so no need for another Plugin besides the Android one (#52). I've heard from several people that the current plugin integration isn't that well
- Free reporting (xml/html)
- Free Gradle plugins
- Proper baseline support is a thing and the plugin shows the baselined issues in the IDE
- Quick fixes (#710) which can probably be applied to 10-30% of our rules

Downsides are obviously that we'd have to rewrite some of the rules. Marvin had the idea that only the core gets rewritten and then we just use the Lint API to get the Kt* classes and call them. (I might be wrong here though as I'm not familiar with that part).

There would be still some things that would need to be worked out but I think it's feasible. I'm also aware that this proposal is coming pretty late.

**Comment by arturbosch** [comment]
Idk about the lint tool, plugin etc just that I also tried to play around with the uast lib which lint uses. Unfortunately it is/was not published somewhere in a state where it can be used outside of the intellij-platform :/.
However they kotlin team is working on an official kotlin compiler plugin api which we should consider ofc to migrate to.

**Comment by vanniktech** [comment]
The latter one. `converting detekt's rules to work with Lint (implementing Detector API)`

> Many parts of lint-api's API are not stable so this might cause problems if user has a different version of lint-api on their classpath for some reason. Perhaps detekt would have to shadow its lint-api dependency?

Ish. I talked to Tor about this and so many have already adopted Lint that he's trying to avoid touching the API as much as possible. Lately, there haven't been any problems. He's converting most of the APIs from Java -> Kotlin while keeping backward compatibility. Once something is in Kotlin he can use the language tools to let everyone know. All in all it's super decent.

**Comment by 3flex** [comment]
> uast lib which lint uses. Unfortunately it is/was not published somewhere

It's packaged by Android team as `com.android.tools.external.org-jetbrains:uast`. The `com.android.tools.lint:lint` artifact depends on it, so I expect it's safe to use as a dependency.

**Comment by 3flex** [comment]
Might be worth experimenting with in future, but for now I think we can close this?

**Comment by vanniktech** [comment]
Yo
