### ISSUE TITLE
Use Semantic Versioning

### ISSUE THREAD

**Issue by vanniktech** [arturbosch/detekt#1201]
Can we start using Semantic versioning from now on?

My motivation for this is that I want to support different Detekt versions in my Gradle Plugin and hence would like to use the GradleVersion class that's being provided by Android Gradle Plugin to check between versions.

Here's what needs to be changed:

`1.0.0.RC9` -> `1.0.0-RC9`
`1.0.0.RC9-2` -> `1.0.0-RC10`

I'm having a hard time believing there's a reason to have `RC9-2`. Numbers are free so just use `RC10` directly which will be understood by everyone.

**Comment by vanniktech** [comment]
Git tags like [RC9](https://github.com/arturbosch/detekt/releases/tag/RC9) are also not helpful. They should be 1.0.0.RC9 at least. Even better would be 1.0.0-RC9.

**Comment by 3flex** [comment]
How to close this issue? Does use of semantic versioning have to be declared in README, or does a RELEASING doc have to be created that documents steps and versioning rules?

Also remember to consider -SNAPSHOT suffix for release process so once a new release is pushed the SNAPSHOT suffix is added to the version number.

**Comment by vanniktech** [comment]
I think we can close this issue once we've seen some releases that are complying with semantic versioning.
