### ISSUE TITLE
Filters apply to absolute paths not relative paths

### ISSUE THREAD

**Issue by 3flex** [arturbosch/detekt#1212]
## Expected Behavior
Filters apply only to relative paths.

## Current Behavior
Filters apply to absolute paths.

## Steps to Reproduce (for bugs)
Identified investigating #1158 (relevant build log: https://travis-ci.org/arturbosch/detekt/jobs/432263468)

## Context
The filters set when Travis build runs includes `.*/build/*.`. Travis checks out the build at `/home/travis/build/arturbosch/detekt` which is also detekt's working directory when it runs. I'd expected that it's filtering based on the relative path, but it appears to be filtering based on the absolute path. Since all Kotlin files have `/build/` in their absolute paths, everything is filtered.

## Your Environment
* Version used: master
* Operating System and version: Ubunty Trusty 14.04 (running on Travis)
* Link to your project: See #1158 and build log: https://travis-ci.org/arturbosch/detekt/jobs/432263468

**Comment by Mauin** [comment]
This behavior is defined in `PathFilter` and I agree it would be good to only apply the filters on relative paths to the project root.

**Comment by 3flex** [comment]
Reminder to anyone reading: before closing, ensure that any fix is effective in fixing the original issue reported at #1158 - the same set of files that are scanned in AppVeyor should be scanned in Travis.
