### ISSUE TITLE
False positive for IteratorNotThrowingNoSuchElementException

### ISSUE THREAD

**Issue by robstoll** [arturbosch/detekt#1219]
## Expected Behavior
Iterator which delegates to another iterator does not have to check if there is a next element and throw if not because the other iterator already does that.

## Current Behavior
Issue is reported

## Steps to Reproduce (for bugs)
See project and sonarcloud link

## Your Environment

* Version used: 1.0.0.RC8
* Link to your project: https://github.com/loewenfels/dep-graph-releaser/blob/master/api/dep-graph-releaser-api-common/src/main/kotlin/ch/loewenfels/depgraph/data/ReleasePlan.kt#L90
* sonarcloud: https://sonarcloud.io/project/issues?id=depgraph&open=AWZZNWEiDZywvPe4693G&resolved=false&severities=CRITICAL&types=CODE_SMELL

**Comment by schalkms** [comment]
This is hard to track without having type solving. So I'm adding the respective label to this issue.

**Comment by 3flex** [comment]
So the logic would have to be:
- check for any Iterator.next calls within the next() function being checked
- check that the Iterator.next call that is being delegated to throws an exception, or delegates to another Iterator.next call that does
- also check that any Iterator.next calls that were delegated to aren't surrounded by a try-catch block that catches the exception

Implementing this could be quite error prone. Is delegating from one list to another like this a common pattern?

Really all that's needed is adding the `if (!hasNext()) throw NoSuchElementException()` at the start of the next() function. It's not strictly necessary in your case but it's simple to implement. Or of course the rule can be suppressed for this specific implementation.

**Comment by robstoll** [comment]
IMO it's more of a nice to have, especially if it is hard to implement because as you said, adding `if (!hasNext()) throw NoSuchElementException()` or @Suppress('IteratorNotThrowingNoSuchElementException') are both good enough workarounds

**Comment by 3flex** [comment]
Thanks for your feedback! Maybe @arturbosch or @schalkms have a better idea of how this could be implemented but my vote would be to close this one.

**Comment by schalkms** [comment]
I agree. Closed..
