### ISSUE TITLE
MethodOverloading with wrong line

### ISSUE THREAD

**Issue by robstoll** [arturbosch/detekt#1223]
## Expected Behavior
The issue should point to the method which is overloaded (e.g. 1251 in the example)

## Current Behavior
Points to 1:1

## Steps to Reproduce (for bugs)
- git clone https://github.com/loewenfels/dep-graph-releaser.git
- remove `'MethodOverloading'` from exlude-rules in ./gradle/scripts/detekt.yml
- run `./gr detektCheck`
- see report in ./build/detekt

## Your Environment
* Version used: 1.0.0.RC8

**Comment by Mauin** [comment]
Can you post a simple code sample that reproduces this issue?

**Comment by robstoll** [comment]
I doubt there is a simple example, at least I don't have one. Yet, I have one use case which you can reproduce as described.

**Comment by marschwar** [comment]
Actually it is really simple. The function `analyseAndCreateReleasePlan` is declared 7 times.

**Comment by robstoll** [comment]
That's not my point. The line number is wrong, it points to 1 instead of e.g. 1251. Also, the error reporting could  (IMO should) include the name of the method.

**Comment by Mauin** [comment]
Adding the method name to the description of the issue definitely makes sense to spot these things easier.

The issue with the wrong line number being reported lies in the Entity we pass to the `report` funcation. https://github.com/arturbosch/detekt/blob/master/detekt-rules/src/main/kotlin/io/gitlab/arturbosch/detekt/rules/complexity/MethodOverloading.kt#L58

This is currently either the class or the file we're visiting so the line number will never point to the line the method is defined in but to the beginning of the file/class.
This could be solved by storing more information about the method in the `visitNamedFunction` function to later pass the `KtMethod` to the `Entity.from()` call once we report the issue.
