### ISSUE TITLE
How to use the formatting extension on Android with Gradle plugin?

### ISSUE THREAD

**Issue by benoitletondor** [arturbosch/detekt#1233]
Hello there 👋 

I'm sorry about creating an issue that is not really an issue but more a question, I tried to find somewhere else to ask my question but I did not find any.

My question is: I'm using Detekt in an Android project, using the `detekt-gradle-plugin` and I can't make the `formatting` extension (the one wrapping Ktlint) work. 

I'm supposed to add

```
detektPlugins "io.gitlab.arturbosch.detekt:detekt-formatting:[version]"
```

to my gradle file but I can't find where. Any instruction on how to make it work?

Many thanks for your amazing work on that project and thank you for your time here.

Cheers,
Benoit

**Comment by pawegio** [comment]
@benoitletondor which gradle version do you use?

**Comment by benoitletondor** [comment]
```
com.android.tools.build:gradle:3.2.0
```

With gradle 4.10

**Comment by benoitletondor** [comment]
Hey there, do you think about anything I can do to make that work? Many thanks

**Comment by esanchos** [comment]
I was having the same problem as you.

To solve that, I needed to remove the formatting dependency from the project to the app build.gradle.
So, jsut remove this from your project's build.gradle:
```
dependencies {
    ...

    detektPlugins "io.gitlab.arturbosch.detekt:detekt-formatting:1.0.0.RC9.2"
}
```

Then add this to the app's build.gradle:
At the top of you file:
apply plugin: 'io.gitlab.arturbosch.detekt'

then inside your dependencies:
```
dependencies {
...
detekt "io.gitlab.arturbosch.detekt:detekt-formatting:${detektVersion}"
}
```

**Comment by Mauin** [comment]
Sorry for the confusion about the `detekt` vs `detektPlugins` configuration. This change has not been released yet but the documentation was already updated as part of the PR which introduced it.

It is scheduled to go out starting with the next release.
Until then the `detekt` configuration should be used, similar to what @esanchos has posted above.
Starting with the next release we advice moving the formatting dependency to the `detektPlugins` configuration, however I believe the `detekt` configuration should also continue to work.

**Comment by benoitletondor** [comment]
Hey guys,

Thank you so much for the follow up. Nice to hear there's a solution and no problem at all encountering a bug in a RC version, that's what it's made for :) 

Thank you again and good luck!

**Comment by benoitletondor** [comment]
Hey there, 

Reopening the issue with a new error :

```
Task :app:detekt FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:detekt'.
> Could not resolve all files for configuration ':app:detekt'.
   > Could not find io.gitlab.arturbosch.detekt:detekt-formatting:io.gitlab.arturbosch.detekt.extensions.DetektExtension_Decorated.
```

Does that sound familiar to anyone?

Many thanks

**Comment by benoitletondor** [comment]
Sorry for bumping this, but anyone have an idea? 🙏

**Comment by benoitletondor** [comment]
I'dl love to but RC10 is still not published on Maven :/

**Comment by benoitletondor** [comment]
I'm using the `detekt-gradle-plugin` and it's still doesn't seem to be available: https://repo.jfrog.org/artifactory/libs-release-bintray/io/gitlab/arturbosch/detekt/detekt-gradle-plugin/

Am i missing something? Sorry about that

**Comment by Mauin** [comment]
In addition to the links that @arturbosch shared it's also available on the Gradle Plugin Portal https://plugins.gradle.org/plugin/io.gitlab.arturbosch.detekt

**Comment by esanchos** [comment]
Hi there, I tryed with RC11 and it seems to be ok. Can you please re-test?

**Comment by benoitletondor** [comment]
Note sure what I'm doing wrong but I'm still getting an error:

```
* What went wrong:
Execution failed for task ':app:detekt'.
> Could not resolve all files for configuration ':app:detekt'.
   > Could not find io.gitlab.arturbosch.detekt:detekt-formatting:io.gitlab.arturbosch.detekt.extensions.DetektExtension_Decorated.
     Searched in the following locations:
       - file:/Users/benoit/android/extras/m2repository/io/gitlab/arturbosch/detekt/detekt-formatting/io.gitlab.arturbosch.detekt.extensions.DetektExtension_Decorated/detekt-formatting-io.gitlab.arturbosch.detekt.extensions.DetektExtension_Decorated.pom
       - file:/Users/benoit/android/extras/m2repository/io/gitlab/arturbosch/detekt/detekt-formatting/io.gitlab.arturbosch.detekt.extensions.DetektExtension_Decorated/detekt-formatting-io.gitlab.arturbosch.detekt.extensions.DetektExtension_Decorated.30585dc5
       - file:/Users/benoit/android/extras/google/m2repository/io/gitlab/arturbosch/detekt/detekt-formatting/io.gitlab.arturbosch.detekt.extensions.DetektExtension_Decorated/detekt-formatting-io.gitlab.arturbosch.detekt.extensions.DetektExtension_Decorated.pom
       - file:/Users/benoit/android/extras/google/m2repository/io/gitlab/arturbosch/detekt/detekt-formatting/io.gitlab.arturbosch.detekt.extensions.DetektExtension_Decorated/detekt-formatting-io.gitlab.arturbosch.detekt.extensions.DetektExtension_Decorated.30585dc5
       - file:/Users/benoit/android/extras/android/m2repository/io/gitlab/arturbosch/detekt/detekt-formatting/io.gitlab.arturbosch.detekt.extensions.DetektExtension_Decorated/detekt-formatting-io.gitlab.arturbosch.detekt.extensions.DetektExtension_Decorated.pom
       - file:/Users/benoit/android/extras/android/m2repository/io/gitlab/arturbosch/detekt/detekt-formatting/io.gitlab.arturbosch.detekt.extensions.DetektExtension_Decorated/detekt-formatting-io.gitlab.arturbosch.detekt.extensions.DetektExtension_Decorated.30585dc5
       - https://dl.google.com/dl/android/maven2/io/gitlab/arturbosch/detekt/detekt-formatting/io.gitlab.arturbosch.detekt.extensions.DetektExtension_Decorated/detekt-formatting-io.gitlab.arturbosch.detekt.extensions.DetektExtension_Decorated.pom
       - https://dl.google.com/dl/android/maven2/io/gitlab/arturbosch/detekt/detekt-formatting/io.gitlab.arturbosch.detekt.extensions.DetektExtension_Decorated/detekt-formatting-io.gitlab.arturbosch.detekt.extensions.DetektExtension_Decorated.30585dc5
       - https://jcenter.bintray.com/io/gitlab/arturbosch/detekt/detekt-formatting/io.gitlab.arturbosch.detekt.extensions.DetektExtension_Decorated/detekt-formatting-io.gitlab.arturbosch.detekt.extensions.DetektExtension_Decorated.pom
       - https://jcenter.bintray.com/io/gitlab/arturbosch/detekt/detekt-formatting/io.gitlab.arturbosch.detekt.extensions.DetektExtension_Decorated/detekt-formatting-io.gitlab.arturbosch.detekt.extensions.DetektExtension_Decorated.30585dc5
       - https://repo.maven.apache.org/maven2/io/gitlab/arturbosch/detekt/detekt-formatting/io.gitlab.arturbosch.detekt.extensions.DetektExtension_Decorated/detekt-formatting-io.gitlab.arturbosch.detekt.extensions.DetektExtension_Decorated.pom
       - https://repo.maven.apache.org/maven2/io/gitlab/arturbosch/detekt/detekt-formatting/io.gitlab.arturbosch.detekt.extensions.DetektExtension_Decorated/detekt-formatting-io.gitlab.arturbosch.detekt.extensions.DetektExtension_Decorated.30585dc5
       - https://maven.fabric.io/public/io/gitlab/arturbosch/detekt/detekt-formatting/io.gitlab.arturbosch.detekt.extensions.DetektExtension_Decorated/detekt-formatting-io.gitlab.arturbosch.detekt.extensions.DetektExtension_Decorated.pom
       - https://maven.fabric.io/public/io/gitlab/arturbosch/detekt/detekt-formatting/io.gitlab.arturbosch.detekt.extensions.DetektExtension_Decorated/detekt-formatting-io.gitlab.arturbosch.detekt.extensions.DetektExtension_Decorated.30585dc5
     Required by:
         project :app
```

Gradle :

```
buildscript {
    repositories {
        maven { url 'https://maven.fabric.io/public' }
        maven { url "https://plugins.gradle.org/m2/" }
    }

    dependencies {
        classpath "io.gitlab.arturbosch.detekt:detekt-gradle-plugin:$detekt"
    }
}

... 

dependencies {
    // Detekt
    detekt "io.gitlab.arturbosch.detekt:detekt-formatting:$detekt"
   
    ...

}
```

```
detekt = "1.0.0-RC11"
```

**Comment by henriquenfaria** [comment]
> Note sure what I'm doing wrong but I'm still getting an error:
> 
> ```
> * What went wrong:
> Execution failed for task ':app:detekt'.
> > Could not resolve all files for configuration ':app:detekt'.
>    > Could not find io.gitlab.arturbosch.detekt:detekt-formatting:io.gitlab.arturbosch.detekt.extensions.DetektExtension_Decorated.
>      Searched in the following locations:
>        - file:/Users/benoit/android/extras/m2repository/io/gitlab/arturbosch/detekt/detekt-formatting/io.gitlab.arturbosch.detekt.extensions.DetektExtension_Decorated/detekt-formatting-io.gitlab.arturbosch.detekt.extensions.DetektExtension_Decorated.pom
>        - file:/Users/benoit/android/extras/m2repository/io/gitlab/arturbosch/detekt/detekt-formatting/io.gitlab.arturbosch.detekt.extensions.DetektExtension_Decorated/detekt-formatting-io.gitlab.arturbosch.detekt.extensions.DetektExtension_Decorated.30585dc5
>        - file:/Users/benoit/android/extras/google/m2repository/io/gitlab/arturbosch/detekt/detekt-formatting/io.gitlab.arturbosch.detekt.extensions.DetektExtension_Decorated/detekt-formatting-io.gitlab.arturbosch.detekt.extensions.DetektExtension_Decorated.pom
>        - file:/Users/benoit/android/extras/google/m2repository/io/gitlab/arturbosch/detekt/detekt-formatting/io.gitlab.arturbosch.detekt.extensions.DetektExtension_Decorated/detekt-formatting-io.gitlab.arturbosch.detekt.extensions.DetektExtension_Decorated.30585dc5
>        - file:/Users/benoit/android/extras/android/m2repository/io/gitlab/arturbosch/detekt/detekt-formatting/io.gitlab.arturbosch.detekt.extensions.DetektExtension_Decorated/detekt-formatting-io.gitlab.arturbosch.detekt.extensions.DetektExtension_Decorated.pom
>        - file:/Users/benoit/android/extras/android/m2repository/io/gitlab/arturbosch/detekt/detekt-formatting/io.gitlab.arturbosch.detekt.extensions.DetektExtension_Decorated/detekt-formatting-io.gitlab.arturbosch.detekt.extensions.DetektExtension_Decorated.30585dc5
>        - https://dl.google.com/dl/android/maven2/io/gitlab/arturbosch/detekt/detekt-formatting/io.gitlab.arturbosch.detekt.extensions.DetektExtension_Decorated/detekt-formatting-io.gitlab.arturbosch.detekt.extensions.DetektExtension_Decorated.pom
>        - https://dl.google.com/dl/android/maven2/io/gitlab/arturbosch/detekt/detekt-formatting/io.gitlab.arturbosch.detekt.extensions.DetektExtension_Decorated/detekt-formatting-io.gitlab.arturbosch.detekt.extensions.DetektExtension_Decorated.30585dc5
>        - https://jcenter.bintray.com/io/gitlab/arturbosch/detekt/detekt-formatting/io.gitlab.arturbosch.detekt.extensions.DetektExtension_Decorated/detekt-formatting-io.gitlab.arturbosch.detekt.extensions.DetektExtension_Decorated.pom
>        - https://jcenter.bintray.com/io/gitlab/arturbosch/detekt/detekt-formatting/io.gitlab.arturbosch.detekt.extensions.DetektExtension_Decorated/detekt-formatting-io.gitlab.arturbosch.detekt.extensions.DetektExtension_Decorated.30585dc5
>        - https://repo.maven.apache.org/maven2/io/gitlab/arturbosch/detekt/detekt-formatting/io.gitlab.arturbosch.detekt.extensions.DetektExtension_Decorated/detekt-formatting-io.gitlab.arturbosch.detekt.extensions.DetektExtension_Decorated.pom
>        - https://repo.maven.apache.org/maven2/io/gitlab/arturbosch/detekt/detekt-formatting/io.gitlab.arturbosch.detekt.extensions.DetektExtension_Decorated/detekt-formatting-io.gitlab.arturbosch.detekt.extensions.DetektExtension_Decorated.30585dc5
>        - https://maven.fabric.io/public/io/gitlab/arturbosch/detekt/detekt-formatting/io.gitlab.arturbosch.detekt.extensions.DetektExtension_Decorated/detekt-formatting-io.gitlab.arturbosch.detekt.extensions.DetektExtension_Decorated.pom
>        - https://maven.fabric.io/public/io/gitlab/arturbosch/detekt/detekt-formatting/io.gitlab.arturbosch.detekt.extensions.DetektExtension_Decorated/detekt-formatting-io.gitlab.arturbosch.detekt.extensions.DetektExtension_Decorated.30585dc5
>      Required by:
>          project :app
> ```
> Gradle :
> 
> ```
> buildscript {
>     repositories {
>         maven { url 'https://maven.fabric.io/public' }
>         maven { url "https://plugins.gradle.org/m2/" }
>     }
> 
>     dependencies {
>         classpath "io.gitlab.arturbosch.detekt:detekt-gradle-plugin:$detekt"
>     }
> }
> 
> ... 
> 
> dependencies {
>     // Detekt
>     detekt "io.gitlab.arturbosch.detekt:detekt-formatting:$detekt"
>    
>     ...
> 
> }
> ```
> ```
> detekt = "1.0.0-RC11"
> ```

Had the same problem as you. To fix it I had to add detekt plugin using `plugins` way:

```
plugins {
    id "io.gitlab.arturbosch.detekt" version "1.0.0-RC12"
}
```

Couldn't make it work when adding it via the classpath...

**Comment by arturbosch** [comment]
Or if you are using the classpath method you have to add `jcenter()` as a repository.
