### ISSUE TITLE
[RFC] activateAll config flag

### ISSUE THREAD

**Issue by robstoll** [arturbosch/detekt#1236]
I use an own config file myself and I am glad that I don't have to configure all rules myself (threshold etc.). Yet, I prefer an opt-out over an opt-in. Especially because I don't know how stable the default config stays and I don't have the time to track this all the time. Thus I would like to be able to say `activateAll` rules and then I only deactivate the ones I don't want.

**Comment by vanniktech** [comment]
Looks like you want: `failFast: true`

**Comment by Mauin** [comment]
Linking to #663 #662

**Comment by robstoll** [comment]
I don't think so. I assume `failFast` is used to stop analysis after first failure. No?

**Comment by robstoll** [comment]
@Mauin oh... I see, it's a naming problem

**Comment by vanniktech** [comment]
`activateAllRulesAndFailFast` would not mind that name although can we find something shorter?
