### ISSUE TITLE
Investigate Travis CI Windows support

### ISSUE THREAD

**Issue by Mauin** [arturbosch/detekt#1242]
See the announcement of the Early Release: https://blog.travis-ci.com/2018-10-11-windows-early-release

Travis now allows to run the same build on multiple operating systems, possibly allowing us to purely rely on it, instead of running Travis and AppVeyor side-by-side.

See #1241 for trying out the multi-OS support.

**Comment by Mauin** [comment]
https://docs.travis-ci.com/user/reference/windows/#supported-languages

There is currently no support for `java`, although the JDK should be installed by default. However builds currently immediately fail with:
`The language 'java' is currently unsupported on the Windows Build Environment.`

Once Java support is added we can re-open #1241 to run a build.

**Comment by schalkms** [comment]
The drawback with this one is that the CI needs longer to finish for every PR. 
Currently, Windows and Linux builds run concurrently which shortens the feedback cycle.

In the last few months, AppVeyor hasn't been flaky at all.
So, I don't see the benefit of introducing this feature.
What do you think? @arturbosch

**Comment by arturbosch** [comment]
But we also run tavis for java8 and 10. So two jobs, one 18 min other 20min. Haven't observed if they run in parallel or after each other. 
@schalkms yep Appveyor runs okay for months ^^

**Comment by schalkms** [comment]
I'd favor to close this then and not invest any more time in it.

**Comment by schalkms** [comment]
If AppVeyor triggers new problems, we should reopen this issue.
For now, staying with AppVeyor is fine. Thus, I'm closing this issue.
