### ISSUE TITLE
Disable formatting auto correct

### ISSUE THREAD

**Issue by esanchos** [arturbosch/detekt#1249]
I am trying to use Detekt to show the formatting issues on my code, but I do not want Detekt to change my code. I turned "autoCorrect: false" on config.yml everywhere.

## Expected Behavior
Detekt should not modify my code if autoCorrect: false

## Current Behavior
Detekt is modifying my code when autoCorrect: false

## Steps to Reproduce (for bugs)
Turn Formatting Rules set on.
On config.yml, disable autoCorrect everywhere (autoCorrect: false)
Force an formatting error, like adding blank ConsecutiveBlankLines
run: ./gradlew detekt

## Context
I want Detekt to show me the formatting erros, so I can fix it.

## Your Environment
* Version used: 1.0.0.RC9.2
* Operating System and version: Ubuntu 18.04

**Comment by 3flex** [comment]
Can you post your full detekt config?

I wonder if it's a bug in the formatting module or with merging configs (there have been a couple of other recent issues raised around configs recently).

**Comment by esanchos** [comment]
Hi, my config is not so different from the default one, except the autoCorrect: false

`
autoCorrect: false
failFast: false

test-pattern: # Configure exclusions for test sources
  active: true
  patterns: # Test file regexes
    - '.*/test/.*'
    - '.*Test.kt'
    - '.*Spec.kt'
  exclude-rule-sets:
    #- 'comments'
  exclude-rules:
    #- 'NewLineAtEndOfFile'
    #- 'NamingRules'
    #- 'WildcardImport'
    #- 'MagicNumber'
    #- 'MaxLineLength'
    #- 'LateinitUsage'
    #- 'StringLiteralDuplication'
    #- 'SpreadOperator'
    #- 'TooManyFunctions'
    #- 'ForEachOnRange'

build:
  maxIssues: 0
  weights:
    # complexity: 2
    # LongParameterList: 1
    # style: 1
    # comments: 1

processors:
  active: true
  exclude:
  # - 'FunctionCountProcessor'
  # - 'PropertyCountProcessor'
  # - 'ClassCountProcessor'
  # - 'PackageCountProcessor'
  # - 'KtFileCountProcessor'

console-reports:
  active: true
  exclude:
  #  - 'ProjectStatisticsReport'
  #  - 'ComplexityReport'
  #  - 'NotificationReport'
  #  - 'FindingsReport'
  #  - 'BuildFailureReport'

comments:
  active: true
  CommentOverPrivateFunction:
    active: false
  CommentOverPrivateProperty:
    active: false
  EndOfSentenceFormat:
    active: false
    endOfSentenceFormat: ([.?!][ \t\n\r\f<])|([.?!]$)
  UndocumentedPublicClass:
    active: false
    searchInNestedClass: true
    searchInInnerClass: true
    searchInInnerObject: true
    searchInInnerInterface: true
  UndocumentedPublicFunction:
    active: false

complexity:
  active: true
  ComplexCondition:
    active: true
    threshold: 4
  ComplexInterface:
    active: false
    threshold: 10
    includeStaticDeclarations: false
  ComplexMethod:
    active: true
    threshold: 10
    ignoreSingleWhenExpression: false
  LabeledExpression:
    active: false
  LargeClass:
    active: true
    threshold: 150
  LongMethod:
    active: true
    threshold: 20
  LongParameterList:
    active: false
    threshold: 6
    ignoreDefaultParameters: false
  MethodOverloading:
    active: false
    threshold: 6
  NestedBlockDepth:
    active: true
    threshold: 4
  StringLiteralDuplication:
    active: false
    threshold: 3
    ignoreAnnotation: true
    excludeStringsWithLessThan5Characters: true
    ignoreStringsRegex: '$^'
  TooManyFunctions:
    active: true
    thresholdInFiles: 11
    thresholdInClasses: 11
    thresholdInInterfaces: 11
    thresholdInObjects: 11
    thresholdInEnums: 11
    ignoreDeprecated: false
    ignorePrivate: false

empty-blocks:
  active: true
  EmptyCatchBlock:
    active: true
    allowedExceptionNameRegex: "^(_|(ignore|expected).*)"
  EmptyClassBlock:
    active: true
  EmptyDefaultConstructor:
    active: true
  EmptyDoWhileBlock:
    active: true
  EmptyElseBlock:
    active: true
  EmptyFinallyBlock:
    active: true
  EmptyForBlock:
    active: true
  EmptyFunctionBlock:
    active: true
    ignoreOverriddenFunctions: false
  EmptyIfBlock:
    active: true
  EmptyInitBlock:
    active: true
  EmptyKtFile:
    active: true
  EmptySecondaryConstructor:
    active: true
  EmptyWhenBlock:
    active: true
  EmptyWhileBlock:
    active: true

exceptions:
  active: true
  ExceptionRaisedInUnexpectedLocation:
    active: false
    methodNames: 'toString,hashCode,equals,finalize'
  InstanceOfCheckForException:
    active: false
  NotImplementedDeclaration:
    active: false
  PrintStackTrace:
    active: false
  RethrowCaughtException:
    active: false
  ReturnFromFinally:
    active: false
  SwallowedException:
    active: false
  ThrowingExceptionFromFinally:
    active: false
  ThrowingExceptionInMain:
    active: false
  ThrowingExceptionsWithoutMessageOrCause:
    active: false
    exceptions: 'IllegalArgumentException,IllegalStateException,IOException'
  ThrowingNewInstanceOfSameException:
    active: false
  TooGenericExceptionCaught:
    active: true
    exceptionNames:
     - ArrayIndexOutOfBoundsException
     - Error
     - Exception
     - IllegalMonitorStateException
     - NullPointerException
     - IndexOutOfBoundsException
     - RuntimeException
     - Throwable
    allowedExceptionNameRegex: "^(_|(ignore|expected).*)"
  TooGenericExceptionThrown:
    active: true
    exceptionNames:
     - Error
     - Exception
     - Throwable
     - RuntimeException

formatting:
  active: true
  android: false
  autoCorrect: false
  ChainWrapping:
    active: true
    autoCorrect: false
  CommentSpacing:
    active: true
    autoCorrect: false
  Filename:
    active: true
  FinalNewline:
    active: true
    autoCorrect: false
  ImportOrdering:
    active: true
    autoCorrect: false
  Indentation:
    active: true
    autoCorrect: false
    indentSize: 4
    continuationIndentSize: 4
  MaximumLineLength:
    active: true
    maxLineLength: 100
  ModifierOrdering:
    active: true
    autoCorrect: false
  NoBlankLineBeforeRbrace:
    active: true
    autoCorrect: false
  NoConsecutiveBlankLines:
    active: true
    autoCorrect: false
  NoEmptyClassBody:
    active: true
    autoCorrect: false
  NoItParamInMultilineLambda:
    active: true
  NoLineBreakAfterElse:
    active: true
    autoCorrect: false
  NoLineBreakBeforeAssignment:
    active: true
    autoCorrect: false
  NoMultipleSpaces:
    active: true
    autoCorrect: false
  NoSemicolons:
    active: true
    autoCorrect: false
  NoTrailingSpaces:
    active: true
    autoCorrect: false
  NoUnitReturn:
    active: true
    autoCorrect: false
  NoUnusedImports:
    active: true
    autoCorrect: false
  NoWildcardImports:
    active: true
    autoCorrect: false
  ParameterListWrapping:
    active: true
    autoCorrect: false
    indentSize: 4
  SpacingAroundColon:
    active: true
    autoCorrect: false
  SpacingAroundComma:
    active: true
    autoCorrect: false
  SpacingAroundCurly:
    active: true
    autoCorrect: false
  SpacingAroundKeyword:
    active: true
    autoCorrect: false
  SpacingAroundOperators:
    active: true
    autoCorrect: false
  SpacingAroundRangeOperator:
    active: true
    autoCorrect: false
  StringTemplate:
    active: true
    autoCorrect: false

naming:
  active: true
  ClassNaming:
    active: true
    classPattern: '[A-Z$][a-zA-Z0-9$]*'
  ConstructorParameterNaming:
    active: true
    parameterPattern: '[a-z][A-Za-z0-9]*'
    privateParameterPattern: '[a-z][A-Za-z0-9]*'
    excludeClassPattern: '$^'
  EnumNaming:
    active: true
    enumEntryPattern: '^[A-Z][_a-zA-Z0-9]*'
  ForbiddenClassName:
    active: false
    forbiddenName: ''
  FunctionMaxLength:
    active: false
    maximumFunctionNameLength: 30
  FunctionMinLength:
    active: false
    minimumFunctionNameLength: 3
  FunctionNaming:
    active: true
    functionPattern: '^([a-z$][a-zA-Z$0-9]*)|(`.*`)$'
    excludeClassPattern: '$^'
  FunctionParameterNaming:
    active: true
    parameterPattern: '[a-z][A-Za-z0-9]*'
    excludeClassPattern: '$^'
  MatchingDeclarationName:
    active: true
  MemberNameEqualsClassName:
    active: false
    ignoreOverriddenFunction: true
  ObjectPropertyNaming:
    active: true
    constantPattern: '[A-Za-z][_A-Za-z0-9]*'
    propertyPattern: '[A-Za-z][_A-Za-z0-9]*'
    privatePropertyPattern: '(_)?[A-Za-z][A-Za-z0-9]*'
  PackageNaming:
    active: true
    packagePattern: '^[a-z]+(\.[a-z][a-z0-9]*)*$'
  TopLevelPropertyNaming:
    active: true
    constantPattern: '[A-Z][_A-Z0-9]*'
    propertyPattern: '[A-Za-z][_A-Za-z0-9]*'
    privatePropertyPattern: '(_)?[A-Za-z][A-Za-z0-9]*'
  VariableMaxLength:
    active: false
    maximumVariableNameLength: 64
  VariableMinLength:
    active: false
    minimumVariableNameLength: 1
  VariableNaming:
    active: true
    variablePattern: '[a-z][A-Za-z0-9]*'
    privateVariablePattern: '(_)?[a-z][A-Za-z0-9]*'
    excludeClassPattern: '$^'

performance:
  active: true
  ForEachOnRange:
    active: true
  SpreadOperator:
    active: true
  UnnecessaryTemporaryInstantiation:
    active: true

potential-bugs:
  active: true
  DuplicateCaseInWhenExpression:
    active: true
  EqualsAlwaysReturnsTrueOrFalse:
    active: false
  EqualsWithHashCodeExist:
    active: true
  ExplicitGarbageCollectionCall:
    active: true
  InvalidRange:
    active: false
  IteratorHasNextCallsNextMethod:
    active: false
  IteratorNotThrowingNoSuchElementException:
    active: false
  LateinitUsage:
    active: false
    excludeAnnotatedProperties: ""
    ignoreOnClassesPattern: ""
  UnconditionalJumpStatementInLoop:
    active: false
  UnreachableCode:
    active: true
  UnsafeCallOnNullableType:
    active: false
  UnsafeCast:
    active: false
  UselessPostfixExpression:
    active: false
  WrongEqualsTypeParameter:
    active: false

style:
  active: true
  CollapsibleIfStatements:
    active: false
  DataClassContainsFunctions:
    active: false
    conversionFunctionPrefix: 'to'
  EqualsNullCall:
    active: false
  ExpressionBodySyntax:
    active: false
    includeLineWrapping: false
  ForbiddenComment:
    active: true
    values: 'TODO:,FIXME:,STOPSHIP:'
  ForbiddenImport:
    active: false
    imports: ''
  ForbiddenVoid:
    active: false
  FunctionOnlyReturningConstant:
    active: false
    ignoreOverridableFunction: true
    excludedFunctions: 'describeContents'
  LoopWithTooManyJumpStatements:
    active: false
    maxJumpCount: 1
  MagicNumber:
    active: true
    ignoreNumbers: '-1,0,1,2'
    ignoreHashCodeFunction: true
    ignorePropertyDeclaration: false
    ignoreConstantDeclaration: true
    ignoreCompanionObjectPropertyDeclaration: true
    ignoreAnnotation: false
    ignoreNamedArgument: false
    ignoreEnums: false
  MandatoryBracesIfStatements:
    active: false
  MaxLineLength:
    active: true
    maxLineLength: 100
    excludePackageStatements: true
    excludeImportStatements: true
    excludeCommentStatements: false
  MayBeConst:
    active: false
  ModifierOrder:
    active: true
  NestedClassesVisibility:
    active: false
  NewLineAtEndOfFile:
    active: false
  NoTabs:
    active: true
  OptionalAbstractKeyword:
    active: true
  OptionalUnit:
    active: false
  OptionalWhenBraces:
    active: false
  PreferToOverPairSyntax:
    active: false
  ProtectedMemberInFinalClass:
    active: false
  RedundantVisibilityModifierRule:
    active: false
  ReturnCount:
    active: true
    max: 2
    excludedFunctions: "equals"
  SafeCast:
    active: true
  SerialVersionUIDInSerializableClass:
    active: false
  SpacingBetweenPackageAndImports:
    active: true
  ThrowsCount:
    active: true
    max: 2
  TrailingWhitespace:
    active: false
  UnnecessaryAbstractClass:
    active: false
    excludeAnnotatedClasses: "dagger.Module"
  UnnecessaryInheritance:
    active: false
  UnnecessaryParentheses:
    active: false
  UntilInsteadOfRangeTo:
    active: false
  UnusedImports:
    active: true
  UnusedPrivateMember:
    active: true
    allowedNames: "(_|ignored|expected|serialVersionUID)"
  UseDataClass:
    active: false
    excludeAnnotatedClasses: ""
  UtilityClassWithPublicConstructor:
    active: false
  VarCouldBeVal:
    active: false
  WildcardImport:
    active: true
    excludeImports: 'java.util.*,kotlinx.android.synthetic.*'
`

The build.gradle I am using are following the recommended from the website, I can post it here if it is necessary.

**Comment by esanchos** [comment]
Hi guys, I am trying to use RC10 but I am getting following error:

`
Could not find gradle.plugin.io.gitlab.arturbosch.detekt:detekt-gradle-plugin:1.0.0-RC10.
Searched in the following locations:
  - https://dl.google.com/dl/android/maven2/gradle/plugin/io/gitlab/arturbosch/detekt/detekt-gradle-plugin/1.0.0-RC10/detekt-gradle-plugin-1.0.0-RC10.pom
  - https://dl.google.com/dl/android/maven2/gradle/plugin/io/gitlab/arturbosch/detekt/detekt-gradle-plugin/1.0.0-RC10/detekt-gradle-plugin-1.0.0-RC10.jar
  - https://jcenter.bintray.com/gradle/plugin/io/gitlab/arturbosch/detekt/detekt-gradle-plugin/1.0.0-RC10/detekt-gradle-plugin-1.0.0-RC10.pom
  - https://jcenter.bintray.com/gradle/plugin/io/gitlab/arturbosch/detekt/detekt-gradle-plugin/1.0.0-RC10/detekt-gradle-plugin-1.0.0-RC10.jar
  - https://plugins.gradle.org/m2/gradle/plugin/io/gitlab/arturbosch/detekt/detekt-gradle-plugin/1.0.0-RC10/detekt-gradle-plugin-1.0.0-RC10.pom
  - https://plugins.gradle.org/m2/gradle/plugin/io/gitlab/arturbosch/detekt/detekt-gradle-plugin/1.0.0-RC10/detekt-gradle-plugin-1.0.0-RC10.jar
  - https://plugins.gradle.org/m2/gradle/plugin/io/gitlab/arturbosch/detekt/detekt-gradle-plugin/1.0.0-RC10/detekt-gradle-plugin-1.0.0-RC10.pom
  - https://plugins.gradle.org/m2/gradle/plugin/io/gitlab/arturbosch/detekt/detekt-gradle-plugin/1.0.0-RC10/detekt-gradle-plugin-1.0.0-RC10.jar
`

Is RC10 already published?

Thank you.

**Comment by arturbosch** [comment]
Hey, try using `classpath "io.gitlab.arturbosch.detekt:detekt-gradle-plugin:[version]"` as was reported in #1315. I do not think that we have changed anything here :/.
Please confirm if formatting autoCorrect still does not work for you with RC10.

**Comment by esanchos** [comment]
Hi, thanks for your support.

Yes, I am trying to validate the autoCorrect issue. But now, I am facing another problem:

I am trying to include the format dependency as:
detektPlugins "io.gitlab.arturbosch.detekt:detekt-formatting:${detekt_version}"

But getting following error:
"Could not find method detektPlugins() for arguments [io.gitlab.arturbosch.detekt:detekt-formatting:1.0.0-RC10] on object of type org.gradle.api.internal.artifacts.dsl.dependencies.DefaultDependencyHandler."

I did also tryed with:
detekt "io.gitlab.arturbosch.detekt:detekt-formatting:${detekt_version}"

But problem still the same.

Any tip on this?

This is my project's build.gradle:
<pre>
// Top-level build file where you can add configuration options common to all sub-projects/modules.

buildscript {
    ext.kotlin_version = '1.2.71'
    ext.detekt_version = '1.0.0-RC10'
    repositories {
        google()
        jcenter()
        maven {
            url "https://plugins.gradle.org/m2/"
        }
    }
    dependencies {
        classpath 'com.android.tools.build:gradle:3.2.1'
        classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:$kotlin_version"
        classpath 'com.google.gms:google-services:4.1.0'
        classpath "io.gitlab.arturbosch.detekt:detekt-gradle-plugin:${detekt_version}"

        // NOTE: Do not place your application dependencies here; they belong
        // in the individual module build.gradle files
    }
}

plugins {
    id "io.gitlab.arturbosch.detekt" version "1.0.0-RC10"
}

apply from: 'versions.gradle'

allprojects {
    repositories {
        google()
        jcenter()
    }
}

task clean(type: Delete) {
    delete rootProject.buildDir
}

detekt {
    toolVersion = "${detekt_version}"                     // Version of the Detekt CLI that will be used. When unspecified the latest detekt version found will be used. Override to stay on the same version.
    input = files(                                        // The directories where detekt looks for input files. Defaults to `files("src/main/java", "src/main/kotlin")`.
            "fsanalytics/src/main/java"
    )
    parallel = false                                      // Runs detekt in parallel. Can lead to speedups in larger projects. `false` by default.
    config = files("tools/detekt/detekt-config.yml")      // Define the detekt configuration(s) you want to use. Defaults to the default detekt configuration.
    //baseline = file("path/to/baseline.xml")               // Specifying a baseline file. All findings stored in this file in subsequent runs of detekt.
    //filters = ''                                          // Regular expression of paths that should be excluded separated by `;` or `,`.
    //disableDefaultRuleSets = false                        // Disables all default detekt rulesets and will only run detekt with custom rules defined in `plugins`. `false` by default.
    //plugins = "other/optional/ruleset.jar"                // Additional jar file containing custom detekt rules.
    debug = false                                         // Adds debug output during task execution. `false` by default.
    reports {
        xml {
            enabled = true                                // Enable/Disable XML report (default: true)
            destination = file("build/reports/detekt.xml")  // Path where XML report will be stored (default: `build/reports/detekt/detekt.xml`)
        }
        html {
            enabled = true                                // Enable/Disable HTML report (default: true)
            destination = file("build/reports/detekt.html") // Path where HTML report will be stored (default: `build/reports/detekt/detekt.html`)
        }
    }
}

apply plugin: 'io.gitlab.arturbosch.detekt
</pre>

And this is the snap of app's build.gradle:
<pre>
...

dependencies {
    implementation fileTree(dir: 'libs', include: ['*.jar'])
    implementation"org.jetbrains.kotlin:kotlin-stdlib-jdk7:$kotlin_version"
    implementation "com.android.support:appcompat-v7:${rootProject.supportLibrary}"
    implementation "com.android.support.constraint:constraint-layout:${rootProject.constraint}"
    detektPlugins "io.gitlab.arturbosch.detekt:detekt-formatting:${detekt_version}"
    implementation project(path: ':fsanalytics')
}
apply plugin: 'io.gitlab.arturbosch.detekt'
</pre>

**Comment by arturbosch** [comment]
Which gradle version do you use? detekt >= RC9 needs gradle 4.9 or higher.
I do not know about the android kind of projects, but try to move the `apply pugin: ...` part to the build file of the app?
And also the `detekt-extensions` and the dependency on formatting to a subprojects closure?

**Comment by esanchos** [comment]
Hi,

I tested with 1.0.0-RC11 and it is fixed.

Thank you!
