### ISSUE TITLE
[Gradle] Don't fail the build if baseline file is missing

### ISSUE THREAD

**Issue by Tapchicoma** [arturbosch/detekt#1265]
## Expected Behavior
I've applied detekt gradle plugin and set common configuration for all modules. In this configuration I've defined baseline file, but when I run `detekt` task and baseline file for this module is missing - task fails.

I expect that task will ignore missing baseline file and if there is no issues - completes successfully. Otherwise I have to create a baseline file for each module.

## Observed Behavior
Gradle `detekt` task fails if baseline file is missing.

## Steps to Reproduce
1. Define `baseline = file("some/path/to/file")` in `detekt {}` configuration.
2. Run `detekt` task.

## Context
I want to have common detekt configuration for all modules, and add some issues module baseline file if I don't have time to fix them now.

## Your Environment
* Version of detekt used: `1.0.0.RC9.2`
* Operating System and version: `Gentoo linux`
* Link to your project (if it's a public repository): private repo

**Comment by marschwar** [comment]
I am a little bit torn on the issue. On the one hand the user intentionally configured a baseline file to be used and if it is not there, something seems to be wrong and must be reported. On the other hand I see your point that you expect a newly added sub project without any code smells not cause the task to fail.

Since sub projects do not appear out of thin air and creating an empty baseline is not hard, I am actually fine with the current behavior. I could also see us ignoring a missing baseline file but issuing a warning in such case. 

What do you guys think?

**Comment by Tapchicoma** [comment]
Ok, a little more about my use-case:
- we had in the project 6 fat modules, that didn't apply detekt checks before.
- now we enabled detekt for all modules in the project and are moving towards much granular modules
- we want to solve detekt issue in this fat modules only when we are moving code from it to more granular modules or when we have to add new code to it.
- that means that there should be a baseline file for fat modules
- detekt configuration is shared in single `detekt.gradle` file and applied to all modules
- now I need to create about 50 baseline files that doesn't contain anything, and will not contain something in the future. And number of this useless baseline files will grow over time.

Personally, I don't see the point of having mandatory empty baseline file, if there are no issues in the module. And this issue can be solved only on gradle plugin level, not touching detekt itself. Gradle plugin should not pass baseline option if baseline file does not exist.

**Comment by Tapchicoma** [comment]
> In each module/subproject for which you want to create a baseline, set the following in the module's build.gradle file

Yes, this approach should work :+1: 

> Explicit is better than implicit and we should not change this. Currently, we are also consistent with Android Lint and it's baseline behaviour.

Valid point.
