### ISSUE TITLE
Drop rules that ktlint implements

### ISSUE THREAD

**Issue by 3flex** [arturbosch/detekt#1281]
## Expected Behavior
Rules that are implemented in ktlint should not be reimplemented in detekt.

## Current Behavior
Some rules are duplicated in both tools:
* max line length
* modifier order
* returning `Unit` from function
* unused imports
* wildcard imports
* indent with spaces not tabs
* empty class block
* new line at end of file

May be others but that illustrates the point.

## Context
Detekt has a wrapper for ktlint rules, so it's easy to apply ktlint's formatting rules when detekt is run. It doesn't make sense to duplicate effort for formatting rules - I understand the direction is for detekt to avoid implementing formatting rules (unless they're not implemented by ktlint for some reason).

**Comment by arturbosch** [comment]
Lets first turn them off, see what people will say and one version later remove them?

**Comment by 3flex** [comment]
Could do that, maybe show a deprecation message if they're enabled with a note to comment on this issue?

I think auto formatter should also be disabled by default for all wrapped ktlint rules, users should have to override the default config to enable if they want to.

**Comment by 3flex** [comment]
> activate autoCorrect for us in failfast.yml
You want ktlint auto correct enabled for detekt itself?

**Comment by schalkms** [comment]
I would like to leave them as they are. I don't to see a reason to remove them. 
However, we shouldn't invest any more time in the development of these rules.

**Comment by arturbosch** [comment]
Actually me too. There are teams which do not rely on formatting tools or do not even trust them.
If the eager detekt user wants formatting, he can turn off the suggested rules.
