### ISSUE TITLE
Add test coverage report for detekt project

### ISSUE THREAD

**Issue by 3flex** [arturbosch/detekt#1285]
## Expected Behavior
After tests run, a test coverage report is available.

## Current Behavior
No test coverage report is available.

## Context
Improving test coverage is a worthy goal!

Apparently Jacoco works with Kotlin & Spek, haven't looked for other options. Once reporting properly in local builds can add a service like Coveralls or Codecov (Codecov has a [Kotlin sample](https://github.com/codecov/example-kotlin)).

**Comment by schalkms** [comment]
duplicate #301

**Comment by schalkms** [comment]
I would be glad if someone has time to pick this up.
