### ISSUE TITLE
Detekt 1.0.0.RC9.2 Build Fails

### ISSUE THREAD

**Issue by ziziana** [arturbosch/detekt#1288]
Hi, 
I am trying to setup Detekt into my new Android project, but when I run `./gradlew detektCheck` I receive this message:

```
FAILURE: Build failed with an exception.

* What went wrong:
Task 'detektCheck' not found in root project 
```

The project **gradle file** looks like this:
```
buildscript {
    ext.kotlin_version = '1.2.71'
    repositories {
        google()
        jcenter()
        
    }
    dependencies {
        classpath 'com.android.tools.build:gradle:3.4.0-alpha02'
        classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:$kotlin_version"
        // NOTE: Do not place your application dependencies here; they belong
        // in the individual module build.gradle files
    }
}

plugins {
    id "io.gitlab.arturbosch.detekt" version "1.0.0.RC9.2"
}

allprojects {
    repositories {
        google()
        jcenter()
        
    }
}

task clean(type: Delete) {
    delete rootProject.buildDir
}

apply plugin: 'io.gitlab.arturbosch.detekt'

detekt {
    input = files("$projectDir/app/src")
    parallel = false
    config = files("$projectDir/detekt.yml")
    filters = ".*test.*,.*/resources/.*"
    plugins = "$projectDir/lib/detect-custom-ruleset.jar"
    debug = true
    reports {
        xml {
            enabled = true
            destination = file("detekt/reports/detekt.xml")
        }
        html {
            enabled = true
            destination = file("detekt/reports/detekt.html")
        }
    }
}
```

Am I doing something wrong? Thanks!

**Comment by ziziana** [comment]
It was something wrong in the MainActivty.kt.

**Comment by KChernenko** [comment]
I have the same issue.

**Comment by KolinLoures** [comment]
Try to **./gradlew detekt**

**Comment by schalkms** [comment]
A change was introduced with RC9. 
> There is no detektCheck task anymore, just a detekt task which is incremental and is bound to the check task.

[Changelog reference](https://arturbosch.github.io/detekt/changelog.html#rc9)

**Comment by ziziana** [comment]
I've already tried that but it generates empty reports. Is my setup wrong?

**Comment by KolinLoures** [comment]
Yes, i have same issue. It does not generate reports at all.

**Comment by arturbosch** [comment]
Hm try removing the `apply plugin: detekt` line as this is done by the `plugins {...}` part.
Hm maybe try moving the detekt closure inside the allprojects block and try if it does anything.
I just tried configurating detekt on the top level project like you do and everything runs.

**Comment by CatalinPrata** [comment]
It turns out that if I comment "plugins = "$projectDir/lib/detect-custom-ruleset.jar"", I get some values in the html output, so it might be because of that plugin.

**Comment by arturbosch** [comment]
Hey,
where do you have `detect-custom-ruleset.jar` from?
A rule `TooManyFunctions` crashes because the `detekt-api` is not binary compatible with the default `detekt-rules`.
You can spot this when rules are crashing in the `init` block.

**Comment by ziziana** [comment]
Hey,
That jar is from a different github project (someone made an example but with an older version of Detekt) [](https://github.com/DSamaryan/kotlindetect/tree/master/lib). With the older version worked for me too, but after I updated Detekt to the latest version RC9.2, I got the errors I mentioned above on this issue.

**Comment by schalkms** [comment]
This plugin seems to be out of date, since the last commit from this 3rd party repository is from `15 July 2017`. A lot changed since then. Do you use specific rules from this plugin?

**Comment by schalkms** [comment]
I'm closing this, since the issue was identified.
