### ISSUE TITLE
Rule: Modifier order

### ISSUE THREAD

**Issue by scottkennedy** [arturbosch/detekt#129]
`private lateinit var` vs. `lateinit private var`

Both are valid in Kotlin, but I'd like the ability to enforce one.

**Comment by vanniktech** [comment]
They defined the modifier order somewhere. I can't find the exact link although [kotlinpoet](https://github.com/square/kotlinpoet/blob/2efc8478173c6c78d3012eb1254b624cf12aa88f/src/main/java/com/squareup/kotlinpoet/KModifier.kt) copied the order.

**Comment by Mauin** [comment]
This issue in the Kotlin Style Guide repo mentions the order: https://github.com/yole/kotlin-style-guide/issues/3.

ktlint also has a `ModifierOrderRule`. See: https://github.com/shyiko/ktlint/blob/master/ktlint-ruleset-standard/src/main/kotlin/com/github/shyiko/ktlint/ruleset/standard/ModifierOrderRule.kt#L35
