### ISSUE TITLE
Drop FunctionMinLength & FunctionMaxLength

### ISSUE THREAD

**Issue by vanniktech** [arturbosch/detekt#1290]
Looking at the inspections of IntelliJ it seems like it does not validate against min/max length. Glancing over the conventions / style guides I also could not find any restrictions.

**Comment by schalkms** [comment]
I don't think that this is good idea. I for one use this rule quite frequently.
In my opinion such a reasonable guideline for function naming makes sense.

As previously said, we should let the user decide. There's always the option in detekt to disable this rule, if you have no need for it.

**Comment by vanniktech** [comment]
`FunctionMaxLength` I might agree.

With `FunctionMinLength` it's hard. Often you have functions like `id` which are flagged. Same for logging verbosity such as `d`, `i`, `e`, `w` which also get flagged.

**Comment by vanniktech** [comment]
Another one is `io`

**Comment by arturbosch** [comment]
As @schalkms said its a good thing that detekt is highly configurable and the user is free to set his defaults as he wants. These rules are also off by default.
