### ISSUE TITLE
Set current directory as default input path

### ISSUE THREAD

**Issue by 3flex** [arturbosch/detekt#1301]
## Expected Behavior
When I run detekt on the CLI without specifying `--input`, the CLI will scan the current working directory and subdirectories.

## Current Behavior
detekt requires a path to be set for `--input`

## Context
Makes CLI a little more friendly to use :)

**Comment by arturbosch** [comment]
Yes, good defaults are important but I also think that many will do the mistake to run it on their home folder :D.

**Comment by vanniktech** [comment]
Then they get everything reported once and be doomed for the rest of their life. Joke aside. I would like it too.

**Comment by schalkms** [comment]
Good point. This definitely makes sense.

**Comment by 3flex** [comment]
Closed by #1308 merge.
