### ISSUE TITLE
Should rule providers have their own package or live in the according package

### ISSUE THREAD

**Issue by Mauin** [arturbosch/detekt#131]
While browsing the `detekt-rules` module I noticed that some of the `RuleSetProvider` classes live in the `... .detekt.rules.providers` package. Other providers live in their according package. An example is the `StyleGuideProvider` which lives in the `... .detekt.rules.style` package.

Should the providers rather be together in the providers package or should each provider be next to the rules in the according package?

**Comment by arturbosch** [comment]
First I thought "oh whole domain for each specific rule set is nice, why not", later I realized I forget the names of the providers and browse for them. This takes time, so the providers package should contain all providers. I'm a bit lazy and only move the providers to the new package if I work on them or their rules ^^

**Comment by Mauin** [comment]
I can create a quick PR to move the providers together 👍
