### ISSUE TITLE
Ignore FunctionOnlyReturningConstant for Dagger provides methods

### ISSUE THREAD

**Issue by vanniktech** [arturbosch/detekt#1313]
It's common when using Dagger to have methods that are annotated with `dagger.Provides` to only return some hardcoded data. Such as:

```kotlin
@Provides
@ApplicationScope
@Named("deviceId")
fun provideDeviceId(): String {
  return "fake-device-id"
}
```

Currently this gets flagged by `FunctionOnlyReturningConstant`. I think it's best to provide some custom annoations similiar to #377 and default to `dagger.Provides`.

**Comment by schalkms** [comment]
In my opinion this is good go. Please provide a list of annotations which should be excluded.

**Comment by vanniktech** [comment]
So far I've only seen `dagger.Provides`
