### ISSUE TITLE
Provide example for UnsafeCallOnNullableType

### ISSUE THREAD

**Issue by christopheblin** [arturbosch/detekt#1320]
The closest existing issue to my question is #202

    fun doSomething(f: Form?) -> Boolean {
       if (f == || ! f.validate()) throw ValidationException("validation")
       val dbRow = DbRow(name = f.name!!) //this triggers the rule
    }
    data class Form(val name:String?) {
        fun validate() = !f.name.isNullOrEmpty()
    }
    data class DbRow(val name: String)

Here, you can see that after calling validate, I am sure that name is not null.
However, detekt does not match that (which I understand)

I am using this "pattern" a lot because if I declare the name attribute as not nullable in Form, the callers of my API do not receive a proper 400 HTTP status code (they receive a ugly 500 from the JSON deserializer)

Is there a proper way to deal with that situation ?

**Comment by schalkms** [comment]
As mentioned in the referenced issue a full data flow analysis would be out of scope for detekt.
I would recommend a [custom rule](https://arturbosch.github.io/detekt/extensions.html#custom-rulesets), if you are using this pattern quite often and want to lint it.

**Comment by schalkms** [comment]
Closed as this is out of scope.
