### ISSUE TITLE
Script: Compare detekt issues for same project with different versions

### ISSUE THREAD

**Issue by arturbosch** [arturbosch/detekt#1338]
## Expected Behavior
Allow to easily compare differences in findings for QA

## Current Behavior
get_analysis_projects script is good, but still much manual work is required.

## Context
Before a release I want to compare the findings of some popular kotlin projects.

**Comment by arturbosch** [comment]
I've implemented a first version of this script which uses `failFast` to look for any changes between two versions.
Automatically judging any differences (false positives fixes etc) is hard, so I think an interactive approach to release could fit here.

The interactive approach could consists of multiple steps combined in a wizard-like script:
- User action: set version
- build & check
- compare results with failFast
- User action: accept or decline differences if any
- gradle bintrayUpload
- gradle publishPlugin
- github cli upload

**Comment by schalkms** [comment]
Closed with eda9f86
