### ISSUE TITLE
RC10 not published?

### ISSUE THREAD

**Issue by menjoo** [arturbosch/detekt#1339]
Hi,

Im looking at https://plugins.gradle.org/m2/gradle/plugin/io/gitlab/arturbosch/detekt/detekt-gradle-plugin/ 
and don't see the latest version RC10 in there. Is this intended? (I would like to update to the version where Travis not picking up .kt files was fixed).

**Comment by arturbosch** [comment]
Hm, it seems like the new url is now:
`https://plugins.gradle.org/m2/io/gitlab/arturbosch/detekt/detekt-gradle-plugin/`.
There I see the RC10. Idk why this got changed as we haven't changed anything in the publishing process oO.

**Comment by Mauin** [comment]
Can we re-publish RC10 & RC11 under the old paths? Otherwise every user would have to switch to the new one which might leave us with quite a few users on old versions.

**Comment by Mauin** [comment]
Taking a look at the diff between RC9.2 and RC10 there were a few changes to the Gradle Plugin (local Gradle Wrapper was removed) 

We also enabled `enableFeaturePreview("STABLE_PUBLISHING")` which in the documentation mentions in the docs:
>We recommend doing a test run with a local repository to see whether all artifacts still have the expected coordinates. In most cases everything should work as before and you are done.

https://docs.gradle.org/current/userguide/publishing_maven.html#publishing_maven:deferred_configuration

See diff: https://github.com/arturbosch/detekt/compare/RC9.2..RC10

**Comment by Mauin** [comment]
I'm not saying to revert the naming. I'm suggesting to re-publish the two latest (and any new upcoming release) under the old naming scheme as well. Changing the artifact path without any notice seems like a huge breaking change to me.

**Comment by arturbosch** [comment]
Just removing the `preview-feature` does not help yet, publishing again says this version is already up.
So this problem only occur to people using the classpath configuration but not for `plugins{...}`?
I will just add more migration info for this change...
