### ISSUE TITLE
UnsafeCast in reified context

### ISSUE THREAD

**Issue by realdadfish** [arturbosch/detekt#1356]
Consider the following code:

```
inline fun <reified T> Fragment.findCallback(): T = when {
    parentFragment is T -> parentFragment as T
    targetFragment is T -> targetFragment as T
    context is T -> context as T
    else -> throw IllegalStateException("Neither parent, target or context implement " + T::class.java)
}
```

This is flagged by Detekt with `UnsafeCast` in all three places where a cast happens, even though the specific branch is properly instance-tested before. 

## Your Environment
* Version of detekt used: 1.0.0-RC10
* Version of Gradle used (if applicable): 4.10
* Operating System and version: macOS

**Comment by realdadfish** [comment]
Hrm... by looking closer at it I don't know if Detekt can actually do this, because all these properties are actually Java method calls that could _potentially_ return a different instance, even though they would not in this particular example.

**Comment by schalkms** [comment]
I think we should be in line with other issues concerning this topic. (linking #1320 and #202 )
As already said we would need data flow analysis for this to work, which is out of scope of detekt.
So I'd argue that we should close this.

**Comment by realdadfish** [comment]
Would this be something that the new Contracts could somehow help solving? I. E. if on the Android side some contract annotation would be added to verify that the condition, once checked, would still be valid in the next step? Or are contracts not verifiable through Detekt?

Of course, this is academic, as of now no such annotation exists on the Android side. 

Am 27. November 2018 18:36:04 MEZ schrieb M Schalk <notifications@github.com>:
>I think we should be in line with other issues concerning this topic.
>(linking #1320 and #202 )
>As already said we would need data flow analysis for this to work,
>which is out of scope of detekt.
>So I'd argue that we should close this.
>
>-- 
>You are receiving this because you authored the thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/arturbosch/detekt/issues/1356#issuecomment-442148676

-- 
Diese Nachricht wurde von meinem Android-Gerät mit K-9 Mail gesendet.

**Comment by schalkms** [comment]
> Would this be something that the new Contracts could somehow help solving?

Could you please elaborate what you actually want to solve here?
Detekt has not touched Kotlin contracts yet. They are still experimental.
I don't quite get what you want to verify with contracts in detekt.

**Comment by realdadfish** [comment]
Well, the idea was that if there is a contract behind a call, say something that ensures the state of something, that Detekt would then figure out this contract's state and act accordingly. But I guess that is not applicable for this issue.

**Comment by schalkms** [comment]
Not so far.
For your use case one could reuse APIs from the compiler if they exist.
We are planning to use Kotlin compiler features like type and symbol solving in the future.
There's no need to reimplement everything from scratch.
