### ISSUE TITLE
"Latest version" on Maven Central repository is not the latest version

### ISSUE THREAD

**Issue by 3flex** [arturbosch/detekt#1366]
## Expected Behavior
"Latest version" field on MavenCentral shows the correct latest version of each artifact (1.0.0-RC11 at time of submitting this issue).

## Observed Behavior
Mix of versions are shown as "latest". None of the artifacts in the `io.gitlab.arturbosch.detekt` group show 1.0.0-RC11 as the latest version.

## Steps to Reproduce
See https://search.maven.org/search?q=g:io.gitlab.arturbosch.detekt

## Context
Likely occurred because of format switch from `.` before the `RC` to `-` before the `RC`.

These are the version ordering rules for Maven:
https://maven.apache.org/ref/3.6.0/maven-artifact/apidocs/org/apache/maven/artifact/versioning/ComparableVersion.html

Note:
> a hyphen usually precedes a qualifier, and is always less important than something preceded with a dot

So the releases with dot separator is treated by Maven as more recent than the hyphen in the same position in the version number.

Suggest switching back to the old convention until the final release goes out.

Suggest in future referring to the ComparableVersion docs before choosing a new versioning scheme (or just use SemVer once the RC phase ends).

## Your Environment
N/A

**Comment by arturbosch** [comment]
This should be fixed when we have 1.x.x up ?
I played with the idea to just release 1.0.0 for all detekt modules except the gradle-plugin.
We are kinda "feature complete" for the first version/e.g. where I wanted detekt to be when calling it 1.0.
The api module is also kinda stable.
The gradle plugin can stay in rc phase until we are happy with it.

**Comment by 3flex** [comment]
> I played with the idea to just release 1.0.0

I'd raised https://github.com/arturbosch/detekt/issues/1206 to start a discussion on that... do you want to pick up the conversation there?

I'm closing this issue since as you say there's not really anything that can be done about it, but please follow semver once 1.0.0 is released (and as you said, that _should_ fix the "latest version", since all releases up until now have had a "qualifier" at the end of the version name, and since `1.0.0` doesn't have a qualifier it should be treated as a higher version than versions with the `rc` or `m` qualifier).

**Comment by schalkms** [comment]
@3flex the versioning got messed up with the release candidates. With v1 detekt should follow the semver pattern mentioned in the linked issue.

**Comment by arturbosch** [comment]
@3flex thanks I will! Semver is coming :)
