### ISSUE TITLE
LazyRegex implementation rethrow any failures with a custom error stating that the regex to configure is wrong

### ISSUE THREAD

**Issue by gellertbiro** [arturbosch/detekt#1369]
Analyzing 'every project file/path' led to an exception.
Running detekt 'unknown' on Java '1.8.0_192-b12' on OS 'Mac OS X'.
Please create an issue and report this exception.
java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:273)
java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:280)
java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1592)
java.util.concurrent.CompletableFuture$AsyncSupply.exec(CompletableFuture.java:1582)
java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)
java.util.regex.Pattern.error(Pattern.java:1957)
java.util.regex.Pattern.range(Pattern.java:2657)
java.util.regex.Pattern.clazz(Pattern.java:2564)
java.util.regex.Pattern.sequence(Pattern.java:2065)
java.util.regex.Pattern.expr(Pattern.java:1998)
java.util.regex.Pattern.group0(Pattern.java:2907)
java.util.regex.Pattern.sequence(Pattern.java:2053)
java.util.regex.Pattern.expr(Pattern.java:1998)
java.util.regex.Pattern.compile(Pattern.java:1698)
java.util.regex.Pattern.<init>(Pattern.java:1351)
java.util.regex.Pattern.compile(Pattern.java:1028)
kotlin.text.Regex.<init>(Regex.kt:93)
io.gitlab.arturbosch.detekt.api.LazyRegex.createRegex(LazyRegex.kt:28)
io.gitlab.arturbosch.detekt.api.LazyRegex.getValue(LazyRegex.kt:24)
io.gitlab.arturbosch.detekt.rules.naming.PackageNaming.getPackagePattern(PackageNaming.kt)
io.gitlab.arturbosch.detekt.rules.naming.PackageNaming.visitPackageDirective(PackageNaming.kt:30)
io.gitlab.arturbosch.detekt.rules.naming.NamingRules$visitPackageDirective$1.invoke(NamingRules.kt:57)
io.gitlab.arturbosch.detekt.rules.naming.NamingRules$visitPackageDirective$1.invoke(NamingRules.kt:21)
io.gitlab.arturbosch.detekt.api.MultiRule.runIfActive(MultiRule.kt:27)
io.gitlab.arturbosch.detekt.rules.naming.NamingRules.visitPackageDirective(NamingRules.kt:57)
org.jetbrains.kotlin.psi.KtVisitorVoid.visitPackageDirective(KtVisitorVoid.java:1049)
org.jetbrains.kotlin.psi.KtVisitorVoid.visitPackageDirective(KtVisitorVoid.java:21)
org.jetbrains.kotlin.psi.KtPackageDirective.accept(KtPackageDirective.java:181)
org.jetbrains.kotlin.psi.KtElementImplStub.accept(KtElementImplStub.java:59)
org.jetbrains.kotlin.com.intellij.psi.impl.source.tree.SharedImplUtil.acceptChildren(SharedImplUtil.java:200)
org.jetbrains.kotlin.com.intellij.psi.impl.source.PsiFileImpl.acceptChildren(PsiFileImpl.java:728)
org.jetbrains.kotlin.psi.KtTreeVisitorVoid.visitElement(KtTreeVisitorVoid.java:25)
org.jetbrains.kotlin.com.intellij.psi.PsiElementVisitor.visitFile(PsiElementVisitor.java:34)
org.jetbrains.kotlin.psi.KtVisitor.visitKtFile(KtVisitor.java:73)
org.jetbrains.kotlin.psi.KtVisitorVoid.visitKtFile(KtVisitorVoid.java:69)
org.jetbrains.kotlin.psi.KtVisitorVoid.visitKtFile(KtVisitorVoid.java:513)
org.jetbrains.kotlin.psi.KtVisitorVoid.visitKtFile(KtVisitorVoid.java:21)
org.jetbrains.kotlin.psi.KtFile.accept(KtFile.kt:221)
org.jetbrains.kotlin.psi.KtFile.accept(KtFile.kt:208)
io.gitlab.arturbosch.detekt.api.BaseRule.visit(BaseRule.kt:26)
io.gitlab.arturbosch.detekt.api.BaseRule.visitFile(BaseRule.kt:20)
io.gitlab.arturbosch.detekt.api.RuleSet.accept(RuleSet.kt:22)
io.gitlab.arturbosch.detekt.core.Detektor.analyze(Detektor.kt:60)
io.gitlab.arturbosch.detekt.core.Detektor.access$analyze(Detektor.kt:15)
io.gitlab.arturbosch.detekt.core.Detektor$run$1$$special$$inlined$map$lambda$1.invoke(Detektor.kt:29)
io.gitlab.arturbosch.detekt.core.Detektor$run$1$$special$$inlined$map$lambda$1.invoke(Detektor.kt:15)
io.gitlab.arturbosch.detekt.core.TasksKt$runAsync$1.invoke(Tasks.kt:23)
io.gitlab.arturbosch.detekt.core.TasksKt$task$1.get(Tasks.kt:27)
java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1590)
java.util.concurrent.CompletableFuture$AsyncSupply.exec(CompletableFuture.java:1582)
java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)

## Context
This happens for all of the files.

## Your Environment
I have a multi-module project. The setup is the following:

```
plugins {
    id("io.gitlab.arturbosch.detekt").version("1.0.0-RC11")
}

...

subprojects {
  ...

    apply plugin: 'io.gitlab.arturbosch.detekt'

    detekt {
        toolVersion = "1.0.0-RC11"
        config = files("${project.rootDir}/detekt-config.yml")
        filters = ".*/resources/.*,./*build/.*"
    }
}
```

Note: the same exception has been thrown for all the files on the CI server as well.

**Comment by Mauin** [comment]
What is the regex you have configured in your `detekt-config.yml` for the `PackageNaming` rule?

**Comment by gellertbiro** [comment]
@Mauin 
`  packagePattern: '^[a-z]+(\.[a-z][a-Z0-9]*)*$'`

**Comment by Mauin** [comment]
This is an issue with the regex pattern you're passing in the config which causes this exception. To compare:

`^[a-z]+(\.[a-z][a-Z0-9]*)*$ // your pattern`
`^[a-z]+(\.[a-z][a-z0-9]*)*$ // default detekt pattern`

Note the uppercase `Z` character in your pattern. As the uppercase characters are before the lowercase characters in the ASCII table your regex Pattern is invalid.

You'll have to either change it to `^[a-z]+(\.[a-z][a-z0-9]*)*$` if you only want to allow lowercase characters. Or `^[a-z]+(\.[a-z][a-zA-Z0-9]*)*$` if you also want to allow for uppercase characters in your package names.

**Comment by gellertbiro** [comment]
@Mauin Yeah, I see the issue now. Thanks for the quick answers. 👍

**Comment by Mauin** [comment]
Glad that helped. I'll close this issue but feel free to re-open it if more questions along this issue arise.

**Comment by arturbosch** [comment]
@Mauin thanks for answering this !

We should patch the LazyRegex so users can react better to such errors:
```
	private fun createRegex(rule: Rule): Regex {
		return Regex(rule.valueOrDefault(key = key, default = default))
	}
```
We should catch and rethrow the errors here.
