### ISSUE TITLE
Gradle detekt task does not respect the --continue flag.

### ISSUE THREAD

**Issue by bitsydarel** [arturbosch/detekt#1373]
## Expected Behavior
while running gradle detekt --continue, if detekt found errors it's should not fail but continue to build.

## Observed Behavior
It's fail even when the --continue flag has been provided.
We have a really old project and a big one. we only want the reports so we can investigate the issues.

Exception in thread "main" io.gitlab.arturbosch.detekt.cli.console.BuildFailure: Build failed with 1210 weighted issues (threshold defined was 10).

> Task :cx:detekt FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':cx:detekt'.
> Process 'command '/opt/android-studio/jre/bin/java'' finished with non-zero exit value 1

## Steps to Reproduce
set maxIssues treshold to 1.
add a issue to your project.
run gradle detekt --continue

## Context
Running detekt in a jenkins pipeline, detekt report will be posted to github pull request but it's should not break the build.

## Your Environment
Linux
* Version of detekt used: latest
* Version of Gradle used (if applicable): 1.0.0-RC11
* Operating System and version: Ubuntu, Mac Os
* Link to your project (if it's a public repository):

**Comment by audkar** [comment]
> Process 'command '/opt/android-studio/jre/bin/java'' finished with non-zero exit value 1

I believe this is expected behavior. `--continue` flag doesn't replace  gradle command exit value from 1 to 0

Its purpose is to continue running all tasks even 1 task failed.

e.g. you execute two gradle tasks: `task1[fails]` `task2`

case 1: `gradle task1 task2` Result: gradle doesn't execute task2 because task1 failed, `exit code 1`

case 2: `gradle task1 task2 --continue` Result gradle executes both tasks, `exit code 1`

**Comment by bitsydarel** [comment]
Is there a flag to ignore errors?

We use detekt for code review and pull requests  with a jenkins bot.

We only want the build to fail if tests didn't pass, detekt result should only be comments on the submitted code, with the current behaviour the only workaround we have found is to set an enormous number of maxErrors

**Comment by audkar** [comment]
There are plenty [answers](https://stackoverflow.com/a/25745593/1398460) to question how to ignore status code on CI.

However you should consider using [Detekt baseline feature](https://arturbosch.github.io/detekt/baseline.html). So you can suppress old issues and fail on new ones.

**Comment by bitsydarel** [comment]
I'm using a declarative pipeline so unfortunately those answer don't apply to my case, I can overcome the crash with running detekt in a scripted block with try catch but that's not a priority for me.

Thanks for the answers.
