### ISSUE TITLE
dependency on detekt task - how?

### ISSUE THREAD

**Issue by glebsts** [arturbosch/detekt#1387]
Taken out from #1357 

@artem-zinnatullin mentioned that 

>You're referencing detekt which is indeed a configuration extension rather than a task which is what Gradle complaints about according to stacktrace and message.

Changelog for RC9 says

> There is no detektCheck task anymore, just a detekt task which is incremental and is bound to the check task.

Which slightly confuses me.
1. `gradle tasks` gives me `detekt` in `verification` group, without any description (along with idea-related tasks).
2. how can I reference `detekt` task if it does not exist?
My case is i.e configuring some other task (i.e test task) to run after `detekt`.
`test.mustRunAfter detekt`
It gives me error message
```org.gradle.api.internal.tasks.TaskDependencyResolveException: Could not determine the dependencies of task ':test'.```
and 
```Caused by: org.gradle.internal.typeconversion.UnsupportedNotationException: Cannot convert io.gitlab.arturbosch.detekt.extensions.DetektExtension_Decorated@73a6a585 to a task.```

But I need this dependency because in project I am working on I see no point of running tests when static analysis shows problems, so I want to fail fast.

What should I do?

**Comment by arturbosch** [comment]
Actually you do not need to specify `test.mustRunAfter detekt`. Detekt should always run before the tests. Can you confirm this?

**Comment by Mauin** [comment]
The `detekt` tasks all will run as part of the `check` task. You could try getting the `detekt` task by it's name `"detekt"` as we also have a `detekt` extension that is the one you're currently referring to in your example.
