### ISSUE TITLE
test set `detekt-rules:test` is not executed

### ISSUE THREAD

**Issue by schalkms** [arturbosch/detekt#1392]
As discussed in PR #1350 the test set `detekt-rules:test` is not executed on the current master branch. The codecov report also gives an indicator here.

## Expected Behavior
test set `detekt-rules:test` runs

## Observed Behavior
test set `detekt-rules:test` does not run
test set `detekt-rules:test` only partially runs

## Steps to Reproduce
- Create a PR and trigger the CI system
- Take a look at the console output
- Take a look at the codecov report

## Your Environment
* Version of detekt used: RC12
* Version of Gradle used (if applicable):
* Operating System and version:
* Link to your project (if it's a public repository):

**Comment by 3flex** [comment]
Here's the Codecov report for commits on master branch: https://codecov.io/gh/arturbosch/detekt/branch/master/commits

Looks like merging #1380 caused the drop off in coverage: https://codecov.io/gh/arturbosch/detekt/pull/1380

Drilling down into the PR's commits, it was the "Inline function call commit" that caused the change.

**Comment by schalkms** [comment]
I second that. I investigated this and it seems like the inlining has caused this.
I am not sure why. I'll revert this commit.

**Comment by schalkms** [comment]
Closed with da6930e
