### ISSUE TITLE
Consider publishing artifacts to mavenCentral instead of jCenter

### ISSUE THREAD

**Issue by julioromano** [arturbosch/detekt#1396]
Would it be possible to publish detekt on maven central instead of jcenter?

Some reasoning behind this request:
https://blog.autsoft.hu/a-confusing-dependency/
https://twitter.com/JakeWharton/status/1005082789824335874

**Comment by schalkms** [comment]
@arturbosch I think we can also close this issue since we provide both options.

**Comment by tasomaniac** [comment]
Are you sure that is the case? The Gradle plugin was published to maven central on Sept 2018 and does not have the latest version

**Comment by schalkms** [comment]
@tasomaniac you are completely right. That's not case. The Gradle plugin is still missing on maven central.

**Comment by arturbosch** [comment]
Ouch, so we removed the gradle plugin from bintray publishing because it is uploaded to the gradle plugin repos.
So if you don't use the `plugins {...}` syntax you can load plugins from maven central?
-> we would upload and sync the gradle plugin to bintray again.

**Comment by tasomaniac** [comment]
Hmmm, maybe if it is only the plugin and that is not published to neither bintray nor maven central, then it might be fine.

**Comment by 3flex** [comment]
This is 90% done, but Gradle plugin still not on Maven Central. If just publishing to Gradle Plugin Portal is ok (I think it is) then this can be closed.

@julioromano (and others) what do you think?

**Comment by 3flex** [comment]
Thanks for the thumbs ups! I'm going to close this. If there's a future need we can reopen in future.
