### ISSUE TITLE
New rule similar to PMD's UseUnderscoresInNumericLiterals

### ISSUE THREAD

**Issue by scottkennedy** [arturbosch/detekt#1398]
The rule or changes you're looking for might have already been suggested!
Please search in the [issues](https://github.com/arturbosch/detekt/issues) before creating a new one.

## Expected Behavior of the rule
Similar to https://pmd.github.io/latest/pmd_rules_java_codestyle.html#useunderscoresinnumericliterals

This forces you to use underscores in numeric literals, such that `1_000_000` is valid, but `1000000` is not, to make the code more readable.

## Context
https://pmd.github.io/latest/pmd_rules_java_codestyle.html#useunderscoresinnumericliterals

**Comment by tylerbwong** [comment]
Hey, I'd like to give this a shot if possible! Feel free to let me know if someone is already working on it.

**Comment by schalkms** [comment]
@tylerbwong nice!

**Comment by 3flex** [comment]
Can close now #1464 is merged?

**Comment by schalkms** [comment]
@3flex thanks for the heads up.

**Comment by schalkms** [comment]
Closed with b9e1820
