### ISSUE TITLE
Could I run detect-cli for list of files(NOT directories)?

### ISSUE THREAD

**Issue by michael-oknov** [arturbosch/detekt#1400]
Hi,

I've used a cli tool with input parameter as list of files
`java -jar detekt-cli-1.0.0-RC12-all.jar --config my-detect-config.yml -i "/path/File1.kt;/path/File2.kt" --report "html:reports/report.html" `
But it reports me issue from other files.

Could I use detekt-cli tools only for files from input?

Thanks

**Comment by arturbosch** [comment]
Yes, you can specify mutliple paths in the `--input` flag by using a comma:
`--input "file1,file2,file3..."`, hope that helps :)

**Comment by michael-oknov** [comment]
Thank you!
