### ISSUE TITLE
Reformat code base before 1.0

### ISSUE THREAD

**Issue by arturbosch** [arturbosch/detekt#1406]
## Expected Behavior
detekt should be formatted according to the offical kotin coding standard and allowing new contributors
to just focus on code and not style.

## Current Behavior
We are using tabs and have some formatting rules deactivated.

## Context
- Cleanup before 1.0.
- shorter contributing guide
- less worrying about style

**Comment by arturbosch** [comment]
Done in 445ffb0c55b0b3af830cea363d42f1730d9642b3.
Unfortunately pushed to master by Intellij accident :( (while GitHub should protect that??).

**Comment by vanniktech** [comment]
> Unfortunately pushed to master by Intellij accident :( (while GitHub should protect that??).

Only if something is enforced like a code review or an integration check (e.g. Travis)
