### ISSUE TITLE
MagicNumber triggers on pure function only returning a value

### ISSUE THREAD

**Issue by vanniktech** [arturbosch/detekt#1409]
I would not `override val id defaultValueForFoo() = -2L` to be triggered by the MagicNumber rule. It's a constant value that's returned with the function name as the proper description.

**Comment by arturbosch** [comment]
Actually I would expect for this something similiar to `ignoreConstantDeclaration`?

**Comment by vanniktech** [comment]
With a default value as true?

**Comment by schalkms** [comment]
According to our tests this behavior is right. `2L` needs to be added to the `ignoreNumbers` config.

https://github.com/arturbosch/detekt/blob/ac4c8eafdfcc5c430967fa48f80c6d607982da0a/detekt-rules/src/test/kotlin/io/gitlab/arturbosch/detekt/rules/style/MagicNumberSpec.kt#L647-L659

https://github.com/arturbosch/detekt/blob/ac4c8eafdfcc5c430967fa48f80c6d607982da0a/detekt-rules/src/test/kotlin/io/gitlab/arturbosch/detekt/rules/style/MagicNumberSpec.kt#L104-L126
