### ISSUE TITLE
TooManyFunctions flags overridden functions

### ISSUE THREAD

**Issue by vanniktech** [arturbosch/detekt#1411]
This is a bit of a dilemma. I'm subclassing an external class and I'm forced to override 15 methods. By doing this `TooManyFunctions` gets triggered. It would be nice if it weren't triggered.

Is there anything we can do?

**Comment by schalkms** [comment]
For me this is a classical use case for the `Ignore` annotation.

**Comment by schalkms** [comment]
Yeah, I meant the `Suppress` annotation.

**Comment by arturbosch** [comment]
Next to
```
    ignoreDeprecated: false
    ignorePrivate: false
```
we could introduce `ignoreOverridden` to be not so opinionated :)

**Comment by IvanAntsiferov** [comment]
@arturbosch is someone working on this issue? If not, I'd like to implement it.

**Comment by schalkms** [comment]
Cool!
So far no one has worked on this.
