### ISSUE TITLE
Documentation - give gradle examples using Kotlin DSL

### ISSUE THREAD

**Issue by binkley** [arturbosch/detekt#1413]
I'd be nice to see the Gradle usage examples written in the Kotlin DSL.  :)

**Comment by schalkms** [comment]
Have you taken a look at this [page](https://arturbosch.github.io/detekt/kotlindsl.html) ?
What do you find missing there?

**Comment by binkley** [comment]
@schalkms Fantastic -- I missed that when going through the docs.  Thank you.

**Comment by binkley** [comment]
Please close this issue.  :)

**Comment by binkley** [comment]
I do note, though, the doc page link above has an issue for me.  I'm using Gradle 5.0 (if relevant).  To get the jcommander dep to pull down, I needed to add `jcenter()` to the top-level `dependencies` block; the one in `buildscript` was not sufficient.

**Comment by schalkms** [comment]
Nothing to worry about. Please create a new issue with a detailed description, so that it's easier to help you.
