### ISSUE TITLE
Documentation - using Gradle 5.0, need jcenter() in top-level dependencies block, not just buildscript

### ISSUE THREAD

**Issue by binkley** [arturbosch/detekt#1420]
While trying out detekt on a new project to encourage teammates to adopt Kotlin, we used Gradle 5.0.  Although I'm not certain this doc request is specifically related to 5.x, I suspect so as the existing docs worked for Gradle 4.10.

To wit: I needed to add `jcenter()` into the top-level script `dependencies` block for detekt plugin to find `jcommander`.  The existing docs only use `jcenter()` in the `buildscript` dependencies block.

**Comment by arturbosch** [comment]
You are right. I will update the docs thanks!
