### ISSUE TITLE
Incompatibility with Gradle 5.0

### ISSUE THREAD

**Issue by kszilagyi** [arturbosch/detekt#1421]
## Expected Behavior
Detekt shouldn't crash.
## Observed Behavior
Detekt did crash. More precisely when I declared and run the following task:
```
task detektTask(type: io.gitlab.arturbosch.detekt.Detekt) {
    input = detektInputs
    filters = detektFilters
    config = detektConfig
}
```
I got this (only relevant part of stacktace here, see "Steps to reproduce" for more):
```
Caused by: java.lang.IllegalStateException: No value has been specified for this provider.
        at org.gradle.api.internal.provider.Providers$1.get(Providers.java:32)
        at org.gradle.api.internal.provider.DefaultPropertyState.get(DefaultPropertyState.java:108)
        at io.gitlab.arturbosch.detekt.Detekt.check(Detekt.kt:133)
        at org.gradle.internal.reflect.JavaMethod.invoke(JavaMethod.java:73)
```

After debugging a little it looks like the `debug` property is `undefined`. If I just change it gradle back to 4.10.3 the issue goes away and detekt works as expected.

## Steps to Reproduce
- Clone `git@github.com:kszilagyi/intellj-kotlin-inspections.git` and check out `2324ed7c6da72ad625283ac87fef82f6b014687b`
- Run `./gradlew detektTask --console=plain --stacktrace`
- If you want to see that it works with 4.10.3 change the gradle version in `gradle-wrapper.properties`.
## Context
I wanted to run detekt on the assembly step so whenever I build in IntellJ it runs and tells me if something is wrong.

## Your Environment
* Version of detekt used: 1.0.0-RC12
* Version of Gradle used (if applicable): 5.0/4.10.3
* Operating System and version: Ubuntu 18.04.1 LTS
* Link to your project (if it's a public repository): https://github.com/kszilagyi/intellj-kotlin-inspections

**Comment by Mauin** [comment]
Does the same happen if you simply call `./gradlew detekt`? 

Overall you should also be able to remove the custom `detektTask` task, as it seems to simply duplicate what the Detekt gradle plugin already does.

**Comment by kszilagyi** [comment]
Thanks for your quick response. 
No, it doesn't happen with `./gradlew detekt`.
>Overall you should also be able to remove the custom detektTask task, as it seems to simply duplicate what the Detekt gradle plugin already does.

That would be great but if I write `assemble.dependsOn detekt` and run `assemble` it complains that `Cannot convert io.gitlab.arturbosch.detekt.extensions.DetektExtension_Decorated@642385ee to a task.`

I am quite new to gradle so there might be a better way to achieve what I want.

**Comment by lwasylkowski** [comment]
@kszilagyi try writing `assemble.dependsOn "detekt"`, with quotes. When writing `detekt` Gradle first finds the extension with this name, but with a string it should look for a task with that name instead

**Comment by shareme** [comment]
I got the same thing recently on as3.4canary9 with gradle 5.1

**Comment by kszilagyi** [comment]
@lwasylkowski Oh, I didn't know that. Just tried it and it works. Thanks a lot!

**Comment by arturbosch** [comment]
Seems the issue got resolved/worked around, I will close this one then ...
