### ISSUE TITLE
Allow camelCase for package name

### ISSUE THREAD

**Issue by BoxResin** [arturbosch/detekt#1429]
## Expected Behavior of the rule
- To allow package name like `com.something.baseActivity`

## Context
According to [official kotlin style guide](https://kotlinlang.org/docs/reference/coding-conventions.html#naming-rules), it allows to use camel humps for package name.

**Comment by vanniktech** [comment]
That's awkward.

**Comment by schalkms** [comment]
Yeah the default value should change here. Nevertheless, you can use a custom Regex for now.
