### ISSUE TITLE
Support regex for forbidden imports

### ISSUE THREAD

**Issue by tasomaniac** [arturbosch/detekt#1430]
Forbidden imports rule is really powerful to prevent usages of certain classes especially when the names clash. 

It would be amazing to support regex to forbid usages of multiple packages and classes at once.

**Comment by poldz123** [comment]
Yes, I agree. On my end we have libraries that are a wrapper to a library that we used. Now we do not want our developer to use the wrapped library. Would be better to have a check on those forbidden imports.

**Comment by schalkms** [comment]
This leaves the discussion whether the current `imports` config option should be changed.
Otherwise, there's needs to be a new config parameter.

**Comment by tasomaniac** [comment]
I would say a new config parameter. Otherwise that would be a behavior change in existing configurations since dot becomes any char
