### ISSUE TITLE
Redundant rules: MaxLineLength and MaximumLineLength

### ISSUE THREAD

**Issue by jonahgreenthal** [arturbosch/detekt#1433]
Is there a good reason that there are both `MaximumLineLength` and `MaxLineLength` rules that appear to do essentially the same thing (though I think `MaxLineLength` is more configurable)?

**Comment by schalkms** [comment]
There is. `MaximumLineLength` was inherited by ktlint. The whole formatting rule set does this.
`MaxLineLength` is the _native_ detekt rule.
