### ISSUE TITLE
Gradle plugin ignores `ignoreFailures` value

### ISSUE THREAD

**Issue by BorzdeG** [arturbosch/detekt#1435]
```gradle
tasks {
  detekt {
    isIgnoreFailures = true
  }
}
```

**Comment by arturbosch** [comment]
Hey, there is no `isIgnoreFailures` property in the gradle plugin.
You can use 
```
build:
    maxIssues: -1
``
to get the same results.

**Comment by BorzdeG** [comment]
[DetektExtension.kt](https://github.com/arturbosch/detekt/blob/master/detekt-gradle-plugin/src/main/kotlin/io/gitlab/arturbosch/detekt/extensions/DetektExtension.kt#L15) > [CodeQualityExtension.java](https://github.com/gradle/gradle/blob/master/subprojects/code-quality/src/main/groovy/org/gradle/api/plugins/quality/CodeQualityExtension.java) > [field `ignoreFailures`](https://github.com/gradle/gradle/blob/master/subprojects/code-quality/src/main/groovy/org/gradle/api/plugins/quality/CodeQualityExtension.java#L66)
