### ISSUE TITLE
False negative TooManyFunctions if both ignorePrivate & ignoreDeprecated is set to true

### ISSUE THREAD

**Issue by IvanAntsiferov** [arturbosch/detekt#1439]
## Expected Behavior
`TooManyFunctions` should ignore private functions, if that option is set to true in config.

## Observed Behavior
`TooManyFunctions` has false negative report on class with private methods count is more than `thresholdInClasses` option in detekt config, even if `ignorePrivate` option is set to true.

## Steps to Reproduce
1. Set to true `ignoreDeprecated` and `ignorePrivate` in `TooManyFunctions` rule.
2. Write class with private functions count more than `thresholdInClasses`
3. Run detekt check.

## Your Environment
* Version of detekt used: 1.0.0-RC12
* Version of Gradle used (if applicable): 3.2.1
* Operating System and version: macOS 10.12.6
* Link to your project (if it's a public repository): private repo

I guess, the problem is [here](https://github.com/arturbosch/detekt/blob/master/detekt-rules/src/main/kotlin/io/gitlab/arturbosch/detekt/rules/complexity/TooManyFunctions.kt#L124), `isIgnoredFunction` don't check function privacy if `ignoreDeprecated` is set to true, so `ignorePrivate` option is not being used.

**Comment by schalkms** [comment]
Hey, thanks for reporting and also for investigating the problem.
The location in the source file is causing the problem as you said.
Do you mind to submit a pull request, since you have already looked into the problem?

**Comment by IvanAntsiferov** [comment]
> Do you mind to submit a pull request, since you have already looked into the problem?

Yes, I can do that next weekend.

**Comment by arturbosch** [comment]
Cool, thank you!

**Comment by schalkms** [comment]
Closed with 86cfcfb
