### ISSUE TITLE
Include androidTest directory as test directory

### ISSUE THREAD

**Issue by vanniktech** [arturbosch/detekt#1449]
Just like detekt knows that `test` has test code it should also by default know that `androidTest` is test code. Happy make the change!

**Comment by schalkms** [comment]
I would say go for it. It makes sense to me.

**Comment by vanniktech** [comment]
I'll wait for @arturbosch @Mauin opinion.

**Comment by arturbosch** [comment]
you mean adding an additional entry to the test-pattern stuff? yeah go for it :)
