### ISSUE TITLE
ForbiddenVoid rule and Mono<Void>

### ISSUE THREAD

**Issue by dkuc84** [arturbosch/detekt#1472]
[ForbiddenVoid](https://arturbosch.github.io/detekt/style.html#forbiddenvoid) rule detects usages of `Void` instead of relying Kotlin `Unit` type. Unsure whether there are many other use cases, but there is a fringe case with usage of `Void` in Reactor `Mono<Void>` -  [Spring Webflux WebFIlter](https://github.com/spring-projects/spring-framework/blob/master/spring-web/src/main/java/org/springframework/web/server/WebFilter.java#L38).

Example code that triggers the rule:
```kotlin
import org.springframework.web.server.ServerWebExchange
import org.springframework.web.server.WebFilter
import org.springframework.web.server.WebFilterChain
import reactor.core.publisher.Mono

class ExampleFilter: WebFilter {
    override fun filter(exchange: ServerWebExchange, chain: WebFilterChain): Mono<Void> = chain.filter(exchange)
}
```

Opened this up as question instead of bug/rule change request as I am unsure whether this should be supported or not. It is a fringe case that could require manual suppression. Potentially rule could also be updated to skip overridden methods or generics.

**Comment by schalkms** [comment]
For me this is a classical edge case for suppressing this one concern.
I would favor to not include any workarounds just for this concern.
Let's see what other people think.

**Comment by arturbosch** [comment]
Or simply turning this rule off as you know the code base relies on Mono/Flux<Void>.
I guess some kind of scripting would be cool to allow users to postprocess reporting of findings :)?

**Comment by schalkms** [comment]
@arturbosch that's a different matter. I don't think detekt should implement a postprocessing feature. If a user wants to do this, it's possible to postprocess the xml or console report.
I am sorry for being off topic.

**Comment by arturbosch** [comment]
To be also off topic: I meant to have some post processing based on the reported KtElement where users can simply extend some rule conditions. This is much more flexible than inspecting the reported lines :).

**Comment by dkuc84** [comment]
Indeed this is a fringe case but I'd assume with Spring Webflux gaining more popularity this may pop up again. Closing it for now as the workarounds are simple - manually suppressing it or just excluding return type from the overriden method.

**Comment by realdadfish** [comment]
I just stumbled upon the very same issue with RxJava and `TestObserver` of a `Completable`:

```
fun testMe(): TestObserver<Void> = Completable.complete().test()
```

is then also flagged with `ForbiddenVoid`. IMHO this rule should get some configuration, such as `onlyCheckTypesInPackage` which we would naturally configure to our project package path and the rule could then ignore types that reside in different (base) packages from that.
