### ISSUE TITLE
RC13 doesn't work on gradlew 4.9

### ISSUE THREAD

**Issue by Macarse** [arturbosch/detekt#1475]
The error I get is:

```
* What went wrong:
A problem occurred configuring project ':x'.
> Could not create task ':x:detekt'.
   > Could not create task of type 'Detekt'.
      > org.gradle.api.model.ObjectFactory.fileProperty()Lorg/gradle/api/file/RegularFileProperty;
```

I am using detekt in an Android app. 

Based on https://developer.android.com/studio/releases/gradle-plugin the latest recommended gradlew version for Android dev is 4.10.1+.

I am using detekt RC12 with gradlew version 4.9 without issues.

To verify this bug, I kept on increasing gradlew version until I found a version which worked. 4.10.1 and 4.10.2 do not work. Gradlew 5.1 worked.

**Comment by 3flex** [comment]
Pretty sure I've identified the issue and will post a PR soon, along with tests so that at least some of the Gradle plugin tests are run on 4.10.2 and 5.2.1 to try and reduce regressions when running on older Gradle versions.
