### ISSUE TITLE
Add "issues found" exit code

### ISSUE THREAD

**Issue by 3flex** [arturbosch/detekt#1493]
## Expected Behavior
Exit codes allow differentiation between:
* Successful run, no issues found/flagged
* Successful run, issues found (`BuildFailure`)
* CLI parameters could not be parsed (`ParameterException`)
* Unrecoverable error/exception occurred (all other exceptions)

## Current Behavior
Exit code for "Unrecoverable error/exception occurred" and "Successful run, issues found" are the same (`1`)

## Context
To implement a feature for https://github.com/arturbosch/detekt/issues/1435 it must be possible to detect the difference between "Unrecoverable error/exception occurred" and "Successful run, issues found", as only "Successful run, issues found" should be ignored when `ignoreFailures` is enabled in the Gradle plugin.

Propose the following:

| Exit code | Description                              |
|-----------|------------------------------------------|
| 0         | Command completed successfully, no issues found |
| 1         | An error occurred                        |
| 2         | detekt ran successfully, issues found    |

Exit code `1` would be used for all exceptions.

Additional codes can be added in future depending on use case, but this would be enough to build a feature for https://github.com/arturbosch/detekt/issues/1435.

**Comment by 3flex** [comment]
I should add that this proposal means removing the `-1` exit code used if JCommander cannot parse the CLI arguments, in favour of returning `1`. For broadest compatibility I understand exit codes should be in the range `0..255` and negative exit codes should not be used.

**Comment by arturbosch** [comment]
Sounds good to me!
