### ISSUE TITLE
java.lang.IllegalArgumentException: Type of value v5.7 does not match the type of default value 6!

### ISSUE THREAD

**Issue by klolo** [arturbosch/detekt#1497]
During build project i get this error:

> [detekt] Using deprecated property 'failFast' in the yaml config. Please migrate to the new '--fail-fast' cli-flag or 'failFast' detekt extension property.
>    [detekt] Analyzing '..........SomeFile.kt' led to an exception.
>    [detekt] The original exception message was: java.lang.IllegalArgumentException: Type of value v5.7 does not match the type of default value 6!
>    [detekt] Running detekt '1.0.0-RC13' on Java '8.0.5.27 - pxa6480sr5fp27-20190104_01(SR5 FP27)' on OS 'Linux'.
>    [detekt] If the exception message does not help, please feel free to create an issue on our github page.
> 

Detekt version: 1.0.0-RC13
Kotlin: 1.2.31
Execution with Maven:

`
<target name="detekt">
                                <java taskname="detekt" dir="${basedir}"
                                      fork="true"
                                      failonerror="true"
                                      classname="io.gitlab.arturbosch.detekt.cli.Main"
                                      classpathref="maven.plugin.classpath">
                                    <arg value="--input"/>
                                    <arg value="${basedir}/src/main/kotlin"/>
                                    <arg value="--filters"/>
                                    <arg value=".*/target/.*,.*/resources/.*"/>
                                    <arg value="--config"/>
                                    <arg value="${basedir}/../detekt-ruleset.yml"/>
                                </java>
                            </target>
`

**Comment by 3flex** [comment]
I'm guessing your configuration `detekt-ruleset.yml` includes a value of `v5.7` somewhere that an `Int` is expected.

Can you please check and advise which config option you set to `v5.7`? If expectation is that this is a valid value for the config then can possibly update detekt to accommodate, otherwise the configuration will need to be changed.

**Comment by klolo** [comment]
![image](https://user-images.githubusercontent.com/18196270/53944184-1ebaca80-40bf-11e9-8a10-4e3fe4d709fd.png)

**Comment by klolo** [comment]
After change configuration it works. Thanks :)
