### ISSUE TITLE
Show friendlier error when wrong type used for a config parameter

### ISSUE THREAD

**Issue by 3flex** [arturbosch/detekt#1498]
## Expected Behavior
When a user enters configuration of a type that is not accepted (e.g. entering a string when an integer is required) then the error message should show the offending configuration item and the type that's accepted.

For example when setting `complexity > LongParameterList > threshold` config, if value is set to `six` instead of `6`, error would show something like `Value "six" set for config parameter complexity.LongParameterList.threshold is not of type Int`.

## Current Behavior
Error says something similar to `java.lang.IllegalArgumentException: Type of value v5.7 does not match the type of default value 6!` which doesn't explicitly describe the accepted type or advise where in the config the error occurred.

## Context
May prevent issues like https://github.com/arturbosch/detekt/issues/1497 being raised.

**Comment by schalkms** [comment]
Agreed
