### ISSUE TITLE
Is there a parameter that can output a result with specified severity?

### ISSUE THREAD

**Issue by violinday** [arturbosch/detekt#1499]
Like Android Logcat, output logs above the specified level.

Thanks. :)

**Comment by schalkms** [comment]
Please take a look at #533

**Comment by violinday** [comment]
I mean "is there a option that **detekt cli** can output a result(like html report) with specified severity".

I don't found the option in "Command Line Interface" documentation https://arturbosch.github.io/detekt/cli.html or in "default-detekt-config.yml" file.

**Comment by arturbosch** [comment]
There are no "real" severities like `info, warning, error` etc just rule set ids with no particular order.
However like @schalkms linked, if we had an option which maps rule ids to some user specific severities, we could totally do this :).

**Comment by violinday** [comment]
I will detect the problem using "sonarlint-cli"

Thanks :)
