### ISSUE TITLE
New rule: Use require() and check() instead of explicitly throwing exceptions

### ISSUE THREAD

**Issue by 3flex** [arturbosch/detekt#1502]
## Expected Behavior of the rule
Several variations, some will be more complex to implement than others if attempting to identify all uses of (this list isn't exhaustive):
* use `error()` in place of `throw IllegalStateException`
* use `check()` in place of a conditional `IllegalStateException`
* use `checkNotNull()` in place of a null check conditional `IllegalStateException`
* use `require()` in place of a conditional `IllegalArgumentException`
* use `requireNotNull()` in place of a null check conditional `IllegalArgumentException`

To simplify implementation the rule could flag any use of any `IllegalStateException` and `IllegalArgumentException` and advise to use one of error, check, checkNotNull or require, requireNotNull respectively.

## Context
Inspired by https://www.bignerdranch.com/blog/write-better-code-using-kotlins-require-check-and-assert/

**Comment by arturbosch** [comment]
Good one. I think we need to check sub-trees like `if (condition) throw IllegalStateException` for check etc here.
