### ISSUE TITLE
Exception thrown when running detekt with -p [detekt-format jar]

### ISSUE THREAD

**Issue by iccen8** [arturbosch/detekt#1503]
I am getting errors when I am running following detekt command:
`
java -jar detekt-cli-1.0.0-RC13.jar -p ..\..\..\..\KotlinTools\detekt\detekt-formatting\build\libs\detekt-formatting-1.0.0-RC13.jar -r html:test_rpt.html -c test-config.yml
`

Following are the errors I got:
`
Using deprecated property 'failFast' in the yaml config. Please migrate to the new '--fail-fast' cli-flag or 'failFast' detekt extension property.
.......Analyzing 'C:\Users\iccengan\Documents\KotlinProjects\SimpleGallery\Simple-Gallery\app\src\main\kotlin\com\simplemobiletools\gallery\pro\activities\EditActivity.kt' led to an exception.
The original exception message was: java.lang.NoClassDefFoundError: com/github/shyiko/ktlint/ruleset/standard/ChainWrappingRule
Running detekt '1.0.0-RC13' on Java '1.8.0_201-b09' on OS 'Windows 10'.
If the exception message does not help, please feel free to create an issue on our github page.
Analyzing 'C:\Users\iccengan\Documents\KotlinProjects\SimpleGallery\Simple-Gallery\app\src\main\kotlin\com\simplemobiletools\gallery\pro\activities\MainActivity.kt' led to an exception.
The original exception message was: java.lang.NoClassDefFoundError: com/github/shyiko/ktlint/ruleset/standard/ChainWrappingRule
Running detekt '1.0.0-RC13' on Java '1.8.0_201-b09' on OS 'Windows 10'.
If the exception message does not help, please feel free to create an issue on our github page.
Analyzing 'C:\Users\iccengan\Documents\KotlinProjects\SimpleGallery\Simple-Gallery\app\src\main\kotlin\com\simplemobiletools\gallery\pro\activities\IncludedFoldersActivity.kt' led to an exception.
The original exception message was: java.lang.NoClassDefFoundError: com/github/shyiko/ktlint/ruleset/standard/ChainWrappingRule
Running detekt '1.0.0-RC13' on Java '1.8.0_201-b09' on OS 'Windows 10'.
If the exception message does not help, please feel free to create an issue on our github page.
Analyzing 'C:\Users\iccengan\Documents\KotlinProjects\SimpleGallery\Simple-Gallery\app\src\main\kotlin\com\simplemobiletools\gallery\pro\activities\ExcludedFoldersActivity.kt' led to an exception.
The original exception message was: java.lang.NoClassDefFoundError: com/github/shyiko/ktlint/ruleset/standard/ChainWrappingRule
Running detekt '1.0.0-RC13' on Java '1.8.0_201-b09' on OS 'Windows 10'.
If the exception message does not help, please feel free to create an issue on our github page.
Analyzing 'C:\Users\iccengan\Documents\KotlinProjects\SimpleGallery\Simple-Gallery\app\src\main\kotlin\com\simplemobiletools\gallery\pro\activities\HiddenFoldersActivity.kt' led to an exception.
The original exception message was: java.lang.NoClassDefFoundError: com/github/shyiko/ktlint/ruleset/standard/ChainWrappingRule
Running detekt '1.0.0-RC13' on Java '1.8.0_201-b09' on OS 'Windows 10'.
If the exception message does not help, please feel free to create an issue on our github page.
Analyzing 'C:\Users\iccengan\Documents\KotlinProjects\SimpleGallery\Simple-Gallery\app\src\main\kotlin\com\simplemobiletools\gallery\pro\activities\MediaActivity.kt' led to an exception.
The original exception message was: java.lang.NoClassDefFoundError: com/github/shyiko/ktlint/ruleset/standard/ChainWrappingRule
Running detekt '1.0.0-RC13' on Java '1.8.0_201-b09' on OS 'Windows 10'.
If the exception message does not help, please feel free to create an issue on our github page.
Analyzing 'C:\Users\iccengan\Documents\KotlinProjects\SimpleGallery\Simple-Gallery\app\src\main\kotlin\com\simplemobiletools\gallery\pro\activities\PanoramaPhotoActivity.kt' led to an exception.
The original exception message was: java.lang.NoClassDefFoundError: com/github/shyiko/ktlint/ruleset/standard/ChainWrappingRule
Running detekt '1.0.0-RC13' on Java '1.8.0_201-b09' on OS 'Windows 10'.
If the exception message does not help, please feel free to create an issue on our github page.
java.util.concurrent.CompletableFuture.encodeThrowable(Unknown Source)
java.util.concurrent.CompletableFuture.encodeThrowable(Unknown Source)
java.util.concurrent.CompletableFuture.encodeThrowable(Unknown Source)
java.util.concurrent.CompletableFuture.encodeThrowable(Unknown Source)
java.util.concurrent.CompletableFuture.encodeThrowable(Unknown Source)
java.util.concurrent.CompletableFuture.completeThrowable(Unknown Source)
java.util.concurrent.CompletableFuture$AsyncSupply.run(Unknown Source)
java.util.concurrent.CompletableFuture$AsyncSupply.exec(Unknown Source)
java.util.concurrent.ForkJoinTask.doExec(Unknown Source)
java.util.concurrent.ForkJoinPool$WorkQueue.runTask(Unknown Source)
java.util.concurrent.ForkJoinPool.runWorker(Unknown Source)
java.util.concurrent.ForkJoinWorkerThread.run(Unknown Source)
java.util.concurrent.CompletableFuture.encodeThrowable(Unknown Source)
java.util.concurrent.CompletableFuture.completeThrowable(Unknown Source)
java.util.concurrent.CompletableFuture$AsyncSupply.run(Unknown Source)
java.util.concurrent.CompletableFuture$AsyncSupply.exec(Unknown Source)
java.util.concurrent.ForkJoinTask.doExec(Unknown Source)
io.gitlab.arturbosch.detekt.formatting.wrappers.ChainWrapping.<init>(ChainWrapping.kt:16)
java.util.concurrent.CompletableFuture.completeThrowable(Unknown Source)
java.util.concurrent.CompletableFuture.completeThrowable(Unknown Source)
java.util.concurrent.CompletableFuture.completeThrowable(Unknown Source)
java.util.concurrent.CompletableFuture$AsyncSupply.run(Unknown Source)
java.util.concurrent.CompletableFuture.completeThrowable(Unknown Source)
java.util.concurrent.CompletableFuture.encodeThrowable(Unknown Source)
java.util.concurrent.CompletableFuture$AsyncSupply.run(Unknown Source)
java.util.concurrent.CompletableFuture$AsyncSupply.exec(Unknown Source)
java.util.concurrent.CompletableFuture$AsyncSupply.exec(Unknown Source)
java.util.concurrent.ForkJoinTask.doExec(Unknown Source)
java.util.concurrent.CompletableFuture$AsyncSupply.run(Unknown Source)
java.util.concurrent.CompletableFuture$AsyncSupply.run(Unknown Source)
java.util.concurrent.CompletableFuture$AsyncSupply.exec(Unknown Source)
java.util.concurrent.ForkJoinTask.doExec(Unknown Source)
java.util.concurrent.ForkJoinPool$WorkQueue.runTask(Unknown Source)
java.util.concurrent.ForkJoinPool.runWorker(Unknown Source)
io.gitlab.arturbosch.detekt.formatting.KtLintMultiRule.<init>(KtLintMultiRule.kt:47)
java.util.concurrent.ForkJoinPool$WorkQueue.runTask(Unknown Source)
io.gitlab.arturbosch.detekt.formatting.FormattingProvider.instance(FormattingProvider.kt:26)
java.util.concurrent.ForkJoinWorkerThread.run(Unknown Source)
java.util.concurrent.CompletableFuture$AsyncSupply.exec(Unknown Source)
java.util.concurrent.ForkJoinTask.doExec(Unknown Source)
java.util.concurrent.ForkJoinPool$WorkQueue.runTask(Unknown Source)
java.util.concurrent.ForkJoinPool.runWorker(Unknown Source)
java.util.concurrent.ForkJoinTask.doExec(Unknown Source)
java.util.concurrent.ForkJoinPool$WorkQueue.runTask(Unknown Source)
java.util.concurrent.CompletableFuture.completeThrowable(Unknown Source)
java.util.concurrent.ForkJoinPool.runWorker(Unknown Source)
java.util.concurrent.ForkJoinWorkerThread.run(Unknown Source)
java.util.concurrent.ForkJoinPool$WorkQueue.runTask(Unknown Source)
java.util.concurrent.ForkJoinPool.runWorker(Unknown Source)
io.gitlab.arturbosch.detekt.formatting.wrappers.ChainWrapping.<init>(ChainWrapping.kt:16)
io.gitlab.arturbosch.detekt.api.RuleSetProvider$DefaultImpls.buildRuleset(RuleSetProvider.kt:28)
java.util.concurrent.ForkJoinPool.runWorker(Unknown Source)
java.util.concurrent.ForkJoinWorkerThread.run(Unknown Source)
io.gitlab.arturbosch.detekt.formatting.FormattingProvider.buildRuleset(FormattingProvider.kt:21)
io.gitlab.arturbosch.detekt.core.Detektor$analyze$ruleSets$1.invoke(Detektor.kt:53)
io.gitlab.arturbosch.detekt.formatting.KtLintMultiRule.<init>(KtLintMultiRule.kt:47)
java.util.concurrent.ForkJoinWorkerThread.run(Unknown Source)
io.gitlab.arturbosch.detekt.formatting.wrappers.ChainWrapping.<init>(ChainWrapping.kt:16)
java.util.concurrent.ForkJoinWorkerThread.run(Unknown Source)
java.util.concurrent.CompletableFuture$AsyncSupply.run(Unknown Source)
io.gitlab.arturbosch.detekt.formatting.wrappers.ChainWrapping.<init>(ChainWrapping.kt:16)
io.gitlab.arturbosch.detekt.formatting.KtLintMultiRule.<init>(KtLintMultiRule.kt:47)
io.gitlab.arturbosch.detekt.formatting.wrappers.ChainWrapping.<init>(ChainWrapping.kt:16)
io.gitlab.arturbosch.detekt.formatting.FormattingProvider.instance(FormattingProvider.kt:26)
io.gitlab.arturbosch.detekt.core.Detektor$analyze$ruleSets$1.invoke(Detektor.kt:14)
io.gitlab.arturbosch.detekt.formatting.wrappers.ChainWrapping.<init>(ChainWrapping.kt:16)
kotlin.sequences.TransformingSequence$iterator$1.next(Sequences.kt:172)
io.gitlab.arturbosch.detekt.api.RuleSetProvider$DefaultImpls.buildRuleset(RuleSetProvider.kt:28)
io.gitlab.arturbosch.detekt.formatting.KtLintMultiRule.<init>(KtLintMultiRule.kt:47)
io.gitlab.arturbosch.detekt.formatting.FormattingProvider.instance(FormattingProvider.kt:26)
io.gitlab.arturbosch.detekt.formatting.KtLintMultiRule.<init>(KtLintMultiRule.kt:47)
java.util.concurrent.CompletableFuture$AsyncSupply.exec(Unknown Source)
io.gitlab.arturbosch.detekt.formatting.FormattingProvider.instance(FormattingProvider.kt:26)
io.gitlab.arturbosch.detekt.api.RuleSetProvider$DefaultImpls.buildRuleset(RuleSetProvider.kt:28)
io.gitlab.arturbosch.detekt.formatting.FormattingProvider.instance(FormattingProvider.kt:26)
io.gitlab.arturbosch.detekt.formatting.FormattingProvider.buildRuleset(FormattingProvider.kt:21)
kotlin.sequences.FilteringSequence$iterator$1.calcNext(Sequences.kt:132)
io.gitlab.arturbosch.detekt.formatting.KtLintMultiRule.<init>(KtLintMultiRule.kt:47)
kotlin.sequences.FilteringSequence$iterator$1.hasNext(Sequences.kt:156)
io.gitlab.arturbosch.detekt.core.Detektor$analyze$ruleSets$1.invoke(Detektor.kt:53)
io.gitlab.arturbosch.detekt.api.RuleSetProvider$DefaultImpls.buildRuleset(RuleSetProvider.kt:28)
io.gitlab.arturbosch.detekt.formatting.FormattingProvider.buildRuleset(FormattingProvider.kt:21)
io.gitlab.arturbosch.detekt.core.Detektor$analyze$ruleSets$1.invoke(Detektor.kt:53)
io.gitlab.arturbosch.detekt.api.RuleSetProvider$DefaultImpls.buildRuleset(RuleSetProvider.kt:28)
java.util.concurrent.ForkJoinTask.doExec(Unknown Source)
io.gitlab.arturbosch.detekt.formatting.FormattingProvider.buildRuleset(FormattingProvider.kt:21)
io.gitlab.arturbosch.detekt.core.Detektor$analyze$ruleSets$1.invoke(Detektor.kt:14)
io.gitlab.arturbosch.detekt.formatting.FormattingProvider.buildRuleset(FormattingProvider.kt:21)
io.gitlab.arturbosch.detekt.core.Detektor$analyze$ruleSets$1.invoke(Detektor.kt:14)
kotlin.sequences.SequencesKt___SequencesKt.toCollection(_Sequences.kt:698)
io.gitlab.arturbosch.detekt.formatting.FormattingProvider.instance(FormattingProvider.kt:26)
kotlin.sequences.SequencesKt___SequencesKt.toMutableList(_Sequences.kt:728)
kotlin.sequences.TransformingSequence$iterator$1.next(Sequences.kt:172)
io.gitlab.arturbosch.detekt.core.Detektor$analyze$ruleSets$1.invoke(Detektor.kt:53)
kotlin.sequences.TransformingSequence$iterator$1.next(Sequences.kt:172)
io.gitlab.arturbosch.detekt.core.Detektor$analyze$ruleSets$1.invoke(Detektor.kt:53)
java.util.concurrent.ForkJoinPool$WorkQueue.runTask(Unknown Source)
io.gitlab.arturbosch.detekt.core.Detektor$analyze$ruleSets$1.invoke(Detektor.kt:14)
kotlin.sequences.FilteringSequence$iterator$1.calcNext(Sequences.kt:132)
io.gitlab.arturbosch.detekt.core.Detektor$analyze$ruleSets$1.invoke(Detektor.kt:14)
kotlin.sequences.FilteringSequence$iterator$1.calcNext(Sequences.kt:132)
kotlin.sequences.SequencesKt___SequencesKt$sortedWith$1.iterator(_Sequences.kt:563)
io.gitlab.arturbosch.detekt.api.RuleSetProvider$DefaultImpls.buildRuleset(RuleSetProvider.kt:28)
kotlin.sequences.DistinctSequence.iterator(Sequences.kt:516)
kotlin.sequences.FilteringSequence$iterator$1.hasNext(Sequences.kt:156)
kotlin.sequences.TransformingSequence$iterator$1.next(Sequences.kt:172)
kotlin.sequences.FilteringSequence$iterator$1.hasNext(Sequences.kt:156)
kotlin.sequences.TransformingSequence$iterator$1.next(Sequences.kt:172)
java.util.concurrent.ForkJoinPool.runWorker(Unknown Source)
java.util.concurrent.ForkJoinWorkerThread.run(Unknown Source)
kotlin.sequences.FilteringSequence$iterator$1.calcNext(Sequences.kt:132)
kotlin.sequences.FilteringSequence$iterator$1.hasNext(Sequences.kt:156)
kotlin.sequences.SequencesKt___SequencesKt.toCollection(_Sequences.kt:698)
kotlin.sequences.SequencesKt___SequencesKt.toMutableList(_Sequences.kt:728)
kotlin.sequences.SequencesKt___SequencesKt.toCollection(_Sequences.kt:698)
kotlin.sequences.SequencesKt___SequencesKt.toMutableList(_Sequences.kt:728)
kotlin.sequences.FilteringSequence$iterator$1.calcNext(Sequences.kt:132)
kotlin.sequences.SequencesKt___SequencesKt.toCollection(_Sequences.kt:698)
kotlin.sequences.SequencesKt___SequencesKt.toCollection(_Sequences.kt:698)
io.gitlab.arturbosch.detekt.formatting.FormattingProvider.buildRuleset(FormattingProvider.kt:21)
kotlin.sequences.SequencesKt___SequencesKt.toMutableList(_Sequences.kt:728)
kotlin.sequences.SequencesKt___SequencesKt.toMutableList(_Sequences.kt:728)
kotlin.sequences.FilteringSequence$iterator$1.hasNext(Sequences.kt:156)
kotlin.sequences.SequencesKt___SequencesKt$sortedWith$1.iterator(_Sequences.kt:563)
kotlin.sequences.SequencesKt___SequencesKt$sortedWith$1.iterator(_Sequences.kt:563)
kotlin.sequences.DistinctSequence.iterator(Sequences.kt:516)
io.gitlab.arturbosch.detekt.formatting.wrappers.ChainWrapping.<init>(ChainWrapping.kt:16)
io.gitlab.arturbosch.detekt.formatting.KtLintMultiRule.<init>(KtLintMultiRule.kt:47)
kotlin.sequences.SequencesKt___SequencesKt.toCollection(_Sequences.kt:698)
kotlin.sequences.SequencesKt___SequencesKt.toMutableList(_Sequences.kt:728)
kotlin.sequences.DistinctSequence.iterator(Sequences.kt:516)
kotlin.sequences.SequencesKt___SequencesKt.toCollection(_Sequences.kt:698)
kotlin.sequences.SequencesKt___SequencesKt.toCollection(_Sequences.kt:698)
kotlin.sequences.SequencesKt___SequencesKt$sortedWith$1.iterator(_Sequences.kt:563)
kotlin.sequences.DistinctSequence.iterator(Sequences.kt:516)
kotlin.sequences.SequencesKt___SequencesKt.toCollection(_Sequences.kt:698)
kotlin.sequences.SequencesKt___SequencesKt.toList(_Sequences.kt:719)
io.gitlab.arturbosch.detekt.core.Detektor$analyze$ruleSets$1.invoke(Detektor.kt:53)
io.gitlab.arturbosch.detekt.core.Detektor.analyze(Detektor.kt:56)
kotlin.sequences.SequencesKt___SequencesKt.toMutableList(_Sequences.kt:728)
kotlin.sequences.SequencesKt___SequencesKt.toMutableList(_Sequences.kt:728)
kotlin.sequences.SequencesKt___SequencesKt$sortedWith$1.iterator(_Sequences.kt:563)
kotlin.sequences.DistinctSequence.iterator(Sequences.kt:516)
kotlin.sequences.SequencesKt___SequencesKt.toMutableList(_Sequences.kt:728)
kotlin.sequences.SequencesKt___SequencesKt.toList(_Sequences.kt:719)
kotlin.sequences.SequencesKt___SequencesKt.toList(_Sequences.kt:719)
io.gitlab.arturbosch.detekt.core.Detektor.analyze(Detektor.kt:56)
io.gitlab.arturbosch.detekt.core.Detektor.access$analyze(Detektor.kt:14)
io.gitlab.arturbosch.detekt.formatting.FormattingProvider.instance(FormattingProvider.kt:26)
io.gitlab.arturbosch.detekt.core.Detektor$run$1$$special$$inlined$map$lambda$1.invoke(Detektor.kt:29)
io.gitlab.arturbosch.detekt.core.Detektor$run$1$$special$$inlined$map$lambda$1.invoke(Detektor.kt:14)
io.gitlab.arturbosch.detekt.core.TasksKt$runAsync$1.invoke(Tasks.kt:23)
io.gitlab.arturbosch.detekt.core.Detektor.analyze(Detektor.kt:56)
kotlin.sequences.SequencesKt___SequencesKt.toCollection(_Sequences.kt:698)
kotlin.sequences.SequencesKt___SequencesKt.toList(_Sequences.kt:719)
io.gitlab.arturbosch.detekt.core.Detektor.analyze(Detektor.kt:56)
io.gitlab.arturbosch.detekt.core.Detektor.access$analyze(Detektor.kt:14)
io.gitlab.arturbosch.detekt.core.Detektor$analyze$ruleSets$1.invoke(Detektor.kt:14)
io.gitlab.arturbosch.detekt.core.Detektor$run$1$$special$$inlined$map$lambda$1.invoke(Detektor.kt:29)
io.gitlab.arturbosch.detekt.core.Detektor.access$analyze(Detektor.kt:14)
io.gitlab.arturbosch.detekt.core.Detektor$run$1$$special$$inlined$map$lambda$1.invoke(Detektor.kt:29)
io.gitlab.arturbosch.detekt.core.Detektor$run$1$$special$$inlined$map$lambda$1.invoke(Detektor.kt:14)
io.gitlab.arturbosch.detekt.core.TasksKt$runAsync$1.invoke(Tasks.kt:23)
kotlin.sequences.SequencesKt___SequencesKt.toMutableList(_Sequences.kt:728)
io.gitlab.arturbosch.detekt.core.Detektor.access$analyze(Detektor.kt:14)
io.gitlab.arturbosch.detekt.core.TasksKt$task$1.get(Tasks.kt:27)
java.util.concurrent.CompletableFuture$AsyncSupply.run(Unknown Source)
java.util.concurrent.CompletableFuture$AsyncSupply.exec(Unknown Source)
java.util.concurrent.ForkJoinTask.doExec(Unknown Source)
io.gitlab.arturbosch.detekt.api.RuleSetProvider$DefaultImpls.buildRuleset(RuleSetProvider.kt:28)
java.util.concurrent.ForkJoinPool$WorkQueue.runTask(Unknown Source)
java.util.concurrent.ForkJoinPool.runWorker(Unknown Source)
java.util.concurrent.ForkJoinWorkerThread.run(Unknown Source)
io.gitlab.arturbosch.detekt.core.Detektor$run$1$$special$$inlined$map$lambda$1.invoke(Detektor.kt:29)
kotlin.sequences.SequencesKt___SequencesKt.toList(_Sequences.kt:719)
io.gitlab.arturbosch.detekt.core.TasksKt$task$1.get(Tasks.kt:27).
io.gitlab.arturbosch.detekt.core.Detektor$run$1$$special$$inlined$map$lambda$1.invoke(Detektor.kt:14)
kotlin.sequences.TransformingSequence$iterator$1.next(Sequences.kt:172)
io.gitlab.arturbosch.detekt.core.TasksKt$runAsync$1.invoke(Tasks.kt:23)
java.util.concurrent.CompletableFuture$AsyncSupply.run(Unknown Source)
io.gitlab.arturbosch.detekt.core.Detektor.analyze(Detektor.kt:56)
io.gitlab.arturbosch.detekt.core.Detektor$run$1$$special$$inlined$map$lambda$1.invoke(Detektor.kt:14)
io.gitlab.arturbosch.detekt.core.TasksKt$runAsync$1.invoke(Tasks.kt:23)
io.gitlab.arturbosch.detekt.formatting.FormattingProvider.buildRuleset(FormattingProvider.kt:21)
io.gitlab.arturbosch.detekt.core.TasksKt$task$1.get(Tasks.kt:27)
java.util.concurrent.CompletableFuture$AsyncSupply.run(Unknown Source)
java.util.concurrent.CompletableFuture$AsyncSupply.exec(Unknown Source)
java.util.concurrent.ForkJoinTask.doExec(Unknown Source)
java.util.concurrent.ForkJoinPool$WorkQueue.runTask(Unknown Source)
io.gitlab.arturbosch.detekt.core.Detektor.access$analyze(Detektor.kt:14)
java.util.concurrent.CompletableFuture$AsyncSupply.exec(Unknown Source)
io.gitlab.arturbosch.detekt.core.TasksKt$task$1.get(Tasks.kt:27)
kotlin.sequences.FilteringSequence$iterator$1.calcNext(Sequences.kt:132)
java.util.concurrent.CompletableFuture$AsyncSupply.run(Unknown Source)
java.util.concurrent.ForkJoinTask.doExec(Unknown Source)
java.util.concurrent.ForkJoinPool$WorkQueue.runTask(Unknown Source)
io.gitlab.arturbosch.detekt.core.Detektor$run$1$$special$$inlined$map$lambda$1.invoke(Detektor.kt:29)
java.util.concurrent.ForkJoinPool.runWorker(Unknown Source)
java.util.concurrent.ForkJoinWorkerThread.run(Unknown Source)
io.gitlab.arturbosch.detekt.core.Detektor$analyze$ruleSets$1.invoke(Detektor.kt:53).
io.gitlab.arturbosch.detekt.core.Detektor$run$1$$special$$inlined$map$lambda$1.invoke(Detektor.kt:14)
java.util.concurrent.ForkJoinPool.runWorker(Unknown Source)
java.util.concurrent.ForkJoinWorkerThread.run(Unknown Source)
java.util.concurrent.CompletableFuture$AsyncSupply.exec(Unknown Source)
kotlin.sequences.FilteringSequence$iterator$1.hasNext(Sequences.kt:156)
java.util.concurrent.ForkJoinTask.doExec(Unknown Source)
java.util.concurrent.ForkJoinPool$WorkQueue.runTask(Unknown Source)
...
`

What I am trying to do is to test running the ktlint plugin(detekt-format).

**Comment by schalkms** [comment]
#1478 possible duplicate

**Comment by 3flex** [comment]
Not sure that's a duplicate, looks like the exception reported is `java.lang.NoClassDefFoundError: com/github/shyiko/ktlint/ruleset/standard/ChainWrappingRule`

**Comment by arturbosch** [comment]
Thanks for reporting this!
If we use the formatting jar via gradle, gradle resolves the KtLint dependencies for us, however if your detekt plugin depends on other dependencies, all this jars must be given to detekt via the `--plugins` property.
We do not provide a fatjar with the ktlint dependencies.
A published formatting fatjar with ktlint BUT without the kotlin-compiler should exist.

**Comment by iccen8** [comment]
> Thanks for reporting this!
> If we use the formatting jar via gradle, gradle resolves the KtLint dependencies for us, however if your detekt plugin depends on other dependencies, all this jars must be given to detekt via the `--plugins` property.
> We do not provide a fatjar with the ktlint dependencies.
> A published formatting fatjar with ktlint BUT without the kotlin-compiler should exist.

Thank you for your response!
I am still a bit confused here. There is no way to integrate the "formatting" rules into detekt's outputting report? I was assuming there are some ways I could use to output violated "formatting" rules, since the default-detekt-config.yml contains the activation of "formatting" rules.
Because of my need, I have to use the ktlint plugin without changing detekt's gradle. Which means I have to use `--plulgins` property. I cloned ktlint's repo, and was trying to use ktlint's built fatjar as a plugin for detekt. But this didn't change the outputting report as I expected. Am I still doing anything not correctly?
`java -jar detekt-cli-1.0.0-RC14.jar --plugins ktlint-all.jar -r html:test_rpt.html -c test-config.yml`

**Comment by arturbosch** [comment]
We wrap KtLint but don't use it directly. For you that means:
1. Clone curent master detekt and run `gradle build` inside the detekt-formatting folder
2. Use `java -jar detekt-cli-1.0.0-RC14.jar --plugins detekt-formatting-[version].jar -r html:test_rpt.html -c test-config.yml`
3. Now you should see something like:
```
Ruleset: comments
Ruleset: complexity
Ruleset: empty-blocks
Ruleset: exceptions
_Ruleset: formatting_
Ruleset: naming
Ruleset: performance
Ruleset: potential-bugs
Ruleset: style
```
