### ISSUE TITLE
Flag --parallel seems to do nothing

### ISSUE THREAD

**Issue by lsrom** [arturbosch/detekt#1513]
When you specify `parallel = true` in gradle or `--parallel` in CLI it doesn't seems to do anything. Only one core is doing all the work. Documentation says that *Gradle will determine optimal number of threads.*

Is it possible to fix this so detekt can run on multiple cores? Or am I doing something wrong? I'm using Windows 10 and Kotlin 1.3.20 with Gradle 5.2.1

**Comment by schalkms** [comment]
May I ask how big is your project actually is? The documentation states the following.

```
--parallel
    Enables parallel compilation of source files. Should only be used if the
    analyzing project has more than ~200 kotlin files.
```

**Comment by lsrom** [comment]
I don't have actual number but I definitely have more than 200 kotlin files.

**Comment by 3flex** [comment]
Where are you using the flag? `./gradlew --parallel`, or applying in gradle.properties, or setting in `detekt {}` block in the Gradle build file?

Only the last one is expected to have any effect on parallel processing of files by detekt, the other two are respected by Gradle only but currently (and I'm not sure whether it's possible) it doesn't pass that flag to detekt. Gradle test tasks work the same way.

**Comment by arturbosch** [comment]
All detekt checks are run in parallel by default. But the kotlin files are not compiled in parallel by default.
I had no big Kotlin projects to test this on but thought it won't hurt to leave the property in ...
I have experienced performance gains of like 50ms so far xD
