### ISSUE TITLE
When I have a violated line of code is reported, am I able to get its whole file content?

### ISSUE THREAD

**Issue by iccen8** [arturbosch/detekt#1514]
Besides outputting the directory of the file, I want to output the file content as well.

**Comment by schalkms** [comment]
It prints out the path to the file where the violation occured. You can navigate to it via a file browser or use the terminal where you able to just click the link to the file.

**Comment by iccen8** [comment]
> It prints out the path to the file where the violation occured. You can navigate to it via a file browser or use the terminal where you able to just click the link to the file.

Seems it is the only way I could do for now :/
Will this feature add to detekt in the future though?
Thanks :)

**Comment by schalkms** [comment]
Detekt itself provides a report with all the violations in XML. All tools can pick up this report and process this information. In your case I would recommend to use [Sonar](https://www.sonarqube.org) with a detekt example shown [here](https://github.com/arturbosch/sonar-kotlin). There you can see in the example image a violation with the corresponding source code.
If this is not enough for your use case, you can always write your own processor which works on the XML report and creates a custom report with all the information you would like to have or you can create a custom report by extending detekt (see [here](https://arturbosch.github.io/detekt/extensions.html#custom-reports)).

HTH

**Comment by iccen8** [comment]
Gotcha! Thank you for your help.
