### ISSUE TITLE
Always show the absolute number of code smells

### ISSUE THREAD

**Issue by sschuberth** [arturbosch/detekt#152]
It would be nice to see the absolute number of code smells also if the `failThreshold` was not exceeded. That way one can more easily determine to which value to lower the `failThreshold` if some smells were fixed.

**Comment by arturbosch** [comment]
Hmm I'm thinking about a flag in the build sub config and not on by default?

**Comment by sschuberth** [comment]
I don't really think anyone would be offended by showing that number by default. You already show the number of files and a bunch of numbers in the "Complexity Report" by default, so why not this one? In fact, it could be just another item in the "Complexity Report", I believe.

**Comment by arturbosch** [comment]
True story, will add it to the "Complexity Report" ;)
