### ISSUE TITLE
Issue with suppressing set (ComplexInterface, TooManyFunctions)

### ISSUE THREAD

**Issue by esoxjem** [arturbosch/detekt#1529]
## Expected Behavior
Following statement should not fail detekt
```kotlin
@Suppress("ComplexInterface", "TooManyFunctions")
```
whereas switching the position of the parameter works

## Observed Behavior
Following statement fails detekt
```kotlin
@Suppress("ComplexInterface", "TooManyFunctions")
```
whereas switching the position of the parameter works makes it pass
```kotlin
@Suppress("TooManyFunctions", "ComplexInterface")
```

## Your Environment
* Version of detekt used: 1.0.0-rc12
* Version of Gradle used (if applicable): 5.0.0
* Operating System and version: Mac OS X Mojave,

**Comment by schalkms** [comment]
This sounds weird. Could you please also mention on which Kotlin element you are applying those annotations?
I am also not sure if there were changes on the suppress functionality after the RC12 release.

**Comment by esoxjem** [comment]
It's applied to an `Interface`. Is that what you mean by Kotlin element?

**Comment by schalkms** [comment]
> It's applied to an Interface. Is that what you mean by Kotlin element?

Yes. This helps to reconstruct the problem.

**Comment by schalkms** [comment]
I couldn't reproduce this problem with RC16 and the following code.

```Kotlin
@Suppress("ComplexInterface", "TooManyFunctions")
interface A {
    fun a1()
    fun a2()
    fun a3()
    fun a4()
    fun a5()
    fun a6()
    fun a7()
    fun a8()
    fun a9()
    fun a10()
    fun a11()

    val p1: Int
    val p2: Int
    val p3: Int
}
```
