### ISSUE TITLE
Running detektBaseline changes sources

### ISSUE THREAD

**Issue by VictorAlbertos** [arturbosch/detekt#1530]
I [followed the docs](https://arturbosch.github.io/detekt/baseline.html) to set the baseline for my project. It indeed geneated the files (as it is a multi-module setup) but it also changes the sources, applying some kind of re-formatting to them (?). Is this documented in some place? And based in what rules it changes the sources? 

Thanks!

**Comment by schalkms** [comment]
You have the formatting ruleset activated in the [config file](https://github.com/arturbosch/detekt/blob/145f0a9a47e87d0a0a68f550bbb504503e2fed88/detekt-cli/src/main/resources/default-detekt-config.yml#L201).
Detekt provides a wrapper around [ktlint](https://ktlint.github.io) which is used for formatting your source code depending on the configuration. [Reference](https://arturbosch.github.io/detekt/formatting.html)

**Comment by VictorAlbertos** [comment]
Thanks for the explanation 👍

**Comment by schalkms** [comment]
You are welcome.

**Comment by arturbosch** [comment]
We should protect our more from these.
autocorrect as close flag with value false by default should help.
