### ISSUE TITLE
NoSuchFieldError: LONG_STRING_TEMPLATE_ENTRY

### ISSUE THREAD

**Issue by petnagy** [arturbosch/detekt#1533]
I have updated detekt from RC12 to RC14. Just changed the version number after run it.
result:
Analyzing '/Users/petnagy/FamilyFinances/Flint/app/src/main/java/com/lippert/flint/pages/onboarding/OnboardingActivity.kt' led to an exception.
The original exception message was: java.lang.NoSuchFieldError: LONG_STRING_TEMPLATE_ENTRY
Running detekt '1.0.0-RC14' on Java '1.8.0_77-b03' on OS 'Mac OS X'.
If the exception message does not help, please feel free to create an issue on our github page.
java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:273)
java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:280)
java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1592)
java.util.concurrent.CompletableFuture$AsyncSupply.exec(CompletableFuture.java:1582)
java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)
com.github.shyiko.ktlint.ruleset.standard.StringTemplateRule.visit(StringTemplateRule.kt:29)
io.gitlab.arturbosch.detekt.formatting.FormattingRule.apply(FormattingRule.kt:64)
io.gitlab.arturbosch.detekt.formatting.KtLintMultiRule$visit$2$$special$$inlined$forEach$lambda$1.invoke(KtLintMultiRule.kt:84)
io.gitlab.arturbosch.detekt.formatting.KtLintMultiRule$visit$2$$special$$inlined$forEach$lambda$1.invoke(KtLintMultiRule.kt:44)
.io.gitlab.arturbosch.detekt.api.MultiRule.runIfActive(MultiRule.kt:27)
io.gitlab.arturbosch.detekt.formatting.KtLintMultiRule$visit$2.invoke(KtLintMultiRule.kt:84)
io.gitlab.arturbosch.detekt.formatting.KtLintMultiRule$visit$2.invoke(KtLintMultiRule.kt:44)
io.gitlab.arturbosch.detekt.formatting.KtLintMultiRule.visitTokens(KtLintMultiRule.kt:96)
io.gitlab.arturbosch.detekt.formatting.KtLintMultiRule.visit(KtLintMultiRule.kt:82)
io.gitlab.arturbosch.detekt.api.BaseRule.visitFile(BaseRule.kt:36)
io.gitlab.arturbosch.detekt.api.RuleSet.accept(RuleSet.kt:23)
io.gitlab.arturbosch.detekt.core.Detektor.analyze(Detektor.kt:62)
io.gitlab.arturbosch.detekt.core.Detektor.access$analyze(Detektor.kt:14)
io.gitlab.arturbosch.detekt.core.Detektor$run$1$$special$$inlined$map$lambda$1.invoke(Detektor.kt:29)
io.gitlab.arturbosch.detekt.core.Detektor$run$1$$special$$inlined$map$lambda$1.invoke(Detektor.kt:14)
io.gitlab.arturbosch.detekt.core.TasksKt$runAsync$1.invoke(Tasks.kt:23)
io.gitlab.arturbosch.detekt.core.TasksKt$task$1.get(Tasks.kt:27)
java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1590)
java.util.concurrent.CompletableFuture$AsyncSupply.exec(CompletableFuture.java:1582)
java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)

## Steps to Reproduce
after everytime when I run ./gradlew detekt

## Your Environment
'1.0.0-RC14' on Java '1.8.0_77-b03' on OS 'Mac OS X'.
* Version of detekt used: 1.0.0-RC14
* Version of Gradle used (if applicable): 3.3.2
* Operating System and version: MacOSx 10.14.3

**Comment by schalkms** [comment]
Please take a look at #1476

**Comment by petnagy** [comment]
I have checked, I have changed to ktlint 0.30.0 but it did not solve the problem :(

**Comment by arturbosch** [comment]
Do you have other plugins/dependencies which depend on the kotlin compiler?
This error was occured when moving from 1.3.10 to 1.3.21 ^^

**Comment by petnagy** [comment]
No. I just upgraded kotlin to the latest version.
However if I am using RC12 than no any problem.

**Comment by arturbosch** [comment]
Any warnings about maybe conflicted kotlin versions on the classpath?
You could `active: false` the `StringTemplate` rule for now, if you want to use RC14...

**Comment by schalkms** [comment]
How does your Gradle config look like?
Maybe the mentioned fix in this [issue](https://github.com/shyiko/ktlint/issues/321) could help. Have you tried that?

**Comment by petnagy** [comment]
@arturbosch I did not find any conflict about Kotlin versions. 
Where shall I put StringTemplate active: false ?

**Comment by petnagy** [comment]
@schalkms I am using next in the gradle file: ktlint "com.github.shyiko:ktlint:0.30.0"

configurations {
    ktlint
}

task ktlint(type: JavaExec, group: "verification") {
    description = "Check Kotlin code style."
    main = "com.github.shyiko.ktlint.Main"
    classpath = configurations.ktlint
    args "src/**/*.kt"
    // to generate report in checkstyle format prepend following args:
    // "--reporter=plain", "--reporter=checkstyle,output=${buildDir}/ktlint.xml"
    // see https://github.com/shyiko/ktlint#usage for more
}

check.dependsOn ktlint

task ktlintFormat(type: JavaExec, group: "formatting") {
    description = "Fix Kotlin code style deviations."
    main = "com.github.shyiko.ktlint.Main"
    classpath = configurations.ktlint
    args "-F", "src/**/*.kt"
}

task detektFailFast(type: io.gitlab.arturbosch.detekt.Detekt) {
    description = "Runs a failfast detekt build."

    input = files("src/main/java")
    config = files("$projectDir/default-detekt-config.yml")
    debug = true
    reports {
        xml {
            destination = file("build/reports/failfast.xml")
        }

        html.destination = file("build/reports/failfast.html")
    }
}

check.dependsOn detekt

**Comment by schalkms** [comment]
> Where shall I put StringTemplate active: false ?

in your `detekt-config.yml` 

Why do you run a separate ktlint task? Detekt provides a wrapper around ktlint, which allows to configure rules. If you have some rules set to true in the `formatting` ruleset configuration (`detekt-config.yml`), then you will actually run these rules twice.

CC @arturbosch

**Comment by petnagy** [comment]
@schalkms I have add ktlint first. And after that I add detekt to my project. And it was good I was able to run ktlint separately. (sometimes when there was no code change detekt do not generate report but the previous was deleted and in this case it is good to run ktlint.)

**Comment by schalkms** [comment]
Then please disable all the rules in the formatting ruleset. (**detekt-config.yml**)
