### ISSUE TITLE
Automatic installation of Android Studio/Intellij detekt plugin?

### ISSUE THREAD

**Issue by andeep49** [arturbosch/detekt#1545]
Is there any way to automatically install the Android Studio/Intellij detekt plugin? It is cumbersome to tell all new joining developers to install and configure the plugin.

**Comment by schalkms** [comment]
You can write a script which automatically installs the plugin for IntelliJ. You need to put it in the **plugins** folder. [Documentation](https://intellij-support.jetbrains.com/hc/en-us/articles/206544519)
The detekt yaml settings file can be shared and also put into the right directory via script.

I am closing this for two reasons

1. this is out of scope of detekt
2. there are exisiting solutions for that.
