### ISSUE TITLE
Rule: Report forEach usages on Ranges

### ISSUE THREAD

**Issue by Mauin** [arturbosch/detekt#155]
As described in this post: https://sites.google.com/a/athaydes.com/renato-athaydes/posts/kotlinshiddencosts-benchmarks

It seems that calling:

```
fun rangeForEachMethod(blackHole: BlackHole) {
     (1..10).forEach {
         blackHole.consume(it)
     }
 }
```

has a huge performance cost compared to a simple `for` loop. We could add a rule pointing out usages of `forEach` on Ranges.

**Comment by arturbosch** [comment]
Such rules would make deteKt much more useful :). Also the spread operator shows a hidden cost according the article. But I think before writing the rules, we should also check the benchmarks ourself.

**Comment by arturbosch** [comment]
Should we introduce a new `performance` rule set?

**Comment by Mauin** [comment]
I did so in #161. Wasn't entirely sure about it, but I also didn't feel like this rule really fits into any of the other rule sets we have right now.

**Comment by arturbosch** [comment]
I will close this and add M13 for this :)
