### ISSUE TITLE
type and dependancy analisis

### ISSUE THREAD

**Issue by mgood7123** [arturbosch/detekt#1550]
could i use this in order to do type and dependancy analisis?

for example:
A.kt
```
class A() {
    inner class B(I : Int ) {
    ...
    }
}
fun B (I : String, II : Int) {}
````

B.kt
```
import A
val k = A.B(5)
```
A is of type class with no paramaters
B is of types class, function
B is a sub class of class A with paramaters I of type Int
B is a function with paramaters I of type String, II of type Int
A is used in B.kt
B, sub class of A, is used in B.kt

and so on

**Comment by schalkms** [comment]
There's currently no type and symbol solving in detekt. 
That means, that you can't do dependency analysis on a serious basis at the moment.
However, there's an open draft in #1532
I suggest that you subscribe to this thread and get notified when a merge happens.

I'm curious. What are you trying to do accomplish besides dependency analysis?

**Comment by mgood7123** [comment]
> There's currently no type and symbol solving in detekt.
> That means, that you can't do dependency analysis on a serious basis at the moment.
> However, there's an open draft in #1532
> I suggest that you subscribe to this thread and get notified when a merge happens.
> 
> I'm curious. What are you trying to do accomplish besides dependency analysis?

im trying to write a macro preprocessor lmao
