### ISSUE TITLE
Gradle Plugin missing jcommander:1.74 dependency

### ISSUE THREAD

**Issue by MarvinSchramm** [arturbosch/detekt#1568]
## Expected Behavior
Adding the gradle plugin as described on the gradle plugins page
https://plugins.gradle.org/plugin/io.gitlab.arturbosch.detekt should allow me to use the plugin

## Observed Behavior
When following the gradle plugin page example the detekt task can not be used due to a missing dependency on maven central
```
> Task :detekt FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':detekt'.
> Could not resolve all files for configuration ':detekt'.
   > Could not find com.beust:jcommander:1.74.
     Required by:
         project : > io.gitlab.arturbosch.detekt:detekt-cli:1.0.0-RC14
```

## Steps to Reproduce
Add the plugin like its described on the gradle plugins page
``` groovy
buildscript {
  repositories {
    maven {
      url "https://plugins.gradle.org/m2/"
    }
  }
  dependencies {
    classpath "io.gitlab.arturbosch.detekt:detekt-gradle-plugin:1.0.0-RC14"
  }
}

apply plugin: "io.gitlab.arturbosch.detekt"
```

Adding jcenter() as buildScript dependency solves my issue for now but i guess its better to correct the example for other users to not run into any issues

**Comment by 3flex** [comment]
Those examples are not provided by the author of the plugin. They're autogenerated by the Gradle plugin portal. So unfortunately those samples cannot be corrected.

The examples provided on the detekt documentation site do ask that users add `jcenter` to the list of repositories, so not sure what else we can do here?

**Comment by schalkms** [comment]
Nothing we could really do here. I agree.

**Comment by MarvinSchramm** [comment]
@3flex Thank you for this clarification!

**Comment by arturbosch** [comment]
Seems like jcommander is not published to maven central anymore: https://mvnrepository.com/artifact/com.beust/jcommander

We could downgrade to 1.72 or look for an alternative to it to not confuse potential users @3flex @schalkms ?

**Comment by 3flex** [comment]
Detekt itself isn't on Maven Central (#1396). Until that's fixed users still need to use jcenter repo anyway.

**Comment by schalkms** [comment]
We should be more careful here and downgrade to 1.72

**Comment by 3flex** [comment]
Sorry not sure I understand the reasoning for downgrading - as long as jcenter is in the list of repositories (which is documented) then build would not fail, and users need jcenter in list of repos because that's where detekt can be found since it's not on maven central. Did I miss something? :confused:

**Comment by schalkms** [comment]
@3flex the second possibility is ofc to update the docs and live with the additional jcenter repo.
