### ISSUE TITLE
ForbiddenVoid should have an ignoreOverriddenFunctions setting

### ISSUE THREAD

**Issue by x80486** [arturbosch/detekt#1569]
## Expected Behavior of the rule

If I set `ForbiddenVoid` to `true`, whenever I encounter an overridden function I eventually cannot change it (or I don't know how to do it) because the `Unit` type is actually _different_ from `Void`.

## Context

I'm trying to activate the rule and use it :sunglasses:

For instance, projects like `Vert.x` where you must extend from `AbstractVerticle` and usually/potentially override `start` and `stop`, have the type `startFuture: Future<Void>` and I don't have a way to exclude those.

**Comment by schalkms** [comment]
Maybe a new config option called *ignoreOverridden* does the trick here.
