### ISSUE TITLE
ForbiddenImport matches on substring, not full class

### ISSUE THREAD

**Issue by josephlbarnett** [arturbosch/detekt#1573]
The bug you're experiencing might have already be reported!
Please search in the [issues](https://github.com/arturbosch/detekt/issues) before creating one.

## Expected Behavior

There should be a way to forbid imports of specific classes and not match classes that are similar, but different.  

## Observed Behavior

because `ForbiddenImport` uses the `contains` method of `SplitPattern`, trying to forbid a class whose name is a substring of another class forbids both classes.  I believe calling `SplitPattern::equals` instead would fix the issue, but have not tested, and would probably break other usages (eg the wildcards in https://github.com/arturbosch/detekt/issues/1001 ).

## Steps to Reproduce

forbid `com.google.inject.Inject`, and run detekt against a class that imports `com.google.inject.Injector`

## Context

We'd like to forbid imports of guice classes that exist in javax.inject, for example `javax.inject.Inject` should be used over `com.google.inject.Inject`.  However, adding `com.google.inject.Inject`to the `ForbiddenImports` rule also forbids imports of `com.google.inject.Injector`, which is a class that has no javax.inject equivalent that we do not want to forbid.

## Your Environment

* Version of detekt used: 1.0.0-RC14
* Version of Gradle used (if applicable):
* Operating System and version:
* Link to your project (if it's a public repository):

**Comment by schalkms** [comment]
Thanks for reporting and having a look into it!
Would you mind to submit a PR including your tests?

**Comment by josephlbarnett** [comment]
PR submitted: https://github.com/arturbosch/detekt/pull/1575
