### ISSUE TITLE
Should detekt-api be Java-friendly?

### ISSUE THREAD

**Issue by 3flex** [arturbosch/detekt#1574]
I'm looking at the Javadoc produced by dokka for detekt-api. There are a few oddities related to Java interop (e.g. because BaseRule has a top level typealias a second class BaseRuleKt is generated in Javadoc - could be fixed by using `@file:JvmName`)

Question is, as a Kotlin focused project, do we care?

If not, should we change dokka config so instead of producing Javadoc (which will need several new annotations sprinkled through the code to get a nicer output) should we instead generate Jekyll compatible markdown which documents only the Kotlin-friendly API which won't require adding these annotations? That could then be published on GitHub pages.

**Comment by schalkms** [comment]
I'm not quite sure if the effort is worth it.
Let's see what others think about it.

**Comment by arturbosch** [comment]
Yep, no wishes for cleaner detekt-api docs for far :)

**Comment by 3flex** [comment]
> Yep, no wishes for cleaner detekt-api docs

Happy to drop Javadoc then and switch dokka output to Jekyll?

If so I can look into doing that. I think this will get rid of the last dokka warning as well since I believe that actually comes from the Javadoc tool

**Comment by arturbosch** [comment]
I think the javadoc jar is needed to be able to publish to maven central.
They need both, sources and javadoc jars.
What do you mean with changing output to jekyll?
Havin the api docs published to the website? That would be great %%

**Comment by 3flex** [comment]
> Havin the api docs published to the website?

Exactly, dokka can do this. I don't know if it can output two formats at once though (jekyll + javadoc) and I didn't realise javadoc is needed for Maven Central - I'll see what dokka can do.
