### ISSUE TITLE
False positive warning about using failFast in yaml config

### ISSUE THREAD

**Issue by Nevvea7** [arturbosch/detekt#1594]
Looked through failFast related issues and doesn't seem like someone's reported this already, sorry if it's a duplicate

## Expected Behavior
Not getting a warning that says `Using deprecated property 'failFast' in the yaml config. Please migrate to the new '--fail-fast' cli-flag or 'failFast' detekt extension property.` when using the default config yaml file

## Observed Behavior
Getting a warning `Using deprecated property 'failFast' in the yaml config. Please migrate to the new '--fail-fast' cli-flag or 'failFast' detekt extension property.` even though there's no `failFast` in my config yaml (I'm using the default yaml from [here](https://github.com/arturbosch/detekt/blob/master/detekt-cli/src/main/resources/default-detekt-config.yml))

## Steps to Reproduce
Use `config` to specify a config yaml in detekt:
```
    detekt {
        toolVersion = "1.0.0-RC14"
        config = files("${rootDir.parentFile.parent}/detekt-config.yml")
    }
```
When `config` is present, even if the yaml file is the same as the default yaml file, when I run `./gradlew detekt` I would get a warning about using deprecated property 'failFast' in the yaml config. If I comment out the config the warning disappears

## Your Environment

* Version of detekt used: 1.0.0-RC14
* Version of Gradle used (if applicable): 5.3.1
* Operating System and version: Mac OS 10.13.6

**Comment by 3flex** [comment]
This should be fixed by https://github.com/arturbosch/detekt/pull/1506 and available in the next release.
