### ISSUE TITLE
DetektTaskDslTest issues on macOS

### ISSUE THREAD

**Issue by pcl** [arturbosch/detekt#1611]
I can't build master. I get 8 errors (seemingly including some duplicates) when building `detekt-gradlew-plugin`. Attached is the report output directory.

I'm running Java 8. I also tried building the last release tag, and got the same errors.

I don't have a jetbrains.com account, so can't sign into the Slack channel. I think I was able to get in in the past; is that a new limitation?

**Comment by 3flex** [comment]
> I get 8 errors (seemingly including some duplicates) when building detekt-gradlew-plugin

Can you please provide the errors?

> Attached is the report output directory.

That would be good if it's available - I don't see any attachments?

> I don't have a jetbrains.com account, so can't sign into the Slack channel.

http://slack.kotlinlang.org/

**Comment by pcl** [comment]
Argh. I uploaded a tgz, but only zips are allowed. Didn't notice the error window. See attached, for real this time.

Thanks for the link; might be worthwhile to change the Slack link in the readme to point to the top-level survey too, or include a link to the survey on the Slack auth screen if such a thing is customizable.

[detekt-gradle-plugin-errors.zip](https://github.com/arturbosch/detekt/files/3116465/detekt-gradle-plugin-errors.zip)

**Comment by schalkms** [comment]
The problem lies in the `DetektTaskDslTest`.
This seems to be a Mac only problem.
Can you please comment out the mentioned class and try to build detekt again?

**Comment by pcl** [comment]
Yep, that was it!

**Comment by 3flex** [comment]
@pcl have just merged your PR, can you please checkout master and build to confirm this is fixed? Thanks!

**Comment by pcl** [comment]
It didn't quite work -- I was lazy and rebased my PR onto origin/master, but someone added a new test to that file over the weekend that also used `absolutePath`! Additional commit forthcoming...

**Comment by schalkms** [comment]
@pcl please submit a PR with the referenced changes and add me as a reviewer. 
I checked out your branch. Everything is running fine on my Mac.

**Comment by schalkms** [comment]
Closed with 2a0c46f
