### ISSUE TITLE
How to generate baseline file with specific Codesmell_Signature

### ISSUE THREAD

**Issue by QinJingjie** [arturbosch/detekt#1614]
Hi, I'm trying to generate a `baseline.xml` using `./gradlew detektBaseline` and define my detekt task :
```
detekt{
     baseline = projectDir.resolve("src/main/resources/reports/baseline.xml")
     input = files("src/main/java", "src/test/java", "src/main/kotlin", "src/test/kotlin", "$name.gradle.kts")
     config = files("kotlincheck/kotlin-common-style-config.yml")
 }
```
But generated `baseline.xml` don't have `Codesmell_Signature`.
Here is my `baseline.xml`:
```
<?xml version="1.0" ?>
<SmellBaseline>
  <Blacklist timestamp="1556192176797"></Blacklist>
  <Whitelist timestamp="1556192176797">
    <ID>ImportOrdering:</ID>
    <ID>Indentation:</ID>
    <ID>MaximumLineLength:</ID>
    <ID>NoItParamInMultilineLambda:</ID>
    <ID>SpacingAroundOperators:</ID>
  </Whitelist>
</SmellBaseline>
```
I'm using detekt RC14.
How can I generate a file with format like `<RuleID>:<Codesmell_Signature>`, I hope `Codesmell_Signature` to be a specific file name

**Comment by zhuruyi2013** [comment]
my baseline file doesn't have` Codesmell_Signature ` too。

**Comment by arturbosch** [comment]
please take a look at the linked issue for an answer. If you still have any troubles, please reopen this issue.
