### ISSUE TITLE
Gradle build failed

### ISSUE THREAD

**Issue by IgorGanapolsky** [arturbosch/detekt#1616]
## Expected Behavior
I should be able to follow the README and run `./gradlew build shadowJar`

## Observed Behavior
Got an error: 
> FAILURE: Build failed with an exception.
* What went wrong:
Execution failed for task ':detekt-gradle-plugin:test'.
> There were failing tests. See the report at: file:///Users/igor.ganapolsky/workspace/git/detekt/detekt-gradle-plugin/build/reports/tests/test/index.html

## Steps to Reproduce
Follow the README

## Context
I am trying to build this library for the first time

## Your Environment

* Version of detekt used: latest master branch
* Version of Gradle used (if applicable): 5.4
* Operating System and version: Mac OS 10.13.6
* Link to your project (if it's a public repository):

**Comment by 3flex** [comment]
Do you have the same test output as #1611?

**Comment by arturbosch** [comment]
Both run on macOS.
What Gradle version did you used?

**Comment by schalkms** [comment]
I'm pretty sure that this is a duplicate.

@IgorGanapolsky 
If this is not the case please ping us here.
Please take a look at the linked issue and my comment.

**Comment by 3flex** [comment]
@IgorGanapolsky hopefully a fix has just been merged to master branch, would be great if you are able to checkout master and confirm? If it's not fixed please comment in #1622. Thank you!

**Comment by IgorGanapolsky** [comment]
@3flex The test report in ticket #1611 states:
> baseline /var/folders/_h/3hlxwcnx7ndf76d7f5mzd0sm0000gn/T/applyPlugin2916622894074676092.tmp/detekt-baseline.xml

However, I do not have such a folder on my machine.  What does it mean?

Also, my tests are still failing (on a second Macbook Pro now).  Please see attached.
[reports.zip](https://github.com/arturbosch/detekt/files/3127547/reports.zip)

**Comment by 3flex** [comment]
That's a temporary folder path generated by the tests - not expected to match a path on your machine as the generated path is random.

I'll wait for confirmation (or not) on the other ticket, if that's closed though I'll reopen this as it sounds like you still have issues. Unfortunately I don't have a mac to test on so if you're able to identify the issue & fix please submit a PR. @pcl may also be able to help.

**Comment by IgorGanapolsky** [comment]
I see a test failure such as
> passes multiple custom report params to cli
java.lang.AssertionError: 
Expecting:
 <"The client will now receive all logging from the daemon (pid: 11989). The daemon log file: /var/folders/gy/gnwqyd813qncsd7rn4sm6qs80000gn/T/.gradle-test-kit-eazyigz/test-kit-daemon/5.4/daemon-11989.out.log
Starting 33rd build in daemon [uptime: 2 mins 11.795 secs, performance: 99%, GC rate: 0.06/s, heap usage: 5% of 358.1 MB, non-heap usage: 39% of 268.4 MB]
Closing daemon's stdin at end of input.

How would I go about fixing this issue?

**Comment by 3flex** [comment]
The build is now tested on macOS in Travis CI on JDK 8, 11 and 12 and the build is passing.

Can you please checkout master once more and verify?

**Comment by schalkms** [comment]
@IgorGanapolsky we are sorry for the inconvenience. We were in the middle of fixing this problem. I hope that this problem is fixed with the current state.
If not, please also provide us the detekt-report files.

**Comment by IgorGanapolsky** [comment]
@3flex @schalkms Thanks for your efforts.  It builds now.
