### ISSUE TITLE
CI for macOS

### ISSUE THREAD

**Issue by schalkms** [arturbosch/detekt#1622]
After the build failure report in #1611 and #1616 on macOS I suggest to also include this in detekt's CI process.
Travis CI supports macOS for instance.  [reference](https://docs.travis-ci.com/user/reference/osx/)

**Comment by IgorGanapolsky** [comment]
Tests are failing on my Macbook Pro for `./gradlew build shadowJar`
[reports.zip](https://github.com/arturbosch/detekt/files/3127563/reports.zip)
.  See attached.

**Comment by schalkms** [comment]
@IgorGanapolsky I suppose you ran this with the latest master branch after #1624 was merged. Is this correct?

**Comment by schalkms** [comment]
I ran the tests with the referenced branch in #1611 and everything runs fine on my Mac.
