### ISSUE TITLE
Document meanings of rule severity levels

### ISSUE THREAD

**Issue by 3flex** [arturbosch/detekt#1630]
These severities are available, but there's no description for them.

I think each should have a single sentence string value which can then be displayed on the documentation site. Looking for suggestions on what each should mean:

1. CodeSmell
2. Style
3. Warning
4. Defect
5. Minor
6. Maintainability
7. Security
8. Performance

It might also be a good time to rename, add or deprecate some of these. I feel CodeSmell and Warning are too generic, and Minor isn't clear (it's a minor what? Minor code smell? Minor defect?)

**Comment by schalkms** [comment]
The rule severity levels definitely need a documentation page.

**Comment by arturbosch** [comment]
It's a minor severity :)
Yeah, some are really unclear and idk if we actually need them all.

`Minor` is not used at all I think. `Defect` could be renamed to `Potential Bug`.
Code Smell is meant to be anything generic which does not met other categories.

**Comment by schalkms** [comment]
> `Minor` is not used at all I think. 

It is actually used, but only in test code and as default value for the issue category in abstract classes.
