### ISSUE TITLE
False positive on ForbiddenVoid

### ISSUE THREAD

**Issue by mjuanes** [arturbosch/detekt#1642]
## Observed Behavior
False positive on ForbiddenVoid when theres a property/field/enum/class name/class or something called void.

## Steps to Reproduce
Call a class Void, o create a Void value in a enum.

## Your Environment

* Version of detekt used: RC 14, last one I think.
* Version of Gradle used (if applicable):
* Operating System and version:
* Link to your project (if it's a public repository):

**Comment by schalkms** [comment]
@mjuanes This only reports when you reference properties or classes called `Void`, but not the declaration itself.
Hence, this needs type and symbol solving.
Please take a look at #1740
