### ISSUE TITLE
how can i find full <RuleID>:<Codesmell_Signature> rules? 

### ISSUE THREAD

**Issue by zhuruyi2013** [arturbosch/detekt#1650]
https://arturbosch.github.io/detekt/baseline.html
https://github.com/arturbosch/detekt
all the above doesn't have full Codesmell_Signature rules， for example i  want to add a whitelist with `LongParameterList `，but i don't know the syntax. Anyone can help me? 
tks.

**Comment by arturbosch** [comment]
Thanks for the feedback. I admit it is very unclear how to figure out the signature.
The above link mentions it `The Codesmell_Signature is not printed to the console but can be retrieved from an output file (see output sections).`

We can print a file with all signatures when using the `txt` output report like:
`java -jar detekt-cli/build/libs/detekt-cli-1.0.0-RC14-all.jar -i . -r "txt:/home/abosch/Repos/detekt/detekt.txt"`

The file now contains entries like `ComplexMethod - 11/10 - [isIgnoredByConfig] at MagicNumber.kt:132:5 - Signature=MagicNumber.kt$MagicNumber$private fun isIgnoredByConfig(expression: KtConstantExpression)` where the last part is the signature which can be used inside the baseline.xml file :). Hope that helps.

**Comment by schalkms** [comment]
duplicate #1614 ?
