### ISSUE TITLE
exporting the rules

### ISSUE THREAD

**Issue by paul58914080** [arturbosch/detekt#1653]
Hello,

Is there a way to export the rules for kotlin so that I can import them in sonar ?

**Comment by arturbosch** [comment]
Please take a look at https://docs.sonarqube.org/display/PLUG/Import+AndroidLint+and+Detekt+Issues+Reports
if you use the official sonar plugin and want to import detekt findings.
Or use our detekt sonarqube plugin which will run detekt for you https://github.com/arturbosch/sonar-kotlin .

**Comment by paul58914080** [comment]
Thank you very much @arturbosch  👍
