### ISSUE TITLE
No kotlin file in test

### ISSUE THREAD

**Issue by tobiasKaminsky** [arturbosch/detekt#1660]
Similar to https://github.com/arturbosch/detekt/issues/754

## Expected Behavior
Detekt should detect kotlin files within test folder

## Observed Behavior
No test files are analyzed

## Steps to Reproduce
Added detekt:
- classpath "io.gitlab.arturbosch.detekt:detekt-gradle-plugin:1.0.0-RC14"
- apply plugin: "io.gitlab.arturbosch.detekt"
- see https://github.com/nextcloud/android/pull/4064/commits/633aee25262e62cd1bd86f534946e91984a536ce
- run it with ./gradlew detektGenerateConfig
- (renamed config to detekt.yml)
- run detekt
- see "number of kt files: 0"
- but: ./src/test/java/com/nextcloud/client/network/ConnectivityServiceTest.kt

## Context

See above 

## Your Environment

* Version of detekt used: 1.0.0-RC14
* Version of Gradle used (if applicable):
* Operating System and version: 5.1.1.
* Link to your project (if it's a public repository):

**Comment by tobiasKaminsky** [comment]
Adding

`input = files("src/")`

helped.
In my opinion this is still a bug, as all files were in src/…:
3 files in src/main/java/…
1 file in src/test/…
and only those in src/main/java were analyzed

**Comment by cortinico** [comment]
This looks like not a but the intended behavior.

If you don't specify the `input` property will default to `src/main/java` + `src/main/kotlin` and will skip your tests. Source: [DetektExtension.kt:28](https://github.com/arturbosch/detekt/blob/master/detekt-gradle-plugin/src/main/kotlin/io/gitlab/arturbosch/detekt/extensions/DetektExtension.kt#L28)

**Comment by tobiasKaminsky** [comment]
@cortinico thanks for the code reference.
Then maybe this could be enhanced in documentation.

**Comment by schalkms** [comment]
@cortinico thanks for helping out.
The [documentation](https://arturbosch.github.io/detekt/groovydsl.html) states this for the various interfaces.
@tobiasKaminsky 
What specific information in the docs would've helped you to solve the problem?
Could you help us to improve the documentation and maybe submit a PR which includes this information?

**Comment by tobiasKaminsky** [comment]
I'll do.

**Comment by marschwar** [comment]
Please see: https://arturbosch.github.io/detekt/groovydsl.html

> detekt - Runs a detekt analysis and complexity report on your source files. Configure the analysis inside the detekt closure. By default the standard rule set without any white- or blacklist is executed on sources files located in src/main/java and src/main/kotlin. Reports are automatically generated in xml and html format and can be found in build/reports/detekt/detekt.[xml|html] respectively. Please note that the detekt task is automatically run when executing gradle check.

**Comment by tobiasKaminsky** [comment]
Well…what shall I say: PEBKAC.

@marschwar thanks for pointing this out.
@schalkms I think this is enough, if I could read ;-)
