### ISSUE TITLE
Unable to Suppress MaxLineLength for multiline string other than on file level

### ISSUE THREAD

**Issue by Jedyny** [arturbosch/detekt#1667]
## Expected Behavior

The suppression applied to the variable in the code below, should prevent detekt from reporting the next line as exceeded the max line length.

```
class Example_Suppress_Variable {
    fun example() {
        @Suppress("MaxLineLength")
        val string = """
            Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.
        """.trimIndent()
    }
}
```

## Observed Behavior

The suppression above doesn't work, unless placed on the file level. I have tried placing it also on the function/class level, which didn't work too. The same for `@SuppressWarnings` alternative.

For simplicity I tested against the default detekt config, namely:

```
  MaxLineLength:
    active: true
    maxLineLength: 120
    excludePackageStatements: true
    excludeImportStatements: true
    excludeCommentStatements: false
```

## Steps to Reproduce

1. Copy-paste the code above into your project
2. Set-up detekt with the default configuration
3. Run detekt

I have also prepared a sample project demonstrating the issue, available from the link below.

## Your Environment
* Version of detekt used: 1.0.0-RC14
* Link to your project (if it's a public repository): https://github.com/Jedyny/max-line-example

**Comment by schalkms** [comment]
I tested this on my machine. You are right. The `@Suppress` annotation doesn't work for multiline strings.

**Comment by arturbosch** [comment]
Thanks for reporting.
Jap, seems like `findAnnotatedStatementInLine(file, offset, line)` is not clever enough for that and should be extended.
