### ISSUE TITLE
Rule: SpreadOperator

### ISSUE THREAD

**Issue by arturbosch** [arturbosch/detekt#167]
As mentioned in #155  and this [benchmark](https://sites.google.com/a/athaydes.com/renato-athaydes/posts/kotlinshiddencosts-benchmarks), using the spread operator can lead to performance costs compared to java.

**Comment by tagantroy** [comment]
Can you assign this issue to me?

**Comment by arturbosch** [comment]
Well I can't as your not a contributor yet, but give the rule a try, I won't work on it. I promise :)

**Comment by tagantroy** [comment]
@arturbosch can you close this issue?
