### ISSUE TITLE
UndocumentedPublicFunction should also report properties

### ISSUE THREAD

**Issue by robstoll** [arturbosch/detekt#1670]
## Expected Behavior
A property without documentation should also be reported

## Observed Behavior
no error (only function was reported)

## Steps to Reproduce
https://sonarcloud.io/project/issues?id=tegonal_atrium-ktor&open=AWsMs313vwsQMbwCGitv&resolved=false&types=CODE_SMELL

Error is only reported for the function as you can see.
To reproduce it manually:
1. git clone https://github.com/tegonal/atrium-ktor
2. ./gr detekt

## Your Environment
* Version of detekt used: 1.0.0-RC14
* Version of Gradle used (if applicable): 5.4.1
* Link to your project (if it's a public repository): https://github.com/tegonal/atrium-ktor

**Comment by schalkms** [comment]
Thanks for the suggestion.
This should be implemented in a new rule called `UndocumentedPublicProperty`.
Could you please have a go on this?

**Comment by robstoll** [comment]
I'll see if I get time for this. I haven't yet contributed to detekt and it seems you impose rules on contributors which have an influence on IDE settings: https://github.com/arturbosch/detekt/blob/master/.github/CONTRIBUTING.md
I don't intend to change my settings, therefore I would like to know if you have a repo where the IDE settings are in there as well so that I can reuse them. Or is there another way to set up the IDE easily according to detekt's needs?

**Comment by schalkms** [comment]
I can understand that you don't want to change your IDE settings.
Which setting do you mean?

**Comment by robstoll** [comment]
I haven't used Ktlint so far, so I have no idea what is all necessary that it works for detekt without affecting other projects within the IDE. Also I am pretty sure I am not using the `Kotlin Coding Conventions` in all cases. I guess I have to change settings as Contributing.md states
>Make sure your IDE uses KtLint formatting rules as well as the settings in .editorconfig

But maybe ktlint can also just be invoked via gradle?

**Comment by schalkms** [comment]
No worries.
Ktlint is invoked via Gradle when doing a build. 
This has no impact on your settings for other projects.
The .editorconfig gets picked up when you open the project just for the detekt project.

**Comment by arturbosch** [comment]
Yep, editorconfig, our formatting check/autocorrection + `kotlin.code.style=official` should not make you change anything. Please tell us otherwise. Thanks!

**Comment by robstoll** [comment]
@arturbosch thanks for the implementation and sorry, did not find the time to do it myself

**Comment by schalkms** [comment]
@robstoll no worries, thanks for all the feedback that you have provided to this repo.
