### ISSUE TITLE
Default NamingConventionViolation classPattern does not allow numbers

### ISSUE THREAD

**Issue by vanniktech** [arturbosch/detekt#169]
The regex is `'[A-Z$][a-zA-Z$]*'` which does not allow digits. Is this done on purpose?

**Comment by arturbosch** [comment]
Yes this was done on purpose.  I must admit it reflects my own opinion but not necessary the java style guides ... what are your reasons for using digits in class names?

**Comment by vanniktech** [comment]
In this case I was having a class for UInt8 that I needed to have for some Bluetooth related code. Also sometimes I end up using numbers when it comes to specific versions. e.g. some RxJava1/2 related code.

**Comment by arturbosch** [comment]
I will leave this open and if a bunch of people upvote this issue, we can extend the pattern?

**Comment by vanniktech** [comment]
Sure sounds perfect.

**Comment by vanniktech** [comment]
Is 2 + me considered a bunch of people? 😆

**Comment by arturbosch** [comment]
I don't think so. Also I'm astonished that not more people want it :/. Just override the pattern as long as we wait for more responses ;)

**Comment by vanniktech** [comment]
Yup that's what I'm doing.

**Comment by vanniktech** [comment]
Seems like not a lot of people want this.

**Comment by vanniktech** [comment]
I'm reopening this for another round of consideration. By now we've got 5 👍 here. I think it's pretty common to have numbers in there when you deal with a certain dependency version. For instance `RxJava2` vs `RxJava1` or brands that have names that contain numbers like `car2go`.
