### ISSUE TITLE
cli arg excludes not working

### ISSUE THREAD

**Issue by vasdeveloper** [arturbosch/detekt#1691]
```xml
apply plugin: "io.gitlab.arturbosch.detekt"

detekt {
        version = "1.0.0-RC15"
        input = files("$projectDir/src/main/java")
        config = files("$project.rootDir/detekt/detekt_config_codecc.yml")   
        baseline = file("$project.rootDir/detekt/detekt.xml")   
        parallel = true
        disableDefaultRuleSets = false
        debug = false
        excludes = ". */one/. *"
        reports {   
            xml {
                enabled = true
                destination = file("$project.rootDir/build/reports/detekt.xml")
            }
            html {
                enabled = true
                destination = file("$project.rootDir/build/reports/detekt.html")
            }
        }
    }
```

## Expected Behavior
work

## Observed Behavior
Gradle not work, error message:

> * What went wrong:
A problem occurred evaluating script.
> Could not set unknown property 'excludes' for object of type io.gitlab.arturbosch.detekt.extensions.DetektExtension.

## Steps to Reproduce
we use in android app.

## Your Environment
* Version of detekt used: RC15
* Version of Gradle used (if applicable): 4.9
* Operating System and version: mac os 10.14.4
* Link to your project (if it's a public repository):

**Comment by schalkms** [comment]
That behavior is correct. The property is called **exclude** without a **s**.

**Comment by vasdeveloper** [comment]
> That behavior is correct. The property is called **exclude** without a **s**.

Stil not work with or without s

> * What went wrong:
A problem occurred evaluating script.
> Could not set unknown property 'exclude' for object of type io.gitlab.arturbosch.detekt.extensions.DetektExtension.

**Comment by schalkms** [comment]
The pattern is still wrong. Detekt uses globbimg pattern since RC15.

[Reference](https://arturbosch.github.io/detekt/configurations.html#path-filters--excludes--includes)
[Changelog](https://arturbosch.github.io/detekt/changelog-rc.html#rc15)

**Comment by arturbosch** [comment]
Argh, @3flex @schalkms should we do an emergency rename from `excludes` to `exclude` to match the gradle way or stay with excludes as these are "two different worlds"?

**Comment by 3flex** [comment]
I don't think exclude or excludes was ever supported on the extension? The parameter was named `filters` (now noop in the plugin and marked with a deprecation message).

Includes & excludes need to be set on the task (see [SourceTask](https://docs.gradle.org/current/javadoc/org/gradle/api/tasks/SourceTask.html))

Perhaps the deprecation message on `filters` on the extension of "Replace with task setIncludes/setExcludes" is not clear?

**Comment by arturbosch** [comment]
Oh I meant the cli flag which got renamed from `filters` to `excludes`.
The gradle plugins allows:
```
    exclude("**/build/**")
    setExcludes(listOf("**/build/**", "\"**/resources/**\""))
```

**Comment by schalkms** [comment]
I wouldn't do it.

**Comment by arturbosch** [comment]
@schalkms yeah with groovy dsl `excludes = [..]` is possible.

**Comment by schalkms** [comment]
@arturbosch I think we should be more careful with breaking changes towards v1.
I guess we can close this issue.
