### ISSUE TITLE
Strange symbols at the beginning of each console message 

### ISSUE THREAD

**Issue by remal** [arturbosch/detekt#1694]
I'm using Detekt with Gradle and getting console output like this:
```
[33m[0mRuleset: complexity
[33m[0mRuleset: empty-blocks
[33m[0mRuleset: exceptions
[33m[0mRuleset: naming
```

Please remove these strange prefixes. If it's for colored output, please make "if the console supports colors" detection smarter, like it's done in Gradle, for example.

I'm running Gradle from IDEA.

## Your Environment
* Version of detekt used: Gradle plugin 1.0.0-RC15
* Version of Gradle used (if applicable): 5.4.1
* Operation system: Windows 10

**Comment by marschwar** [comment]
Thank you for reporting this.

**Comment by schalkms** [comment]
Thanks for reporting this bug. 
Please answer the following questions to help us reproduce the problem.
Which default system shell are you using on Windows?
Which shell does IntelliJ's terminal emulator emulate?

**Comment by remal** [comment]
> Which default system shell are you using on Windows?
Basically I don't use system shell. But if I have to, I use ёсьвёю I'm not sure if I answered correctly...

> Which shell does IntelliJ's terminal emulator emulate?
I don't know.

---

As I can see in Gradle sources, Gradle uses [Ansi](https://github.com/fusesource/jansi) library to colorize the output. As I understand, the library checks if current OS is Windows and if it's so, it does some magic.

If I'm right, I suggest choosing between these options:
* Omit colors on Windows systems (you can check if `os.name` system property contains `win`)
* Use Ansi library to colorize output. Personally I don't like this solutions, as it requires to add one more dependency. But you can shade this dependency :)

**Comment by remal** [comment]
@marschwar @schalkms I've submitted 2 PRs. Suggest we merge #1702 and close the other.

**Comment by schalkms** [comment]
@remal big thanks 🥇
