### ISSUE TITLE
The `hasLocationStrings` custom assert is broken

### ISSUE THREAD

**Issue by cortinico** [arturbosch/detekt#1706]
_This issue is related to the detekt testing framework and the `hasLocationStrings` custom assert._

After some investigation looks like the `hasLocationStrings` we're using in the tests is broken and is never asserting properly. Apparently the `hasLocationStrings` are always succeeding and a failure is never raised.

## Expected Behavior
The `hasLocationStrings` assertion should fail if the provided location string is not correct.

## Observed Behavior
The `hasLocationStrings` assertion never fails.

## Steps to Reproduce
I do have a branch where tests are supposed to be broken:
https://github.com/cortinico/detekt/tree/break-hasLocationString

Specifically in this commit: https://github.com/cortinico/detekt/commit/7077bf3df40c6d64ea1db0afeb9406fab00f8d70
Looks like all the tests passed:
https://github.com/cortinico/detekt/runs/149976114

## Context
See comments in #1690

**Comment by rock3r** [comment]
Just for later reference if anyone stumbles upon this being closed — it was fixed in #1707 :)
