### ISSUE TITLE
Terminal Output customization

### ISSUE THREAD

**Issue by vanniktech** [arturbosch/detekt#171]
Coming from #60

Some things that could be customized:

- having a clickable link to the file so it can be edited directly via the default editor
- only print name + package of file to save space

**Comment by vanniktech** [comment]
Where should those be configured?

**Comment by arturbosch** [comment]
The starting point would be `OutputFacade`. There I just use `println` for console printing. This issue sounds much wider. Maybe more the direction of `OutputFormat`

**Comment by arturbosch** [comment]
I hope your not started with this issue. I'm working on detekt extensions (RuleSets, Processors, OutputFormat's, ConsoleReport's) which will be included in api module in the next RC version.

**Comment by vanniktech** [comment]
Nope haven't. Knock yourself out.

**Comment by vanniktech** [comment]
Closing as this should be done. If not I'll open a new one.

**Comment by vanniktech** [comment]
Just picking this one up again. How can I achieve `having a clickable link to the file so it can be edited directly via the default editor` the part thats missing is the module name.

```diff
-src/androidTest/java/com/vanniktech/chessclock/screenshots/ScreenshotsTest.kt:33:3
+app/src/androidTest/java/com/vanniktech/chessclock/screenshots/ScreenshotsTest.kt:33:3
```

**Comment by arturbosch** [comment]
So the project name is only missing? Which shell do you use so you can click on that link?

**Comment by vanniktech** [comment]
iTerm 2 and I think the normal apple terminal can do this too.
