### ISSUE TITLE
1.0.0-RC15 is not published to maven central

### ISSUE THREAD

**Issue by ayberk** [arturbosch/detekt#1721]
I see that it has been released to [jcenter but not to maven central](https://mvnrepository.com/artifact/io.gitlab.arturbosch.detekt/detekt-core). All previous versions are there, is there a reason why the latest version is missing on maven central?

Unfortunately our internal tooling makes it really hard to work with packages that are not on maven central, so please consider publishing there :)

**Comment by schalkms** [comment]
Related #1396

**Comment by arturbosch** [comment]
Just pushed a sync from bintray. It may take a while.
Strangely this time it didn't run automatically.
Thanks for reporting. I will close this as @schalkms mentioned the other open issue.
