### ISSUE TITLE
Total weight of issues on build success

### ISSUE THREAD

**Issue by hgijeon** [arturbosch/detekt#1723]
Detekt shows weight of total issues and threshold on build failure. Is there any configuration for report/printing issue weight on successful build?

**Comment by cortinico** [comment]
Hey @hgijeon 
Looks like there is no solution out of the box.

You could use the deprecated fields: `warningThreshold` and `failThreshold`. If you set the `warningThreshold` to `1` you will see the total weight on the terminal, also when the build is green.

Ideally we could add this information on every output as I think is useful for the user.

**Comment by schalkms** [comment]
I think we should print this on every output, except when the issue count equals zero.

**Comment by cortinico** [comment]
> I think we should print this on every output, except when the issue count equals zero.

Agree, I can take care of it :)

**Comment by schalkms** [comment]
Puhh, that was fast.

**Comment by arturbosch** [comment]
Oh we should totally delete the deprecated stuff :D
