### ISSUE TITLE
There is no such a Gradle Task : detektMain

### ISSUE THREAD

**Issue by neugaojin** [arturbosch/detekt#1726]
I'm Writing Custom rules that rely on symbols and types being resolved
I want use BindingContext for analysis
But there is no such task : detektMain

When My Project Access Plugin `1.0.0-RC15`
rootDir/build.gradle
```
    dependencies {
        classpath 'com.android.tools.build:gradle:3.4.0'
        classpath "io.gitlab.arturbosch.detekt:detekt-gradle-plugin:1.0.0-RC15"
        // NOTE: Do not place your application dependencies here; they belong
        // in the individual module build.gradle files
    }
```
app/build.gradle
```
apply plugin: 'io.gitlab.arturbosch.detekt'

detekt {
    toolVersion = "1.0.0-RC15"
    config = files("${rootProject.projectDir}/config.yml")
    buildUponDefaultConfig = false
    disableDefaultRuleSets = true
    def fileCollection = files("${rootProject.projectDir}/")
    input = fileCollection
    reports {
        html {
            enabled = false
            destination = file("${rootProject.projectDir}/config/html.html")
        }
    }
}
```
when i run `./gradlew tasks --group="verification"`
i got:
```
detekt
detektBaseline - Creates a detekt baseline on the given --baseline path.
detektGenerateConfig - Generate a detekt configuration file inside your project.
detektIdeaFormat - Uses an external idea installation to format your code.
detektIdeaInspect - Uses an external idea installation to inspect your code.
...
```
There is no task `detektMain`

**Comment by schalkms** [comment]
Have you specified the **default-classpath**?
See: https://arturbosch.github.io/detekt/cli.html

**Comment by 3flex** [comment]
The Kotlin JVM plugin needs to be applied to the project for the tasks to be auto generated... The Gradle plugin checks for plugin ID "org.jetbrains.kotlin.jvm", then creates the tasks.

Is that being applied to your project?

**Comment by neugaojin** [comment]
> The Kotlin JVM plugin needs to be applied to the project for the tasks to be auto generated... The Gradle plugin checks for plugin ID "org.jetbrains.kotlin.jvm", then creates the tasks.
> 
> Is that being applied to your project?

it is my mistake
my project has no apply plugin "org.jetbrains.kotlin.jvm"

**Comment by 3flex** [comment]
Thanks for your patience. Documentation is missing and it's a very new feature, so I hope you're able to build what you intended and can contribute the new rule(s) back to the project. Good luck!

**Comment by schalkms** [comment]
@3flex can you please update the [extension page](https://arturbosch.github.io/detekt/extensions.html) if you have time?
Since you implemented this feature, I think you have a good knowledge of detekt's extension mechanism.
