### ISSUE TITLE
Default values for properties with MagicNumber

### ISSUE THREAD

**Issue by msogrin** [arturbosch/detekt#1731]
Should MagicNumber rule trigger on values which are assigned to meaningfully named properties in a class?

Example: default values for Spring configuration properties
```
@ConfigurationProperties
class SampleProperties {
    var concurrentLimit: Int = 4
}
```
It's `var` and not constant because Spring might override this default value with a value provided in a configuration file or via env variable or via JVM property. But IMHO the number 4 here is already properly named and doesn't need to be extracted into another constant (like `DEFAULT_CONCURRENT_LIMIT`).

Somewhat related item is #1536.

**Comment by schalkms** [comment]
The `MagicNumber` rule has a config option called `IGNORE_PROPERTY_DECLARATION` for this reason. 
You need to set it to `true` in order to ignore your code sample.
