### ISSUE TITLE
Adding detekt to classpath causes builds to fail

### ISSUE THREAD

**Issue by Blisse** [arturbosch/detekt#1743]
I added 

```
buildscript {
  dependencies {
    classpath "io.gitlab.arturbosch.detekt:detekt-gradle-plugin:1.0.0-RC15"
  }
}
```

to my root build.gradle, and my builds now fail with

```
e: [...] Type mismatch: inferred type is String? but String was expected
```

on this line of code (since parcel.readString() is inferred as Nullable).

```
      val key = Screen.Key<Any, Any>(
          typeName = parcel.readString(),
          value = parcel.readString()
      )
```

Appreciate the error happening, but to be clear, **I did not add anything else to my codebase, except the classpath**. I never enabled the detekt plugin.

This prevents us from introducing detekt slowly into our large codebase.

This happens on both RC15 and RC16. It does not happen on RC14.

## Expected Behavior
compilation should succeed, nothing should change as the plugin hasn't been applied, is not active.

## Observed Behavior
compilation fails

## Your Environment
* Version of detekt used: 1.0.0-RC15 gradle plugin
* Version of Gradle used (if applicable): 5.4.1
* Operating System and version: 2015 MBP running 10.14.5 Mojave

**Comment by schalkms** [comment]
Can you please post the complete stack trace?
Can you please post your Gradle config which relates to configuring detekt?

**Comment by schalkms** [comment]
@Blisse could you please help us to reproduce the problem?

**Comment by schalkms** [comment]
Closed because it's not reproducible
