### ISSUE TITLE
How to keep configuration up to date?

### ISSUE THREAD

**Issue by igorwojda** [arturbosch/detekt#1744]
I have generated configuration some time ago using version `RC-13`. I also modified many of the attributes (mainly enabling more rules and updated a few settings). 

New detect versions introduce new "configuration attributes" (like `ignoreLocalVariableDeclaration` introduced here https://github.com/arturbosch/detekt/pull/1555).

What is the best way to make sure that my configuration contains all the "config attributes" (not just use default values because an attribute is missing from my old config)?

**Comment by schalkms** [comment]
I think using your favorite diff viewer for the config file might be the easiest option to see what changed between different versions.
Checking the change log is also helpful.
If you only have minor changes the flag `--build-upon-default-config` makes sense.

**Comment by igorwojda** [comment]
Diff tool works, but nowadays detect config has 500+ lines, so considering the fact that I have also changed some default settings there are many other diffs in this file than simple "attribute difs".
As a last result, diff tool works, but it is a bit painful, so I was really hoping for something extra like "add missing config attributes " task (I would be nice to have).

Anyway. Which change log you refer to? This one is empty 🤔 
So regarding https://arturbosch.github.io/detekt/changelog.html

**Comment by schalkms** [comment]
> so considering the fact that I have also changed some default settings there are many other diffs in this file than simple "attribute difs" 

You should compare the **un**modified default **default-detekt-config.yml** of RC15 and RC16 for example. This is easier than comparing your modified file with the config file of a newer version.
As I suggested building upon a default config also helps to solve this issue.

I refer to the following change log. It lists all changes.
https://arturbosch.github.io/detekt/changelog-rc.html

> As a last result, diff tool works, but it is a bit painful, so I was really hoping for something extra like "add missing config attributes " task

That's not as easy to do as it might sound. Furthermore, I don't think messing with the users config is worth the effort.

**Comment by igorwojda** [comment]
Thanks a lot for help 👍

**Comment by schalkms** [comment]
You're welcome.
