### ISSUE TITLE
Android Studio highlighting issue for excluded files

### ISSUE THREAD

**Issue by schauersbergern** [arturbosch/detekt#1745]
## Expected Behavior
When in the detekt-config.yml  a file or path is excluded for a rule, the line which
violates the rule should not be highlighted

## Observed Behavior
When in the detekt-config.yml  a file or path is excluded for a rule, the line which
violates the rule is still highlighted

## Steps to Reproduce

open a .kt class, add function:

suspend fun testfun() {
        var counter = 0

        val tasks = arrayOf<suspend () -> Unit>(
            { counter++ }
        )

        doParallel(*tasks)
    }

in detekt-config.yml add 

SpreadOperator:
    active: true
    excludes: "**/path/to/file"

after detekt check, the line doParallel(*tasks) is still highlighted with error color and
error "SpreadOperator: Using a spread operator causes a full copy of the array to be created before calling a method has a very high performance penalty."
is displayed

## Context
We wand to accomplish the same behaviour of visual plugin inspection and authomatic gradle inspection

## Your Environment

* Version of detekt used: 1.0.0-RC15
* Version of Gradle used (if applicable): 3.4.1
* Operating System and version: macOS 10.14.6
* Link to your project (if it's a public repository):

**Comment by schalkms** [comment]
I couldn't reproduce your problem.
Can you please post your Gradle config which relates to configuring detekt?

**Comment by schauersbergern** [comment]
I have set up a minimal detekt project,
Here is the config:
https://github.com/schauersbergern/detektMinimalSetup/blob/master/build.gradle

Note: Highlighting cannot be suppressed for the files in the excludes, e.g test, androidTest

![image](https://user-images.githubusercontent.com/22813752/60493648-8e2b7a00-9cad-11e9-9df4-7d4202687445.png)

![image](https://user-images.githubusercontent.com/22813752/60493696-b2875680-9cad-11e9-9208-ee84a8b2cbec.png)

**Comment by schalkms** [comment]
So you are using the Detekt IntelliJ plugin, right?
https://github.com/arturbosch/detekt-intellij-plugin

**Comment by schauersbergern** [comment]
Yes, thanks for the hint, I have filed the issue in the plugin repo
