### ISSUE TITLE
Do not treat codefactor warnings as error

### ISSUE THREAD

**Issue by schalkms** [arturbosch/detekt#1753]
Recently, PR have been failing because codefactor treats warnings as errors.
I think we should change this behavior.

**Comment by arturbosch** [comment]
I do not find an option in codefactor itself, maybe its a feature of github.
I added some excluding patterns for our testcases.

**Comment by schalkms** [comment]
Since there's nothing we can do about for now, I'll close this.
Unfortunately, only you as the repository owner can see all the config options on codefactor.

**Comment by schalkms** [comment]
I didn't receive an invitation.

**Comment by arturbosch** [comment]
Maybe you don't need one. Just log in with your GitHub account and detekt should be listed left in your project list.

**Comment by schalkms** [comment]
It works fine. Thanks!
