### ISSUE TITLE
Run checks without formatting on CI but with formatting on local

### ISSUE THREAD

**Issue by tallnato** [arturbosch/detekt#1765]
I would like to run the check (without formatting) on the CI, but still run the check and format  locally.

Is it possible to do it without  a custom `detekt.yml` file?

**Comment by cortinico** [comment]
> Is it possible to do it without a custom detekt.yml file?

Why this would be a problem? Is actually the easiest way that comes to my mind to address your scenario.

**Comment by schalkms** [comment]
You can also specify multiple config files and have the different configuration options in a separate file.
Please take a look at the following config option copied from [here](https://arturbosch.github.io/detekt/cli.html).
```
--config, -c
  Path to the config file (path/to/config.yml). 
  Multiple configuration files can be specified with ',' or ';' as separator.
```

**Comment by arturbosch** [comment]
@tallnato hey, with the newer detekt versions RC15+ you can have two detekt tasks, one with `autoCorrect` one without. Please take a look at our build.gradle.kts file for examples on adding additional detekt tasks.
