### ISSUE TITLE
Not running formatting autocorrect

### ISSUE THREAD

**Issue by akhbulatov** [arturbosch/detekt#1766]
Hey. I looked at similar issues and tried solutions from there, but it didn't work for Android project. For example, adding a new line at the end of a file. Maybe I missed something. When I run `./gradlew detekt`, the analysis is run and creates a report, but without formatting. For formatting need another task or reason for something else?

**build.gradle (project-level)**:
```
buildscript {
    ext.versions = [
            ....
            'detekt' : '1.0.0-RC16'
    ]

    repositories {
        google()
        jcenter()
        maven { url "https://plugins.gradle.org/m2/" }
    }

    dependencies {
        ...
        classpath "io.gitlab.arturbosch.detekt:detekt-gradle-plugin:${versions.detekt}"
    }
}

allprojects {
    apply from: "$rootDir/detekt.gradle"

    repositories {
        google()
        jcenter()
        maven { url 'https://jitpack.io' }
    }
}
```

**build.gralde (app module)**:
```
dependencies {
    ...
    detektPlugins "io.gitlab.arturbosch.detekt:detekt-formatting:${versions.detekt}"
}
```
**detekt.gradle (in project's root):**
```
apply plugin: "io.gitlab.arturbosch.detekt"

detekt {
    toolVersion = "${versions.detekt}"
    input = files("src/main/java")
    parallel = true
    filters = ".*build.*,.*/resources/.*,.*/tmp/.*"
    config = files("$rootDir/default-detekt-config.yml")
}
```

**default-detekt-config.yml:**
```
formatting:
  active: true
  android: true
  autoCorrect: true
  ...
  FinalNewline:
    active: true
    autoCorrect: true
```

**Comment by arturbosch** [comment]
Please try adding `autoCorrect = true` to your gradle build file inside the detekt extensions.

**Comment by bagage** [comment]
I'm facing the same issue. I tried your suggestion, but `autoCorrect` is not a know property:

```
Build file '/build.gradle' line: 86
A problem occurred evaluating root project 'testproject'.
> Could not set unknown property 'autoCorrect' for object of type io.gitlab.arturbosch.detekt.extensions.DetektExtension.
```

**Comment by akhbulatov** [comment]
@bagage try this:

**Comment by bagage** [comment]
Yes it works! Thanks a lot @akhbulatov!!

**Comment by bagage** [comment]
@akhbulatov maybe it's worth adding a note on the readme? I think many people would love to have autoCorrect enabled :).

**Comment by arturbosch** [comment]
@bagage @akhbulatov with the new release soon, you do not need the `tasks.withType...` thingy anymore, autoCorrect will work on the `detekt {...}` closure.
By mistake it was only added for the task but not for the extension.
