### ISSUE TITLE
Html Report add code preview

### ISSUE THREAD

**Issue by ZhouGongZaiShi** [arturbosch/detekt#1779]
## Expected Behavior
Html Report add an error code preview, it's like the html report of lint.

## Current Behavior
Html reports only source files and line number.  
If I want to know the specific error code, I also need to search, more cumbersome.

## Context
It's like the html report of lint. 
![lint html report](https://b2.bmp.ovh/imgs/2019/07/a382bf6102e95c09.png)
Add a block of code, this way I can have a rough preview.  
I'm sure there are other developers who have similar needs.  
Thank you!

**Comment by schalkms** [comment]
Thanks for your feedback!
You are actually the first one, who brought that up.

One would need to adapt the html report template and the `HtmlOutputReport` class, which handles the HTML rendering.

https://github.com/arturbosch/detekt/blob/f98ccac9aa352805621dd6a19888bb472d776cef/detekt-cli/src/main/resources/default-html-report-template.html#L1

https://github.com/arturbosch/detekt/blob/f98ccac9aa352805621dd6a19888bb472d776cef/detekt-cli/src/main/kotlin/io/gitlab/arturbosch/detekt/cli/out/HtmlOutputReport.kt#L16

@ZhouGongZaiShi would you mind to take a stab at this feature?

**Comment by BraisGabin** [comment]
We can close this issue now.

**Comment by schalkms** [comment]
Closed by d31e162
