### ISSUE TITLE
Custom ConsoleReport exclude by default

### ISSUE THREAD

**Issue by IlyaPavlovskii** [arturbosch/detekt#1781]
I've created a custom `ConsoleReport` class and I don't want to use it by default. How I can add it to exclusion by default? Only through `config.yml`?

**Comment by schalkms** [comment]
Yes, as you mentioned this can be done as shown in the following lines.

https://github.com/arturbosch/detekt/blob/ac4c8eafdfcc5c430967fa48f80c6d607982da0a/detekt-cli/src/main/resources/default-detekt-config.yml#L18-L22

You can also specify two config files and have the different configuration options in a separate file.
Please take a look at the following command copied from [here](https://arturbosch.github.io/detekt/cli.html).
```
--config, -c
  Path to the config file (path/to/config.yml). 
  Multiple configuration files can be specified with ',' or ';' as separator.
```

Please take a look at the following [section](https://arturbosch.github.io/detekt/extensions.html#let-detekt-know-about-your-extensions), which describes several options to let detekt know about your extension.

Does this answer your question?

**Comment by IlyaPavlovskii** [comment]
@schalkms Thanks a lot.
