### ISSUE TITLE
Too slow to run in precommit hook

### ISSUE THREAD

**Issue by srcreigh** [arturbosch/detekt#1792]
Hi, is there a way to set up detekt gradle task to run on only staged git files?

I did try my hand at it, subclassing the detekt task. However I couldn't re-use the settings in the subclassed detekt task (IIRC they are configured outside of the task itself) and there may have been some caching issues.

Similar issue #1057, do you strongly recommend SonarQube? This is for my workplace so it would be much higher scope to add that to CI, ideally we would get a quick check locally...

**Comment by schalkms** [comment]
Hi @srcreigh 
Yeah the answer is pretty much the same as in the linked issue.
In your case, you could also use a git commit hook shown in this [recorded talk](https://youtu.be/LT6m5_LO2DQ?t=690) on YouTube.
HTH

**Comment by schalkms** [comment]
This [code post](https://stackoverflow.com/questions/2412450/git-pre-commit-hook-changed-added-files) shows you how to get all staged files.
While we don't recommend this, it's certainly possible.
Detekt runs very fast. Unless you have a very big code base, this shouldn't matter at all.

**Comment by srcreigh** [comment]
Hi, forgive me, of course it is fast, I am just very impatient :-) I have a detekt pre-commit hook set up, but it usually takes 7-10 seconds to run the detekt gradle task.

Is there a particular reason you don't recommend detekting only staged files? For example could that produce false positives?

**Comment by schalkms** [comment]
> Is there a particular reason you don't recommend detekting only staged files?

When more rules use type and symbol solving, detekt will need the information from referenced types as well. Currently, only a very small number of rules (2-3) use type and symbol solving.

> I have a detekt pre-commit hook set up, but it usually takes 7-10 seconds to run the detekt gradle task.

If this is a dealbreaker for you, you can also use detekt's console application.

Anyways, fetching the staged files with the code snippet in the mentioned post should work. You need to feed the received file path list into detekt (via Gradle Groovy or Kotlin DSL or CLI).
If you manage to hack this together, I can also see this pre-commit hook as a nice addition to detekt. It would also help other users with the same use case. So please feel free to submit a PR.

There are so many ways for integrating detekt into a users CI toolchain. We are actively learning from the community. Thank you for bringing this up and for the nice active discussion in this issue!

**Comment by arturbosch** [comment]
You can list of changed files and pipe them to detekt via the `--input x,y,z` parameter.

See `git ls-files --modified` for example.
