### ISSUE TITLE
kotlin.KotlinNullPointerException

### ISSUE THREAD

**Issue by ber4444** [arturbosch/detekt#1803]
## Expected Behavior
Detect does static analysis

## Observed Behavior
NPE

## Steps to Reproduce
  FinalNewline:
    active: true
(setting it to false makes it work)

## Your Environment
com.pinterest.ktlint.ruleset.standard.FinalNewlineRule.visit(FinalNewlineRule.kt:18)
Analyzing '.../CardInfo.kt' led to an exception.
The original exception message was: kotlin.KotlinNullPointerException

* Version of detekt used:1.0.0-RC16
* Version of Gradle used (if applicable):5.5-rc-1
* Operating System and version:Mac 10.14.6

**Comment by schalkms** [comment]
Since detekt provides a wrapper over ktlint, this is not directly a problem of detekt.
@ber4444 May I ask you to report this issue with the complete stack trace and the report lines of code to ktlint's repository?

**Comment by afaucogney** [comment]
Is the FinalNewline did not disappear from Ktlint ?

**Comment by schalkms** [comment]
@afaucogney I don’t see that. How did you conclude that?
https://github.com/pinterest/ktlint/blob/master/ktlint-ruleset-standard/src/main/kotlin/com/pinterest/ktlint/ruleset/standard/FinalNewlineRule.kt
What
