### ISSUE TITLE
Detekt plugin not able to download from Maven central

### ISSUE THREAD

**Issue by ruchirnaphade** [arturbosch/detekt#1805]
The bug you're experiencing might have already be reported!
Please search in the [issues](https://github.com/arturbosch/detekt/issues) before creating one.

## Expected Behavior
It should download plugin from Maven central repo

## Observed Behavior
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-antrun-plugin:1.8:run (detekt) on project agathe: Execution detekt of goal org.apache.maven.plugins:maven-antrun-plugin:1.8:run failed: Plugin org.apache.maven.plugins:maven-antrun-plugin:1.8 or one of its dependencies could not be resolved: Could not find artifact com.beust:jcommander:jar:1.74 in central (https://repo.maven.apache.org/maven2) -> [Help 1]

## Context
I am working with Kotlin and want to do static analysis using Detekt plugin. My problem is, when I want to download it from Maven central repository, it is giving me below error. But when I use company's repository (Nexus), it does not give me any error and downloads it smoothly. I don't understand this.

Can someone tell me why this is happening? I want to use this plugin and have not found out any other alternative.

## Your Environment
I am using Detekt for Kotlin with Maven.
Version of detekt is 1.8

**Comment by schalkms** [comment]
Duplicate #1568 

> Jcommander isn't published to maven central anymore.

> The examples provided on the detekt documentation site do ask that users add jcenter to the list of repositories

**Comment by arturbosch** [comment]
The last release tag for jcommander on github is from [2017](https://github.com/cbeust/jcommander/releases). I can't find the release notes for the 1.74 release. 1.72 is latest on Maven central and 1.71 is latest on github.
As detekt is now fully published to maven central, we should use 1.72 of jcommander instead.
Maybe even migrate away from jcommander ...

**Comment by schalkms** [comment]
> As detekt is now fully published to maven central, we should use 1.72 of jcommander instead.

Agreed.

> Maybe even migrate away from jcommander

Jcommander does a good job for detekt. I don't think it's worth the effort to migrate away.
