### ISSUE TITLE
latest version 1.0.0 or 1.0.0-RC16?

### ISSUE THREAD

**Issue by robstoll** [arturbosch/detekt#1813]
What is the newest version 1.0.0 as advertised in README or 1.0.0-RC16 as advertised under releases. I am asking as I updated to 1.0.0 and got a lot of false positives (the false positives are due to #1806, still wondering what I should use though)

**Comment by schalkms** [comment]
1.0.0 is the newest version. Detekt just got out of the RC phase.
@arturbosch 1.0.0 doesn't appear in the GitHub release page. Can you please push the binaries to GitHub?
Please use this [guide](https://arturbosch.github.io/detekt/howto-migratetestpattern.html) for migrating away from the **test-pattern** feature, which got deprecated in RC15.

@robstoll thanks for informing us about the missing binary!

**Comment by robstoll** [comment]
Feel free to close the issue at any point, I am using 1.0.0 and it worked :)

**Comment by schalkms** [comment]
Anyhow, version 1.0.0 should appear on the GitHub release page.

**Comment by arturbosch** [comment]
Github release tag should be up, thanks for the reminder!
