### ISSUE TITLE
Rule TodoComment

### ISSUE THREAD

**Issue by vanniktech** [arturbosch/detekt#182]
Basically flags the usage of `// TODO: something`

Inspired by [this checkstyle rule](http://checkstyle.sourceforge.net/config_misc.html#TodoComment).

Sidenote: I'd not flag `// TODO something` as sometimes you can't do something regarding a Todo - [like here](https://github.com/arturbosch/detekt/blob/d8456af3e639947b773cff0516e0866825c74d2b/detekt-gradle-plugin/src/test/kotlin/io/gitlab/arturbosch/detekt/extensions/DetektExtensionTest.kt#L40). Checkstyle also has this behavior.

**Comment by arturbosch** [comment]
I like the differences between `TODO:` and just `TODO`. Ofc I could just have created an issue for that ...

Should this be added to the `style` rule set? Fixme should also be handled ^^

**Comment by vanniktech** [comment]
To fix me I'd apply the same behavior regarding the `:`. I'm not that familiar with the rule sets. But yeah style sounds logical.

**Comment by vanniktech** [comment]
To get this moving. The idea is now to have a Rule which works on `PsiComments`.

How do we want this to be configured? Three options are wanted `TODO`, `STOPSHIP` and `FIXME`.

Having one rule is an idea, since one might want TODO to get flagged but not to break the build whereas STOPSHIP should break the build.

Another option would be to have a rule which takes some keywords over the configuration file like `TODO:,FIXME:,STOPSHIP:` and just does a simple contains on the comments and then decides to flag this or not. Also this would then be pretty extensible which is also nice and so far my favorite.

**Comment by arturbosch** [comment]
The second shoulds good to me. I think I would also prefer to name the strings the comment should contain like you did instead of a very flexible regex. Should be build really fail on STOPSHIP from the detekt side? What are the cases when STOPSHIP is used?

**Comment by vanniktech** [comment]
No, it'll just flag the code with `STOPSHIP`. There's no separation between `STOPSHIP` and `TODO`. `STOPSHIP` will just also be included in the default values.

How should this rule be named then?

InvalidComment
ForbiddenComment

**Comment by Mauin** [comment]
Do we make the configuration parameters to list the forbidden comments mandatory? Or do we use `TODO:,FIXME:,STOPSHIP:` as a default and let users override them if needed?

**Comment by vanniktech** [comment]
Yes we use those as a default. However we let the user the ability to override them to for instance only `TODO:,FIXME:`.

**Comment by Mauin** [comment]
Sounds good 👍
