### ISSUE TITLE
Gradle 6 planning

### ISSUE THREAD

**Issue by 3flex** [arturbosch/detekt#1820]
Gradle 5.6 was released today. The release notes state it's the final release in the 5.x series, with Gradle 6 coming next.

Today's plugin works on 4.10 through 5.6, but when 6 is released some deprecated code that detekt Gradle plugin uses is expected to be removed, so we won't easily be able to support 4.10 and 6.0 at the same time (I think there are some tricky workarounds but it's debatable if the effort is worth it).

There are some features in later 5.x releases including 5.6 that would simplify the plugin implementation but cannot use because of backward compatibility issues.

Thoughts on future support? I'd suggest that when 6 is released that we use a similar strategy of supporting final 5.x release for as long as possible as well as 6 ongoing.

**Comment by schalkms** [comment]
> Thoughts on future support? I'd suggest that when 6 is released that we use a similar strategy of supporting final 5.x release for as long as possible as well as 6 ongoing.

+1

**Comment by arturbosch** [comment]
I agree with dropping 4.x support. Are there some important api changes that we should support 5.1+ or 5.2+ ?

**Comment by 3flex** [comment]
Not that I know of. Simplifying the plugin implementation using all the features released in 5.x series probably means requiring 5.6 for users of the plugin, but I'll test earlier versions to see... Maybe some features only require compilation with 5.6 but can be consumed in earlier versions?

**Comment by 3flex** [comment]
I will close this since we have agreement on a plan. Actually some deprecated features we use may not be removed in 6.0 after all, so it might be possible to keep supporting 4.9. If that's possible without difficult workarounds we could keep supporting it, but if we have to drop 4.x support then we can go to 5.6 and take advantage of some newer features without causing much trouble for users.

**Comment by arturbosch** [comment]
Just for your interest. Currently a major amount of Bintray downloads comes from Gradle 4.10.

**Comment by schalkms** [comment]
@arturbosch Thanks for providing the stats. Should we reconsider our plan?

**Comment by arturbosch** [comment]
Bintray provides us with logs of the last 30 days: https://bintray.com/arturbosch/code-analysis/detekt#statistics -> Download Logs (I'm not sure if you can see them, I guess not).

I've downloaded two days of logs and scrolled through the entries. I can confirm that most Gradle 4 users are on version `<= RC14` (and there are a lot of downloads for older versions, bintray shows us only the last 10, maybe I can ask them if they can give us more permissions as we are an OSS).

I think we need to wait and see if we can still support 4.9 when 6.0 is out or not.

**Comment by 3flex** [comment]
I've been following the nightly builds, and some deprecated methods have been removed which the plugin used.

So minimum version will have to be 5.0, though we can go higher if we choose. I'll open a WIP PR so changes can be removed, I think we can carry over the conversation there.
