### ISSUE TITLE
Gradle `detekt` task is not incremental

### ISSUE THREAD

**Issue by lwasyl** [arturbosch/detekt#1821]
Changelog for RC9 mentions `detekt task which is incremental and is bound to the check task`. However when running Detekt task for a single module, I do not observe incremental behavior: regardless of whether I change one file or almost all files in module, the task runs for similar amount of time.

I confirmed this by running `detekt` task ona module couple of times without changing any files and observing that first run invokes Detekt and subsequent don't invoke it at all (as expected). I then modified one file and inspected cliArguments passed to the cli - the files list contained all files of the module, instead of just the one that has been changed.

I made sure to invoke each task in the same way so that Gradle doesn't discard incrementality for some reason like changed classpath.

## Your Environment
* Version of detekt used: 1.0.0
* Version of Gradle used (if applicable): 5.5
* Operating System and version: macOS 10.14.6

**Comment by 3flex** [comment]
The description is maybe misleading, what it means to say is that the Gradle task supports Incremental Builds (if inputs don't change then the task will not be run as you observed).

But detekt task itself is not incremental. I'll update the change log so it's more accurate.

**Comment by lwasyl** [comment]
Thanks for answering :) Is there any specific incompatibility that makes it difficult to make the task incremental, or it just wasn't a priority?

**Comment by schalkms** [comment]
Please see my comment in https://github.com/arturbosch/detekt/issues/1792#issuecomment-516989962, where I describe the circumstances.

**Comment by arturbosch** [comment]
> Thanks for answering :) Is there any specific incompatibility that makes it difficult to make the task incremental, or it just wasn't a priority?

I think it does not justify the work to do this as the kotlin compiler setup is really slow.
If you have 1 changed files or a whole module with 50 files, detekt itself will be like ~5% of the time.

You can experiment with `git ls-files --modified` and `java -jar detekt.jar --input x,y,z...`
