### ISSUE TITLE
Please provide autoCorrect for TrailingWhitespace

### ISSUE THREAD

**Issue by bagage** [arturbosch/detekt#1834]
## Expected Behavior of the rule
The `TrailingWhitespace` rule is complaining but cannot fix whitespaces automatically. It would be really great to have it though, cause it's quite boring to fix them manually.

PS: same idea for `PsiWhiteSpace` but unfortunately this is ktlint.

**Comment by cortinico** [comment]
Ideally you should be able to use the `NoTrailingSpaces` rule that is a wrapper for the ktlint homonymous rule. That will allow you to enable the `autoCorrect`.

**Comment by schalkms** [comment]
If you want the `autoCorrect` feature you should use ktlint's `NoTrailingWhitespace` rule, which does exactly what you want.
Detekt does not support `autoCorrect` at the moment. Because that's were ktlint shines, we decided against it in the early RC versions, though that's not set in stone.
