### ISSUE TITLE
Can I handle exit code after 1.0.1 release?

### ISSUE THREAD

**Issue by duck8823** [arturbosch/detekt#1842]
Hi, I'm using detekt and it has been great! 

I exclude BuildFailureReport in detekt config and be using custom report that throws BuildFailure at a specified timing for change  exit code dynamically in CI.

But #1818 changes `BuildFailureReport` and `Runner`. And thereby, detekt command always failure even if exclude BuildFailureReport. ( I tried and confirmed it in master branch. )

Can I handle exit code after 1.0.1 release?

thanks.

**Comment by arturbosch** [comment]
Hi, I'm not sure I understood your use case fully.
Having the `BuildFailurReport` throwing an exception was an architectural bug which needed to be fixed. It's purpose is just to notify the user about threshold warnings and the failure.

I see that [you are using the BuildFailureReport inside your report](https://github.com/duck8823/detekt-ci-extension/blob/master/src/main/kotlin/com/github/duck8823/detekt/ci/extension/CIBuildFailureReport.kt).

You could turn off the off build failure in the config file (`build -> maxIssues: -1`) and then reimplement the build failure logic like here:
 https://github.com/arturbosch/detekt/blob/366612612af3ca6121964482126d40bc58f9cca8/detekt-cli/src/main/kotlin/io/gitlab/arturbosch/detekt/cli/runners/Runner.kt#L28-L34

**Comment by duck8823** [comment]
Thanks you for your reply !

I understood it was an architectural bug and can be disabled in the configuration file.

Where should I reimplement a build failure logic? My CustomReport?

**Comment by arturbosch** [comment]
> Where should I reimplement a build failure logic? My CustomReport?

Yes, I would say for now this is the way. Ofc it is not same we had before, but for now we do not have an official way to filter the `Detektion` result. Maybe we can implement a way through our extension mechanism (#1836).

**Comment by duck8823** [comment]
I see. So many thanks!
I close this issue.

thank you.
