### ISSUE TITLE
false positive: ExplicitItLambdaParameter when having two or more parameters

### ISSUE THREAD

**Issue by robstoll** [arturbosch/detekt#1858]
## Expected Behavior
this check should only apply if the lambda has one parameter

## Observed Behavior
it also reports if there is more than 1 parameter

## Steps to Reproduce
listOf(1,2).forEachIndexed { index, it -> println("element $index: $it")}

## Your Environment
* Version of detekt used: 1.0.1
* Link to your project (if it's a public repository): https://github.com/robstoll/kbox

**Comment by schalkms** [comment]
According to our tests and specification this behavior is correct. 
You might want to choose a better name for the control variable than the implicit lambda parameter name `it`.
Please take a look at the following code and the [documentation](https://arturbosch.github.io/detekt/style.html#explicititlambdaparameter) for this rule.

https://github.com/arturbosch/detekt/blob/ed77f0c9ebff73a50348c76782e6dcb1bd7d7b08/detekt-rules/src/test/kotlin/io/gitlab/arturbosch/detekt/rules/style/ExplicitItLambdaParameterSpec.kt#L41-L56

**Comment by robstoll** [comment]
Fair enough and thanks for the quick reply
