### ISSUE TITLE
Is not a valid offset for file 

### ISSUE THREAD

**Issue by Garf1eldGit** [arturbosch/detekt#1877]
I decided to use sonar in conjunction with sonar-kotlin and gained error. If i use the standard sonar plugin everything works correctly.

When i run the scanner with ./gradlew sonarqube I get an error.
When i reformat code with random rules it works, but another files get me same error.

SonarQube 7.4 and 7.6 and 7.9.1
sonarqube scanner gradle plugin 2.7.1
sonar-kotlin-1.0.0.jar
```
Error :  Caused by: java.lang.IllegalArgumentException: Unable to highlight file FileName.kt
Caused by: java.lang.IllegalArgumentException: 1890 is not a valid offset for file  */*/*/FileName.kt. Max offset is 1882
```
Gradle properties

```
sonarqube {
    properties {
        property "sonar.projectName", "Project"
        property "sonar.projectKey", "test"
        property "sonar.sourceEncoding", "UTF-8"
        property "sonar.host.url", "http://localhost:9000/"
        property "sonar.language", "kotlin"
        property "sonar.sources", "src/main/"
        property "sonar.login", "*******"
    }
}
```

**Comment by schalkms** [comment]
What rule causes this error? Can you please post the complete stack trace?

**Comment by schalkms** [comment]
Closed
Please take a look at https://github.com/arturbosch/sonar-kotlin/issues/102
