### ISSUE TITLE
Error Installing the plugin in IntelliJ Community Edition

### ISSUE THREAD

**Issue by jcpea** [arturbosch/detekt#1878]
### Just adding the plugin into build.gradle.kts with no other parameter

plugins {
  id("io.gitlab.arturbosch.detekt") version "1.0.1"
}

> Failed to notify project evaluation listener.
   > Receiver class org.jetbrains.kotlin.allopen.gradle.AllOpenKotlinGradleSubplugin does not define or inherit an implementation of the resolved method abstract getNativeCompilerPluginArtifact()Lorg/jetbrains/kotlin/gradle/plugin/SubpluginArtifact; of interface org.jetbrains.kotlin.gradle.plugin.KotlinGradleSubplugin.
   > Receiver class org.jetbrains.kotlin.allopen.gradle.AllOpenKotlinGradleSubplugin does not define or inherit an implementation of the resolved method abstract getNativeCompilerPluginArtifact()Lorg/jetbrains/kotlin/gradle/plugin/SubpluginArtifact; of interface org.jetbrains.kotlin.gradle.plugin.KotlinGradleSubplugin.

### Environment:
- Java-jdk-11
- IntelliJ Community 2019.2.1
- Gradle v5.6
- Kotlin 1.2.71

**Comment by schalkms** [comment]
Did you add `jcenter()` do your build file?
Could you please try to use a newer Kotlin version? 1.2.71 is nearly 1 year old.

**Comment by schalkms** [comment]
Could you please try to use a newer Kotlin version? 1.2.71 is nearly 1 year old.

**Comment by jcpea** [comment]
Thanks for your reply! Yes, updating solved the problem

kotlin("jvm") version "1.3.50"
kotlin("plugin.spring") version "1.3.50"

I was doing a test with a generated project in start.spring.io and came with Kotlin 1.2.71 as default.
