### ISSUE TITLE
Prototype a WrapperRule which can execute similar rules at once

### ISSUE THREAD

**Issue by arturbosch** [arturbosch/detekt#188]
For example `TodoComment` and `MaxLineLength` do both the same, splitting the content of a kotlin file and operate on it. Combining them would speed up the performance.

**Comment by Mauin** [comment]
I can take a stab at this.

**Comment by arturbosch** [comment]
Cool, give it a try.

**Comment by vanniktech** [comment]
`NewlineAtEndOfFile` introduced in #190 could also benefit from this.

**Comment by arturbosch** [comment]
See MultiRule & SubRule implementation.
