### ISSUE TITLE
Updating from 1.0.0-RC9 to 1.0.1 triggers error

### ISSUE THREAD

**Issue by kikoso** [arturbosch/detekt#1882]
Updating a working installation from 1.0.0-RC9 to 1.0.0 triggers following error when synchronizing Gradle files.

> Failed to notify project evaluation listener.
   > Receiver class org.jetbrains.kotlin.allopen.gradle.AllOpenKotlinGradleSubplugin does not define or inherit an implementation of the resolved method abstract getPluginArtifact()Lorg/jetbrains/kotlin/gradle/plugin/SubpluginArtifact; of interface org.jetbrains.kotlin.gradle.plugin.KotlinGradleSubplugin.

## Expected Behavior
The application should keep working with the new version

## Steps to Reproduce
Update from 1.0.0-RC9 to 1.0.1

## Your Environment
* Version of detekt used: new one 1.0.1
* Version of Gradle used: 5.6
* Operating System and version: Macintosh 10.14.6

**Comment by 3flex** [comment]
Are there any clues as to what's failing in detekt? The error message only refers to Kotlin classes.

Possibly upgrading detekt is bringing in a newer version of Kotlin dependency than your project is compatible with?

**Comment by schalkms** [comment]
That's the same error as in #1878 (duplicate).
Please update to a newer Kotlin version.
Please also make sure that you use an up-to-date detekt yml config file.
