### ISSUE TITLE
Generate default-detekt-config.yml according to rules

### ISSUE THREAD

**Issue by vanniktech** [arturbosch/detekt#189]
It's quite tedious to go and change the `default-detekt-config.yml` every time a new rule / property is added. I think it'd be possible to generate it. The only problem that I'm seeing is maybe the fact that both are living in separate modules.

**Comment by arturbosch** [comment]
Hmm yeah you are right, we need to automate that. A script which loads all RuleSetProviders and queries the id, all declared fields or better all used config parameters should exists as a constant inside a companion object. We could use them for generation ^^

**Comment by arturbosch** [comment]
Basic idea would be to create a new module which contains a `FileProcessListener` to visit the `rules` module and obtaining the information by using a `DetektVisitor`. Extracting KDoc should be added later when the rules have documentation + examples.
