### ISSUE TITLE
How to not execute detekt task on check gradle's phase?

### ISSUE THREAD

**Issue by gregorius2514** [arturbosch/detekt#1894]
Hello,

my questions:
1. How to 'turn off' attaching detekt tasks to gradles 'check' task?
2. Where find contribution informations how to add new detekt properties (any the most important common problems with it)?

context:

I have problem when I'm building my project detekt is executed (on check phase) and build fails.
I would like to have more controll on detekt gradle's task so I looking to execute detek's task in CI in separate step.

I looked for any configure property but I did find any so I try to make changes in detekt's source code to make that configurable feature.

Right now I have problem when my properties injected from build.gradle file are not visible inside DetektExcension, DetektPlugin classes (default values from DetektExcension are always getting). Does any one have similar problem?

Best regards

**Comment by schalkms** [comment]
I'm afraid, I don't quite understand your problem description. Could you please explain that in more detail?

> How to 'turn off' attaching detekt tasks to gradles 'check' task?

Could you please post your of the Gradle build script that configures detekt?

> Where find contribution informations how to add new detekt properties (any the most important common problems with it)?

I'm also not sure what you mean.
The rules can be added in the `default-detekt-config.yml` file [Source](https://arturbosch.github.io/detekt/configurations.html).
All of detekt's parameters are listed [here](https://arturbosch.github.io/detekt/groovydsl.html) in the getting started guide.

> Right now I have problem when my properties injected from build.gradle file are not visible inside DetektExcension

What exactly are you trying to do? Could you also please post the relevant Gradle build script part here?

**Comment by schalkms** [comment]
I'm afraid, I don't quite understand your problem description. Could you please explain that in more detail?

> How to 'turn off' attaching detekt tasks to gradles 'check' task?

Could you please post the part of your Gradle build script that configures detekt?

> Where find contribution informations how to add new detekt properties (any the most important common problems with it)?

I'm also not sure what you mean.
The rules can be added in the `default-detekt-config.yml` file ([Source](https://arturbosch.github.io/detekt/configurations.html)).
All of detekt's parameters are listed [here](https://arturbosch.github.io/detekt/groovydsl.html) in the getting started guide.

> Right now I have problem when my properties injected from build.gradle file are not visible inside DetektExcension

What exactly are you trying to do? Could you also please post the relevant Gradle build script part here?

**Comment by marschwar** [comment]
> How to 'turn off' attaching detekt tasks to gradles 'check' task?

I don't really understand your use case either, but you could run `gradle check - x detekt` to exclude the detekt run I guess.

**Comment by gregorius2514** [comment]
Ok, I will try to explain in more technical way my case.

I see in git changes new feature when as below you can see detekt dependsOn CHEK_TASK_NAME.

Why is done i that way? After upgrade from version 1.0.0-RC8 to version 1.0.1 right now detekt will fail builds in any project that has some issues in code.

Can I revert `dependOn` via detekt configuration?
I'm looking for that feature but I cannot find one so I'm trying to do it by my one but maybe you know any solution to do it?

Right now I would like to make below code fragment to be turn on / off by some detekt's config property. It's good idea?

```class DetektPlugin : Plugin<Project> {

 private fun registerOldDetektTask(project: Project, extension: DetektExtension) {
    
    project.tasks.matching { it.name == LifecycleBasePlugin.CHECK_TASK_NAME }.configureEach {
------------------> here----->            it.dependsOn(detektTaskProvider)
        }
    }
```

**Comment by gregorius2514** [comment]
@marschwar Yes I can do that but when my project is build on gitlab for example by command 
`gradle build` detekt is executed as well after tests was executed I guess (detekt depends on `gradle check` task as I can see in code).

I would like to run `gradle build` without executing dektekt's tasks but when I want to I would like to run `gradle detekt` to check my code.

**Comment by gregorius2514** [comment]
Sorry, for so many comments but I would like to help to improve detekt plugin.
Right now I started from:
1. adding new property to DetektExcention: `notAttachDetektTaskToGradleCheckTask = false`
2. handle new property in DetektPlugin class
```class DetektPlugin : Plugin<Project> {

    override fun apply(project: Project) {
        project.pluginManager.apply(ReportingBasePlugin::class.java)
        val extension = project.extensions.create(DETEKT_TASK_NAME, DetektExtension::class.java, project)
            ...
    }

    private fun registerOldDetektTask(project: Project, extension: DetektExtension) {
...
// I wrapped code that is realated with my case and make him configurable
// The change can be writen more 'clean' but for now I want to show you my point of view how I could resolve this (my) problem

        if (!extension.notAttachDetektTaskToGradleCheckTask) {
            project.tasks.matching { it.name == LifecycleBasePlugin.CHECK_TASK_NAME }.configureEach {
                it.dependsOn(detektTaskProvider)
            }
        }
    }
```

3. When I load my custom version of detekt plugin and override default value from build.gradle file for added by myself property (`notAttachDetektTaskToGradleCheckTask`)
by adding to build.gradle file:

```
detekt.notAttachDetektTaskToGradleCheckTask = true

```
property is not overrided but always inside DetektPlugin class I see default value of the property that is `false`.

I make my own gradle plugin and there overriding of gradle's plugin extension properties works fine.
You have more knowledge about gradle and detekt so maybe could you help me by giving me some tip?

Thank you for previous commens as well.

**Comment by marschwar** [comment]
The current behavior is intended and inspired by plugins such as checkstyle and findbugs. The gradle documentation states:

> check
> Aggregate task that performs verification tasks, such as running the tests. Some plugins add their own verification tasks to check. 
> ...

I am opposed to making this behavior optional.

**Comment by schalkms** [comment]
@marschwar +1
I agree. We should not do this.
@gregorius2514 optionally, you could use the command line integration of detekt via script.

**Comment by gregorius2514** [comment]
@marschwar and @schalkms  Thank you for consultation. I think your point of view have more sens to me right now especially where it's gradle and other plugins standard.

Right now I find workaround to resolve my problem by disabling detekt's default configuration and register custom detekt's task and it works but I look on proposeb by you @schalkms idea.

Great, thanks and have a nice day :)

**Comment by schalkms** [comment]
We are glad that we could help. Thank you for the kind words!

**Comment by MiguelAraCo** [comment]
Coming late to the party but I needed to do this in a project since we started using detekt and we wanted to slowly tackle the warnings as part of different pull requests while keeping builds running.

To circumvent the problem, I added the following to Gradle's configuration:

```kotlin
tasks.getByName("check") {
    this.setDependsOn(this.dependsOn.filterNot {
        it is TaskProvider<*> && it.name == "detekt"
    })
}
```

Hope it helps someone who finds this issue in the future.

**Comment by arturbosch** [comment]
@MiguelAraCo thanks for the code, I wonder which page would be right to put this info on the website hm

**Comment by schalkms** [comment]
@arturbosch good idea
