### ISSUE TITLE
Prototype Kotlin DSL to configure detekt

### ISSUE THREAD

**Issue by arturbosch** [arturbosch/detekt#19]
Ideas:
- like the yaml configuration options but as a kotlin script
- allow to write output/console reports
- allow to define rules

**Comment by Mauin** [comment]
Can we give this Issue a better description of what this DSL should do and how it could look? Otherwise lets close this.

**Comment by arturbosch** [comment]
Basically I though about using a kotlin file to configure detekt as we are now doing with yaml. It would also be cool to use such a file to configure own output/console reports or even write own rules inside such files hmmm :D

**Comment by Mauin** [comment]
Is this still something we consider?

**Comment by arturbosch** [comment]
We can reopen it if ever considered :)
