### ISSUE TITLE
Baseline ignoring MaxLineLength: on 1.0.1

### ISSUE THREAD

**Issue by nicodn** [arturbosch/detekt#1906]
## Expected Behavior
I upgraded from `1.0.0-RC14` to `1.0.1` and my baseline file stopped working.

## Observed Behavior
I had a baseline file like so:
```
<?xml version="1.0" ?>
<SmellBaseline>
  <Whitelist>
    <ID>MaximumLineLength:</ID>
    <!-- other rules with specific signatures -->
  </Whitelist>
</SmellBaseline>
```

After upgrading I get over 200 issues failed with `MaxLineLength`. Even if I add `<ID>MaxLineLength:</ID>` to the baseline file it fails.

## Steps to Reproduce
Relevant build.gradle

```
plugins {
id "io.gitlab.arturbosch.detekt" version "1.0.1"
}

dependencies {
detektPlugins "io.gitlab.arturbosch.detekt:detekt-formatting:1.0.1"
}

detekt {
    toolVersion = "1.0.1"
    input = files("src/main/kotlin", "src/test/kotlin")
    filters = ".*/resources/.*,.*/build/.*"
    baseline = file(".config/detektBaseline.xml")
}
```

## Context

If I regenerate the baseline it adds each of the occurrences of `MaxLineLength` with it's own signature and at this point it works but the baseline file becomes unmaintainable.

## Your Environment

* Version of detekt used: `1.0.1`
* Version of Gradle used (if applicable): `5.2.1`
* Operating System and version: macOS 10.14.5
* Link to your project (if it's a public repository):

**Comment by 3flex** [comment]
If you want to ignore all instances of MaximumLineLength you could disable the rule in the YAML config file instead.

I don't know the history of baseline file support so I'm not sure whether adding items to the baseline like that was ever actually supported, but I might be wrong. The docs only describe adding the entire signature to the baseline.

**Comment by schalkms** [comment]
@nicodn Please be aware that there are two rules which basically do the same.
`MaxLineLength` is the detekt native rule. This one provides more configuration options.
`MaximumLineLength` is the wrapped ktlint rule.
So you need to choose between one of the two.

In your code only `MaximumLineLength` is included in your baseline file. `MaxLineLength` is missing.

HTH

**Comment by nicodn** [comment]
Hi @schalkms , thanks for your reply.

I tried adding <ID>MaxLineLength:</ID> to the whitelist in the baseline file but it still gives the 200+ errors.

It's strange because on `1.0.0-RC14` it never reported any issues with `MaxLineLength`.

**Comment by arturbosch** [comment]
Hi, the baseline does not support the formatting ruleset (yet).
Also an `ID` entry looks like this `NewLineAtEndOfFile:PluginVersion.kt$io.gitlab.arturbosch.detekt.PluginVersion.kt</ID>`.
It is not only the rule id but the signature of a code element. In this case it is the whole file itself.
Try running `detektBaseline` and see what happens.

Additionally we could indeed support suppressing formatting findings via baseline like:
`MaximumLineLengthPluginVersion.kt$io.gitlab.arturbosch.detekt.PluginVersion.kt#[line].[column]</ID>`.

**Comment by schalkms** [comment]
@arturbosch What do you mean by that?
Currently, the baseline feature doesn't support rules in the formatting rule set.
We would need to adapt detekt's codebase in order to support this feature.
Am I right?

**Comment by blazeroni** [comment]
@arturbosch Some additional info.  It looks like the formatting of the MaxLineLength rule changed for certain elements.  I recently upgraded to 1.0.1 from RC14 and saw a lot of errors that were already in the baseline.  I reran the baseline and saw that rules previously formatted like this:
```
<ID>MaxLineLength:FileName.kt$ClassName$private val fieldName = {code}</ID>
<ID>MaxLineLength:FileName.kt$ClassName$override fun method(...) {</ID>
```
became this after the baseline was regenerated:
```
<ID>MaxLineLength:FileName.kt$ClassName$private</ID>
<ID>MaxLineLength:FileName.kt$ClassName$override</ID>
```
They are no longer uniquely identified and apparently no longer match older baselines.

**Comment by arturbosch** [comment]
I could not reproduce this issue, my tested MaxLineLength findings have a correct signature.
Could you test it with 1.1.1 again?
I've implemented a way to suppress formatting issues in the link PR.

**Comment by arturbosch** [comment]
I could reproduce this on the sonar-kotlin repository.
The signature is right and contains the whole line but is not considered when filtering findings.

**Comment by schalkms** [comment]
@arturbosch Is this reproducible after 6b21237 in your scenario?

**Comment by arturbosch** [comment]
@schalkms baseline suppressing works as expected in current master ^^
