### ISSUE TITLE
Enable more rules by default

### ISSUE THREAD

**Issue by arturbosch** [arturbosch/detekt#1911]
## Expected Behavior
Many rules aged together with the detekt codebase and should be ready to be enabled by default. No "highly subjective" rules should be enabled though. 

## Current Behavior
Only a subset of detekt rules are enabled by default.

## Context
1.2.0 Release

Which are the rules you want to see enabled by default, lets list and discuss them.

**Comment by schalkms** [comment]
Good idea! 
We need to be careful regarding the rules that need type and symbol solving.
Furthermore, we should also move some rules into other rulesets. I highlighted them.
Here's my list:

`comments`:

- UndocumentedPublicClass
- UndocumentedPublicFunction

`complexity`:

- ComplexInterface
- MethodOverloading
- StringLiteralDuplication

all rules in the `exceptions` ruleset

`naming`:

- MemberNameEqualsClassName

`performance`:

- ArrayPrimitive

`potential-bugs`:

- EqualsAlwaysReturnsTrueOrFalse
- InvalidRange
- IteratorHasNextCallsNextMethod
- IteratorNotThrowingNoSuchElementException
- MissingWhenCase
- RedundantElseInWhen
- UnsafeCallOnNullableType
- UnsafeCast
- UselessPostfixExpression
- WrongEqualsTypeParameter

`style`:

- DataClassShouldBeImmutable
- EqualsNullCall
- ForbiddenComment
- FunctionOnlyReturningConstant
- LoopWithTooManyJumpStatements (**should be moved to the `complexity` ruleset!**)
- NestedClassesVisibility
- ProtectedMemberInFinalClass
- ReturnCount (**should be moved to the `complexity` ruleset!**)
- ThrowsCount (**should be moved to the `complexity` ruleset!**)
- UnnecessaryAbstractClass
- UnnecessaryInheritance
- UnusedImports
- UnusedPrivateClass
- UnusedPrivateMember
- UseDataClass
- UselessCallOnNotNull
- UtilityClassWithPublicConstructor

**Comment by 3flex** [comment]
Should #921 be rolled into this discussion?

**Comment by arturbosch** [comment]
Sounds good, so closing #921 you mean? This one is pinned :)

**Comment by schalkms** [comment]
Since the style package is getting bigger, I would split it up

- Design
- Readability

**Comment by schalkms** [comment]
I updated my initial post after implementing #1935.

**Comment by tasomaniac** [comment]
Android Lint has this property to enable all checks by default. It's a Gradle property in the extension called `enableAllWarnings`.

For projects that wants extensive analysis, this makes sense a lot. What you do is to enable everything and if a rule does not make sense for your project, disable that explicitly.

**Comment by arturbosch** [comment]
@tasomaniac Can you please elaborate on the difference between `enableAllWarnings` and our `failFast`. Unfortunately I don't get what you mean.
`enableAllWarnings` is a good replacement for our failFast name :).

**Comment by tasomaniac** [comment]
Hmm, I need to check what `failFast` does in detekt. Usually they would mean to run normally and abort with the first failure. I wouldn't expect that to enable everything. If that's the case already, I support renaming idea 😊

**Comment by tasomaniac** [comment]
Here is the failFast option definition in Gradle for reference
https://docs.gradle.org/4.6/release-notes.html#fail-fast-option-for-test-tasks

**Comment by afaucogney** [comment]
I agree with @tasomaniac. Running all rules should be a quick option. As a detekt user, this is hard to track new rules, so we expect to use every rules released by the detekt community and just disable the rules we cannot live with or out of context !

**Comment by arturbosch** [comment]
@schalkms @3flex I suggest enabling all rules activated in #1935 by default for 1.2.0.
We should wait for 2.0 to move rules to other rule sets as this will break config files and baselines.

**Comment by schalkms** [comment]
@arturbosch I agree.

**Comment by schalkms** [comment]
@arturbosch Isn't this done now?

**Comment by arturbosch** [comment]
> @arturbosch Isn't this done now?

Yes, the "move rules part" not but we will come up with a new issues when the time comes :).
