### ISSUE TITLE
Prototype wiki structure

### ISSUE THREAD

**Issue by arturbosch** [arturbosch/detekt#192]
Suggestions welcome

**Comment by Mauin** [comment]
Is this issue meant to collect feedback on the current baseline structure of the Wiki or to propose a structure for the Wiki? How can contributors best contribute to the documentation efforts we need for v1.0?

**Comment by arturbosch** [comment]
I plan to divide the readme into different sections and maybe add or rewrite stuff. If you have ideas on some extra topics, you can suggest new section. Also if there are unclear sections in the readme now, it would be cool to know that for the wiki ^^ If I find time tomorrow, I start to copy paste some text from the readme :D

**Comment by arturbosch** [comment]
I will close this as the website is (will be) the new wiki.
