### ISSUE TITLE
Calculate MCC (McCabe Complexity) accordingly

### ISSUE THREAD

**Issue by schalkms** [arturbosch/detekt#1921]
Your feature request may already be reported!
Please search in the [issues](https://github.com/arturbosch/detekt/issues) before creating a new one.

## Expected Behavior
The cyclomatic complexity should be calculated with reference to the control flow graph of the program.

## Current Behavior
Some statements that introduce are new path are still not counted.

## Context

- [ ] Refactor `cases/ComplexClass.kt`!!
- [x] elvis operator `?:`
- [x] `&&` and `||` not only in if statements but rather in every binary-expression
- [x] jumps (`break` / `continue`)
- [x] `throw`
- [x] ~~safe call operator `?.` (can only be accurately calculated using Java byte code)~~

reference #1793

**Comment by arturbosch** [comment]
Thanks for tackling this. I suggest to get all points implemented before shipping this if you are okay with it.

**Comment by schalkms** [comment]
The refactoring of `ComplexClass.kt` can be done in a single PR.
The rest is mostly testing effort.

**Comment by arturbosch** [comment]
I mean this rule is a breaking change/bug fix/improvement and we should ship it in a new minor version when all 6 bullet points are ready.
