### ISSUE TITLE
InstanceOfCheckForException should be ignored for catch blocks that is more than an if expression

### ISSUE THREAD

**Issue by Mygod** [arturbosch/detekt#1927]
## Expected Behavior of the rule

For this line: https://github.com/shadowsocks/shadowsocks-android/blob/41730631bb386c8c61c2790821db0560b52ceae1/core/src/main/java/com/github/shadowsocks/bg/BaseService.kt#L365

## Context

Since after `if` there is some additional work done, it might be acceptable to ignore cases like this.

detekt 1.0.1

**Comment by arturbosch** [comment]
For me this would be a classical "suppress because I know what I'm doing" case.

**Comment by Mygod** [comment]
Yes but suppressing all warnings like this is kind of tedious. Is there any case like this that should still raise a warning?

**Comment by schalkms** [comment]
Why do you not want to have a separate `catch` for the `ExpectedException`?

**Comment by Mygod** [comment]
Because there are some common code to share between two blocks.

Why do I want to use two catches? Is it for performance reasons?

**Comment by schalkms** [comment]
What you do in your referenced code is essentially a code smell.
I'll cite the [Carnegie Mellon University](https://wiki.sei.cmu.edu/confluence/display/java/ERR51-J.+Prefer+user-defined+exceptions+over+more+general+exception+types) that explains why this is bad practice.

> Because an exception is caught by its type, it is better to define exceptions for specific purposes than to use the general exception types for multiple purposes. Throwing general exception types makes code hard to understand and maintain and defeats much of the advantage of the Java exception-handling mechanism.

Furthermore, there's a Sonar(Java) [rule](https://rules.sonarsource.com/java/RSPEC-1193) that works the same way as detekt's `InstanceOfCheckForException` rule.

> Because there are some common code to share between two blocks.

You can still do that with the help of a function, which contains the common behavior.

I don't see any reason to change the behavior of this rule based on this code sample.

**Comment by Mygod** [comment]
Well actually [`ExpectedException` here is an interface](https://github.com/shadowsocks/shadowsocks-android/blob/41730631bb386c8c61c2790821db0560b52ceae1/core/src/main/java/com/github/shadowsocks/bg/BaseService.kt#L67) and because it is not a `Throwable`.

**Comment by schalkms** [comment]
That's hard to tell for the code analyzer without type and symbol solving.
The rule can only go up the inheritance tree and check if the type in the `is` expression derives from `Exception`, but that's really an edge case here.
How does it sound to you?

**Comment by schalkms** [comment]
I see.
That's hard to tell for the code analyzer without type and symbol solving.
The rule can only go up the inheritance tree and check if the type in the `is` expression derives from `Exception`, but that's really an edge case here.
How does it sound to you?

**Comment by Mygod** [comment]
Well since you can only ever throw throwables I think checking for an interface should be fine.

Putting that aside, I still think this rule is too strict. Say I want to report errors only if it is unexpected, otherwise suppress it, I can write something like this: https://github.com/Mygod/VPNHotspot/blob/5e2aeef1d200297496cf09541cfa36324eb4703d/mobile/src/main/java/be/mygod/vpnhotspot/net/IpNeighbour.kt#L100

**Comment by Mygod** [comment]
So I guess this is a won't fix then.

**Comment by schalkms** [comment]
This rule needs type and symbol solving for this to work.
This will be fixed. However, it doesn’t have such a high priority for now. 
This might be a good first issue, if anyone wants to work on this and help out.

**Comment by Mygod** [comment]
It seems like 1.3.1 fixed this.
