### ISSUE TITLE
ReturnFromFinally should ignore return@ expressions when appropriate

### ISSUE THREAD

**Issue by Mygod** [arturbosch/detekt#1928]
## Expected Behavior of the rule

https://github.com/shadowsocks/shadowsocks-android/blob/41730631bb386c8c61c2790821db0560b52ceae1/core/src/main/java/com/github/shadowsocks/bg/GuardedProcessPool.kt#L99

## Context

Here `return@withContext` is fine because it does not escape the finally block.

detekt 1.0.1

**Comment by 3flex** [comment]
Duplicate of #1467?

**Comment by Mygod** [comment]
lmfao
