### ISSUE TITLE
Gradle task doesn't work

### ISSUE THREAD

**Issue by xgouchet** [arturbosch/detekt#195]
I'm trying to add Detekt on my project, using gradle. I get the following error whenever I want to run a detekt* task : 

> Cannot resolve external dependency io.gitlab.arturbosch.detekt:detekt-cli:1.0.0.M13 because no repositories are defined.

Here's my project's `build.gradle`

```
buildscript {

    ext {
        kotlin_version = '1.1.3'
        detekt_version = '1.0.0.M13'
    }

    repositories {
        jcenter()
        maven { url "https://jitpack.io" }
        maven { url "https://plugins.gradle.org/m2/" }
        maven { url "http://dl.bintray.com/arturbosch/code-analysis" }
    }
    dependencies {
        classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:$kotlin_version"
        classpath "gradle.plugin.io.gitlab.arturbosch.detekt:detekt-gradle-plugin:$detekt_version"
    }
}

allprojects {
    repositories {
        jcenter()
        mavenCentral()
        maven { url "https://jitpack.io" }
        maven { url "https://plugins.gradle.org/m2/" }
        maven { url "http://dl.bintray.com/arturbosch/code-analysis" }
    }
}
```

And here's my module's `build.gradle`

```
apply plugin: 'java'
apply plugin: 'kotlin'
apply plugin: "io.gitlab.arturbosch.detekt"

dependencies {
    compile "org.jetbrains.kotlin:kotlin-stdlib:$kotlin_version"
}


detekt {
    version = "$detekt_version"

    profile("main") {
        input = "$projectDir/src/main/kotlin" // Which part of your project should be analyzed?
        config = "$projectDir/detekt.yml" // Use $project.projectDir or to navigate inside your project
        output = "$project.rootDir/reports/detekt.xml" // If present, prints all findings into that file.
        outputFormat = "plain" // Can be either 'xml' or 'plain', default is 'xml'
    }

}

sourceCompatibility = "1.7"
targetCompatibility = "1.7"
```

**Comment by arturbosch** [comment]
Is your project Android? You have two build.gradle files ^^

Delete everything detekt related in your buildscript-closure and just add 

```
plugins {
    id "io.gitlab.arturbosch.detekt" version "1.0.0.M13"
}
```

to your module, where also your code is. Hope that helps

**Comment by xgouchet** [comment]
Thanks for youhelp. 
Using that syntax does work, but I had to upgrade my gradle to be able to use it. 
Shouldn't the plugin work with the earlier gradle syntax ?

**Comment by arturbosch** [comment]
The old syntax does also work, maybe not on Android when the config is separated in two build.gradle files. I'm no Android guy and haven't spend time on investigate that, sorry. You should definitely update to Gradle 4.0 just for the performance ;)

**Comment by vanniktech** [comment]
You need to move the `classpath "gradle.plugin.io.gitlab.arturbosch.detekt:detekt-gradle-plugin:$detekt_version"` into the `app/build.gradle` file.

**Comment by arturbosch** [comment]
I will close this one now. If you have more questions just ask :)
