### ISSUE TITLE
Is there a way to make console output less verbose?

### ISSUE THREAD

**Issue by AOrobator** [arturbosch/detekt#1955]
I remember seeing an older issue closed about making Detekt only show style issues, not a whole code report, but I don't see anything in the docs. How do I get Detekt to only output style issues?

**Comment by schalkms** [comment]
I guess you don't want to activate just rules in the `style` ruleset. You could take the different output formats that detekt provides and manipulate them as you like.

https://github.com/arturbosch/detekt/blob/89e7fd841d82b93bd72d4dc861177c249a1ddf28/detekt-cli/src/main/resources/default-detekt-config.yml#L19-L27

The other an option, which is preferable in your case, is to implement a custom processor for your use case as seen [here](https://arturbosch.github.io/detekt/extensions.html#custom-reports).

**Comment by AOrobator** [comment]
Awesome, just what I needed. Thanks!
