### ISSUE TITLE
ComplexMethod FP on Ternary Operator

### ISSUE THREAD

**Issue by wenhuanli** [arturbosch/detekt#1965]
ComplexMethod reports complex method for real simple methods that needs several if..else.. as ternary operator equivalent for parameter passing for other methods invocation.

## Expected Behavior
Write a method with one level when with several cases. Inside each case just call another method. For some parameters a ternary operator if..else.. is needed for parameter passing. Since the method is short it is really easy to understand even without referencing other methods. ComplexMethod rule should not complain.

## Observed Behavior
As Kotlin removed ternary operator and let you just use if..else.., ComplexMethod rule cannot tell the difference between real block control and simple `var=if (flag) a else b`.

**Comment by schalkms** [comment]
We use [McCabe's Cyclomatic Complexity](https://en.wikipedia.org/wiki/Cyclomatic_complexity) to measure the complexity of a method.
This metric is standard in that regard.
Of course it has some weaknesses.
In your case I recommend using the `@Ignore` annotation or refactoring the method to use a simple when entry and setting the `ignoreSimpleWhenEntries` config option to `true`.
