### ISSUE TITLE
UndocumentedPublicClass new property alsoSearchInNested

### ISSUE THREAD

**Issue by vanniktech** [arturbosch/detekt#198]
I'd propose a new property in the `UndocumentedPublicClass`. Something along the lines of `alsoSearchInNested`. 

The following code:

```kotlin
/**
 * @author niklasbaudy / vanniktech
 * @since 12.05.17
 */
interface ApiInterface {
  enum class FooBar {
    FOO,
    BAR
  }
}
```

gets flagged by the rule since there's no Java doc above `FooBar`. One way to fix it is to change the file to:

```kotlin
/**
 * @author niklasbaudy / vanniktech
 * @since 12.05.17
 */
interface ApiInterface {
  /**
   * @author niklasbaudy / vanniktech
   * @since 12.05.17
   */
  enum class FooBar {
    FOO,
    BAR
  }
}
```

With the new property `alsoSearchInNested` set to false it would not flag the first case.

What do you think?

**Comment by arturbosch** [comment]
I like the idea. More configuration possibilities for the user :)

**Comment by arturbosch** [comment]
The idea for this would be not to call `super.visitClass` etc.
