### ISSUE TITLE
Could not fetch model of type 'KotlinBuildScriptModel' using Gradle

### ISSUE THREAD

**Issue by rafalschmidt97** [arturbosch/detekt#1983]
## Observed Behavior

After adding to gradle:

```
repositories {
  ......
  jcenter()
}

plugins {
    .....
    id("io.gitlab.arturbosch.detekt") version "1.0.1"
}
```

I'm getting error with gradle. My project is Spring Boot with gradle.

```
Failed to notify project evaluation listener.
   > java.lang.AbstractMethodError (no error message)
   > java.lang.AbstractMethodError (no error message)
```

or

```
Could not fetch model of type 'KotlinBuildScriptModel' using Gradle...
```

More info: [resolver-2019-10-05-15-43-10-706.log](https://github.com/arturbosch/detekt/files/3693234/resolver-2019-10-05-15-43-10-706.log)

## Steps to Reproduce

1. Download clear spring boot [here - kotlin, gradle, 2.1.9](https://start.spring.io/#!type=gradle-project&language=kotlin&platformVersion=2.1.9.RELEASE&packaging=jar&jvmVersion=1.8&groupId=com.example&artifactId=demo&name=demo&description=Demo%20project%20for%20Spring%20Boot&packageName=com.example.demo)
2. Add plugin

## Your Environment

* Version of detekt used: 1.0.1
* Version of Gradle used (if applicable): 5.6.2
* Operating System and version: macOS mojave

Maybe I don't get something. Detekt works with RC6 version.

**Comment by schalkms** [comment]
RC6 is nearly 2 years old. We don't support this old release candidate version anymore.
A lot has changed since then. There were also some breaking changes regarding the Gradle support in detekt since then.
Could you please try to start from scratch with your Gradle and detekt config and give us feedback about this issue?

**Comment by rafalschmidt97** [comment]
> RC6 is nearly 2 years old. We don't support this old release candidate version anymore.
> A lot has changed since then. There were also some breaking changes regarding the Gradle support in detekt since then.
> Could you please try to start from scratch with your Gradle and detekt config considering [this guide](https://arturbosch.github.io/detekt/kotlindsl.html) and give us feedback about this issue?

Hi,
Of course RC6 is old and I'm not even asking for help with this. version. I said that only as a hint for a further thinking. Detekt doesn't work for me with newest 1.0.1 as I described in this issue. I think they are more people who generate project with Spring Boot initialiser and they would love to use detekt. I'm not a specialist of gradle so it's really hard for me to tell what happened. It's super simple to recreate that just download generated Kotlin project and add this as I described above.

**Comment by schalkms** [comment]
Which Kotlin version are you using? Could you please try it with a newer one?

```Kotlin
kotlin("jvm") version "1.3.50"
```

**Comment by schalkms** [comment]
Could you please show the complete build script in order to make it easier to investigate the problem?

**Comment by rafalschmidt97** [comment]
> Which Kotlin version are you using? Could you please try it with a newer one?
> 
> ```kotlin
> kotlin("jvm") version "1.3.50"
> ```

Perfect! Solved. Thanks.

**Comment by schalkms** [comment]
I’m glad that I could help.
