### ISSUE TITLE
Exclusions for ThrowsCount

### ISSUE THREAD

**Issue by madhead** [arturbosch/detekt#2006]
## Expected Behavior of the rule
`ThrowsCount` should be more intelligent and allow intellectual exclusions (e.g. by thrown exception class).

## Context
Too many exit points like returns or throws is indeed code smell, but there are exceptions. Currently, `ThrowsCount` is pretty dumb. It only counts throws expressions without any context. One example is "guarding" throws used to fail fast the program.

Imagine I have a class `Effect`:

```kotlin
data class Effect(
    val id: String,
    val name: String,
    val size: Long
)
```

I store it in the NoSQL key-value storage like DynamoDB. I wrote a function to convert DynamoDB's object into Effect:

```kotlin
fun Map<String, AttributeValue>.toEffect(): Effect = Effect(
    id = this["id"]?.s() ?: throw MissingPropertyException("id"),
    name = this["name"]?.s() ?: throw MissingPropertyException("name"),
    size = this["size"]?.n()?.toLong() ?: throw MissingPropertyException("size")
)
```

Currently detekt reports an issue here (default number of throws is 2). I should either increase the default, or use `@Supress`. But both solution are not perfect: increasing the limit will skip the warnings for really complex codes and `@Supress` feels like I am cheating to make detekt happy.

Ideally, there should be a list of exclusions for `ThrowsCount`, so some exceptions used across the code base to guard and fail fast are not counted.

**Comment by madhead** [comment]
Probably all the `throw`s and `return`s in a syntax like `?: throw` / `?: return` could be configured to be excluded, as it is a pretty common pattern of defensive programming style.

**Comment by madhead** [comment]
I found `excludeGuardClauses` in returns rule, it is a perfect solution. Need something for throws.

**Comment by BraisGabin** [comment]
Can we close this issue? The PR is merged.

**Comment by madhead** [comment]
Oh, sure. I thought, it would be closed automatically…
