### ISSUE TITLE
Lack of JAR file of v1.1.0

### ISSUE THREAD

**Issue by dive5617** [arturbosch/detekt#2010]
There isn't the corresponding JAR file of detekt v1.1.0.

**Comment by jamiehunt** [comment]
I'm assuming this is why nothing has been pushed to the Maven repos?

https://mvnrepository.com/artifact/io.gitlab.arturbosch.detekt/detekt-core

**Comment by arturbosch** [comment]
I think you meant 1.1.1. Yep, the sync from JCenter to MavenCentral failed due to timeout.
I triggered a resyn. I should be up today. Thanks!
