### ISSUE TITLE
Cleaning Entity

### ISSUE THREAD

**Issue by BraisGabin** [arturbosch/detekt#2014]
The class `Entity` has two unused properties: `name` and `className`. The first one can be private (we need it for `compat()`) but the second one can be removed completely.

With this we cane remove `HasEntity.name` and `HasEntity.inClass` too.

I supose that this is part of the public API. So probably for now we could add a `@Deprecation`.

**Comment by arturbosch** [comment]
These properties can be used to post-process Findings or write custom reports.
I would't make `name` private.
We could remove the className or make it a function which will `searchClass` on demand to safe some cpu cycles though.

**Comment by BraisGabin** [comment]
The problem of making it a function (or just a property with `get()`) is that, some times, we are losing the `PsiElement` (because it's not a `KtElement`) so we can't compute the `className` later. I would vote to remove.
