### ISSUE TITLE
Travis osx fails a lot

### ISSUE THREAD

**Issue by BraisGabin** [arturbosch/detekt#2015]
I'm getting a lot of false negatives in my PRs. This false negatives are always related with the osx workers. The log is like this:

>adding /Users/travis/.gradle/caches to cache
>creating directory /Users/travis/.gradle/caches
>adding /Users/travis/.gradle/wrapper to cache
>creating directory /Users/travis/.gradle/wrapper
>
>No output has been received in the last 10m0s, this potentially indicates a stalled build or something wrong with the build itself.
>Check the details on how to adjust your build configuration on: https://docs.travis-ci.com/user/common-build-problems/#Build-times-out-because-no-output-was-received
>
>The build has been terminated

This is kind of a pain for not maintainers because we can't rerun them. Any idea about how can we fix this?

**Comment by 3flex** [comment]
Unfortunately CI is sometimes flakey. Some issues are easier than others to fix (or we need to wait on Travis/AppVeyor to correct a problem in their environment). Hopefully this will be addressed soon.

Though you may not be able to restart builds or jobs, it helps if you're able to point out in a comment if you suspect a build failed because of something unrelated to the PR.

**Comment by BraisGabin** [comment]
> Though you may not be able to restart builds or jobs, it helps if you're able to point out in a comment if you suspect a build failed because of something unrelated to the PR.

Good to know, I will

Yeah, this seems a problem in travis more than in detekt. I was just wondering if we could do something to reduce/workaround them. Or if someone has a link to the issue in travis so we know the insides and we can find that workaround (I did a quick research in Google and couldn't find it).

**Comment by arturbosch** [comment]
@3flex it feels a bit overkill to have also 3 builds for osx. There should't be too many differences in the jdks of Linux and OSX. Maybe lets just test the recent Java version on osx (12 for now untill Gradle supports 13)?

**Comment by schalkms** [comment]
I'd test version 8 and 12 for now.
