### ISSUE TITLE
Navigating to imported class.

### ISSUE THREAD

**Issue by tevjef** [arturbosch/detekt#2018]
```kotlin
// A.kt
class A {
   val data: String = "data"
}

// B.kt
class B {
  val a: A = A()
}
```

Is it possible to navigate to class A's `PsiFile` from B?

**Comment by 3flex** [comment]
What are you trying to do? Not sure what you mean by "navigate" but there's a way to resolve the reference to `A()` from `B.kt`. There's no documentation on how to do this but if you search for string "BindingContext" in `detekt-rules` module you'll find some rules that use this technique which may help.

**Comment by tevjef** [comment]
I essentially want to lint file `A` even though I'm currently visiting `B`.

**Comment by schalkms** [comment]
The `BindingContext` does the trick here. Please take a look at the existing rules in this codebase that use the `BindingContext`.
