### ISSUE TITLE
Hi, which api can I use to see the method's name with package in function  

### ISSUE THREAD

**Issue by CuiLam** [arturbosch/detekt#2020]
hi, I want to find the method's full name in function.

**Comment by CuiLam** [comment]
so, whice api can I use, plase

**Comment by arturbosch** [comment]
I guess you are in the context of writing a custom rule and want to resolve a call inside a function to the declaration.

I would start with something like this:
```
override fun visitCallExpression(expression: KtCallExpression) {
        println(expression.getResolvedCall(bindingContext)?.resultingDescriptor)
}
```

See a rule like this for example: https://github.com/arturbosch/detekt/blob/f80fe60383c78bed811cdad1fd54402e21b58a11/detekt-rules/src/main/kotlin/io/gitlab/arturbosch/detekt/rules/bugs/UnsafeCallOnNullableType.kt

Also take a look at a tutorial for the PSI the kotlin compiler uses: https://www.jetbrains.org/intellij/sdk/docs/basics/architectural_overview/psi.html
