### ISSUE TITLE
Add complexity report to HTML output

### ISSUE THREAD

**Issue by kumarpratyush** [arturbosch/detekt#2046]
## Expected Behavior
The **complexity report** is only printed in console output. To get a count of code smells and McCabe Complexity in order to keep a tab on them, we have to push the console output to a file and parse that. This would break if the format of console reporter changes. 

## Current Behavior
Currently, the HTML output gives a summary of project metrics, but not the complexity report. It would be good to have the complexity report as well as part of some reporter.

## Context
We are trying to get more metrics out of detekt in one place. This could enable people to get these values and represent them graphically over time to keep a tab on the code quality of their project. 

**P.S. -** I have gone through the code and it is a small change. If you think this feature request is good to have, I can raise a PR for the same. Please let me know.

**Comment by schalkms** [comment]
We would very much appreciate this. Please go ahead and submit a PR. Thanks for your time and contribution. If you have any questions please fell free to ask.

**Comment by kumarpratyush** [comment]
Thank you for the response. I will raise the PR in some time.

**Comment by schalkms** [comment]
Closed by 85c93ea
