### ISSUE TITLE
Defining Custom detekt task

### ISSUE THREAD

**Issue by pawanchauhan043** [arturbosch/detekt#2047]
I am trying to implement 'detekt' for code checks in kotlin in my android project.
I have made a custom task exactly the way mentioned on the github page as follows :

```groovy
task detekt(type: io.gitlab.arturbosch.detekt.Detekt) {
    description = "Runs a failfast detekt build."
    group = "code quality"

    input = files("$projectDir/src/main/")
    config = files("${project.rootDir}/config/quality/detekt/default-detekt-config.yml")
    baseline = file("${project.rootDir}/config/quality/detekt/baseline.xml")
    debug = true
    reports {
        xml {
            destination = file("build/reports/failfast.xml")
        }
        html.destination = file("build/reports/failfast.html")
    }
    include '**/*.kt'
    include '**/*.kts'
    exclude 'resources/'
    exclude 'build/'
}
```

The issue is , it gives an error on line 1 , i.e , the type of task . 
I get the following error 
`Could not get unknown property 'io' for project`

I have added the dependencies and repository in the build.gradle file at the root level , still I am facing this issue . What might be the reason ?

Thanks in advance.

**Comment by cortinico** [comment]
> What might be the reason ?

Do you happen to have the following code placed in a separated Gradle file?
I faced the same issue and the problem was that I created the custom task in a `detekt.gradle` external file.

**Comment by pawanchauhan043** [comment]
> > What might be the reason ?
> 
> Do you happen to have the following code placed in a separated Gradle file?
> I faced the same issue and the problem was that I created the custom task in a `detekt.gradle` external file.

Yes , it is exactly like you have said . How did you resolve it . A separate detekt.gradle file looks more nice to me though.

**Comment by cortinico** [comment]
If you wish to use a separate file, the cleanest approach is probably to use the `detekt {}` block to configure it (as described here https://arturbosch.github.io/detekt/groovydsl.html)

If you really need to define a new task, you would need to provide a `buildscript` block in order to provide a `classpath` dependency:

```groovy
buildscript {
    repositories {
        gradlePluginPortal()
    }
    dependencies {
        classpath "io.gitlab.arturbosch.detekt:detekt-gradle-plugin:1.1.0"
    }
}

apply plugin: 'io.gitlab.arturbosch.detekt'

task myCustomTask(type: io.gitlab.arturbosch.detekt.Detekt) { ...
```

**Comment by 3flex** [comment]
@pawanchauhan043 did the suggestion above suit your use case? If so please consider closing the issue. Thanks!

**Comment by danikula** [comment]
@cortinico I've tried to add `buildscript` section, but executing custom tasks fails with message:
`Error: Could not find or load main class io.gitlab.arturbosch.detekt.cli.Main`
Everything works when I define custom task in `app/build.gradle`

**Comment by cortinico** [comment]
@danikula 
Can you please post the content of your secondary gradle file?
Have you tried using the `detekt {}` block instead?

**Comment by danikula** [comment]
I've published simple [demo project](https://github.com/danikula/DetektDemo) to show my issue. I [created](https://github.com/danikula/DetektDemo/commit/158a51a5909e83e362f2e546cf09c12c4101f67e) gradle task `detektFix` with enabled `autoCorrect` property.  So I can run `gradle detekt` to detekt problems and `gradle detektFix` to fixing issues. Everything is ok until I try to extract detekt related stuff to separate gradle script.  I've made it in [extract](https://github.com/danikula/DetektDemo/commits/extract) branch. In this branch executing `gradle detektFix` fails with message `Error: Could not find or load main class io.gitlab.arturbosch.detekt.cli.Main`

**Comment by cortinico** [comment]
Hi @danikula 
Looks like you're not applying the plugin in your `detekt.gradle` file:

https://github.com/danikula/DetektDemo/blob/845cab9852f9a02fe784fef026a57e889e8a7f08/app/detekt.gradle#L9

Can you please add `apply plugin: 'io.gitlab.arturbosch.detekt'` just after the `buildscript {}` block? This should solve your problem.

**Comment by danikula** [comment]
Unfortunately adding `apply plugin: 'io.gitlab.arturbosch.detekt'` to `detekt.gradle:9` doesn't help. Same problem `Error: Could not find or load main class io.gitlab.arturbosch.detekt.cli.Main`

**Comment by jenda** [comment]
Same exact issue here (separate gradle file -> trying to create a gradle task)

**Comment by danikula** [comment]
I fixed my issue by applying plugin in separate gradle script
```
apply plugin: io.gitlab.arturbosch.detekt.DetektPlugin
```
See my fix [here](https://github.com/danikula/DetektDemo/commit/07d38d9aed8b421ebb9d601763499a0353ff8bab)

**Comment by cortinico** [comment]
Glad to hear you solved :)

@arturbosch I guess you can close this issue

**Comment by GurpreetSK95** [comment]
I'm facing the same issue, and the custom task is running but not analysing anything. Attaching the external task alongwith:
```
buildscript {
    repositories {
        gradlePluginPortal()
    }
    dependencies {
        classpath "io.gitlab.arturbosch.detekt:detekt-gradle-plugin:1.7.4"
    }
}

apply plugin: "io.gitlab.arturbosch.detekt"

task detektCi(type: io.gitlab.arturbosch.detekt.Detekt) {
    description = "Runs detekt build without failing on CI."

    failFast = false
    buildUponDefaultConfig = false
    ignoreFailures = true
    parallel = true
    config.from(files("$rootDir/quality/detekt/detekt-config.yaml"))
    baseline = file("$rootDir/quality/detekt/detekt-baseline.xml")

    reports {
        html.enabled = true
        xml.enabled = true
        txt.enabled = true
    }
}
```

**Comment by GurpreetSK95** [comment]
Thanks for the reply. I tried adding the property and the sources are now being found.
However, now I'm facing the same issue as [2564](https://github.com/arturbosch/detekt/issues/2564): `java.lang.ClassNotFoundException: io.gitlab.arturbosch.detekt.cli.Main`. My project doesn't have `detekt-cli` dependency added, however it doesn't seem to work even on adding it.

P.S. I previously tried with `input` as mentioned in the config file but that didn't work, I think `source` should be mentioned there too.

**Comment by arturbosch** [comment]
Mh, Just an idea. You are registering the task eagerly instead of lazily.
Maybe the plug-in somehow is not initialized fully.

Please try `tasks.register(...)`

**Comment by GurpreetSK95** [comment]
Sure, let me try that.
A quick update: if I move the task to parent build.gradle file, it works fine. The issue seems to be when it is placed in a external file.

**Comment by GurpreetSK95** [comment]
Hey, registering the task didn't work.

**Comment by arturbosch** [comment]
I could not get it to run in an external build file too.
Some resolution problems.
What I figured out is that the preferred way to modularize kotlin-dsl scripts is to use a `buildSrc` and the `kotlin-dsl` plugin.
This worked for me: https://github.com/arturbosch/detekt/pull/2621
