### ISSUE TITLE
Meaning of Dept

### ISSUE THREAD

**Issue by Mauin** [arturbosch/detekt#205]
Is it meant to give an indication of how much debt has accumulated in the codebase and the amount of time it might take to fix all of the issues we have found?

I always wondered if it is supposed to be called `Debt` and was just a typo or if it carries a meaning that is not obvious to me.

**Comment by vanniktech** [comment]
Thank you for asking this. I'm also puzzled by this class.

**Comment by arturbosch** [comment]
:D yes it is a typo! A debt value was needed for sonar so I introduced one for detekt too, maybe for the complexity report later when there are hotspot reports (packages/files with the most smells -> developers can better estimate new features when they know which code part is hard to change) and other metrics ^^

PS: this one is embarrassing, like the poll pool thing :D
