### ISSUE TITLE
Run detekt with an Exception

### ISSUE THREAD

**Issue by CuiLam** [arturbosch/detekt#2053]
Run EqualsAlwaysReturnsTrueOrFalse will report an exception.
The bug is in function isSingleReturnWithBooleanConstant(), it can use `firstOrNull` instead of `first` in ` val lastValidReturnExpression = returnExpressionsInBlock.first().returnedExpression`

**Comment by 3flex** [comment]
Same as #2021?

**Comment by CuiLam** [comment]
yes

**Comment by 3flex** [comment]
Closing as duplicate. Thanks for reporting!
