### ISSUE TITLE
LateInitUsage: Ignore this rule in tests

### ISSUE THREAD

**Issue by vanniktech** [arturbosch/detekt#207]
I'd like a way to let this rule be inactive when having test code since all of the times I end up initializing those properties in the `setUp()` method of JUnit4.

Feedback is welcome.

**Comment by arturbosch** [comment]
Use a second `profile` in your gradle config.

```gradle
detekt {
  ...
  profile("main") {
    ....
  }
  profile("test") {
    config = "override LateInitUsage in second config"
  }
}
```

**Comment by arturbosch** [comment]
Hmm, extending the gradle-plugin to always run all profiles could be an idea for later ...

**Comment by vanniktech** [comment]
Hmm I don't like the idea that much of having multiple configurations, that way I end up using more and more configurations file. Would it be possible to have an extra property in the `LateInitUsage` like `ignoreOnClasses` that gets a regex and does not run on certain files. I'd then set it to `[\w]+Test`

**Comment by arturbosch** [comment]
Sorry for forgetting to answer on this. Maybe we should add a property on top level of the configuration which just handles test classes. Like the class pattern you implemented for LateinitUsage, we could do the check when running a rule ?

I think tests are so common that it makes sense to integrate the 'knownledge of tests' into detekt? @vanniktech , @Mauin

**Comment by vanniktech** [comment]
So there's `active` and `activeInTests`? That would apply to every rule?

**Comment by Mauin** [comment]
I see the general point. But how many rules would we actually want to turn off/modify in test source sets?

**Comment by vanniktech** [comment]
LateInit for sure and maybe the SpreadOperator.

**Comment by arturbosch** [comment]
Hmm yeah maybe not that many rules. Better to start small just in this rule and maybe later adopt for more ^^

NamingConventionsViolation comes into my mind that some ppl wanted to turn it off in test cases

`deactivateInTestsWithpattern=*Test` sounds strange and yes could be used in BaseRule when the isActive check is done (we already have the ktFile and can easily check the name)

**Comment by arturbosch** [comment]
Well, I think using the profiles is a much better way to override certain properties in the config instead of inventing new properties for each rule which is considered subjective.

**Comment by Mauin** [comment]
I agree that the LateinitUsage rule (and probably also others) will be annoying/unnecessary in tests. 
Do Checkstyle/PMD/whatever have some "Tests" mode that alter the behavior of rules?

**Comment by arturbosch** [comment]
For LateinitUsage I think it is ok to have this class pattern, we can make an exception as `lateinit` is common in Android

**Comment by vanniktech** [comment]
Checkstyle suppressions work like this:

```
<?xml version="1.0"?>
<!DOCTYPE suppressions PUBLIC
  "-//Puppy Crawl//DTD Suppressions 1.1//EN"
  "http://www.puppycrawl.com/dtds/suppressions_1_1.dtd">
<suppressions>
  <suppress files="[\w]*Test.java" checks="MagicNumberCheck"/>
  <suppress files="[\w]*Test.java" checks="MultipleStringLiterals"/>
</suppressions>
```

With PMD you'd use `// NOPMD` or `@SuppressWarning("PMD.Name")`.

**Comment by arturbosch** [comment]
Just to be sure:

 I did not mean to introduce a second property for each rule! Just one 'excludedRulesForTests=LateinitUsage` on config top level

**Comment by Mauin** [comment]
Sounds good to me. Should it then be one property to define a regex for test classnames and a second property to suppress certain rules for those files?

**Comment by vanniktech** [comment]
I did it a bit differently in #226 I've basically got a regex.

**Comment by arturbosch** [comment]
Yes a test classnames regex like in #226 + a comma separated list of rules (yaml supports lists oO)
