### ISSUE TITLE
Improve how to test the textLocation

### ISSUE THREAD

**Issue by BraisGabin** [arturbosch/detekt#2089]
Right now to test `TextLocation` is a pain. And it's even worst to mantain those tests. @schalkms said that to me multiple times and I agree with him. I had an idea to fix this:

Right now we are doing things like this:

```kotlin
val findings = subject.compileAndLint("object SomeObject {}")
assertThat(findings).hasTextLocations(18 to 20)
```

But we could change to something like this:

```kotlin
val findings = subject.compileAndLint("object SomeObject {}")
assertThat(findings).hasTextLocations("{}")
```

We can overload the `hasTextLocations` to accept a `vararg` of `String`s. It will find that text in the code, take the char position and then call to the other `hasTextLocations`.

I implemented it and you can check the code in this diff: https://github.com/arturbosch/detekt/compare/master...BraisGabin:textLocations

What do you think? If you like the idea but not some of the implementation details I can create a PR to make it easier to provide feedback.

Maybe this code will help with #2087

**Comment by schalkms** [comment]
Thanks! That's actually a very nice idea.
Please go ahead and create a PR. I'd like to immediately merge this.

**Comment by arturbosch** [comment]
Maybe we need both variants. If the findings is attached to the whole KtFile/KtNamedFunction we do not want to duplicate the entire code or am I missing something?

**Comment by schalkms** [comment]
@arturbosch I’m not sure what you mean. Can you please elaborate?
In my opinion this check covers the text location functionality.
I think the codebase needs a refactoring towards the new API introduced in the referenced PR.

**Comment by BraisGabin** [comment]
I didn't remove the other method. I just overload the current one so we can use both depending which one works better for the current situation.
