### ISSUE TITLE
Deprecate ignoreOverriddenFunction(s) in favor fo ignoreOverridden

### ISSUE THREAD

**Issue by BraisGabin** [arturbosch/detekt#2096]
`EmptyFunctionBlock`, `FunctionParameterNaming` and `MemberNameEqualsClassName` uses the configuration flag `ignoreOverriddenFunction(s)` but the rest of rules uses the generic `ignoreOverridden`.

I cheked the uses and I think that its safe to rename those three to `ignoreOverridden` too. I think that this change will make the API a bit more consistent.

This is clearly a breaking change but we can deprecate `ignoreOverriddenFunction` but honor it. We can show a warning too if someone uses it. And we can remove it later.

What do you think?

**Comment by schalkms** [comment]
I appreciate consistency across our rules configuration.
However, in this case it doesn't bring that much to the table.
`MemberNameEqualsClassName:ignoreOverriddenFunction` should stay, since it isn't clear from the rule name what should be ignored.
If @arturbosch agrees, I think we can integrate this change, but not before v1.3.

**Comment by BraisGabin** [comment]
I understand your point but... Why do we allow overriden functions and don't allow overriden properties too? Probably we should change a bit what `MemberNameEqualsClassName:ignoreOverriddenFunction` does to add the properties and then rename it to `ignoreOverridden` as the other ones.

**Comment by schalkms** [comment]
> Why do we allow overriden functions and don't allow overriden properties too? Probably we should change a bit what MemberNameEqualsClassName:ignoreOverriddenFunction does to add the properties and then rename it to ignoreOverridden as the other ones.

Yeah, thanks for your input. You are completely right. This rule should also ignore overridden properties.
