### ISSUE TITLE
UnusedImports: False positive if referenced only in @throws/@exception clause

### ISSUE THREAD

**Issue by eekboom** [arturbosch/detekt#2098]
The bug you're experiencing might have already be reported!
Please search in the [issues](https://github.com/arturbosch/detekt/issues) before creating one.

## Expected Behavior
The UnusedImports rule should not warn if an imported class is only referencedf in a @throws or @exception clause in KDoc.

## Observed Behavior
False positive

From looking at the source code: The rule only checks for @see and for inline references.

## Your Environment

* Version of detekt used: 1.1.1
* Version of Gradle used (if applicable): 5.6.4
* Operating System and version: Windows 10

**Comment by schalkms** [comment]
Thank you for reporting this problem!
Since you already looked into the problematic code area, may I ask you to submit a PR that fixes the regex? We would really appreciate that.
