### ISSUE TITLE
Idea: detekt-sonarqube-plugin

### ISSUE THREAD

**Issue by McPringle** [arturbosch/detekt#21]
I use [SonarQube](https://sonarqube.com) for all of my projects (it is a free service for open source projects). It would be great to have a plugin, which can be used to show the results of a static code analysis of Kotlin code done by detekt in SonarQube (I use the [sonarqube-gradle-plugin](https://plugins.gradle.org/plugin/org.sonarqube)).

**Comment by arturbosch** [comment]
Yes that would be a good step to make detekt more popular, thx for the suggestion! But I do not know when I will have time to work myself into sonar -> masterthesis.

**Comment by McPringle** [comment]
Thank you very much for your reply. Unfortunately I don't have any experience with writing sonar plugins. This month we have a few Hackergarten events here (Bern, Basel, Lucerne) where I suggest this topic – maybe there is someone who can help.

**Comment by arturbosch** [comment]
Some useful links:
https://deors.wordpress.com/2014/03/20/sonarqube-plugins-1/  
https://www.beyondjava.net/blog/write-sonarqube-plug-in/  
http://ashismo.github.io/java-code%20quality%20analyzer/2016/06/09/Custom-Java-Plugin-For-SONAR  
https://github.com/SonarSource/sonar-custom-plugin-example  

I will take a look at these ^^

**Comment by sliskiCode** [comment]
How is it going with this?

**Comment by arturbosch** [comment]
It's delayed after 1.0 release without the milestone number :). Take a look at the `ROADMAP.md` file.

**Comment by arturbosch** [comment]
Well, worked started for this. Prototype works and is in a PR, just need to figure out why sonar-runner does not sent the issues to the server :O

**Comment by arturbosch** [comment]
`detekt-sonar-kotlin`-plugin in early access version 0.1.0 can be build from master and used in sonar 5.6 or 6.4 :)

![sonar-descriptions](https://user-images.githubusercontent.com/20924106/27639651-1d819d30-5c17-11e7-92ce-9dd2b40a35fd.png)

Syntax-Highlighting, more descriptions etc will follow!

**Comment by arturbosch** [comment]
As [sonar-kotlin](https://github.com/arturbosch/sonar-kotlin) now has it's own repository, I will close this one.

**Comment by McPringle** [comment]
Thank you very much for your work! I hope to have some time soon to try it out.
