### ISSUE TITLE
DetektAll with baseline fails with error

### ISSUE THREAD

**Issue by adrianczuczka** [arturbosch/detekt#2100]
I have a multi-module project and I want to create one baseline file for the entire project instead of one per module, so I'm trying to replicate the detektAll task that is created in this project's build.gradle.kts file. However, I have had to translate this task into Groovy, and it looks like this:
```
task detektAll(type: io.gitlab.arturbosch.detekt.Detekt) {
    description = 'Runs over whole code base without the starting overhead for each module.'
    config = files("$rootDir/detekt-config.yml")
    parallel = true
    input = files(projectDir)
    include '**/*.kt'
    include '**/*.kts'
    exclude '**/resources/**'
    exclude '**/build/**'
    baseline = file("$rootDir/config/detekt/baseline.xml")
    reports {
        xml {
            enabled = true
        }
        html {
            enabled = true
        }
        txt {
            enabled = true
        }
    }
}
```
However, running this fails with the error  
```
A problem was found with the configuration of task ':detektAll'.
File (my root directory)/config/detekt/baseline.xml does not exist.
```
Is there a fix for this?

**Comment by schalkms** [comment]
Did you execute the `detektBaseline` task before, which generates the `baseline.xml` file?
./gradlew detektBaseline

**Comment by adrianczuczka** [comment]
When I run `detektBaseline`, it generates a baseline file for every module, which is what I want to avoid

**Comment by adrianczuczka** [comment]
I have run `detektBaseline` again but this time I set my baseline in the detekt block to the same file:
```
detekt {
    config = files("$rootDir/detekt-config.yml")
    filters = ".*build.*,.*/resources/.*,.*/tmp/.*"
    //Optional baseline, uncomment & run gradle command detektBaseline to exclude existing issues
    baseline = file("$rootDir/baseline.xml")
}
```
This does generate only one baseline, but the file itself is basically empty even after the task has finished:
```
<?xml version="1.0" ?>
<SmellBaseline>
  <Blacklist></Blacklist>
  <Whitelist>
    <ID>ParameterListWrapping:</ID>
  </Whitelist>
</SmellBaseline>
```
That's the entire file. Additionally, running the `detektAll` task does not update this baseline at all.

**Comment by adrianczuczka** [comment]
It might be that if the baseline is the same the whole time, it gets overwritten every time a new module is scanned?

**Comment by schalkms** [comment]
I also suspect that.
@arturbosch can you confirm that?

**Comment by arturbosch** [comment]
Sorry for the late response @adrianczuczka , you can create a custome baseline task which generates it for the whole project as well:
```groovy
task baseline(type: io.gitlab.arturbosch.detekt.DetektCreateBaselineTask) {
    description = "Overrides current baseline."

    input = files(rootProject.projectDir)
    config = files("$rootDir/detekt/config.yml")
    baseline = file(new File(rootProject.projectDir, "/detekt/baseline.xml"))
    failFast = true
    parallel = true
    include '**/*.kt'
    include '**/*.kts'
    exclude '**/test/resources/**'
    exclude '**/afk-*/build/**'
}
```

**Comment by schalkms** [comment]
That's cool!
We might want to add this to the documentation as well.

**Comment by adrianczuczka** [comment]
Thank you so much for the Gradle task! I had to change a few things to make it work:
`baseline = file(new File(rootProject.projectDir, "/detekt/baseline.xml"))`
gave me an error saying `cannot resolve symbol File` and had to be changed to 
`baseline = file(rootProject.projectDir, "/detekt/baseline.xml")`.

Also, `failFast = true` causes the task to fail, and it seems like any `DetektCreateBaselineTask` does not correctly handle failures. I had to comment out the `maxIssues` property in my config file, but I think adding `ignoreFailures = true` instead works as well.

Otherwise, seems like it works! Thanks!

**Comment by adrianczuczka** [comment]
Just checked again and it seems the error in `baseline = file(new File(rootProject.projectDir, "/detekt/baseline.xml"))` is reported by the IDE but does **not** actually cause a build error, which is weird.

**Comment by adrianczuczka** [comment]
My final Gradle task that I used to generate a baseline (file names and paths are changed):
```
task baseline(type: io.gitlab.arturbosch.detekt.DetektCreateBaselineTask) {
    description = "Overrides current baseline."

    input = files(rootProject.projectDir)
    config = files("$rootDir/detekt-config.yml")
    baseline = file("${rootProject.projectDir}/detekt-baseline.xml")
    ignoreFailures = true
    parallel = true
    include '**/*.kt'
    include '**/*.kts'
    exclude '**/test/resources/**'
    exclude '**/afk-*/build/**'
}
```

**Comment by adrianczuczka** [comment]
I __think__ it works now, and what I had to do is move the task into a `subprojects` block.
