### ISSUE TITLE
Run Detekt on Detekt

### ISSUE THREAD

**Issue by vanniktech** [arturbosch/detekt#212]
So also the Detekt Code gets checked by Detekt.

**Comment by arturbosch** [comment]
What do you mean? detekt has the detekt gradle plugin imorted and `detektCheck` is run in CI ...

**Comment by vanniktech** [comment]
Then how come the MaxLine rule doesn't complain on my previous PR?

**Comment by arturbosch** [comment]
Because of this line `usedDetektGradlePlugin=1.0.0.M12.1` :D, need upgrade to M13 ^^

**Comment by arturbosch** [comment]
Also I think with the baseline we should have 0 code smells. Lets turn the threshold to 1 then ^^

**Comment by vanniktech** [comment]
Also might be an option to use the `failFast` flag.

**Comment by arturbosch** [comment]
Will try it out!
