### ISSUE TITLE
Wrong configuration parameter in README.md

### ISSUE THREAD

**Issue by samarjan92** [arturbosch/detekt#215]
'rulesets' writes instead 'ruleSets' in section [Options for detekt configuration closure](https://github.com/arturbosch/detekt#options-for-detekt-configuration-closure)

**Comment by arturbosch** [comment]
Hey, it is the perfect way for you to contribute, wanna try :) ?

**Comment by samarjan92** [comment]
Ok, thnks!) I'll try.
