### ISSUE TITLE
Include changelog in Github release page

### ISSUE THREAD

**Issue by lwasyl** [arturbosch/detekt#2150]
With Github's `watch releases` option I get updates about new release on my email. However when I want to see what changed in a new Detekt release, right now I need to:
 - navigate to the release from the email,
 - no changes information there, so I navigate to the main page (readme)
 - still nothing, not even a changelog.md file, so I open 'project website'
 - no changelog right away, I need to click releases link
 - I can see changelog

For comparison, with RxJava releases I see what changed right there in the email:

![image](https://user-images.githubusercontent.com/3951580/69904326-b37bfb80-13a5-11ea-9c9d-743c88376bf3.png)

I'd be great if Detekt also included changelog in the Github's release page

**Comment by arturbosch** [comment]
Good idea, please see if the 1.2.2 release has the changelog attached to the release email :)

**Comment by lwasyl** [comment]
Seems to works perfect :) Thank you!

![image](https://user-images.githubusercontent.com/3951580/70225365-2fcc6100-174f-11ea-8e35-8642d9c448d1.png)
