### ISSUE TITLE
Support total Complexity Report

### ISSUE THREAD

**Issue by imanushin** [arturbosch/detekt#2162]
## Expected Behavior
Detekt generates single report for all projects (for multi-module setup) by aggregation granular reports

## Current Behavior
Detekt generates only report per single project, which prevents total solution analysis

## Context
We have medium-sized Kotlin solution with ~30 subprojects. All of them are inside gradle project, all of them are built at one time (and dependency versions are synchronized, JVM language is Kotlin only, etc.). Detekt generates useful project complexity statistic, however it couldn't be used for global analysis. For example, when I move code from subproject A to subproject B, I expect to see the same number of global complexity.

To support this configurations, I'd like to see:
* Separate task for "detekt global reporting". Reportes can be the same. And result can include granula reports from subproject and aggregated report (which can be used for complex project analysis)
* By using this values we can also show comparison numbers with existing projects on Github. For example, "81 McCabe complexity, which is 69% worse than ktor.io on link xxx". This can help numbers understanding.
* Probably (not related for target issue, however): we can introduce additional checks on global level. For example: if class/method is ```public``` AND it is not used outside the subproject then it is better to mark it is ```internal```.

**Comment by schalkms** [comment]
This issue has already been discussed quite intensively in #1295.
I think you should subscribe to #1295.
