### ISSUE TITLE
Do you have any example project that use Detekt?

### ISSUE THREAD

**Issue by theerasan** [arturbosch/detekt#217]
For now, I'm kinda confused how to setup detekt, and honestly, I can't even if I go thru the step or comment. I think It's nice to have example project to follow

Thanks

**Comment by samarjan92** [comment]
You could see my android sample project in that [repo](https://github.com/samarjan92/kotlindetect)

**Comment by arturbosch** [comment]
You can also just look at the detekt [build.gradle](build.gradle) file. Also some of my other projects use detekt [here](https://github.com/arturbosch/quide) and [here](https://github.com/arturbosch/sonar-kotlin/blob/master/build.gradle)

**Comment by theerasan** [comment]
Thanks, Guys it does work.  Seem like I have to update Gradle version also Android Studio Version to be able to process your code. Thanks

**Comment by arturbosch** [comment]
Glad that it worked for you, feedback is always welcome :)
