### ISSUE TITLE
How to limit scope for Detekt?

### ISSUE THREAD

**Issue by SerG3z** [arturbosch/detekt#2175]
Now Detekt analyzing all the code in my project, but I want to parse only the files in which the changes occurred.
The problem is that I write custom rules and so many classes will not correspond to them, so as not to rewrite the entire project at once, you need to apply these rules only to files that are currently modified, you can recognize them through git. 

Perhaps someone knows how to solve this problem?

**Comment by schalkms** [comment]
This has been covered in #1792 and #1057. The referenced YouTube video shows exactly how to write a Git commit hook for detekt.

Please note that we don't recommend this. You cannot use rules that need type and symbol solving to work.
I'll probably add this to the documentation on detekt's homepage as well if I have time.
