### ISSUE TITLE
MaximumLineLength is ignored at function or line level

### ISSUE THREAD

**Issue by dafi** [arturbosch/detekt#2179]
## Expected Behavior

Declaring `@Suppress("MaximumLineLength", "MaxLineLength")` at function definition level should apply to the function/single line of code

## Observed Behavior

The `@Suppress` is simply ignored but if declared at file level `@file:Suppress("MaximumLineLength", "MaxLineLength")` then the rules are applied

## Steps to Reproduce
The example [here](https://gist.github.com/dafi/da14013fb2769698b962508f64a14713) reproduces the bug

## Your Environment
* Version of detekt used: 1.2.2

**Comment by arturbosch** [comment]
Sorry, unfortunately we can't support suppression on expression or statement level for rules not actually operating on the AST. This applies to rules from `detekt-formatting` and rules like MaximumLineLength.
I've added an extra sentence for the rule set documentation page for this.
