### ISSUE TITLE
Jenkins Plugin

### ISSUE THREAD

**Issue by vanniktech** [arturbosch/detekt#219]
It'd be super cool if there would be a Jenkins Plugin for detekt. I also believe that the core functionality already exists since Checkstyle, PMD & Findbugs Plugin all show the errors the same way with the same information.

Maybe it's as simple as parsing the report and transforming it to the Jenkins structure.

**Comment by arturbosch** [comment]
Do you have an example of an output which is shown in jenkins or something?

**Comment by vanniktech** [comment]
I'll post screenshots and more information tomorrow.

**Comment by vanniktech** [comment]
It can be configured like this:

![screen shot 2017-07-18 at 17 03 14](https://user-images.githubusercontent.com/5759366/28324148-094de89a-6bdb-11e7-9a8c-3342a6393329.png)

and all of them have the same advanced options:

![screen shot 2017-07-18 at 17 03 58](https://user-images.githubusercontent.com/5759366/28324239-1bc610c4-6bdb-11e7-9d63-dcd4f7950a65.png)

---

[Link to Jenkins Checkstyle Plugin](https://wiki.jenkins.io/display/JENKINS/Checkstyle+Plugin) - [Source Code](https://github.com/jenkinsci/checkstyle-plugin)

Also note that there's this on the page:

> This plug-in requires the utility plug-in "analysis-core" (called "Static Analysis Utilities" in the update manager). Please ensure that the latest version of this plug-in is also installed.

Which I'd assume is the common functionality that all of the plugins can use and share.

Same for PMD + Findbugs.

[Link to Jenkins PMD Plugin](https://wiki.jenkins.io/display/JENKINS/PMD+Plugin) - [Source Code](https://github.com/jenkinsci/pmd-plugin)

[Link to Jenkins Findbugs Plugin](https://wiki.jenkins.io/display/JENKINS/FindBugs+Plugin) - [Source Code](https://github.com/jenkinsci/findbugs-plugin)

I also think that given all of the plugins are open source and share the same underlying structure this should be pretty straight forward to implement. (Haven't looked at the source code though)

**Comment by arturbosch** [comment]
That somehow reminds me of sonar if you can see the code smells with syntax highlighting of the code :D

**Comment by vanniktech** [comment]
Yes, somewhat, I assume.

**Comment by alapshin** [comment]
I created feature request for Jenkins plugin to add support for detekt https://issues.jenkins-ci.org/browse/JENKINS-46158

As a temporary workaround you could use existing Jenkins Checkstyle plugin since detekt generates report in checkstyle format by default.

Something like
```
checkstyle canRunOnFailed: true, pattern: "$BUILD_DIR/reports/checkstyle/checkstyle.xml, $BUILD_DIR/reports/detekt/detekt.xml"
```

While this is not ideal since it mixes checkstyle and detekt warnings in the same view it works for simple cases when you want to see detekt output on Jenkins page.

**Comment by vanniktech** [comment]
ktlint also generates checkstyle like xml reports that can be used although I also very much prefer having separate plugin / views.

**Comment by psukys** [comment]
There's as well [Violation Comments to GitHub Lib](https://github.com/tomasbjerre/violation-comments-to-github-lib) which in essence have [pretty trivial parsers](https://github.com/tomasbjerre/violations-lib/tree/master/src/main/java/se/bjurr/violations/lib/parsers).

**Comment by uhafner** [comment]
For the [next major release|https://github.com/jenkinsci/warnings-plugin/tree/3.0/src/main/java/io/jenkins/plugins/analysis/warnings] of Jenkins' warnings plugin you can provide a small wrapper class that will provide a better user experience if you are interested. There is no need to write a new file format, checkstyle compatibility is sufficient. You could even integrate the rule descriptions in the UI.

**Comment by vanniktech** [comment]
I think we need to write that class ourself.

**Comment by uhafner** [comment]
Yes, that would be the simplest thing for me if you would provide a simple class that basically defines the labels and icons in the UI. The parser is already there.  

In a second step you can also integrate the rule descriptions into the UI. I can give you the pointers if you are interested.

**Comment by 3flex** [comment]
Jenkins warnings plugin now [claims support for detekt](https://github.com/jenkinsci/warnings-plugin/blob/master/SUPPORTED-FORMATS.md), and [JENKINS-46158](https://issues.jenkins-ci.org/browse/JENKINS-46158) is closed as `RESOLVED`... so assuming those work as advertised, can this issue be closed?
