### ISSUE TITLE
Naming Convetion Violation ignoring patterns

### ISSUE THREAD

**Issue by xMickeymikex** [arturbosch/detekt#22]
Hey, 

I have encountered this problem and cannot find a way to fix it. 
style:
  active: true
  WildcardImport:
    active: true
  NamingConventionViolation:
    active: true
    variablePattern: '^(_)?[a-z$][a-zA-Z$0-9]*$'
    constantPattern: '^([A-Z0-9_]*|serialVersionUID)$'
    methodPattern: '^[a-z$][a-zA-Z$0-9]*$'
    classPattern: '[A-Z$][a-zA-Z0-9$]*'

Even if i delete all the patterns, i get the NamingConventionViolation in my report, when i try to modify these patterns, no changes are detected in process. The only thing that works for me is activate or deactivate.

**Comment by MyDogTom** [comment]
@xMickeymikex This is because support for custom `NamingConventionViolation` is added recently in [this commit](https://github.com/arturbosch/detekt/commit/ee3ec5509b55c832d6db3da0c015067aae2b5d2f) and not yet released. Once it's released, it should work perfectly.

**Comment by arturbosch** [comment]
Hey as your the second to ask for this, I just released 1.0.0.M8.1 with this feature + one bug fix from a contributor (thx @olivierlemasle)

If the new release works for you, please close the ticket, thx.
