### ISSUE TITLE
Should an invalid config fail the build?

### ISSUE THREAD

**Issue by allenhumphreys** [arturbosch/detekt#2213]
After upgrading detect, I started seeing warnings about unknown/misspelled configurations, but the gradle build passed. It seems when the configuration is invalid, detekt does not actually run the valid rules AND it doesn't fail the build. As a result, our project had detekt effectively disabled for several weeks.

I'm wondering if an invalid configuration should result in a failed build?

**Comment by cortinico** [comment]
Thanks for reporting @allenhumphreys 
Looks like a duplicate of #2168 ?

**Comment by schalkms** [comment]
Which version of detekt are you currently using?

**Comment by allenhumphreys** [comment]
I was using 1.2.2 but have updated to 1.3.1 while fixing my configurations. This does look like a duplicate! Sorry I didn’t find it!
