### ISSUE TITLE
Exclude class/file/property from certain rules

### ISSUE THREAD

**Issue by Nevvea7** [arturbosch/detekt#222]
It would be nice to be able to do something like
```kotlin
@DetektIgnore(rule = "TooManyFunctions")
class A() 
```
because I think `filter` would exclude a file from all rules, and setting TooManyFunctions' `active` to `false` in `detekt.yml` would turn it off for all files, right? Thoughts?

**Comment by arturbosch** [comment]
You can use the Java's `@SuppressWarnings` or Kotlin's `@Suppress` annotations for this.

**Comment by Nevvea7** [comment]
It does! Sorry I didn't know it would work for detekt rules as well :P

**Comment by Nevvea7** [comment]
Hi @arturbosch, I wrote a [medium post](https://medium.com/@annayan/writing-custom-lint-rules-for-your-kotlin-project-with-detekt-653e4dbbe8b9) about how to make and use custom rules with detekt. It's probably very trivial stuff for you but for people that aren't so familiar with ASTs, gradle and jars (like me) it might take them some time to figure out how it works, where to find the jars, which jar to use etc. Would love to get your feedback before I publish!

**Comment by arturbosch** [comment]
Hey @Nevvea7 thank you more the awesome post! I updated the sample test case to meet the new prefered style using the `detekt-test` module. I also included a test class + test using normal JUnit. Would be awesome if you mention it in your post :). I will tweet about it :+1:

**Comment by Nevvea7** [comment]
@arturbosch just to make sure I understand the new style, are you moving away from Spek? It looks like the new test that extends from `RuleTest` is sufficient?

**Comment by arturbosch** [comment]
No I do not. When Spek was very unstable I started to write in Junit5 too. Now only in Spek. Just that the readers know that they do not need to use Spek if they are not familiar with it. The interesting part is `rule/subject.lint(code)` - shortcut :) (also `rule.format(code)`)

**Comment by Nevvea7** [comment]
i see. i updated the testing part. please take another look!

**Comment by arturbosch** [comment]
Looks good!
