### ISSUE TITLE
How to run debug detekt?

### ISSUE THREAD

**Issue by tuyennc** [arturbosch/detekt#2222]
There is only code for unit test in test/ source folder.
How can I run detekt in main(args: String[]) function like cli does?
Sorry I didn't go through code too munch to know the answer so I asked for quick help.

**Comment by schalkms** [comment]
In the package
`io.gitlab.arturbosch.detekt.cli`
run the `main()` function in the `Main.kt` file.

The command line parameters shown in the doc can be configured in IntelliJ's run configuration (Run>Edit configuration).
doc: https://arturbosch.github.io/detekt/cli.html
