### ISSUE TITLE
Detekt not running on test folder

### ISSUE THREAD

**Issue by gismoranas** [arturbosch/detekt#2223]
The bug you're experiencing might have already be reported!
Please search in the [issues](https://github.com/arturbosch/detekt/issues) before creating one.

## Expected Behavior
I should get some report logs after running ./gradlew detekt
I also expect to receive an error of type TooGenericExceptionCaught.
I am using the default configuration from this repo and removed the "excludes" line from TooGenericExceptionCaught:

```
  TooGenericExceptionCaught:
    active: true
    exceptionNames:
      - ArrayIndexOutOfBoundsException
      - Error
      - Exception
      - IllegalMonitorStateException
      - NullPointerException
      - IndexOutOfBoundsException
      - RuntimeException
      - Throwable
    allowedExceptionNameRegex: "^(_|(ignore|expected).*)"

```

I have this code in a file named src/test/kotlin/.../FeatureSwitchUtils.kt

```
        try {
            // do something
        } catch (e: Exception) {
            false
        }

```

## Observed Behavior
I don't get any output and the command runs without errors. 

## Your Environment

* Version of detekt used: 1.3.1

**Comment by schalkms** [comment]
Does any other rule report smells for code in your test package?

**Comment by schalkms** [comment]
Couldn't reproduce this problem. The [exclude filters](https://arturbosch.github.io/detekt/configurations.html#path-filters--excludes--includes) shouldn't mention **test**.
