### ISSUE TITLE
Exclude newInstance functions from LongParameterList rule

### ISSUE THREAD

**Issue by adrianczuczka** [arturbosch/detekt#2224]
Hi!
The `LongParameterList` rule makes sense for normal functions, however for Fragments, the common pattern to construct one is by using `newInstance`. This `newInstance` is more like a constructor than a function, and I think there are cases where it is acceptable to pass many parameters to it. However, I would not like to use `@Suppress` for this, so is there or can there be a way where we exclude any function with the signature `newInstance`, for example?

**Comment by BraisGabin** [comment]
I'm not a huge fan of this rule (I usually disable it). But, if you agree with it I think that this rule should be keeped for those cases too. You should create a dto object to pass all those parameters.

Side note: You can even add `@Parcelize` to it and pass that object as the fragment argument.

I repeat, I'm not a huge fan of this rule, but I don't think that newInstance is an exception to it.

**Comment by 3flex** [comment]
I also vote against adding the ability to have specific function names that are whitelisted - in most cases suppressing the rule for that particular function is the best way to deal with it, or if it's a major issue, disable the rule and try and catch it in code review instead.

I'll leave this open to collect other feedback though.

**Comment by schalkms** [comment]
I agree with @3flex in that regard.

**Comment by arturbosch** [comment]
I am also against adding such an option but see here another opportunity to support post-processing of detekt findings via an unified api interface.

**Comment by schalkms** [comment]
Since the maintainers are on the same page regarding this topic, I'll close this issue.

@adrianczuczka you could either use the `Suppress` annotation or copy this rule into a [custom detekt rule](https://arturbosch.github.io/detekt/extensions.html#custom-rulesets) and customize it by ignoring the mentioned function.
