### ISSUE TITLE
Wrapping kotlin inspections

### ISSUE THREAD

**Issue by BraisGabin** [arturbosch/detekt#2245]
## Expected Behavior
If we see an inspection inside kotlin that we think that could be worth it in detekt we should have an easy way to integrate it.

## Current Behavior
Right now I see that a lot of our rules are ports from the original code.

## Context
These has some downsides:

- Add a new rule is slow. And we can't imporve other things where we could give more value.
- We don't get the fixes from jetbrains.
- If we find an issue in the rule we fix it in our code, but we don't even report it as a bug to kotlin because we don't know if they have that problem too.

I did nearly 0 research but it would be great to develop a wrapping code to execute the kotlin's inspection code and adapt it to a detekt's rule. Something similar that what we have with ktlint.

What do you think? Is it possible? Did you try it before?

And then we have android lint that has a lot of not android specific kotlin rules too.

**Comment by schalkms** [comment]
Do you have a wrapper in mind similar to the ktlint one?
There seems to be a library that provides a Gradle plugin to launch IDEA inspections.
https://github.com/JetBrains/inspection-plugin

**Comment by BraisGabin** [comment]
I did 0 research on this but it could have sense, right? Maybe as a third/first party plugin or even as core part of the project. For example instead of porting #1501 we could use directly that inspection. 

Maybe add all the inspections in core has not sense. Or maybe we prefer to port some of them to get more flexibility. But in general I think that it could be good. What do you think?

**Comment by 3flex** [comment]
This depends on the original rule. Those that are easy to port are pretty self-contained, and a wrapper might be possible if the original rule doesn't use anything in `org.jetbrains.kotlin.idea.*`.

Most (all?) seem to use `org.jetbrains.kotlin.idea.caches.resolve.analyze` though, so a wrapper would need to factor that in at a minimum.

Would be a huge win if possible. https://github.com/JetBrains/inspection-plugin has its place but it's a pretty heavy solution I think.

**Comment by schalkms** [comment]
I think should consider this case by case then.
If there are new ideas for rule, we will come back to this awesome idea.
For now, I'll close this and potentially have it reopened when this questions pops up again.
