### ISSUE TITLE
Indentation should support useTabs property

### ISSUE THREAD

**Issue by radimvaculik** [arturbosch/detekt#229]
Should be awesome to have ability format the code, which is indented by tabs.

**Comment by arturbosch** [comment]
Have you tried formatting with a local intellij? See the detekt build.gradle or readme for more info + configuration. I think in the long term, we will wrap ktlint for formatting and concentrate more on the core rules and features. The `detektIdeaFormat` is a good option to use the same formatting as you are using in Intellij itself (same code-style.xml).

**Comment by radimvaculik** [comment]
We'd like to use it on CI to check, if the code is properly indented with tabs. Currently, we are not able to do it.

**Comment by radimvaculik** [comment]
@arturbosch any ETA on this issue?

**Comment by arturbosch** [comment]
Sorry forgot about this. No plan for this yet, to be true, it has low priority. As mentioned above, the ideaFormat is the preferred way, which can also work on CI if you download an idea on your CI system.
Maybe in far future I will consider this as I also prefer tabs. For now the community can pick this up.
