### ISSUE TITLE
Sample extension rule with autocorrect?

### ISSUE THREAD

**Issue by ahampe** [arturbosch/detekt#2314]
The sample rules don't override `withAutoCorrect` and I can't tell from the documentation how it's intended to be used. I don't know what the `block` parameter is, whether or not I'm supposed to explicitly call `withAutoCorrect` when visiting a node, or what I'm capable of doing within this method. A simple example would help, or some further explanation in the docs.

**Comment by cortinico** [comment]
I'm afraid `withAutoCorrect` should probably be deprecated or removed from the public API. Is actually never called in the codebase.

@arturbosch has way more context on this. So far `autoCorrect` in Detekt is used only for the `formatting` rules that are actually KtLint wrappers.

**Comment by ahampe** [comment]
Okay, I see now. I was able to write a custom auto-correcting rule without ever needing `withAutoCorrect`, instead I just checked for the config's `autoCorrect` after reporting in the `visit` call. I still think it would be nice to see a sample that utilizes auto-correct, though, unless the whole feature is going to be deprecated?

**Comment by schalkms** [comment]
`autoCorrect` is intended for ktlint's rules, which detekt wraps. Detekt's native rules don't support this feature.
Now, I'm curios. How do you `autoCorrect` with the Psi? Do you replace user code? @ahampe

**Comment by ahampe** [comment]
There is this "hack" that you'll find in many ktlint rules if you look at the source:
```
if (autoCorrect) {
    (node as LeafPsiElement).rawReplaceWithText("...")
}
```
It works just as well from a detekt rule.

**Comment by schalkms** [comment]
> But I guess now that I know that it's intended only for ktlint rules, it would be kind of odd to provide an example of autoCorrect, wouldn't it?

Yes, your are right. That's why we don't include it for now. I'm sorry for the confusion.

However, nothing prevents you from writing `autoCorrect` rules with detekt. At some time in the past, there was a decision that detekt rules don't mess with user code.

**Comment by ln-12** [comment]
Hey @ahampe, did you find a solution how to do this in detekt? I don't see how I can cast for example a `KtNamedFunction` or the `bodyExpression` to a `LeafPsiElement` as the cast will always fail.
