### ISSUE TITLE
Allow Detekt CLI to take an args file.

### ISSUE THREAD

**Issue by tyvsmith** [arturbosch/detekt#2318]
When using Detekt in the Uber monorepo, we've run into issues with extremely long argument lists that result in "Argument list too long" exceptions in the build, for things like Classpath or source lists. We've worked around it for now by trimming down our use of absolute paths in a custom Buck genrule.

Detekt CLI should have the ability to take an args file containing this information to work with larger argument lists that exceed the shell limits.

**Comment by arturbosch** [comment]
We have just figured out that detekt supports them out of the box! Please see the PR for examples :).

**Comment by tyvsmith** [comment]
Oh, cool, I'll take a look and see about bringing that internal this week or next.
