### ISSUE TITLE
Is it possible to run detekt for a single file?

### ISSUE THREAD

**Issue by VictorAlbertos** [arturbosch/detekt#2320]
We're trying to speed up our build time on the CI so we're considering only run static analytical tools on those files that actually contain changes. Is it possible (and if it's possible, is it advisable?) to run Detekt for single files? If not, what's the smaller scope in which Detekt can run with (Is it a Gradle module)?

Thanks!

**Comment by schalkms** [comment]
Yes it is via scripts. Please take a look at the following link for an example.
https://arturbosch.github.io/detekt/git-pre-commit-hook.html

Please note that the approach of analyzing a single file is not recommend, since rules using type and symbol solving don’t work.

**Comment by VictorAlbertos** [comment]
Thanks for the information!

But I don't understand how to use Detekt for specific files based on what you've shared. Can you put a specific example of how to call Detekt for a group of files, please? 

> Please note that the approach of analyzing a single file is not recommend, since rules using type and symbol solving don’t work.

And what are those rules? I don't see in the [docs about the rules](https://arturbosch.github.io/detekt/comments.html) anything telling if one specif rule falls into that category 🤔

**Comment by schalkms** [comment]
Using a Git commit hook could work in your case.
I just outlined a simple example.
When more rules use type and symbol solving, detekt will need the information from referenced types as well. For more sophisticated analysis, detekt needs more context. Using a single that just changed is in this case not enough.

> Can you put a specific example of how to call Detekt for a group of files, please?

I'm citing #1792.

> You can list of changed files and pipe them to detekt via the `--input x,y,z` parameter.
 See `git ls-files --modified` for example.

> And what are those rules?

All rules that use the `bindingContext` fall into that category.
- MissingWhenCase
- HasPlatformType
- UnsafeCallOnNullableType
- MapGetWithNotNullAssertionOperator
- UnsafeCast
- Deprecation
- RedundantElseInWhen
- ForbiddenVoid
- ExplicitCollectionElementAccessMethod
- RedundantExplicitType
- PreferToOverPairSyntax
- ForbiddenMethodCall
- UselessCallOnNotNull
- RedundantSuspendModifier
- SpreadOperator

I hope that I didn't miss a rule. Furthermore, we plan to have more existing rules that use type and symbol solving (#1915).

HTH

**Comment by VictorAlbertos** [comment]
Thank you very much for the detailed response!

**Comment by MaksimDmitriev** [comment]
> Yes it is possible via scripts. Please take a look at the following link for an example.
> https://arturbosch.github.io/detekt/git-pre-commit-hook.html
> 
> Please note that the approach of analyzing a single file is not recommend, since rules using type and symbol solving don’t work.

https://arturbosch.github.io/detekt/git-pre-commit-hook.html
404 - the link doesn't work

**Comment by BraisGabin** [comment]
https://detekt.github.io/detekt/git-pre-commit-hook.html
