### ISSUE TITLE
detekt does not always inject the required EDITOR_CONFIG_USER_DATA_KEY for ktlint

### ISSUE THREAD

**Issue by sschuberth** [arturbosch/detekt#2339]
This is a follow-up issue for #1803 as I believe @schalkms' [statement](https://github.com/arturbosch/detekt/issues/1803#issuecomment-519266029) of "Since detekt provides a wrapper over ktlint, this is not directly a problem of detekt" is not correct, and the issue seems to be in *detekt*, not in *ktlint*, as *detekt* does not properly inject `EDITOR_CONFIG_USER_DATA_KEY` before calling *ktlint*.

## Expected Behavior

Enabling *ktlint*'s `FinalNewline` rule should *not* crash *detekt*.

## Observed Behavior

Enabling *ktlint*'s `FinalNewline` rule *does* crash *detekt*.

## Steps to Reproduce

Use 

```
FinalNewline:
    active: true
```

on a file with missing final new line.

## Context

*ktlint* expects the `EDITOR_CONFIG_USER_DATA_KEY` [to be present](https://github.com/pinterest/ktlint/blob/b41aa2281f271d80255da727b838c0a111b6c293/ktlint-ruleset-standard/src/main/kotlin/com/pinterest/ktlint/ruleset/standard/FinalNewlineRule.kt#L18), and *detekt* actually [has code to add it](https://github.com/arturbosch/detekt/blob/d06b10deacd3e27060f6113355f029f0d624f828/detekt-formatting/src/main/kotlin/io/gitlab/arturbosch/detekt/formatting/FormattingRule.kt#L50-L53), but that code does not seem to be called as [FinalNewline](https://github.com/arturbosch/detekt/blob/master/detekt-formatting/src/main/kotlin/io/gitlab/arturbosch/detekt/formatting/wrappers/FinalNewline.kt) does not override `editorConfigUpdater` to return [something different](https://github.com/arturbosch/detekt/blob/d06b10deacd3e27060f6113355f029f0d624f828/detekt-formatting/src/main/kotlin/io/gitlab/arturbosch/detekt/formatting/FormattingRule.kt#L57) than `null`.

## Your Environment

* Version of detekt used: 1.5.1
* Version of Gradle used (if applicable): 6.1.1
* Operating System and version: Windows 10
* Link to your project (if it's a public repository): https://github.com/heremaps/oss-review-toolkit

**Comment by schalkms** [comment]
Thanks for describing the bug in detail with some sample code, so that we can reproduce it!
Yes, my statement in the linked issue is wrong. Based on the issue report it wasn't possible to reproduce it.
