### ISSUE TITLE
New Rule: No Force Unwrapping

### ISSUE THREAD

**Issue by joshfriend** [arturbosch/detekt#2345]
## Expected Behavior of the rule
Any uses of `!!` should be flagged.

This rule would be disabled by default as it is potentially divisive.

## Context
My preference is to avoid `!!` if possible and would appreciate a rule to help enforce this as part of the coding standard my team follows. We currently utilize [a similar rule for Swift code provided by swiftlint](https://realm.github.io/SwiftLint/force_unwrapping.html)

**Comment by schalkms** [comment]
Today is your lucky day. 🙂
We already provide such a rule. Please take a look at the following link.
https://arturbosch.github.io/detekt/potential-bugs.html#unsafecallonnullabletype

**Comment by joshfriend** [comment]
Gosh, I _promise_ I searched for it! Sorry for the dupe.

Maybe this is because Kotlin doesn't have a real name for the `!!` operator besides literally ["The !! Operator](https://kotlinlang.org/docs/reference/null-safety.html#the--operator). Not very searchable compared to swift's term "Force Unwrapping"

**Comment by schalkms** [comment]
No worries 😉 
Not-null assertion operator is the name.
