### ISSUE TITLE
Was passed main parameter '--project' but no main parameter was defined in your arg class

### ISSUE THREAD

**Issue by vanniktech** [arturbosch/detekt#235]
I get this when running `M13.2`:

Was passed main parameter '--project' but no main parameter was defined in your arg class

Usage: detekt [options]
  Options:
    --baseline, -b
      If a baseline xml file is passed in, only new code smells not in the
      baseline are printed in the console.
    --config, -c
      Path to the config file (path/to/config.yml).
    --config-resource, -cr
      Path to the config resource on detekt's classpath (path/to/config.yml).
    --create-baseline, -cb
      Treats current analysis findings as a smell baseline for further detekt
      runs.
      Default: false
    --debug, -d
      Debugs given ktFile by printing its elements.
      Default: false
    --disable-default-rulesets, -dd
      Disables default rule sets.
      Default: false
    --filters, -f
      Path filters defined through regex with separator ';' (".*test.*").
    --format
      Enables formatting of source code. Cannot be used together with
      --config.
      Default: false
    --generate-config, -gc
      Export default config to default-detekt-config.yml.
      Default: false
    --help, -h
      Shows the usage.
  * --input, -i
      Input path to analyze (path/to/project).
    --output, -o
      Specify the file to output to.
    --output-format, -of
      Specify the output format.
      Default: XML
      Possible Values: [PLAIN, XML]
    --parallel
      Enables parallel compilation of source files. Should only be used if the
      analyzing project has more than ~200 kotlin files.
      Default: false
    --rules, -r
      Extra paths to ruleset jars separated by ',' or ';'.
    --useTabs
      Tells the formatter that indentation with tabs are valid.
      Default: false

I feel like an old artifact was uploaded since it still says `input` instead of `project` in the output of all command line options.

**Comment by iNoles** [comment]
Rename -p to -i.

**Comment by vanniktech** [comment]
The gradle plugin is doing the work for me so I can't rename it.

**Comment by arturbosch** [comment]
That sounds not good. I can't reproduce it. If I seach for `--project` I get no matches.

**Comment by vanniktech** [comment]
Yeah already saw it. Could it be that an old artifact was uploaded? Or that there's a mismatch with versions?

**Comment by arturbosch** [comment]
Maybe you build detekt local and overwrote some of the jars? try cleaning your m2 and gradle caches for detekt und redownload everything?

**Comment by vanniktech** [comment]
Never mind. There's something mixed up on my machine. Got it resolved now.
