### ISSUE TITLE
Switching off detekt for a directory

### ISSUE THREAD

**Issue by yeltayev22** [arturbosch/detekt#2369]
Is there a way or feature that allows to switch off the detekt for a whole directory(like **/legacy-directory/**), not only for specific rule-sets? Couldn't find something related.

**Comment by cortinico** [comment]
You can configure the Detekt gradle task as described here: https://arturbosch.github.io/detekt/groovydsl.html#leveraging-gradles-sourcetask---excluding-and-including-source-files
