### ISSUE TITLE
detekt-gradle-plugin 1.5.1 is not published to Maven Central

### ISSUE THREAD

**Issue by Nycto** [arturbosch/detekt#2372]
## Expected Behavior
All of detekt 1.5.1 is available from Maven Central

## Observed Behavior
detekt-gradle-plugin 1.5.1 has not been published

## Steps to Reproduce
https://search.maven.org/search?q=g:io.gitlab.arturbosch.detekt%20AND%20a:detekt-gradle-plugin

## Context
I was able to use the rest of detekt 1.5.1 without adding other repositories, but this one failed.

## Your Environment

* Version of detekt used: 1.5.1
* Version of Gradle used (if applicable): N/A
* Operating System and version: N/A
* Link to your project (if it's a public repository): N/A

**Comment by 3flex** [comment]
Hi @Nycto, the Gradle plugin is only published to the Gradle plugins repository. You can find 1.5.1 there: https://plugins.gradle.org/plugin/io.gitlab.arturbosch.detekt
