### ISSUE TITLE
Should fail if `--baseline` file does not found?

### ISSUE THREAD

**Issue by ybiquitous** [arturbosch/detekt#2374]
Hi,

When I'm using detekt via CLI, I noticed a behavior that is not very intuitive.

When I accidentally pass a non-existent file to the `--baseline` option, detekt never outputs about the invalid file and succeeds.

```shell
# NG: basline.xml
# OK: baseline.xml
$ detekt --baseline basline.xml
```

I wasted time until I noticed the filename was incorrect, so I think it more useful if detekt would fail fast when passing an invalid file path to the `--baseline` option.

For example:

```shell
$ detekt --baseline basline.xml
Invalid the file path `basline.xml` is specified to the `--baseline` option!
```

What do you think about this idea?

Thank you for reading.

**Comment by BraisGabin** [comment]
I think that you are right. This is the current behaviour of the detekt gradle plugin so we should fail if the baseline file doesn't exist too.

**Comment by ybiquitous** [comment]
Thank you! 😊
