### ISSUE TITLE
How to disable colored output

### ISSUE THREAD

**Issue by ybiquitous** [arturbosch/detekt#2375]
Hello,

I'm using detekt via CLI and I sometimes want to disable colored output for machine readability:

<img width="908" alt="image" src="https://user-images.githubusercontent.com/473530/75333144-f4ae7980-58c8-11ea-8de5-288b2b682c2d.png">

Is there a good way to disable colored output via CLI?

Thank you for reading.

**Comment by schalkms** [comment]
If it’s really a dealbreaker for you, you can use a terminal that doesn’t support colorization (Windows cmd) or deactivate this feature completely.
The value/effort ratio isn’t given for realizing configuration options here, sorry.

**Comment by ybiquitous** [comment]
I understand. Thanks.
