### ISSUE TITLE
Support suppressing "EnumNaming" with Intellij's "EnumEntryName"

### ISSUE THREAD

**Issue by daphil19** [arturbosch/detekt#2377]
## Expected Behavior of the rule
It would be helpful if the [EnumNaming rule](https://arturbosch.github.io/detekt/naming.html#enumnaming) would support suppression via the `EnumEntryName` inspection ([description](https://github.com/JetBrains/kotlin/blob/master/idea/resources/inspectionDescriptions/EnumEntryName.html)).

## Context
Intellij has an inspection for enums to check if enums follow kotlin's naming conventions. This is supprssed using `@Suppress("EnumEntryName")`. In detekt, the same rule is defined as `EnumNaming`, so to suppress it in detekt and intellij, one would have to either 
1. Suppress with `@Suppress("EnumEntryName", "EnumNaming")`, which feels redundant, or
2. Exclude the file in `detekt.yml`, which isn't obvious and would require remembering to update it if the file gets renamed.

**Comment by schalkms** [comment]
In this case you have to decide, whether you want to activate IntelliJ’s or detekt’s inspection rule. It just doesn’t make much sense to activate both of them, since they serve the exact same purpose.
