### ISSUE TITLE
var properties in Objects

### ISSUE THREAD

**Issue by carlaf92** [arturbosch/detekt#2400]
I think that Objects and companion objects of classes should have only val properties, and that if an 
Object has any var property it is a code smell.
Because objects are kotlin singletons and should be designed to be static and immutable such as companion objects for classes.
It would be nice to report a violation in these cases.

**Comment by schalkms** [comment]
Could you please cite a few reliable resources (for instance official Kotlin docs) where this is discouraged? I think this rule is very opinionated and therefore not a good fit for detekt’s standard ruleset.
In my opinion mutable properties in objects are not per se bad in Kotlin. 
However, you can write a [custom rule](https://arturbosch.github.io/detekt/extensions.html#custom-rulesets) if you really want to enforce this.

**Comment by BraisGabin** [comment]
Any public var with a public setter in an object, companion object or "top level" is exactly the same as a global variable.

So I would agree about this rule but only when the visibility is public or internal. If it's private or protected they are OK, at least you don't have a global mutable state.

I would like to have more insights about this but for me the top level example is clear and the other two allows you to accomplish exactly the same, so...
