### ISSUE TITLE
Regex-based custom rules in detekt.yml

### ISSUE THREAD

**Issue by Jeehut** [arturbosch/detekt#2406]
## Expected Behavior
It would be great if there was a special section in the `detekt.yml` file where one could provide custom rules based on Regexes, similar to the [Custom Rules Feature in SwiftLint](https://github.com/realm/SwiftLint#defining-custom-rules). I know that custom rules can be defined via providing code, but I would rather prefer a Regex-based faster approach. This will make Detekt so much easier to customize!

## Current Behavior
A [custom rule](https://arturbosch.github.io/detekt/extensions.html) needs to be implemented for each simple check, even if a Regex would work fine.

## Context
While using SwiftLint, it is very easy and fast to add new custom rules, as you can see [here](https://github.com/Flinesoft/BartyCrouch/blob/stable/.swiftlint.yml#L124) I use them a lot and they are really useful. Would love to be able to do the same thing with Detekt.

**Comment by schalkms** [comment]
Thanks for the suggestion!

You can do that in detekt with the help of the naming ruleset and the formatting ruleset, which is wrapper of ktlint by the way.
This provides similar functionality but in a more structured way.
https://github.com/arturbosch/detekt/blob/3481ae7391f9a285a6b898fd1d4ee5646c4c37c1/detekt-cli/src/main/resources/default-detekt-config.yml#L311

If you find something missing in the ruleset, please feel free to suggest a new rule.

Furthermore, detekt architecture concerning the configuration loader mechanism is not build for having dynamics like this. It would require us to completely change it. I don't think it's worth investing time in it.

Please also keep in mind that regular expressions are not as powerful as using a context free grammar and the resulting abstracting syntax tree. In this case, regexes tend to have a higher false-positive, which should be avoided for detekt's rules.
Maybe ktlint is more suitable for this feature.
