### ISSUE TITLE
Gradle Quick-Start docs producing "unexpected token" error

### ISSUE THREAD

**Issue by Jeehut** [arturbosch/detekt#2408]
## Expected Behavior
When I copy & paste the Gradle documentation from the README and fulfill the minimum requirement (Gradle 5+), Gradle should build fine.

## Observed Behavior
I'm getting an error for this part of the code:

```groovy
tasks {
    withType<Detekt> { // <-- 78: unexpected token: > @ line 78, column 20
        // Target version of the generated JVM bytecode. It is used for type resolution.
        this.jvmTarget = "1.8"
    }
}
```

## Steps to Reproduce
Copy and paste README code to `build.gradle` in an Android project and click "Sync Now" in Android Studio.

## Your Environment

* Version of detekt used: 1.6.0
* Version of Gradle used (if applicable): 3.6.1 (Android Studio 3.6.1)
* Operating System and version: macOS 1.15.3
* Link to your project (if it's a public repository): –

**Comment by schalkms** [comment]
On Android this has to be configured differently. I hope that I find some time to write a blog post about it.
Please consult #2259 and report back whether the mentioned solution helps you.

**Comment by mandrachek** [comment]
I'm seeing the same issue, but it's not on Android.

I'm using gradle 5.6.4, with a standard (non-kotlin) build.gradle.  

I am using kotlin-gradle-plugin 1.3.70, and am targeting JDK8 for both java and kotlin.

I am using detekt 1.6.0, and running it under IntelliJ IDEA Ultimate 2019.3.3.

Adding the snippet mentioned above makes the gradle configuration blow up with the unexpected token error.

**Comment by arturbosch** [comment]
Please try if `tasks.detekt.jvmTarget = "1.8"` works for you.
The quick-start example uses the kotlin dsl. I will open a PR to add a groovy example.
