### ISSUE TITLE
Squash and merge results in rewriting the author information

### ISSUE THREAD

**Issue by schalkms** [arturbosch/detekt#2412]
This started to happen today (5th March) when merging the PRs.
For example I'm not the author of the PR #2397. Nevertheless, the commit 3481ae7 on the master branch still shows my email in the author field.

**Comment by schalkms** [comment]
@arturbosch did you change something in the repositories settings?

**Comment by arturbosch** [comment]
@schalkms nope, no changes. Also just noticed this PR :O.
I would expect something like:
```
Sort html report (#2290)
@BraisGabin
@arturbosch
BraisGabin authored and arturbosch committed on Jan 27

```

**Comment by schalkms** [comment]
> Maybe GitHub somehow messed up once.

Seems to be the case. Never mind.
