### ISSUE TITLE
The Detekt HTML Report should include date, version number, website link (Feature Request)

### ISSUE THREAD

**Issue by ozmium** [arturbosch/detekt#2416]
## Expected Behavior

The "detekt report" HTML file should contain the following:

* The date the report was generated, using a suitable long date format, something like `"Generated on: Saturday, 7 March 2020, 14:45, UTC"`
* The version number of the detekt tool.
* A URL link to the detekt website (or to the detekt Github page)

## Current Behavior

The HTML report does not contain any of these 3 items.

## Context

When 1 or more HTML reports are viewed in a web browser, the user cannot tell when the report was generated, or which detekt version was used. This makes it difficult to compare reports. Other code analysis Lint tools, like SpotBugs, will display some of these things.

**Comment by schalkms** [comment]
Good idea!
I agree with the first and second point.
What purpose does the third point serve? @ozmium

**Comment by ozmium** [comment]
A URL link to the website has multiple purposes:
* Attribution / referencing -- just in case there is another project called "detekt"
* Branding and marketing -- increase awareness of the project
* Make it easier for people to find out more about the tool, particularly if they are seeing the report for the first time, with no prior knowledge

**Comment by schalkms** [comment]
Thanks for stating that!
Do you have resources to help us out here? @ozmium 

The following class and the corresponding test cases should be adapted.
https://github.com/arturbosch/detekt/blob/master/detekt-cli/src/main/kotlin/io/gitlab/arturbosch/detekt/cli/out/HtmlOutputReport.kt

**Comment by ozmium** [comment]
I can try. I could submit a pull request of an initial change. But I won't be able to check out the whole project or test the change, or write a unit test for it. Someone else will have to test it and tidy it up, but I don't mind helping to refine it, if given guidance. Let me know if that's acceptable to you.

**Comment by schalkms** [comment]
That's acceptable. Please go ahead!

**Comment by BraisGabin** [comment]
I agree with all of them too, but: would the date mess up the gradle cache?

**Comment by schalkms** [comment]
> I agree with all of them too, but: would the date mess up the gradle cache?

I would add `Date.now()` to the HtmlReport. Thus it shouldn't be a problem.
