### ISSUE TITLE
file does not end with .yml!

### ISSUE THREAD

**Issue by Fleshgrinder** [arturbosch/detekt#2417]
Trying to load a `.yaml` file leads to an exception with the message from the issue title. [The official YAML FAQ recommends `.yaml` over `.yml`](https://yaml.org/faq.html) and I also believe that it is not up to detekt to prescribe what the file extension has to be. This choice should be up to the project. 😊

**Comment by schalkms** [comment]
I agree with that. I never understood why detekt handles it this way.
