### ISSUE TITLE
Debugging custom rule

### ISSUE THREAD

**Issue by Smoofie** [arturbosch/detekt#2431]
Hello there,

I'm implementing custom rule and I wanted to run debugger, to debug the code of my new rule.
I tried java remote debugging to debug gradle task, but it didn't work.
How can I connect debugger?

**Comment by arturbosch** [comment]
Hey,
have you seen the samples for example:
https://github.com/arturbosch/detekt/blob/0be10e81db1a7cfd00265b4309a042b171021359/detekt-sample-extensions/src/test/kotlin/io/gitlab/arturbosch/detekt/sample/extensions/TooManyFunctionsSpec.kt

The sample module has `detekt-test` as a test dependecy which has useful functions to quickly write tests. Within IntelliJ you can debug the tests aka debug your rule :).
Hope that helps

**Comment by schalkms** [comment]
As @arturbosch mentioned, this is the preferred way of debugging the functionality of your custom rule. Btw it's always great to here that users extend detekt. 🙂
Furthermore, it's much quicker to prototype your custom rule.
Please also take a look at our [contributing guide](https://github.com/arturbosch/detekt/blob/master/.github/CONTRIBUTING.md#when-implementing-new-rules-) which provides further information.
