### ISSUE TITLE
Plugin development to detekt violations of design principles

### ISSUE THREAD

**Issue by Mkohm** [arturbosch/detekt#2437]
Hi!

As some of you might have seen, i am developing a plugin to detekt called detekt-hint (https://github.com/mkohm/detekt-hint). I am writing my master thesis about detekt and how one could write an extension to detekt design principle violations. The main focus is trying to detect violations of common design principles (SOLID etc.). Because this is hard, i am essentially giving the developer "hints" instead of telling the developer that a design principle is violated. Therefore i am using detekt's ruleset-weight-feature, giving detections a 0 weight, such that hints won't break the build, but instead act as weak warnings. I have a few questions:

1. I am looking for feedback and testing of the plugin and wonder if some of you would like to help me out? If so, please reach out to me! (marius.kohmann@gmail.com)
- See the repo for some samples that is already developed
- Which design principles do you think is of most importance, and that could be "enforced" by detekt rules?
- Would you use such a tool? Why, why not?
- How can i reduce the amount of false-positives to a minimum?
- Should the weak-warnings be long and include possible solutions, or should they be kept it short and concise?

2. Is such a ruleset/feature of interest to detekt when the plugin is more mature? Or would it make sense to still keep as a plugin?

3. Would featuring my plugin in a section in the readme be something of interest? Would gladly create such a PR if it is of interest.

**Comment by schalkms** [comment]
Cool! 🙂👍
I like this plugin. It's always great to see in which ways the community extends detekt and how it can be customized to domain-specific needs.
I already gave it a star. 😉

> I am looking for feedback and testing of the plugin and wonder if some of you would like to help me out? If so, please reach out to me! 

Why don't you integrate your awesome tool to open source repos here on GitHub and have a huge amount of code running and testing your tool?
You could for instance add your CI tool to the CI chain in detekt's main repo.
We would really welcome such an integration. CC @arturbosch 

> Is such a ruleset/feature of interest to detekt when the plugin is more mature? Or would it make sense to still keep as a plugin?

I've laid out my opinion in #1381. We already discussed rules regarding the SOLID principles in detail. Concerning specific rules we encourage the community to submit issues. We've already merged a good number of 3rd party rules into detekt's main ruleset.

> Would featuring my plugin in a section in the readme be something of interest? Would gladly create such a PR if it is of interest.

Yes, we have a separate **integrations** section here:
https://github.com/arturbosch/detekt#mentions

Please go ahead and add your tool to this section.

**Comment by Mkohm** [comment]
> Cool! 🙂👍
> I like this plugin. It's always great to see in which ways the community extends detekt and how it can be customized to domain-specific needs.
> I already gave it a star. 😉

Thank you :) !! 



> Why don't you integrate your awesome tool to open source repos here on GitHub and have a huge amount of code running and testing your tool?

Good suggestion! I will definitely do that, when the tool is a little bit more mature. I think it needs a few more rules before it will have any useful impact!

> You could for instance add your CI tool to the CI chain in detekt's main repo.
> We would really welcome such an integration. CC @arturbosch

That is awesome, that would really help me out with some real testing of the tool! I will create a PR 😄 

  
> I've laid out my opinion in #1381. We already discussed rules regarding the SOLID principles in detail. Concerning specific rules we encourage the community to submit issues. We've already merged a good number of 3rd party rules into detekt's main ruleset.

Cool! I am currently working on a rule for LCOM (Lack of Cohesion Of Metods) that probably could be merged into detekt's main ruleset. I just need to filter out some more edge cases, and bugs 👍 



> Yes, we have a separate **integrations** section here:
> https://github.com/arturbosch/detekt#mentions
> 
> Please go ahead and add your tool to this section.

Upcoming PR !

**Comment by schalkms** [comment]
> I am currently working on a rule for LCOM (Lack of Cohesion Of Methods) that probably could be merged into detekt's main ruleset.

Sounds good!
Just to be clear, specific rules that contribute to the adherence to the SOLID principles are very welcome. Practically, these rules should go into a separete `design` ruleset.
But it's hard to formalize a rule that decides, whether a piece of code complies for instance with the SRP principle or not.

**Comment by schalkms** [comment]
> And when i have you here, i find the PSI API very huge, and not documented. And i can't get the source code either. Most of the time goes to tons of trial and error with the API. Any good tips/resources other than looking at how other rules are implemented?

You might find the following resources helpful in order to debug rules and the PSI.
- To print the AST of sources you can pass the --print-ast flag to the CLI which will print each Kotlin files AST. This can be helpful when implementing and debugging rules. 
Source: [When implementing new rules](https://github.com/arturbosch/detekt/blob/master/.github/CONTRIBUTING.md#when-implementing-new-rules-)
- The [PSI Viewer plugin](https://plugins.jetbrains.com/plugin/227-psiviewer) for IntelliJ

**Comment by Mkohm** [comment]
Thanks, i already knew about the PSI Viewer plugin! the --print-ast flag seems useful!

> Just to be clear, specific rules that contribute to the adherence to the SOLID principles are very welcome. Practically, these rules should go into a separete `design` ruleset.
> But it's hard to formalize a rule that decides, whether a piece of code complies for instance with the SRP principle or not.

We're on the same page :) I am totally aware of that!

**Comment by schalkms** [comment]
I've pinned your issue. This issue will stay open for some days.
You might also want to try to gather feedback in our official [Slack channel](https://kotlinlang.slack.com/messages/C88E12QH4/convo/C0BQ5GZ0S-1511956674.000289/).

**Comment by schalkms** [comment]
If you want to provide feedback, feel free to post on Slack or here on GitHub.

**Comment by schalkms** [comment]
@Mkohm Keep on rocking your project! 💪🙂
