### ISSUE TITLE
ComplexInterface - should it also count private methods?

### ISSUE THREAD

**Issue by Wrent** [arturbosch/detekt#2446]
`ComplexInterface` is triggered even if the number of overrideable functions / properties is less than treshold, but there are private methods within the interface (used by default implementation of the functions), which trigger the rule.

Should it be the case? Instinctively, I would not think they would be counted, but maybe I am wrong..

**Comment by cortinico** [comment]
> Should it be the case? Instinctively, I would not think they would be counted, but maybe I am wrong..

I don't think so. Having too many private methods could be easily spotted by this other rule: https://arturbosch.github.io/detekt/complexity.html#toomanyfunctions

I like to think at `ComplexInterface` as a way to inspect the API surface of my interface so I would prefer having only `public` method considered during the inspection.

**Comment by Wrent** [comment]
> I like to think at ComplexInterface as a way to inspect the API surface of my interface so I would prefer having only public method considered during the inspection.

Exactly my thoughts, thanks for opinion.

**Comment by schalkms** [comment]
Thanks for raising this interesting discussion thread.
I completely agree with the points made in @cortinico 's post. That's the reason why we have a separate rule for the mentioned case.

**Comment by BraisGabin** [comment]
I think that there was a confusion here. If we all agree (I agree too) we should fix it. Becase, right now, `ComplexInterface` is counting the `private` functions.

**Comment by cortinico** [comment]
> Becase, right now, ComplexInterface is counting the private functions.

Agree. Here a potential fix for this #2478
