### ISSUE TITLE
Is --config-resource useful in production?

### ISSUE THREAD

**Issue by BraisGabin** [arturbosch/detekt#2464]
Reviewing #2457 I had a doubt. `--config-resource` seems like a very handy parameter for testing propouses, but: is it useful for production? Is there any use case where you want to use `--config-resource`? Maybe we should remove it from our CLI.

**Comment by arturbosch** [comment]
It was actually a contributed feature for maven multi projects -> https://gitlab.com/arturbosch/detekt/-/merge_requests/2 when we were still at GitLab ;)

https://maven.apache.org/plugins/maven-checkstyle-plugin/examples/multi-module-config.html

It looks like a convention or just a proposed way to share the config. I haven't used Maven for the last years but I'm pretty sure there should be a way to share the same path constant from a parent pom to their children.

Should we close this issue?

**Comment by BraisGabin** [comment]
🤐 It seems a legit parameter then. Closing.
