### ISSUE TITLE
Support yaml lists in the configuration values

### ISSUE THREAD

**Issue by BraisGabin** [arturbosch/detekt#2498]
This issue is a continuation of #2463. There we talked about ForbiddenImports but we should generalice that solution to the rest of lists that we have in our yaml config file. (This case was implemented already #2474).

The reason for doing this is: 
- It's easier to mantain the configuration using lists than strings
- We don't need to handle strange cases splitting strings (empty strings and similar)

The idea is to allow the use of yaml list where we are now using a string with `,`. And if all goes well remove we can remove this old way in 2.0.

This is the list of configurations that, in 1.7.0, are lists splited by `,`:

- [x] *>excludes
- [x] ComplexMethod>nestingFunctions
- [x] ExceptionRaisedInUnexpectedLocation>methodNames
- [x] ForbiddenClassName>forbiddenName
- [x] ForbiddenComment>values
- [X] ForbiddenImport>imports
- [x] ForbiddenMethodCall>methods
- [x] ForbiddenPublicDataClass>ignorePackages
- [x] FunctionOnlyReturningConstant>excludeAnnotatedFunctions
- [x] LabeledExpression>ignoredLabels
- [x] LateinitUsage>excludeAnnotatedProperties
- [x] LongParameterList>ignoreAnnotated
- [x] MagicNumber>ignoreNumbers
- [x] SwallowedException>ignoredExceptionTypes
- [x] ThrowingExceptionsWithoutMessageOrCause>exceptions
- [x] UnnecessaryAbstractClass>excludeAnnotatedClasses
- [x] UseDataClass>excludeAnnotatedClasses
- [x] WildcardImport>excludeImports

**Comment by BraisGabin** [comment]
All the PRs are done now :)

**Comment by arturbosch** [comment]
Great work!
