### ISSUE TITLE
Allow Indentation check to handle "align when multiline" option

### ISSUE THREAD

**Issue by scottkennedy** [arturbosch/detekt#25]
https://github.com/arturbosch/detekt/blob/master/detekt-formatting/src/main/kotlin/io/gitlab/arturbosch/detekt/formatting/Indentation.kt seems to assume every line will be indented by some multiple of 4 spaces.

In Android Studio, I have these options checked:
![screen shot 2017-05-08 at 14 22 42](https://cloud.githubusercontent.com/assets/881690/25825965/d515a87e-33f9-11e7-96d2-f11df16eb191.png)

The result is code that looks like:
```
fun example(arg0: String, arg1: String,
                      arg2: String) {
```

This is not a multiple of 4 spaces.

In general, I want to ensure that all code is indented properly, but it's not always going to be a multiple of 4 spaces.

**Comment by arturbosch** [comment]
I think I will rework the formatting part in M11, after the gradle plugin and jcenter publishing in M10 is out. Thx!

**Comment by arturbosch** [comment]
Indentation check was enhanced a bit but will not be so powerful as idea. I integrated idea formatting and inspections as gradletasks. The recommend way is to use the new `detektIdeaFormat` task as of M11
