### ISSUE TITLE
IllegalImportRule

### ISSUE THREAD

**Issue by vanniktech** [arturbosch/detekt#250]
Checks for imports from a set of illegal packages.

This could be turned off by default and only when packages are provided be turned on.

As for the configuration I'd either have a list of packages with pattern matching support (e.g. `com.foo.bar*` or a regex.

[Checkstyle reference](http://checkstyle.sourceforge.net/config_imports.html#IllegalImport)

**Comment by vanniktech** [comment]
How should we do the configuration for this rule?

**Comment by arturbosch** [comment]
I think a list of regex would be sufficient?

**Comment by Mauin** [comment]
Since its imports we could just put in packages that we want to mark as illegal including all its subpackages.

**Comment by vanniktech** [comment]
Yeah so maybe a list like: `com.foo.bar*,org.something.blub.MyClass,de.bla.blub.*`, basically the same configuration for annotations in LateInitUsage.
