### ISSUE TITLE
SpacingAroundColon rule is different from Android Studios default formatting

### ISSUE THREAD

**Issue by tobilarscheid** [arturbosch/detekt#252]
By default, Android Studio will format code like so:

```kotlin
interface C: D
```

The `SpacingAroundColon` rule would rather like to have it like this:

```kotlin
interface C : D
```

Who is wrong?

**Comment by arturbosch** [comment]
I would argue that the official kotlin styling guide prefers our solution :) (see [here](https://kotlinlang.org/docs/reference/coding-conventions.html))

**Comment by vanniktech** [comment]
Yep same here. For variables and their types it is the first way.

**Comment by arturbosch** [comment]
I will close this. If you have more questions, reopen the issue :)
