### ISSUE TITLE
regression 1.7.1, threshhold does not exist

### ISSUE THREAD

**Issue by robstoll** [arturbosch/detekt#2523]
## Expected Behavior
Upgrading a patch version should always work

## Observed Behavior
```
> Task :detekt FAILED

Property 'complexity>LongParameterList>threshold' is deprecated. Use 'functionThreshold' and 'constructorThreshold' instead.

Property 'complexity>LongParameterList>threshold' is misspelled or does not exist.
```

## Steps to Reproduce
https://github.com/robstoll/niok/pull/41/files
https://travis-ci.org/github/robstoll/niok/jobs/667554736

## Your Environment
* Version of detekt used: 1.7.0

**Comment by schalkms** [comment]
That's why it's dangerous to change configuration options. It's always a model change so to speak. Changing the options could always lead to breaking the user configuration, which should be avoided.

**Comment by BraisGabin** [comment]
Maybe we can rethink the branching model. If we need to create a patch release we can create a new branch starting at the previus tag and cherry-pick the desired fixes. Then we merge that branch again in `master`

**Comment by arturbosch** [comment]
Well, imo this property deprecation was the perfect case that it worked as expected.
The old and the new properties work; default will be the old; a deprecation message was printed.
The problem was that the config validation framework had a bug. It needed/needs some iterations to be stable.

Versions between 1.5.0-1.7.1 had this problem. Maybe other users experienced it but didn't report this.

**Comment by Tolriq** [comment]
If the properties are deprecated should not the default from generateConfig use the new ones?

When I update detekt I always diff the default config to see the changes and the impact of the version. Not having deprecated properties replaced with the new ones hides such changes and makes it harder to know what to do.

**Comment by robstoll** [comment]
Maybe it makes sense to have a flag, turning deprecation warnings into errors (in case that does not already exist)? This way detekt would still provide the current behaviour which might be what users want and now kind of expect.

**Comment by arturbosch** [comment]
> If the properties are deprecated should not the default from generateConfig use the new ones?
> 
> When I update detekt I always diff the default config to see the changes and the impact of the version. Not having deprecated properties replaced with the new ones hides such changes and makes it harder to know what to do.

Yes, the generator uses the new properties so the default config does not have the old properties anymore. This is why the config validation failed for this "unknown" property.

> Maybe it makes sense to have a flag, turning deprecation warnings into errors (in case that does not already exist)? This way detekt would still provide the current behaviour which might be what users want and now kind of expect.

This sounds good to me and could be a config property next to `validation`.
```yaml
config:
  validation: true
  warningsAsErrors: true
  excludes: ...
```

**Comment by Tolriq** [comment]
@arturbosch  this is what the generated config generate :) still the deprecated values.
```
  LongParameterList:
    active: true
    threshold: 6
    ignoreDefaultParameters: false
```

**Comment by arturbosch** [comment]
@Tolriq I've just tested this and I get the new values.
The gradle task/cli flag just copies the default config from the jar to your directory.
If you use 1.7.1/1.7.2 it should generate the right values.
Maybe you were using the 1.7.0 release?

**Comment by Tolriq** [comment]
@arturbosch 
I did update to 1.7.1 and the detekt.yml still had the value linked before while it did update the "" to '' in
```  # when writing own rules with new properties, exclude the property path e.g.: 'my_rule_set,.*>.*>[my_property]'```

But I've deleted the file and generated again and now the new values are shown. So seems it does not take the new one and replace but do some kind of merge and the merge does not replace the deprecated ones.

I suppose I need to add delete the file in my update process but this is strange behavior. This is the same process I use since ages and usually the changed are properly updated in the default generated file.

**Comment by arturbosch** [comment]
Do you use the cli or gradle plugin? When running `detektGenerateConfig` the task stops when the config file already exists. The cli should override but not merge it.
Strange that it somehow worked that way for you.
I guess `rename-re-generate-diff` as a process could be used.

**Comment by Tolriq** [comment]
@arturbosch  ```.\gradlew detektgenerateconfig```

It works perfectly since ages like that and did merge the changes in a `` config/detekt/detekt.yml``` file. Never stopped or error with the file already existing.
