### ISSUE TITLE
Detekt using gradle documentation out of data

### ISSUE THREAD

**Issue by mrf7** [arturbosch/detekt#2528]
## Expected Behavior
Using the gradle properties on https://arturbosch.github.io/detekt/groovydsl.html should give an easy set up path.

## Observed Behavior
Specifically, the documentation calls out "source" as the property to set to give source code directories. This gives an error because the actual property is "input" 

## Context
Setting up detekt in a gradle build took longer and needed external sources 

## Your Environment
* Version of detekt used: 1.7.1

**Comment by schalkms** [comment]
Thanks for the feedback regarding the documentation! The 2 PRs correct this.
