### ISSUE TITLE
UndocumentedPublicProperty reported for documented data classes property

### ISSUE THREAD

**Issue by jcornaz** [arturbosch/detekt#2529]
## Expected Behavior
The following code:

```kotlin
/**
 * @property prop1 The property is documented
 */
data class MyDataClass(val prop1: String)
```

should not see any `UndocumentedPublicProperty` being reported because all properties are documented.

## Observed Behavior
Running detekt reports an issue:

```
UndocumentedPublicProperty - [prop1] at /home/me/workspace/project/src/main/kotlin/Example.kt:8:24
```

## Steps to Reproduce
The code above is all you need to reproduce the issue.

## Context
I was trying to update detekt from `1.6.0` to `1.7.1` and I got this errors. But I cannot fix them, because the properties are already documented.

## Your Environment
* Version of detekt used: `1.7.1`
* Version of Gradle used: `6.3`
* Operating System and version: `linux 5.5.11`
* Link to your project: https://github.com/jcornaz/kwik/pull/141

**Comment by schalkms** [comment]
Ugh, this slip through, unfortunately. Sorry for the inconvenience. Thanks for reporting it though.
With 1.7.1 a bug concerning undocumented properties that were not documented was fixed.
I think we should be a bit more conservative here and also allow `@param` in addition to `@property`.
