### ISSUE TITLE
codecov test coverage report doesn't work correctly

### ISSUE THREAD

**Issue by schalkms** [arturbosch/detekt#2558]
## Expected Behavior
The codecov report should report the test coverage for all packages inside the detekt repository.

## Observed Behavior
The codecov report reports 0 % coverage for 3 packages (formatting...)
Furthermore, it doesn't yield the correct coverage for other packages. It's too low.

## Steps to Reproduce
Take a look at the dashboard:
https://codecov.io/gh/arturbosch/detekt

## Context
The coverage report gives a good indication on how well a feature is tested.

The problem occured after merging 8a48551.

**Comment by arturbosch** [comment]
It seems that we run the codecoverage action for each OS and JVM. Maybe the Gradle caching leads to incomplete results.
Maybe it's worth to try to add a custom Github action just for coverage which runs `detekt clean test jacocoTestReport -Dorg.gradle.caching=false` ?

**Comment by cortinico** [comment]
I was actually thinking about this issue last week. We should probably publish the codecov report only from one instance of the CI matrix (say Ubuntu - JDK 8). 

The current setup could create concurrency problems where the first worker that succeeds will actually be the one where you read the coverage report from.

**Comment by arturbosch** [comment]
I've run sonar-kotlin over detekt and got a test coverage of 76.6%.
So this is definitely our CI not the gradle build file refactoring ^^

**Comment by schalkms** [comment]
Yes, I can confirm that the coverage works on the local IDEA installation.

**Comment by arturbosch** [comment]
Fixed by #2622
