### ISSUE TITLE
ignore vs exclude in the configuration file

### ISSUE THREAD

**Issue by BraisGabin** [arturbosch/detekt#2586]
We have a lot of configurations that allows us to add exceptions to our rules. But we use two ways to name those:

```yml
ignoreAnnotated
ignoreAnnotation
ignoreCompanionObjectPropertyDeclaration
ignoreConstantDeclaration
ignoreDataClasses
ignoreDefaultParameters
ignoreDeprecated
ignoreEnums
ignoreHashCodeFunction
ignoreLabeled
ignoreLocalVariableDeclaration
ignoreNamedArgument
ignoreNestingFunctions
ignoreNumbers
ignoreOnClassesPattern
ignoreOverridableFunction
ignoreOverridden
ignorePackages
ignorePrivate
ignorePropertyDeclaration
ignoreRanges
ignoreSimpleWhenEntries
ignoreSingleWhenExpression
ignoreStringsRegex
ignoreUsageInGenerics
ignoredExceptionTypes
ignoredLabels

excludeAnnotatedClasses
excludeAnnotatedFunction
excludeAnnotatedProperties
excludeClassPattern
excludeCommentStatements
excludeGuardClauses
excludeImportStatements
excludeImports
excludeLabeled
excludePackageStatements
excludeReturnFromLambda
excludeStringsWithLessThan5Characters
excludedFunctions
```

Does this difference have sense? For example we have `excludeLabeled` and `ignoreLabeled`. Which one should we use? Both?

Other topic are `excluded` and `ignored` that I think that we should rename to `exclude` and `ignore`.

**Comment by schalkms** [comment]
Thanks for bringing this to attention. Naming things is hard. This has to be accepted.

> There are only two hard things in Computer Science: cache invalidation and naming things.
> -- Phil Karlton

 I don't think that a uniform naming guideline for configuration options can be reached. There are many contributed rules and you can't make sure that everyone adheres to the naming guidelines. That would make it harder for 3rd contributors to actually contribute a rule. Furthermore, you change a public API here. As a user of detekt, I'm tired of constantly changing my existing config just for the sake of change. It costs time. I'm not sure regarding the user benefit of having a uniform naming. The rules are different and would be hard to achieve a uniform naming.

Related #2403

**Comment by BraisGabin** [comment]
> There are only two hard things in Computer Science: cache invalidation and naming things.

☝️ That's SO TRUE

You are right. Even with deprecations and supporting both configurations this costs time for our users.

A consistent configuration is good, but changing the configuration is bad... I don't know which option is better.

**Comment by schalkms** [comment]
You trade freedom and flexibility for consistency. I don’t think that consistent naming improves anything except being more consistent. The user has to evaluate the effect of each of the listed config options. They don’t have that much of a uniform behavior.
I would have a different opinion if the config option names were misleading, but that’s not the case here.
That’s why we should close this issue.
