### ISSUE TITLE
Distribute cli as an executable file

### ISSUE THREAD

**Issue by BraisGabin** [arturbosch/detekt#2605]
Extracted from ["Getting started with the CLI"](https://arturbosch.github.io/detekt/cli.html)

> 1. `cd detekt`
> 2. `gradle build`
> 3. `java -jar detekt-cli/build/libs/detekt-cli-[version]-all.jar [parameters]*`

We are forcing to our user to clone the repo.

It would be great to have something like:
1. `curl -sSLO https://github.com/arturbosch/detekt/releases/download/[version]/detekt && chmod a+x detekt`
2. `detekt [parameters]*`

(example taken from ktlint: https://ktlint.github.io/)

To acomplish this we need to generate an executable file with ALL detekt in it.

What do you think? This will allow us to easily distribute detekt with https://brew.sh/, https://chocolatey.org/ and similars. But that's another topic.

**Comment by arturbosch** [comment]
We upload the `cli-all.jar` when releasing (https://github.com/arturbosch/detekt/releases/tag/v1.7.4).
Would this help? 
We could also upload the distribution zip as it contains a unix and windows executable.

**Comment by BraisGabin** [comment]
I think so. I'll check how can we improve this.
