### ISSUE TITLE
Can't Find UnnecessaryNotNullOperator and UnnecessarySafeCall Rules

### ISSUE THREAD

**Issue by simonassank** [arturbosch/detekt#2624]
I am doing a detekt update from version `1.2.2` to `1.7.4` and found ran into some issues.

As I seen that there were some new cool rules added I figured to update my config using  [default-detekt-config.yml](https://github.com/arturbosch/detekt/blob/master/detekt-cli/src/main/resources/default-detekt-config.yml)

But it seems that I cannot find a few recently added rules. Could it be something with the configuration or is it a bug?

<img width="622" alt="image" src="https://user-images.githubusercontent.com/3253131/79741635-417f6100-830a-11ea-9893-2aadb0a5439a.png">

Thanks!

**Comment by arturbosch** [comment]
Hey, 
these two rules will be available in 1.8.0.
They are in master but not yet released :).
