### ISSUE TITLE
Data class rule

### ISSUE THREAD

**Issue by schalkms** [arturbosch/detekt#263]
If a class does nothing but hold data the developer can introduce a data class.

The following methods should be considered.

- equals
- hashCode
- toString
- copy

**Comment by schalkms** [comment]
It seems that data classes are nice, but are WIP when it comes to features like inheritance.

https://github.com/Kotlin/KEEP/blob/master/proposals/data-class-inheritance.md

**Comment by tagantroy** [comment]
@arturbosch @schalkms can use close this issue?

**Comment by schalkms** [comment]
Closed with #353
