### ISSUE TITLE
Allow backticks and spaces in method names

### ISSUE THREAD

**Issue by Tapchicoma** [arturbosch/detekt#264]
Kotlin allows to use backtick and spaces in method names:

```
   fun `Some function name`() {}
```

But default generated configuration doesn't allow to do it. 

Though I am not sure if it is normal practice to use this names other then test names.

**Comment by arturbosch** [comment]
Is there any source from the kotlin developers mentioning this? It is not only about what kotlin allows us to do, but is the preferred way for this. Coming from a java background I would say don't use backticks, only in test names. If you have good reasons, override the Naming patterne :)

**Comment by Tapchicoma** [comment]
Personally I don't want to use often method names with backtick and spaces in main code.

According to the [Kotlin docs](https://kotlinlang.org/docs/reference/java-interop.html#escaping-for-java-identifiers-that-are-keywords-in-kotlin) it was mainly added to have easier interop with java, because Kotlin has other set of reserved words.

But, for example, tests becomes more readable when using it. And also some testing frameworks uses such approach to their method names, so it also improves tests readability.

So, at least, for test classes I'd like to have this support.

**Comment by arturbosch** [comment]
For test classes you can use another deteKt profile where you override the regex  used for function names :)

**Comment by Tapchicoma** [comment]
Fair point.
