### ISSUE TITLE
Rule: Usages of @Deprecated functions/classes

### ISSUE THREAD

**Issue by Mauin** [arturbosch/detekt#267]
If we had access to the compile Context we could check every function call and check if the function or its containing class has been marked as `@Deprecated`.

Without the Context we could first collect a list of everything that is marked as `@Deprecated` and then check function calls for matches.

**Comment by arturbosch** [comment]
This could be done with a `Processor` storing all deprecated functions in a cache in the `onStart`-function and using this rule to run against the cache.

**Comment by Mauin** [comment]
I'd love to give this one a try.

**Comment by Mauin** [comment]
Should we add a GitHub label for rules that are "waiting" for context resolution?

**Comment by arturbosch** [comment]
Like this :)
