### ISSUE TITLE
Publish straight to JCenter

### ISSUE THREAD

**Issue by sschuberth** [arturbosch/detekt#27]
Please [publish the artifacts straight to JCenter](https://bintray.com/docs/usermanual/uploads/uploads_promotingyourmaterial.html#_including_your_package_in_jcenter) instead of "misusing" Bintray as a Maven repository. That would simplify the setup for most users as JCenter usually is already added as a repository.

**Comment by arturbosch** [comment]
Yes, thx. That's the next step, I try to deploy to jcenter with the next milestone release (today or few days). I think `detekt` is not only my private project anymore ;)

**Comment by arturbosch** [comment]
M10 is out on bintray. I asked for jcenter approvement, don't know how long to wait ;)

**Comment by arturbosch** [comment]
Do you know what I did wrong in my bintray package?

It's a maven repository and I use the maven conventions for package structure, jar and pom ... :O

**Comment by sschuberth** [comment]
Why do you think something got wrong? Maybe your request simply wasn't processed yet. The official docs say

> If the request is approved, an indication that the package is included in JCenter is displayed in the Package page, in the Included in work area in the bottom right corner of the page.

I don't see that indication (yet), but no error either, so I'd simply think you're still in the queue. Or did you get a response from JFrog?

**Comment by arturbosch** [comment]
The Bintray Bot keeps spaming me this:

```
Hi, 

JCenter hosts java applications that follow maven convention. In addition to the .pom file and binary file a sources jar, and optionally a javadoc jar. 
Your files should be under a maven path layout. (See https://bintray.com/docs/usermanual/uploads/uploads_includingyourpackagesinjcenter.html) 
Once those files are added, we'll be glad to include your package in JCenter. 

Regards, 
JFrog Support
```

**Comment by sschuberth** [comment]
I'm not entirely sure how to read that message, but it could be interpreted in the way that the `-sources.jar` is required...

**Comment by arturbosch** [comment]
You were right, sources and javadoc jars were needed. M10.1 is now up at jcenter, but still does not work as expected for the gradle-plugin ...

```
buildscript {
    repositories {
        // still need to add this instead of jcenter()
        maven { url "http://dl.bintray.com/arturbosch/code-analysis" }
    }
}

plugins {
    id "io.gitlab.arturbosch.detekt" version "1.0.0.M10.2"
}
```

**Comment by sschuberth** [comment]
Odd indeed, I'm having the same issue:

```
   > Could not find io.gitlab.arturbosch.detekt:detekt-cli:1.0.0.M10.1.
     Searched in the following locations:
         https://jcenter.bintray.com/io/gitlab/arturbosch/detekt/detekt-cli/1.0.0.M10.1/detekt-cli-1.0.0.M10.1.pom
         https://jcenter.bintray.com/io/gitlab/arturbosch/detekt/detekt-cli/1.0.0.M10.1/detekt-cli-1.0.0.M10.1.jar
         https://plugins.gradle.org/m2/io/gitlab/arturbosch/detekt/detekt-cli/1.0.0.M10.1/detekt-cli-1.0.0.M10.1.pom
         https://plugins.gradle.org/m2/io/gitlab/arturbosch/detekt/detekt-cli/1.0.0.M10.1/detekt-cli-1.0.0.M10.1.jar
     Required by:
         project : > gradle.plugin.io.gitlab.arturbosch.detekt:detekt-gradle-plugin:1.0.0.M10.2
```

I wonder what *would* be the correct JCenter URLs then. Maybe you can ask JFrog support about it?

**Comment by sschuberth** [comment]
BTW, the search result at https://bintray.com/search?query=detekt looks like only the `detect-core` artifact is published at JCenter, but not the `detect-cli` one.

**Comment by sschuberth** [comment]
@arturbosch Any luck finding out why only `detect-core` got published at JCenter?

**Comment by arturbosch** [comment]
Still no luck :(, I've contacted JFrog about my issue. Will keep you informed.

**Comment by vanniktech** [comment]
I'm trying this out in one of my pet projects. However I can't seem to find the gradle plugin. This is my configuration:

```
buildscript {
  repositories {
    jcenter()
  }
  dependencies {
    classpath "io.gitlab.arturbosch.detekt:detekt:1.0.0.M10.2"
  }
}

apply plugin: 'io.gitlab.arturbosch.detekt'

detekt {
  version = "1.0.0.M10.2"  // Specify current detekt version
  input = "$input/src/main/java" // input is preconfigured to 'project.projectDir.absolutePath'
  config = "$project/../code_quality_tools/detekt.yml" // Use $project.projectDir to navigate inside your project
  filters = ".*test.*, .*/resources/.*" // What paths to exclude? Use comma oder semicolon to separate
  rulesets = "other/optional/ruleset.jar" // Custom rule sets can be linked to this, use comma oder semicolon to separate
}
```

The precise error message is: `> Plugin with id 'io.gitlab.arturbosch.detekt' not found`

**Comment by sschuberth** [comment]
@vanniktech Yeah, that's the reason why this issue is still open. See the [README](https://github.com/arturbosch/detekt#using-the-detekt-gradle-plugin), you need to use `maven { url "http://dl.bintray.com/arturbosch/code-analysis" }`.

**Comment by vanniktech** [comment]
Still yields the same error message: `> Plugin with id 'io.gitlab.arturbosch.detekt' not found.`

Note: I'm not using the `plugins` block instead I'm using `apply plugin:`.

**Comment by arturbosch** [comment]
Take a look here [detekt@plugins.gradle](https://plugins.gradle.org/plugin/io.gitlab.arturbosch.detekt).

it says to use it in the old way you have to use:

```
buildscript {
  repositories {
    maven { url "http://dl.bintray.com/arturbosch/code-analysis" }
    maven { url "https://plugins.gradle.org/m2/" }
  }
  dependencies {
    classpath "gradle.plugin.io.gitlab.arturbosch.detekt:detekt-gradle-plugin:1.0.0.M10.2"
  }
}

apply plugin: "io.gitlab.arturbosch.detekt"
```

The support wrote me they forwared my problem to other team which will check it and reply to me ... still waiting ...

**Comment by dinomite** [comment]
@arturbosch I'm no expert, but if it's any help I publish this library to JCenter via Bintray: https://github.com/dinomite/unfurling

My Bintray Maven repo is here: https://bintray.com/dinomite/maven

**Comment by vanniktech** [comment]
@arturbosch thanks this does seem to work now.

**Comment by arturbosch** [comment]
@dinomite I do not see any major differences in your build.gradle and my file ... you use your group:artifactId as the bintray package name hmm

**Comment by arturbosch** [comment]
It looks like detekt is on [jcenter](http://jcenter.bintray.com/io/gitlab/arturbosch/detekt) !! But it will still not be able to live without the hard dependency on my repo as I use a dependency from my other project ..., will be fixed in #57

**Comment by sschuberth** [comment]
I'm a bit skeptical as https://bintray.com/search?query=detekt still only returns `detekt-core`, but I'm keeping fingers crossed!

**Comment by arturbosch** [comment]
Your searching on Bintray not jcenter.bintray.com. I tried it yesterday and all dependencies of detekt are found, just the smell-baseline-format jar not ^^

**Comment by sschuberth** [comment]
> Your searching on Bintray not jcenter.bintray.com.

That's what I though at first, too, but if you look closely that page says "The current results are in Maven context". Which I believe to refer to JCenter. Anyway, I'll just try it out once #57 is resolved :-)

**Comment by arturbosch** [comment]
Ok, now
```groovy
buildscript {
    repositories {
        jcenter()
    }
}

plugins {
    id "io.gitlab.arturbosch.detekt" version "1.0.0.M10.3"
}
```

should work ^^

**Comment by dinomite** [comment]
Works for me 👍 

What change did it require?

**Comment by arturbosch** [comment]
First I had to wait till the support fixes somehow my package then I had to eliminate a dependency on my other project which also was not on jcenter :). Finally it works :+1:
