### ISSUE TITLE
UnnecessaryParentheses

### ISSUE THREAD

**Issue by vanniktech** [arturbosch/detekt#270]
Checks for Parentheses that are not needed.

Some examples:

```kotlin
val k = (5 + 3)
val o = (5)
val t = 3.plus((5))
vh.itemView.setOnClickListener({ it.doSomething() })
```

[PMD reference](http://pmd.sourceforge.net/pmd-5.1.0/rules/java/unnecessary.html#UselessParentheses) [Checkstyle reference](http://checkstyle.sourceforge.net/config_coding.html#UnnecessaryParentheses)

**Comment by schalkms** [comment]
I think the rule makes sense. Although, I guess that in rare cases (formulas) parentheses improve readability.

**Comment by Mauin** [comment]
Picked this one up this morning. Should be able to finish this in the evening.
