### ISSUE TITLE
MagicNumber rule throw report for null initialized variable

### ISSUE THREAD

**Issue by samarjan92** [arturbosch/detekt#276]
Code below

`private var pair: Pair<String, Int>? = null`

will broken by MagicNumber rule. 
Is that an expected behaviour?

I could prepare PR

**Comment by vanniktech** [comment]
Nope it should not.

**Comment by rock3r** [comment]
I have [a fix](https://github.com/rock3r/detekt/compare/improve_build_setup...rock3r:fix_magic_number_check) ready, waiting for #275 to be merged to open a PR for that. It's one of many bugs in MagicNumber, which was added in the RC phase IIRC. Use M13.2 for now!

**Comment by arturbosch** [comment]
Cool thx for the report and fixes. Will try to review everything after I'm home and have a laptop :). I flied over your fix @rock3r. Remove the wildcards ;)

**Comment by rock3r** [comment]
...done :) I think I'll need to do a PR to make sure the IDE project settings are consistent with your code style, cause that was the IDE :D

**Comment by arturbosch** [comment]
There is a code-style.xml in this repo if your working with intellij :)

**Comment by Mauin** [comment]
Can this one be closed now that #278 is merged?

**Comment by arturbosch** [comment]
I will add a test case for this and close it together with #280 :+1:

**Comment by mikezx6r** [comment]
This seems to be triggered for 'true' and 'false' too.

**Comment by rock3r** [comment]
It was addressed in #278
