### ISSUE TITLE
ExpressionBodySyntaxLineBreaks autocorrect only runs for the first instance on a file 

### ISSUE THREAD

**Issue by pakoito** [arturbosch/detekt#285]
After updating from M7 to M13 I added a ExpressionBodySyntaxLineBreaks rule along with MaxLineLength to set a new standard. When I ran detekt from CLI as per [our rules]( https://github.com/kategory/kategory/blob/master/detekt.gradle) it only modified the first instance of the detection per file.

Version: M13
Repro: 
Get this diff
https://github.com/kategory/kategory/pull/172/commits/a6e4926a8b50dd4a3d3b5e305588c90c8dc22258
Run ./gradlew detekt
Check file changes with git diff
See that successive runs of CLI updates the files until all of them are completed

**Comment by arturbosch** [comment]
Thanks for reporting! Make sure to use M13.2 as M13 had some issues if I remember correctly (maybe just the gradle plugin).

**Comment by pakoito** [comment]
Thanks for the response. I'll update to M13.2, I believe I tried updating to M13-2 and it obviously failed to resolve it hahaha

**Comment by pakoito** [comment]
M13.2 did still have this issue :(

**Comment by arturbosch** [comment]
Yes it is a defect. The M13.2 update was an advice as M13 had some issues :).
