### ISSUE TITLE
ExpressionBodySyntaxLineBreaks autofix doesn't respect MaxLineLength

### ISSUE THREAD

**Issue by pakoito** [arturbosch/detekt#286]
After updating my configuration for M13 to have MaxLineLength of 160 and ExpressionBodySyntaxLineBreaks, I applied autofixes until all lines were correct. I afterwards saw detekt would complain that those line fixes would run over the MaxLineLength. 

Version : M13

Repro:
Update to
https://github.com/kategory/kategory/pull/172/commits/d026ba8d32a112166a586d76afe11a8ab25c8538
Run ./gradlew detekt
See many MaxLineLength reports
Fix one of the max lines, i.e. https://github.com/kategory/kategory/pull/172/commits/d026ba8d32a112166a586d76afe11a8ab25c8538#diff-0439ac4ce81f1f0d4002d56c68e30c4fR189
Run ./gradlew detekt again
See report for ExpressionBodySyntaxLineBreaks and auto-fix applied

**Comment by arturbosch** [comment]
Yes this is known behavior but has low priority as there is the option to let intellij format theh code for you with `gradle detektIdeaFormat` task. (needs local community idea, see [README](https://github.com/arturbosch/detekt#configure-a-local-idea-for-detekt))

Detekt has no format indentation feature, which is also hard to extract from intellij - not in kotlin compiler.
If someone from the community wants to try to write an indentation formatting I would be glad to merge it!

**Comment by pakoito** [comment]
We'll try to change from CLI to the plugin in the project! cc @wiyarmir

**Comment by wiyarmir** [comment]
Oh well, I guess this bumps the priority for us to switch to the plugin 😄
