### ISSUE TITLE
For multiple instances of the same issue on a file --create-baseline creates one entry in the baseline file

### ISSUE THREAD

**Issue by pakoito** [arturbosch/detekt#287]
I've had multiple instances of MaxLineLength in a file, like the ones seen in #286

When running detekt with -cb, it creates more than one identical entry in the baseline file which can be safely removed.

Repro:
Update to
https://github.com/kategory/kategory/commit/d026ba8d32a112166a586d76afe11a8ab25c8538
Run ./gradlew detekt
See many MaxLineLength reports
Run ./gradlew detektEstablishAcceptedErrors
See duplicates in reports/baseline.xml

**Comment by arturbosch** [comment]
This is due the fact how signature works. Thanks for reporting!
