### ISSUE TITLE
MagicNumber add ignoreOnClassesPattern (same as LateinitUsage)

### ISSUE THREAD

**Issue by vanniktech** [arturbosch/detekt#291]
I'd like to add the configuration property `ignoreOnClassesPattern` in the `MagicNumber` rule with the same behavior as in `LateinitUsage`.

**Comment by arturbosch** [comment]
I'm not sure about it. What kind of classes you would like to ignore?

**Comment by vanniktech** [comment]
Again for Tests :D

**Comment by vanniktech** [comment]
Before releasing 1.0.0 we should come up with a consistent way either something along the lines of `ignoreOnClassesPattern` or #227. #227 would definitely be the better long term solution.

**Comment by arturbosch** [comment]
I added the 1.0 milestone to #227 to make sure we have a solution.

**Comment by vanniktech** [comment]
Then I'll close this in favor of #227
