### ISSUE TITLE
Extend naming ruleset

### ISSUE THREAD

**Issue by schalkms** [arturbosch/detekt#302]
Maybe, add some more rules which detect too long or too short names.

This could be tagged as "easy".

reference file: NamingConventionViolation.kt

**Comment by arturbosch** [comment]
Maybe also some words that are forbidden to use in class names like data or manager.

**Comment by Khang-NT** [comment]
It maybe more helpful if **detekt** has these rules for NamingConvention like Intelliji Java inspections.
![screen shot 2017-08-27 at 10 40 12 am](https://user-images.githubusercontent.com/13332950/29746943-75be15f6-8b14-11e7-8cf7-d0c0b6f21fc4.png)

**Comment by Mauin** [comment]
Should we close this issue after #374 is merged? Or should we work on some more naming rules mentioned in the IntelliJ warnings as well? Should we break those up into separate issues to make them easier to track and easier for contributors to pick up?

**Comment by vanniktech** [comment]
I'd say close or split them up individually so people can say what they're working on.

**Comment by arturbosch** [comment]
Thats a lot of rules if we want to implement them all. I also want to close this and if users want more rules, they can feature request them or just file a PR ;)
