### ISSUE TITLE
OptionalReturnKeyword: Fails with expressions

### ISSUE THREAD

**Issue by PaulWoitaschek** [arturbosch/detekt#304]
When using an expression like this:

```kotlin
  fun test() {
    val a = try {
      returnsIntOrThrows()
    } catch (e: Exception) {
      return
    }
    println(a)
  }
```
Using 1.0.0-RC2, it reports that the return is optional (which it's not).

**Comment by arturbosch** [comment]
Thank you for reporting this!

**Comment by PaulWoitaschek** [comment]
What do you mean by the label "waiting for feedback"?

**Comment by arturbosch** [comment]
Good question :D. Either I need more details from the reporter or I need some time to reproduce it and then removing the label again ;)
