### ISSUE TITLE
Cannot execute CLI Jar after building locally.

### ISSUE THREAD

**Issue by Mauin** [arturbosch/detekt#315]
Currently working on detekt and after building detekt with 

`gradle build shadow` and then running the JAR throws the following error:

```
--- mauin/detekt (mr/naming_length_multi_rule* RM)» java -jar detekt-cli/build/libs/detekt-cli-1.0.0.RC2.jar -i .
no main manifest attribute, in detekt-cli/build/libs/detekt-cli-1.0.0.RC2.jar
```

Did I just completely break something on my branch or is there an issue?

**Comment by arturbosch** [comment]
I'm having no issues on local master ^^

**Comment by Mauin** [comment]
Oh, I see. I was running `detekt-cli-1.0.0.RC2.jar` which shows the error above. But running `detekt-cli-1.0.0.RC2-all.jar` is successful.
