### ISSUE TITLE
[1.0.0.RC3] - no main manifest attribute

### ISSUE THREAD

**Issue by jaredsburrows** [arturbosch/detekt#323]
After following these instructions: https://github.com/arturbosch/detekt#build--use-the-commandline-interface, I get the following issue:

```
$ java -jar detekt-cli/build/libs/detekt-cli-1.0.0.RC3.jar 
no main manifest attribute, in detekt-cli/build/libs/detekt-cli-1.0.0.RC3.jar
```

It looks like you are specifying the `mainClassName` here:https://github.com/arturbosch/detekt/blob/master/detekt-cli/build.gradle#L1 and applying the correct plugins: https://github.com/arturbosch/detekt/blob/master/build.gradle#L43.

**Comment by Mauin** [comment]
If you run the `-all.jar` it should work.

**Comment by jaredsburrows** [comment]
@Mauin Thanks. I misread!
