### ISSUE TITLE
Deprecate formatting

### ISSUE THREAD

**Issue by arturbosch** [arturbosch/detekt#326]
Reasons:
- stop messing with users code (autoCorrect)
- let ktlint handle formatting
- let intellij handle formatting (detektIdeaFormat task)
- invalid locations from kotlin-compiler (ArrayOutOfBoundExceptions, no dirty fixes)
- missing indentation formatting algorithm 
- more time for core rules and integrations (sonar)
- hadi mentioned on twitter, that jetbrains plans to release a checkstyle equivalent for kotlin

**Comment by arturbosch** [comment]
To remove:

- JunktKt#getTextSafe()
- Location#startLineAndColumn - try-catch
- formatting module
- extract some rules like expression body syntax to own style rules without autoCorrect
- close all formatting related issues

**Comment by arturbosch** [comment]
Added new point:
- hadi mentioned on twitter, that jetbrains plans to release a checkstyle equivalent for kotlin (cant find the tweet anymore ...)

**Comment by arturbosch** [comment]
My post from #406 for documentation purpose:

To make it short: Yes.

The long explanation: It seemed like a good idea to combine every aspect (complexity/codesmell/formatting) into detekt to have everything in one place. The downside is that this requires much more maintenace for the detekt contributors and of course is a bit redundant work with KtLint.
We get feedback on two sides, the rules diverge, new rules get added. There are also two different paradigm to write rules: standard rules uses Expressions/Statements/Declarations and formatting rules use a low level token approach (complexer).
The last point is that I do not want to deal with users code anymore (false positives lead to more work for the user).
Everything in one plugin (detekt) still sounds great, so we try to provide wrappers over intellij commandline scripts (detektIdeaFormat/detektIdeaInspect), KtLint (should replace the formatting rule set), 'official jetbrains kotlin formatting tool' (if possible) which will be released soon.

But I'm still not sure when to merge this PR. Just do it? Write a ktlint wrapper immediately and risk unnecessary work when jetbrains tool come out? ... Suggestions welcome :)

**Comment by schalkms** [comment]
Do you have a source where Jetbrains mentions the release of the upcoming formatting tool for Kotlin?

**Comment by vanniktech** [comment]
Can this be closed now?

**Comment by schalkms** [comment]
I think so. One more question. Is the infrasture for formatting still there, so that the users can write rules themselves like in #430?

**Comment by arturbosch** [comment]
Yes I dropped the commits that deleted mutating the ast. withAutoCorrect is also there.

**Comment by arturbosch** [comment]
@schalkms no I dont have a source. Someone on twitter asked for a tool like checkstyle and hadi responded that they plan to release one in the nearest future. I tried to search for that post again, but no luck.

**Comment by schalkms** [comment]
No worries. I'm glad that as a user you can still write custom formatting rules if they want.

**Comment by arturbosch** [comment]
Formatting dependant issues won't get fixed: #286 #285 #229
