### ISSUE TITLE
PackagePattern in naming conventions

### ISSUE THREAD

**Issue by jonathanrz** [arturbosch/detekt#327]
I posted a question in StackOverflow (https://stackoverflow.com/questions/45846555/detekt-snake-case-package) because I can't specify the naming conventions for packages names.

Is it possible?

**Comment by schalkms** [comment]
Thanks for reporting. I submit a PR with a fix.

**Comment by Mauin** [comment]
You can set `packagePattern` in the `NamingViolationConvention` rule.

**Comment by arturbosch** [comment]
We are on Stackoverflow :D. Thanks for answering and PR @schalkms and @Mauin !

**Comment by jonathanrz** [comment]
Thanks for the help folks 💯
