### ISSUE TITLE
Intellij Plugin

### ISSUE THREAD

**Issue by vanniktech** [arturbosch/detekt#340]
Since more and more rules are added it might be worth to have an Intellij Plugin. I think it should be pretty straight forward to implement since it'll just delegate down to the binary (same way the Gradle Plugin works).

It'd also be super cool if the plugin would detekt the profiles that you configured and would allow you to choose from which if you have more than one. Or maybe as an MVP just let it point to a project aware configuration file.

**Comment by arturbosch** [comment]
I like the profile idea :+1: I would love to work on an idea plugin! But still a duplicate of https://github.com/arturbosch/detekt/issues/52 ;)

**Comment by vanniktech** [comment]
Whops. I was only searching for IntelliJ. Sorry for the noise :D

Closing this here and wrote my idea in 52.
