### ISSUE TITLE
Maven can't find the detekt dependency

### ISSUE THREAD

**Issue by philipbankier** [arturbosch/detekt#342]
I am trying to add detekt to my maven project but the dependency cant be found. I have tried moving the dependency to the dependency section but no luck. I get the error below when using the pom.xml in this projects README.md.

Dependency '''io.gitlab.arturbosch.detekt:detekt:1.0.0.RC3''' not found

**Comment by arturbosch** [comment]
Can you post your pom configuration so I can better analyze your issue? 

Have you added my code-analysis bintray repository?

**Comment by arturbosch** [comment]
Possible duplicate of #421
