### ISSUE TITLE
Generate documentation for rules from source code comment

### ISSUE THREAD

**Issue by schalkms** [arturbosch/detekt#343]
Since we don't have documentation for the detekt rules at this point I suggest that we generate it from source. (not only because it sounds cool)

This would mean that the source code comments have to updated. These comments then are parsed and a markdown/html page is generated with this kind of information. Furthermore, the level of documentation for detekt increases.

I also think the detekt documentation should provide noncompliant and compliant code examples. SonarJava does this for example.
https://www.sonarsource.com/products/codeanalyzers/sonarjava/rules.html

A solution could be to annotate our test cases with appropriate examples and then the documentation generator reads it via reflection.

This tool can also be integrated in the detekt build process. Thus, detekt always has up-to-date documentation

Let me know what you think.

**Comment by vanniktech** [comment]
Goes a bit into the direction of #189

**Comment by vanniktech** [comment]
I like it though. Let's automate as much as possible.

**Comment by arturbosch** [comment]
That would be awesome to have a documentation hosted via github pages with Jekyll or something. Generation through source documentation sounds good to me. Don't know if we should annotate specific test cases or just put the examples to the kdoc for each rule. A Gradle task can be used to extract the doc.

**Comment by Mauin** [comment]
I like the idea. Just having one standard way of documenting a Rule class (with a bunch of standard parameters) would allow us to both generate a `default-detekt-config.yml` without forgetting any configuration options and also generate better overall documentation. 👍  from me
