### ISSUE TITLE
Was passed main parameter '--rules' but no main parameter was defined in your arg class

### ISSUE THREAD

**Issue by Khang-NT** [arturbosch/detekt#344]
I'm trying to build custom rule set, just following example code. But when I add my rule set, it can't run.
>
> --rules, -r
>      Extra paths to ruleset jars separated by ';'.

But `--rules` doesn't exists in [Args.kt](https://github.com/arturbosch/detekt/blob/master/detekt-cli/src/main/kotlin/io/gitlab/arturbosch/detekt/cli/Args.kt)

I'm using detekt gradle plugin RC3.

**Comment by arturbosch** [comment]
Hey, sorry I forgot to update the readme. The parameter is now called plugins and is discribed in the migration guide.
