### ISSUE TITLE
Document rationales for rules

### ISSUE THREAD

**Issue by sschuberth** [arturbosch/detekt#347]
It would be nice if violations would come along with rationales for the respective rules. That is, why is violating that rule considered bad practice, and what's the reference for that bad practice (like a link to a community wiki or issue / PR discussion)? This may seem obvious in many cases, at least for experienced developers, but not for everybody. Also, for rules like `CommentOverPrivateMethod` at least to me it's completely not obvious why adding more documentation than absolutely necessary is supposed to be a "bad" thing.

**Comment by mnonnenmacher** [comment]
You could use Codenarc as inspiration, it does a good job in explaining the rules and giving examples:
http://codenarc.sourceforge.net/codenarc-rule-index.html

**Comment by Mauin** [comment]
Goes a little into the direction of #273 as well, giving each finding a clear description as to what's actually wrong. Many rules check for multiple cases so having a good issue description and rationale toally makes sense.

**Comment by schalkms** [comment]
@arturbosch @Mauin this is done, isn't it?
