### ISSUE TITLE
Rule: Expression syntax

### ISSUE THREAD

**Issue by nanodeath** [arturbosch/detekt#35]
Hi there! I have a couple ideas for rules that would help my team *a lot*, and hopefully would help others, too.

### Always use expression syntax in functions when possible

Suppose you have
```kotlin
fun foo(): String {
  return ""
}
```
If there's only one statement and the method has a non-void return value, it should always be turned into the equivalent expression version:
```kotlin
fun foo(): String = ""
```
While just a style issue, this is something we end up calling out in our code reviews constantly and...we'd like to not have to do that 😉 

Remainder was split off into #36.

**Comment by arturbosch** [comment]
+1 for `Always use expression syntax in functions when possible` and its not that hard to implement it.

I think the second rule is subjectiv. I for example would always write the `=` on the line with the method header :D. For the formatting rule set I focus on the kotlin conventions on the kotlin page and this repo https://github.com/yole/kotlin-style-guide/issues

Another option would be to write your own rule set for the second rule :D

**Comment by nanodeath** [comment]
Agreed the second half is more subjective. I moved it into a new issue (#36) because...well, I should have done that originally.

**Comment by arturbosch** [comment]
I implemented this rule and the first half of #36 in [PR46](https://github.com/arturbosch/detekt/pull/46)

After using this rules the identation gets messed up, which hinders me to merge it. Maybe I find out IntelliJ handles reformating (Ctrl+Alt+L) and I can use it after performing all formating rules ...

Would you check out the test cases to make sure I have not forgotten any?
