### ISSUE TITLE
Rule: Expression-syntax line breaks

### ISSUE THREAD

**Issue by nanodeath** [arturbosch/detekt#36]
Split off from #35.

### Expression-syntax line breaks

Another more nuanced (and admittedly, somewhat arbitrary) rule is the following:
When using expression syntax:
1. If the expression is a one-liner, the `=` should be on the same line as the expression, and both should be on the line following the method prototype.
2. Otherwise, the `=` should be right after the method prototype, and the rest of the expression should be on the following lines.

Example:
```kotlin
fun foo(): String
    = " Hello World ".trim()

fun bar(): String =
    foo()
        .baz()
        .bat()
```

**Comment by arturbosch** [comment]
I've added support for 1. and 2. in the rule `ExpressionBodySyntaxLineBreaks`. It works on my test cases and projects. I've disabled this rule in the default-config for now as I need to rework Indentation.

**Comment by nanodeath** [comment]
Awesome, thanks Artur 😁
