### ISSUE TITLE
Tests are not executed anymore but skipped!

### ISSUE THREAD

**Issue by arturbosch** [arturbosch/detekt#373]

**Comment by Mauin** [comment]
This seems like a dealbreaker and we shouldn't merge any more PRs until we have this one fixed. Looking at the history in Travis it seems like this build was the first one that didn't execute any tests: https://travis-ci.org/arturbosch/detekt/builds/264664547

That translates to the update to Kotlin v1.1.4 in this commit https://github.com/arturbosch/detekt/commit/7f7ecd4aef713030d14f7abe09a37980908ffda6

**Comment by schalkms** [comment]
What can we do here? Should we set the kotlin compiler back to the old one?

**Comment by arturbosch** [comment]
Sorry for missing the comments - just noticed. I expected it to be a junit/spek issue and by upgrading to the newest version it now works again.

**Comment by Mauin** [comment]
Ah, good to see it fixed. Was it only those tests that were red? That's pretty good for almost a month without tests I'd say. 

Sorry for breaking this and not paying closer attention to the build 😞  And sorry for writing those broken rules that you now had to fix. Awesome work @arturbosch

**Comment by arturbosch** [comment]
One month without tests is crazy :D

Np, we are in the same boat, happens when using working with software in development. Does just mean that the process is not optimal.

Seems like we need a RC4-3 with more fixes (and new rules :P)
