### ISSUE TITLE
UnnecessaryAbstractClass: Relax when the class is annotated with Module

### ISSUE THREAD

**Issue by vanniktech** [arturbosch/detekt#377]
In dagger it makes sense to have an abstract class with a few abstract methods since it'll tell the Dagger Compiler how certain types can be bound.

An example is the following class:

```kotlin
@Module abstract class SomeModule {
  @Binds abstract fun provideSomeThing(mySomeThing: MySomeThing): SomeThing
}
```

We probably want to ignore those cases when `dagger.Module` is applied.

What do you think?

**Comment by arturbosch** [comment]
Makes sense for annotation processing . Coma separated list of annotations :D + comma separated list of class name patterns?

**Comment by vanniktech** [comment]
Yeah maybe the same as the `LateInit` rule. I thought the class name pattern wanted to be solved differently according to #227.

However coming to think about this now maybe it'd make sense to have this also for annotations.

- Certain rules will be skipped when an annotation is applied
- Certain rules will be skipped when the class matches a regex

**Comment by schalkms** [comment]
Yeah. It makes sense. It is just one more config options.

**Comment by vanniktech** [comment]
Should we do this config option on this rule or provide a way to exclude multiple rules when a given annotation is applied?

**Comment by arturbosch** [comment]
I want to start working on #227 at the end of the week after my exam. I think annotation based excluding should be done on the rule level with properties and excluding by class name can be efficiently done by #227.

**Comment by vanniktech** [comment]
Good luck for your exams. Alright that way sounds good to me. Probably we want to reuse the logic for collecting the Annotations together with the `LateInit` rule.

**Comment by vanniktech** [comment]
How should we proceed on this given that it's still waiting for feedback?

**Comment by arturbosch** [comment]
I think it is okay to have such a property for the whole. I mean annotation processing is really common on the jvm. Feel free to implement that :).
