### ISSUE TITLE
Get rules parameters programmatically

### ISSUE THREAD

**Issue by carlospinho04** [arturbosch/detekt#388]
Right now i'm using `getIssue` method  to get the information (id, severity, ...) about the rules programmatically, but i'm not able to get the parameters (i.e From `StringLiteralDuplication` the parameters are: threshold, ignoreAnnotation, ...). Is there any way to get them programmatically?

**Comment by schalkms** [comment]
Thanks for contributing to detekt.
Would you mind to share the code and describe what you are trying to do?

**Comment by carlospinho04** [comment]
I'm trying to generate a json with  the rules, descriptions, parameters, etc.

Currently i'm invoking this from Scala. The code is still just a prototype to see that I can gather:
```
val rules: List[Rule] = ResourceHelper.getResourceContent("META-INF/services/io.gitlab.arturbosch.detekt.api.RuleSetProvider")
  .get
  .flatMap {
  clazz =>
    Class.forName(clazz)
      .getDeclaredConstructor()
      .newInstance()
      .asInstanceOf[RuleSetProvider]
      .instance(config)
      .getRules
      .flatMap {
        case r: MultiRule =>
          r.asInstanceOf[MultiRule].getRules
        case r: Rule =>
          Seq(r.asInstanceOf[Rule])
      }
}(collection.breakOut)
```

**Comment by schalkms** [comment]
The configuration parameters of the rules are stored in companion objects. This means that they can for example be accessed via reflection. One exemption is **threshold** where we have a separate class `ThresholdRule`.
Your intention goes a bit into the direction of #343 and #189 

Here is the code to access the configuration parameters.
```kotlin
val f = MagicNumber::class.java.getField("IGNORE_NUMBERS")
println(f)
```

**Comment by arturbosch** [comment]
Interesting work on your side. Goes into the direction of #189. As @schalkms mentioned reflection is the way to go if you prefer scala. For  #189 I would use a `FileProcessListener` and a `DetektVisitor`.
