### ISSUE TITLE
Issues with XML output format

### ISSUE THREAD

**Issue by scottkennedy** [arturbosch/detekt#390]
```xml
<checkstyle version="4.3">
  <file name="src/.../Blah.kt">
    <error line="807" column="52" severity="warning" message="" source="detekt.ExpressionBodySyntax"/>
  </file>
</checkstyle>
```

The lack of a `message` is both hard to read, and causing exceptions to be thrown when using https://github.com/tomasbjerre/violations-lib.

The text output has quite a long message there, such as the method name, so it would be useful to populate the `message` attribute.

I'm not sure if this affects all rules, or only certain ones.

**Comment by arturbosch** [comment]
The message field is populated with the description of an _Issue_. Unfortunately the formatting rules have no description. With RC5 formatting gets removed from the code base and your problems should go away. See #326.
