### ISSUE TITLE
Add editorconfig?

### ISSUE THREAD

**Issue by 3flex** [arturbosch/detekt#397]
The project includes `idea-code-style.xml` which requires a manual import into the IntelliJ settings before it takes effect (to my knowledge).

The project could include an `.editorconfig` file which would enforce indentation and required newline rules. See http://editorconfig.org/ for details. If the file exists it's used by default in IntelliJ.

**Comment by schalkms** [comment]
I like this idea. +1

**Comment by arturbosch** [comment]
Good idea ^^
