### ISSUE TITLE
Hotspot report -> which packages need refactoring/have the most code smells

### ISSUE THREAD

**Issue by arturbosch** [arturbosch/detekt#40]
- how many smells lead to a hotspot?
- how many hotspot to show in the report? just one, the biggest?

**Comment by schalkms** [comment]
`FileBasedFindingsReport` does in my opinion work exactly like that.
Is that what you had in mind when creating this issue?

**Comment by arturbosch** [comment]
I'm not sure anymore actually.
As of now, I think hotspot analysis needs repository mining.
`FileBasedFindingsReport` + #modifications -> refactoring opportunities
