### ISSUE TITLE
Remove log from result

### ISSUE THREAD

**Issue by carlospinho04** [arturbosch/detekt#411]
Hi again, when I analyze one file, the log: `Analyzing 1 kotlin files: .` is always appearing. There's any way to remove this?

**Comment by arturbosch** [comment]
Yep, it is one of the processors which gets loaded by default if you use `DetektFacade.instance(settings)`

Use 
`private val detektor = DetektFacade.instance(settings,RuleSetLocator(settings).load(),emptyList())` instead.

**Comment by carlospinho04** [comment]
It works, thank you ! 👍
