### ISSUE TITLE
IDEA inspections does not work under Windows

### ISSUE THREAD

**Issue by mglukhikh** [arturbosch/detekt#413]
Because detektIdeaInspect tries to run inspect.sh, but under Windows the relevant file has name inspect.bat.

**Comment by mglukhikh** [comment]
Same thing is true for detektIdeaFormat

**Comment by schalkms** [comment]
Thanks for reporting!

**Comment by arturbosch** [comment]
Oh yeah, my bad, stupi linux preferences :D. Thanks!
