### ISSUE TITLE
FunctionNaming regex should work for test cases that are sentences

### ISSUE THREAD

**Issue by snowe2010** [arturbosch/detekt#423]
Currently the regex for FunctionNaming is too specific to allow for tests that use the sentence syntax, a massive boom for readability.

```
fun `Test doUpcast() upcasts ExpenseProvided to created, candidate and qualifying events`() {
}
```

should be fine, but because it starts with a capital, has spaces, and is surrounded by backticks, it does not pass the test. 

a regex like this should work ``` ^([a-z$][a-zA-Z$0-9]*)|(`.*`)$ ```

**Comment by arturbosch** [comment]
Thanks for the feedback. Do you mind opening a PR with this fix?
