### ISSUE TITLE
Participate together in the Hacktoberfest

### ISSUE THREAD

**Issue by vanniktech** [arturbosch/detekt#441]
The issues could get some visibility in combination with the [Hacktoberfest](https://github.com/blog/2433-celebrate-open-source-this-october-with-hacktoberfest). All that would need to be done is adding the `hacktoberfest` to issues / PR so that other people can see it.

**Comment by schalkms** [comment]
I agree. It would be nice to have new contributors.

**Comment by arturbosch** [comment]
So basically adding a new label?

**Comment by vanniktech** [comment]
Yes.

**Comment by schalkms** [comment]
I think there should be some tasks which can be implemented by hacktoberfest participants. Does anyone have any ideas?

**Comment by vanniktech** [comment]
Probably the ones that are marked with `easy`?

**Comment by schalkms** [comment]
So far one task is marked as easy. Putting thebhacktoberfest label will make it easier for new contributors to locate this task. Furthermore, some new issues might be helpful.

**Comment by arturbosch** [comment]
I try to look through the issues and mark some as __easy__ and __hackobergest__.

**Comment by vanniktech** [comment]
Given that there are now a few already marked, I'd say let's close this issue?
