### ISSUE TITLE
Suppressing string duplication doesn't work

### ISSUE THREAD

**Issue by lwasylkowski** [arturbosch/detekt#442]
`@Suppress("all")` or `@Suppress("StringLiteralDuplication")` have no effect when put on class, and all string literal duplications are reported & contributed to the weight threshold anyway

**Comment by arturbosch** [comment]
Thanks for reporting!

**Comment by arturbosch** [comment]
Confirmed: The containing file is always reported as the position for the smell. Need to change that.

**Comment by lwasylkowski** [comment]
If you point me to where it probably should be fixed, I'll be happy to contribute

**Comment by arturbosch** [comment]
Sorry, didn't read your comment, was busy fixing the issue :). This fix will be included in the next version in a few days.
