### ISSUE TITLE
Single report in multi module project

### ISSUE THREAD

**Issue by MaximYesman** [arturbosch/detekt#449]
Hello!

 I configure gradle task in my project

		task detekt(type: JavaExec) {
			main = "io.gitlab.arturbosch.detekt.cli.Main"
			classpath = configurations.detekt
			def input = "$projectDir"
			def config = "$projectDir/detekt.yml"
			def filters = ".*test.*"
			def output = "$buildDir/reports/detekt"
			def params = [ '-i', input, '-c', config, '-f', filters, '-o', output]
			args(params)
		}
		....
		check.dependsOn detekt

When I run build for each module report generated in corresponding directory. But, when I _change_ output param to "$rootDir/reports/detekt", only last report shown. 
Is it any flag, like [jacoco append](http://www.jacoco.org/jacoco/trunk/doc/agent.html), to merge reports for multi module projects?

Thank you!

**Comment by arturbosch** [comment]
If I understand you correctly you have configured the task for each sub project? Or in the `allprojects` or `subprojects` closure? Just configure the detekt task on the top level `build.gradle` and you will get the report file with all issues.
