### ISSUE TITLE
MagicNumber: Should methods that only return that number be flagged?

### ISSUE THREAD

**Issue by Mauin** [arturbosch/detekt#465]
`override fun getTheNumber(): Int = 123`

Should `123` be flagged as a magic number? The method name already gives it some context.

**Comment by schalkms** [comment]
No. I have a better idea.
This is another code smell. Methods should not return only constants. This includes **"magic numbers"**.
I would implement this after approval. :)

**Comment by arturbosch** [comment]
Good idea @schalkms, go ahead ^^
