### ISSUE TITLE
Should enums be a data classes?

### ISSUE THREAD

**Issue by adauvalter** [arturbosch/detekt#479]
I have an enum and detekt fails with an error: `UseDataClass` Could we exept enums from check for that?

**Comment by Mauin** [comment]
Sounds like a good idea. Either excluding enums by default or at least giving a configuration option to exclude them.

Could you post a code snippet that is showing the violation?

**Comment by arturbosch** [comment]
That's already fixed in master. New release should come in a few days ^^ - duplicate of #435
