### ISSUE TITLE
Generate default yaml configuration on cli flag

### ISSUE THREAD

**Issue by arturbosch** [arturbosch/detekt#48]

**Comment by lummax** [comment]
I'd like to help. Could you provide some details?

**Comment by arturbosch** [comment]
It would be awesome if users could generate a default-detekt-config.yml by using the cli or gradle-plugin instead of copying the default config from this repo.

- src/main/resources must contain the default config
- the flag --generate-config  (-gc) should copy the config to `.` location (pls also rename disableDefaultRuleSets to --disable-default-rulesets)
- when providing this flag, detekt-cli should generate the config and shutdown (like debug flag in main method)
- add a generateConfig field to `DetektExtension` in gradle-plugin -> `gradle detekt` should also shut down after generating the config
