### ISSUE TITLE
VariableNaming and VariableMinLength: Exclude simple Underscore from Rule

### ISSUE THREAD

**Issue by devtribe** [arturbosch/detekt#481]
detekt marks an underscore `_` as an VariableNaming and VariableMinLength smell. But this is a correct feature of Kotlin. See https://kotlinlang.org/docs/reference/multi-declarations.html#underscore-for-unused-variables-since-11

Underscore should be excluded from these Rules

**Comment by Mauin** [comment]
Thanks for reporting this!
