### ISSUE TITLE
HTML report

### ISSUE THREAD

**Issue by rock3r** [arturbosch/detekt#490]
I think Detekt would benefit from having an HTML report like other tools do, so that we can accompany the name of the check to a description etc. to make it easier to fix. Right now I have to go and look at the Detekt code to understand the point of some checks.

**Comment by pocmo** [comment]
This is something I would like to see too.

@Mauin @arturbosch Could I pick this up?

**Comment by arturbosch** [comment]
Sure thing, think yourself assigned :)

**Comment by flobaader** [comment]
when will the feature be released? Would really appreciate it.

**Comment by arturbosch** [comment]
RC6 which shippes html output format is out !
