### ISSUE TITLE
UselessPostfixExpression rule will detekt a wrong expression like “mInstance!!”

### ISSUE THREAD

**Issue by cyw3** [arturbosch/detekt#491]

**Comment by Mauin** [comment]
@cyw3 Could you please provide some code that will report this issue?

**Comment by cyw3** [comment]
![image](https://user-images.githubusercontent.com/11549103/31654133-a7aad77c-b2ea-11e7-99d2-f503db94842c.png)

**Comment by vanniktech** [comment]
Why is `SwiftBrowserIdleTaskHelper` not an `object` where you get the singleton for free?

**Comment by arturbosch** [comment]
Can you just copy-paste the code here, so we can copy-paste it ourself for the test code base :D

**Comment by cyw3** [comment]
fun getInstance(): SwiftBrowserIdleTaskHelper {
    if (null == sInstance) {
        synchronized(SwiftBrowserIdleTaskHelper::class) {
            if (null == sInstance) {
                sInstance = SwiftBrowserIdleTaskHelper()
            }
        }
    }
    return sInstance!!
}

**Comment by arturbosch** [comment]
Thanks for reporting, this will be fixed in the next release by #493
