### ISSUE TITLE
Allow detekt suppression prefix 

### ISSUE THREAD

**Issue by Mauin** [arturbosch/detekt#497]
Taken from the comments in #494 

When suppressing a rule we should allow the String in the `Suppress` annotation to contain a `detekt` prefix.

Checkstyle allows this: @SuppressWarnings("checkstyle:magicnumber")
PMD allows this: @SuppressWarnings("PMD.ShortClassName")

So something along the lines of `@Suppress("detekt.SomeRuleName")` should still suppress the rule.

I'm happy to take a stab at this if people agree.

**Comment by arturbosch** [comment]
So basically to track down for which tool you suppress this? Sounds good!
The file you are looking is `Suppressible`, happy for file name changes too :D
