### ISSUE TITLE
WildcardImport should support regex exclusions

### ISSUE THREAD

**Issue by rock3r** [arturbosch/detekt#506]
Currently WildcardImport only checks if a given wildcard import matches exactly entries from a set of exclusions, but it should support regexes because a lot of people have wildcard imports for stuff like Kotlin Android Extension's `kotlinx.android.synthetic.*` packages, which are very easy to allow with a regex but almost impossible to exclude without.

Having `kotlinx.android.synthetic` use star imports is a default IDE configuration so we should likely allow those by default too.

**Comment by arturbosch** [comment]
Agree, we also have the logic for it see `LateInitUsage.excludeAnnotatedProperties` and the `Excludes` class.

**Comment by arturbosch** [comment]
Just checked out. It is already implemented. The config property was just absent ;)

**Comment by rock3r** [comment]
Hmmm not that I know of. That was a glaring example as it's a default one in Android Studio (and I suppose IDEA), and Android Kotlin projects get the Android Kotlin extensions by default in the template...

**Comment by rock3r** [comment]
So these are the ones the IDE allows and converts to wildcards by default:

![image](https://user-images.githubusercontent.com/153802/31860426-ccc4e7e8-b711-11e7-90d9-4bab81ea4d8e.png)

I suppose we should have those as defaults

**Comment by arturbosch** [comment]
I've added intellij's defaults to the default config ^^

**Comment by rock3r** [comment]
Great, thanks :)
