### ISSUE TITLE
Auto-deployed SNAPSHOTs

### ISSUE THREAD

**Issue by vanniktech** [arturbosch/detekt#512]
Maybe I'm missing something but it would be really beneficial to have auto-deployed snapshots to verify certain newly added behaviors without the need to create another RC.

**Comment by arturbosch** [comment]
Should be somehow possible with bintray ^^
Now that I'm not the only contributor the milestone and rc phases are kinda slow. Ofc I want to ship every user contribution as fast as possible. Snapshot deploys would be cool and after 1.0.0 weekly release too :)

**Comment by 3flex** [comment]
This should be fairly easy using something like [this](https://github.com/square/kotlinpoet/commit/e1f9e71a79b4d7dbc10de42b5a9f7f7f134141fb).

It would automatically deploy to Sonatype's snapshot repository when the Travis build succeeds.

**Comment by vanniktech** [comment]
Is this really as simple as adding the script to run in travis? If so could you @arturbosch generate the encrypted keys for publishing? Nexus username + pw
