### ISSUE TITLE
FunctionOnlyReturningConstant & Parcelable's describeContents

### ISSUE THREAD

**Issue by vanniktech** [arturbosch/detekt#514]
In Android, we have the [`Parcelable`](https://developer.android.com/reference/android/os/Parcelable.html) interface, which specifies that you need to implement a `describeContents` method. In 99% of the cases this ends up looking like this `override fun describeContents() = 0`.

What do you guys think about whitelisting that specific method?

**Comment by Mauin** [comment]
I had the same basic question in #465 and the `FunctionOnlyReturningConstant` rule got created as a result. But I'd still like a configuration param for the `FunctionOnlyReturningConstant` rule/`MagicNumber` rule for overriden functions that return a constant.

**Comment by schalkms** [comment]
Yes. I think this rule should ignore overridden functions. Furthermore, it should provide a custom list.

**Comment by scott-kennedy-ck** [comment]
I'm not sure this is good enough.

I have an `open fun blah() = true` that's triggering this warning.  The default value is `true`, but subclasses can override it.  Maybe there should also be an option for ignoring overridable functions?

**Comment by scottkennedy** [comment]
I'm not sure this is good enough.

I have an `open fun blah() = true` that's triggering this warning.  The default value is `true`, but subclasses can override it.  Maybe there should also be an option for ignoring overridable functions?

**Comment by schalkms** [comment]
@scottkennedy Would you mind creating a new issue?
