### ISSUE TITLE
IDEA Plugin

### ISSUE THREAD

**Issue by Takhion** [arturbosch/detekt#52]
It would be awesome if the analysis could be done in the background directly in IDEA in order to see/fix every problem before even compiling anything!

**Comment by arturbosch** [comment]
Yes! It's planned after the 1.0.0 release as stated in the `ROADMAP.md`. Will keep this Issue for that, thx!

**Comment by Takhion** [comment]
@arturbosch that is **awesome**! Sorry for missing the (obvious) `ROADMAP.md` :D
BTW thank you so much for creating this, it was much needed!

**Comment by arturbosch** [comment]
No problem! Sooner or later this ticket would have been created :). If you have any ideas for user interfaces/windows or how the plugin should behave, let me know!

**Comment by vanniktech** [comment]
It'd also be super cool if the plugin would detekt the profiles that you configured and would allow you to choose from which if you have more than one. Or maybe as an MVP just let it point to a project aware configuration file.

**Comment by arturbosch** [comment]
New idea: Prevent git commit/push when unsolved detekt issues

**Comment by v-grishechko** [comment]
May be create fork from this plugin and rewrite for kotlin support?
https://github.com/SonarSource/sonarlint-intellij
This plugin able to analyze code by internal rules or rules from sonar qube server.

**Comment by deeprim** [comment]
@arturbosch 

I suppose, it would be sufficient, as for an MVP, just to apply the *default* rules without any configuration at all. (it'll cover the case when the project is not using detekt as part of CI/CD, a developer could benefit from detekt just applying it to the code he/she writing at the moment)

The detekt's feedback would look like this:
![image](https://user-images.githubusercontent.com/5381880/36945075-360d1ec0-1fb1-11e8-8138-d78008c153f8.png)

The ability to configure the rules or/and integrate existing maven or gradle configuration would a subject for next releases

Any ideas?

**Comment by arturbosch** [comment]
An early working prototype is now located at https://github.com/arturbosch/detekt-intellij-plugin.
