### ISSUE TITLE
Strange behavior with CollapsibleIfStatements

### ISSUE THREAD

**Issue by scottkennedy** [arturbosch/detekt#522]
```kotlin
if (BuildConfig.DEBUG) {
    if (Constants.isTestApp) {
        doSomething()
    } else {
        throw UnsupportedOperationException("This method only exists for tests")
    }
}
```

I'm not sure how it expects me to collapse this.  I don't want to do anything if it's a RELEASE build.

If there weren't an `else` case, It would make sense, but I don't think this should be triggering CollapsibleIfStatements.

**Comment by schalkms** [comment]
Thanks for reporting. I'll take a look.
