### ISSUE TITLE
FunctionOnlyReturningConstant should have option for open functions

### ISSUE THREAD

**Issue by scottkennedy** [arturbosch/detekt#523]
Per https://github.com/arturbosch/detekt/issues/514#issuecomment-339477803

I have an `open fun blah() = true` that's triggering this warning.  The default value is `true`, but subclasses can override it.  Maybe there should also be an option for ignoring overridable functions?

**Comment by schalkms** [comment]
Good point! I would add a new option to the rule.

**Comment by schalkms** [comment]
IMHO this can be closed.
