### ISSUE TITLE
Feedback: Generating documentation & default configuration

### ISSUE THREAD

**Issue by Mauin** [arturbosch/detekt#531]
I'm currently working on a new `detekt` module that will parse the `detekt-rules` module and gather all `RuleSetProviders` and their `Rules`.

The goal in the end is to generate `*.md` files for documentation of each RuleSet and its rules as well as generating the `default-detekt-config.yml` automatically.

So far I've gathered the following parameters for the items:
RuleSets:
 - name
 - description (for documentation)
 - List<Rule>

Rules:
- name
- description (for documentation)
- rationale (for documentation)
- configuration options (including their name, description for documentation and default value)

If you can think of more parameters I should consider adding to those entities, feel free to let me know.

The biggest question I'm thinking about right now is: Where to put these parameters. I will comment with 2 comments to this issue for solutions I've come up with. Feel free to leave thoughts or more solutions as well.

**Comment by Mauin** [comment]
Solution 1: KDoc
```
/**
 * @name example
 * @description This is an example
 * @rules ExampleRule, .., ..
 */
class ExampleProvider : RuleSetProvider {

	override val ruleSetId: String = "example"

	override fun instance(config: Config): RuleSet {
		return RuleSet(ruleSetId, listOf(
				ExampleRule(config),
				..,
				..
		))
	}
}
```

```
/**
 * @name ExampleRule
 * @description Super cool description
 * @rationale Explanation as to why this rule exists, examples, ways to solve it, links to benchmarks, discussions, etc.
 * @configuration `excludeSomething` - Explanation of the config option (default: `something`)
 * @configuration ...
 * @configuration ...
 */
class ExampleRule(config: Config = Config.empty) : Rule(config) {
   ...
}
```

This gives each RuleSet and Rule some great KDoc documentation already and we can parse that from the documentation generation script.
However it requires us to keep the KDoc always _exactly_ up-to-date with the code. Especially looking at configuration options I fear that we might get out of date KDoc very quickly.

**Comment by Mauin** [comment]
Solution 2: Code

```
class ExampleProvider : RuleSetProvider {

	override val ruleSetId: String = "example"
  
  override val description: String = "This is an example"
	
	override fun instance(config: Config): RuleSet {
		return RuleSet(ruleSetId, listOf(
				ExampleRule(config), // Parsing list of rules from here
				..,
				..
		))
	}
}
```

```
class ExampleRule(config: Config = Config.empty) : Rule(config) {
    override val issue = Issue("ruleName we can parse",
    			Severity.Defect,
        "rule description we can parse.")
        
    override val rationale: String = "Rationale for the rule, maybe also in Issue?"
    
    override val configurationOptions: List<ConfigurationOption> = listOf(...)
}
```

This option requires some work to get all `Rule` classes updated to contain the necessary properties so that we can parse all configuration options correctly. But it ensures that the generated documentation/default config can never become out of sync with the code itself.

**Comment by schalkms** [comment]
Fantastic job so far! I really like the idea of generation documentation automatically.

Regarding the first comment I think the rule description belongs into the comment above the respective class.
Regarding the documentation of the options I think that **detekt** should implement a check at build time which checks if all config options have a comment. 

I don't like the idea of having a `List<ConfigurationOption>` in the second comment.

**Comment by Mauin** [comment]
Another thing I realized just now: If we want to generate the `default-detekt-config.yml` we need some way to mark a rule as active/inactive. Maybe with a `@since v1.0.0-RC5` annotation and then we can automatically decide that new rules are turned off by default, but older rules might be enabled automatically.

**Comment by schalkms** [comment]
@Mauin
Yes. You will also need one for the default value of the config options.

**Comment by arturbosch** [comment]
Great job!

My suggestions:
`@name` can be extracted from the class name
`@description` could be just the Kdoc without a tag -> 
```
/**
 * Super cool description
 * 
 * @rationale Explanation as to why this rule exists, examples, ways to solve it, links to benchmarks, discussions, etc.
 * @configuration `excludeSomething` - Explanation of the config option (default: `something`)
 * @configuration ...
 * @configuration ...
 */
class ExampleRule(config: Config = Config.empty) : Rule(config) {
   ...
}
```

**Comment by Mauin** [comment]
With tags it will be easiest to directly address those parts of the KDoc. Otherwise we can't distinct the description from actual code documentation that might be in the KDoc.

With the KDoc approach I'm just a bit scared that we'd have rules that don't match the correct formatting and even worse: That the configuration documentation gets outdated, we generate a faulty default config and don't realize it until after we released something.

**Comment by schalkms** [comment]
@Mauin Detekt has a test which checks the config option. I've recently committed this.

**Comment by arturbosch** [comment]
For the default values we could introduce a convention that all property names and their default values must be in an companian object, which can clash with other constants because of DRY ...

For the active rules, I do not have a solution now. A predefined lookup table?

**Comment by schalkms** [comment]
@arturbosch maybe with an annotation `@active`

**Comment by Mauin** [comment]
Thanks for all the feedback. I'll close this issue for now and will try to finish the prototype with the KDoc approach this week.
