### ISSUE TITLE
Implement Android Kotlin style guide

### ISSUE THREAD

**Issue by rock3r** [arturbosch/detekt#532]
Today Google has released the official Kotlin Android style guides, maybe there's something in there that is worth implementing, if anything as an "android" profile that is used by default on Android projects?

See https://android.github.io/kotlin-guides/style.html

**Comment by arturbosch** [comment]
Thanks for the link! Interesting to read them.

**Comment by rock3r** [comment]
At first sight many of these practices cannot be enforced with the IDE formatter, which means:
1) I'll be lobbying the Kotlin tooling team (I'm at KotlinConf right now)
2) Detekt is even more valuable on the topic :)

**Comment by Mauin** [comment]
Agree on supplying a `default-android-config.yml` that matches the style
guide you linked. I'm happy to start something along those lines tomorrow.

**Comment by rock3r** [comment]
I'm happy to help as much as I can. If we manage to make a list of things we're missing/that need tweaking I can pick some up myself.

**Comment by arturbosch** [comment]
Some rule ideas based on the coding style:
- FileStructure: Licence, FileAnnotations, Package, Imports, TopLevelDecls
- LicenceApplied
- NoTabs
- FileNamingEqualsClassNaming: for single class files
- GroupedAndSortedImports

Rules we already have:
- MaxLineLength, ignore for imports and packages
- 

I will continue this list tomorrow or maybe @rock3r can all our ideas together into the first post.

**Comment by Mauin** [comment]
To start out with this I'd suggest combining this a little with #542. When no specific configuration is supplied and a plugin by the name `com.android.*` is applied in the Gradle configuration we use a second `default-android-config.yml`.

We can then fine-tune the actual config to be in line with the official recommendations.

**Comment by arturbosch** [comment]
A `default-android-config.yml` could also be the preferred copy-paste-config way for android developers. I just think about all the issues and PR's @vanniktech provided :D

**Comment by rock3r** [comment]
Makes a lot of sense!

BTW I'm sorry I've sort of disappeared since opening this but I've been AFK a lot and moving around continents, it's been hard to sit down and find time for contributing. I'm really sorry :(

**Comment by schalkms** [comment]
I think this can be closed now, since the mentioned rules are either part of ktlint or detekt.
Some of them were implemented. Others have separate issues.
If some rule is still missing for you, then please create a separate issue.
