### ISSUE TITLE
UnnecessaryAbstractClass does not see member variables

### ISSUE THREAD

**Issue by melashkov** [arturbosch/detekt#534]
Hello,
I would like to report an issue, 
the UnnecessaryAbstractClass check is to strict, ie:
I am getting warning ```An abstract class without a concrete member can be refactored to an interface.``` 
for the code
```
abstract class SomePresenter<out F: Form>(val form: F) {
    abstract fun submit()
}
``` 
but if I refactor and trick detekt seeing val form it passes evaluation:
```
abstract class SomePresenter<out F: Form>(f: F) {
    val form: F = f
    abstract fun submit()
}
```
Looks like it does not see member variable in the first example, it is both valid in kotlin

The version I am running is RC5-3

**Comment by arturbosch** [comment]
Closed by #535
