### ISSUE TITLE
ExceptionRaisedInUnexpectedLocation in constructer 

### ISSUE THREAD

**Issue by melashkov** [arturbosch/detekt#537]
Hi, I have found another issue, I am rising en exception when class being constructed
example:
```
class FooBar(isValid: Boolean) {

    init {
        if (!isValid) {
            throw IllegalArgumentException()
        }
    }
}
```
The detekt tells me "This method is not expected to throw exceptions. This can cause weird behavior.", is that expected that you should not rise exceptions in init?

**Comment by arturbosch** [comment]
This is a good question. Init is often used to validate state in Kotlin. Should we fix this case/make it optional @Mauin @schalkms ?

**Comment by schalkms** [comment]
I think an exception thrown in an init block is ok. I wouldn’t call it a bug. I’ll take a look at it tomorrow.

**Comment by arturbosch** [comment]
Yeah. how about a new label `false-positive`? So make init optionally detected or just remove this case?

**Comment by schalkms** [comment]
Sounds good to me!
