### ISSUE TITLE
Gradle Plugin: Behavior of profiles

### ISSUE THREAD

**Issue by Mauin** [arturbosch/detekt#540]
Spawned from the discussion in #536

Currently I feel like two things are weird in the way profiles are defined and used in the `detekt` configuration in the gradle plugin.

1. Only the profile `"main"` is run by default.
We let the user enter a free string for the profile name, but in the end the Gradle Plugin will only search for and run the `main` profile. If there is no `main` profile the fallback will be run. Profiles with different names can be run through a `profile: <profilename>` variable in the `detekt` closure or via a command line gradle flag. Both of these seem cumbersome to me. And realizing that the fallback is used might not be obvious to users.

2. Even if multiple profiles are defined only the `main` profile is run. Other profiles can only be run with the above mentioned configuration methods.

I suggest to change this behavior to run _any_ profile that was defined in the `detekt` plugin configuration regardless of the name. If no profile was defined, we still fall back to the default fallback values.
This means multiple profiles can be run at the same time with the `detektCheck` command.
Should the user want to run a single profile the configuration options to add `profile: <profilename>` to the plugin configuration would still work. As would the command line parameter.

Additionally we could generate new tasks for each profile:
`detektCheck` - runs all profiles defined in the configuration (in this example `"sample"` and `"test"`)
`detektCheckSample` - runs the profile with the name `"sample"`
`detektCheckTest` - runs the profile with the name `"test"`

**Comment by 3flex** [comment]
PMD, Checkstyle and FindBugs plugins for Gradle all use sourcesets to auto-generate tasks, for example:
- findbugsMain - Runs FindBugs against the production Java source files.
- findbugsTest - Runs FindBugs against the test Java source files.
- findbugsSourceSet - Runs FindBugs against the given source set’s Java source files

It would be good to see detekt move in that direction as well for consistency with other code quality tools.

So I'd suggest any auto-generation of tasks should be based on configured source sets, not on the detekt profile names. Users could then select a profile using `./gradlew detektCheck -Ddetekt.profile=override`.

The tasks would be:
- detektCheck - Runs all detekt tasks, including detektCheckMain and detektCheckTest, plus any automatically generated for other source sets.
- detektCheckMain - Runs detekt against the production Kotlin source files.
- detektCheckTest - Runs detekt against the test Kotlin source files.
- detektCheckSourceSet - Runs detekt against the given source set’s Kotlin source files.

Running any of the above would use the default detekt config. If additional profiles are setup in build.gradle, the user can specify `-Ddetekt.profile=override` on the command line, or specify the preferred profile in build.gradle.

**Comment by isuPatches** [comment]
I would really appreciate this.  I have been struggling trying to write a custom gradle trask to run all of the profiles I have created for a multi-module project.  Not having to pass in a flag and simply depending on a task would greatly improve my life :)

**Comment by Mauin** [comment]
Closing this as the `profile` API has been removed completely. #1198 tracks the generation of tasks per sourceset.
