### ISSUE TITLE
Using plugin rulesets in Android project

### ISSUE THREAD

**Issue by Nevvea7** [arturbosch/detekt#545]
Hi!

I've setup detekt like this in my Android project's project level build.gradle, with gradle 3.0:
```
detekt {
  version = "1.0.0.RC5-3"
  profile("main") {
    input = "$project.projectDir/app"
    config = "$project.projectDir/app/detekt.yml"
    filters = ".*Test.*;.*Factory.*"
    plugins = "$project.projectDir/app/rulesets.jar"
  }
}
```
But I get this err:
```
Error:(66, 0) Cannot set the value of read-only property 'plugins' for root project 'android' of type org.gradle.api.Project.
```
Is this feature not available in Android projects?

Thank you!

**Comment by arturbosch** [comment]
Wow. Your right. The ProfileExtension does not have the `plugins` parameter which is a shame. This needs to be fixed asap. Thanks for reporting.

**Comment by Nevvea7** [comment]
Thank you!
