### ISSUE TITLE
Gradle Plugin RC5-4 not available on plugins.gradle.org

### ISSUE THREAD

**Issue by Mauin** [arturbosch/detekt#547]
Saw this while updating to the latest release. 

The gradle plugin artifacts were correctly published to jcenter: http://jcenter.bintray.com/io/gitlab/arturbosch/detekt/detekt-gradle-plugin/1.0.0.RC5-4/

However https://plugins.gradle.org/plugin/io.gitlab.arturbosch.detekt still reports `RC5-3` as the latest release and `RC5-4` is not available from the plugin portal. Was this just missed or is this related to #539 ?

**Comment by mkobit** [comment]
What command is executed as part of the release process?

**Comment by arturbosch** [comment]
Ups, my fault. Forgot this task. Done. Should be up :).

I run manually  `gradle bU` to upload the artifacts to Bintray and `gradle pubPlu` to publish the plugin.
