### ISSUE TITLE
TooManyFunctions message can be misleading

### ISSUE THREAD

**Issue by scottkennedy** [arturbosch/detekt#552]
"Classes with many functions tend to do too many things and often come in conjunction with large classes and can quickly become God classes. Consider extracting methods to (new) classes better matching their responsibility."

I have a file that only contains extension functions, so there is actually no "class" involved here.

Maybe the word "Classes" should be replaced with "Files" (though then the concept of a "God class" doesn't apply either), or maybe the check should be adjusted to only look at actual classes.

**Comment by arturbosch** [comment]
I propose to add following properties to the check which replace just the `threshold` property:
```
thresholdInFiles: 10
thresholdInClasses: 10
thresholdInInterfaces: 10
thresholdInObjects: 10
```

**Comment by schalkms** [comment]
I like this idea!

**Comment by arturbosch** [comment]
Fuck forgot `-b` and it failed and I pushed everything to master ...
