### ISSUE TITLE
Spek Rule: duplicated test case message

### ISSUE THREAD

**Issue by schalkms** [arturbosch/detekt#572]
If multiple it test cases in the same given or describe function have the same name only one of them gets executed.

**Comment by vanniktech** [comment]
This will be fixed in spek v2

**Comment by schalkms** [comment]
Okay. Thanks for the hint. Does it print a warning or does it throw a compiler error in v2?

**Comment by vanniktech** [comment]
It just works.

**Comment by schalkms** [comment]
Okay! :)
Do you have a reference link or something?
Then I’ll close this.

**Comment by vanniktech** [comment]
It was mentioned somewhere in @artem-zinnatullin talk at Kotlinconf about spek.

**Comment by artem-zinnatullin** [comment]
Yep, anyways doesn't look right to put framework/library specific checks into generic checker :)

**Comment by arturbosch** [comment]
When ist spek 2.0 ETA? Doesnt it make sense to provide such a check for people using spek 1.x? Until the issue ist fixed and the adoption rate is high enough?

We wont include the check into the standard rule set though.

**Comment by arturbosch** [comment]
Closing this on as its unlikely to create a new rule set for testing frameworks in the near future.

**Comment by schalkms** [comment]
I agree on this.
