### ISSUE TITLE
Output is a folder and not a file anymore

### ISSUE THREAD

**Issue by pocmo** [arturbosch/detekt#577]
According to the gradle docs:
> output = "$project.projectDir/reports/detekt.xml" // If present, prints all findings into that file.

However it seems like this specifies a folder now; in which a plain text and XML report are saved.

**Comment by Mauin** [comment]
Yep, you're right. The `output` parameter in the Gradle Plugin matches the `--output` parameter of the command line tool which defines the output directory where all enabled results will be stored.
