### ISSUE TITLE
InterruptedException as too generic

### ISSUE THREAD

**Issue by koral--** [arturbosch/detekt#586]
In Detekt, catching `InterruptedException` is covered by `TooGenericExceptionCaught` rule:
https://github.com/arturbosch/detekt/blob/02c183bba187a12fd56f6b9c822f83e3dc7b13da/detekt-rules/src/main/kotlin/io/gitlab/arturbosch/detekt/rules/exceptions/TooGenericExceptionCaught.kt#L43

Is it intended? In corresponding sonar-java rule, there is no such exception: https://next.sonarqube.com/sonarqube/coding_rules#rule_key=squid%3AS2142
However, there is another rule "InterruptedException" should not be ignored https://next.sonarqube.com/sonarqube/coding_rules#rule_key=squid%3AS2142

**Comment by schalkms** [comment]
I agree. 
This should be removed.
Thanks for reporting!
