### ISSUE TITLE
Add Support For GSK

### ISSUE THREAD

**Issue by napperley** [arturbosch/detekt#59]
Support is needed for [GSK](https://github.com/gradle/gradle-script-kotlin) (Gradle Script Kotlin) which is used by some Kotlin projects, and there are some which provide support for it (eg [Spek](http://spekframework.org/docs/latest/#_gradle_kotlin_script)). Currently GSK is at version 0.9.1 which means now would be a good opportunity to start supporting GSK before it reaches a stable version.

**Comment by arturbosch** [comment]
I haven't used GSK yet, but am I wrong to assume that GSK provides the same blocks as groovy gradle and configuration is the same?

**Comment by napperley** [comment]
Not the same. However there are big similarities between the Groovy and Kotlin versions (**mostly** the same). See the samples below for the Groovy and Kotlin versions:

**Kotlin Version (GSK)**

```kotlin
val KOTLIN_VER = "1.1.2-2"
val JUNIT_VER = "4.12"

buildscript {
    repositories {
        jcenter()
    }

    dependencies {
        classpath(kotlinModule("gradle-plugin"))
    }
}

apply {
    plugin("kotlin")
    plugin("application")
}

configure<ApplicationPluginConvention> {
    mainClassName = "org.example.codekata.MainKt"
}

repositories {
    jcenter()
}

dependencies {
    compile(kotlinModule("stdlib-jre8", version = KOTLIN_VER))
    testCompile("junit:junit:$JUNIT_VER")
}
```

**Groovy Version (Traditional Gradle)**

```groovy
group 'org.example'
version '0.1-SNAPSHOT'

buildscript {
    ext {
        KOTLIN_VER = '1.1.2-2'
        JUNIT_VER = '4.12'
    }

    repositories {
        mavenCentral()
    }
    dependencies {
        classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:$KOTLIN_VER"
    }
}

apply plugin: 'kotlin'
apply plugin: 'application'

repositories {
    mavenCentral()
}

mainClassName = 'org.example.codekata.MainKt'

dependencies {
    compile "org.jetbrains.kotlin:kotlin-stdlib-jre8:$KOTLIN_VER"
    testCompile "junit:junit:$JUNIT_VER"
}
```

**Comment by arturbosch** [comment]
So you mean basically add documentation on how to use detekt with GSK?

**Comment by napperley** [comment]
GSK documentation would be very helpful. Presumably the **detekt** Gradle plugin works with GSK (after the plugin has been imported)?

**Comment by arturbosch** [comment]
Ok, will be done sone, thx!
