### ISSUE TITLE
Rule: UnsafeCast with whitelist

### ISSUE THREAD

**Issue by almozavr** [arturbosch/detekt#591]
There are cases when we want to whitelist some `myClass.myMethod()` from `UnsafeCast` rule. E.g. android's `context.getSystemService` which returns `Object` but is quite safe to be ignored for  `as SomeSystemService`. I wrote simple rule (based on `UnsafeCast`) to check expression call for method match, but struggle to implement check for class of the callee instance. If some one could give a hint on approach how to find out type of the callee object, I would be very pleasant and would proceed with MR for UnsafeCast.

Current implementation:
```kotlin
/**
 * Whitelist-able unsafe cast check. E.g.
 *
 * FilterableUnsafeCast:
 * 	whitelist: android.content.Context#getSystemService
 */
class FilterableUnsafeCast(config: Config = Config.empty) : Rule(config) {

	companion object {
		val WHITELIST_CONFIG_KEY = "whitelist"
	}

	override val issue: Issue = Issue("FilterableUnsafeCast",
			Severity.Defect,
			"Cast operator throws an exception if the cast is not possible.")


	override fun visitBinaryWithTypeRHSExpression(expression: KtBinaryExpressionWithTypeRHS) {
		val isCast = expression.operationReference.getReferencedNameElementType() === KtTokens.AS_KEYWORD
		if (!isCast || !KtPsiUtil.isUnsafeCast(expression)) return

		val whitelisted = valueOrDefault(WHITELIST_CONFIG_KEY, "")
				.takeIf { it.isNotEmpty() }
				?.let { parseFilterSpec(it) }
				?.let { isWhitelisted(expression.left, it) } ?: false
		if (whitelisted) return

		report(CodeSmell(issue, Entity.from(expression), message = ""))
	}

	private fun isWhitelisted(expression: KtExpression, specs: Collection<WhitelistSpec>): Boolean {
		var instanceClass: String? = null
		var expressionMethod: String? = null
		// check is callee method is a part of whitelisted expression
		if (expression is KtDotQualifiedExpression) {
			expressionMethod = (expression.lastChild as KtCallExpression).calleeExpression?.text
		}
		// TODO check is instance class is a part of whitelisted expression
		//
		val isWhiteListed = if (instanceClass == null || expressionMethod == null) false
		else specs.contains(WhitelistSpec(instanceClass, expressionMethod))
		//
		return isWhiteListed
	}

	private fun parseFilterSpec(filter: String): Collection<WhitelistSpec> {
		return filter.split("""\s+""")
				.takeIf { it.isNotEmpty() && it[0].isNotEmpty() }
				?.map {
					val split = it.split("#")
					if (split.size < 2) throw IllegalArgumentException("Bad format of 'ignore' config: $split")
					WhitelistSpec(split[0], split[1])
				} ?: emptyList()
	}

	private data class WhitelistSpec(val classLiteral: String, val methodLiteral: String)
}
```

**Comment by arturbosch** [comment]
Unfortunately this is not possible as detekt does not resolve the types and symbols ... 
We are working on it and have a prototype but nothing that will be merged in the next days.

Until then you can just live with 1. matching the method name or 2. trying to find the declaration of the callee starting from the current scope. Now you get the type of the class. If you want to match the qualified type, try to search inside the imports.

Hope that helps!

**Comment by almozavr** [comment]
@arturbosch thanks! I would definitely go with the 1st option but would keep an eye on type resolution support 👍

**Comment by 3flex** [comment]
@almozavr it's many months later but we now have type and resolution capability in detekt - an easy way to try it out is with #1597. You could try implementing your enhancement by seeing how the `UselessCallOnNotNull` rule has been implemented.

**Comment by almozavr** [comment]
Thanks, guys! I'm closing the issue
