### ISSUE TITLE
TooManyFunctions description could be improved

### ISSUE THREAD

**Issue by vanniktech** [arturbosch/detekt#592]
`TooManyFunctions - 11/10 - [VehicleRenderer] at car2go/src/main/java/com/foo/barui/renderer/VehicleRenderer.kt:8:1`

It's not really clear which of the many threshold properties I'll need to use here.

**Comment by arturbosch** [comment]
What do you mean with `which of the many threshold properties I'll need to use here`?
If a class has too many functions the signature and position would change. This tells me that the file has too many functions ^^.

**Comment by vanniktech** [comment]
In this case the range is pointing to the class though and not the file.

**Comment by arturbosch** [comment]
Hm can you provide the class to me via email or something if it is closed source and I can check?

**Comment by vanniktech** [comment]
This is the file. I replaced the names with some arbitrary ones. It's still getting reported though:

```kotlin
package com.foo.bar.ui.renderer

import android.support.annotation.RestrictTo
import android.support.annotation.RestrictTo.Scope.LIBRARY
import com.foo.bar.Model
import com.foo.bar.model.Model2

@RestrictTo(LIBRARY) interface VehicleRenderer {
  fun renderA(model: Model): String

  fun renderB(walk: Model2): String

  fun renderC(model: Model): String

  fun renderD(model: Model): String

  fun renderE(model: Model): String

  fun renderF(model: Model): String

  fun renderG(model: Model): String

  fun renderH(model: Model): String

  fun renderI(model: Model): Int

  fun renderJ(model: Model): Int

  fun renderK(seconds: Long): String
}
```

Could it be that it'll report it on the interface scope since that's the first scope in hierachy level (file, class, interface) where the threshold is exceeded?

**Comment by Mauin** [comment]
Looking at the `TooManyFunctions` rule it reports it's issues with detailed descriptions. These currently don't get printed to the CLI output, but are included in the HTML and XML reports. 

See: https://github.com/arturbosch/detekt/blob/master/detekt-rules/src/main/kotlin/io/gitlab/arturbosch/detekt/rules/complexity/TooManyFunctions.kt#L68 which clearly mentions that an interface has too many functions. That in turn makes the `THRESHOLD_IN_INTERFACES` parameter the obvious candidate.
I'm not sure about putting the config param in the issue message as that would be a bit along the lines of: "To fix this codesmell simply turn up the thresholds".

**Comment by vanniktech** [comment]
Oh okay, got it. Then I'll next time look at the xml / html report.

**Comment by Mauin** [comment]
We could think about adding the `message` to the CLI output as well. But that might make the CLI output very noisy.
