### ISSUE TITLE
DetektCli depends on kotlin-compiler-embeddable which pulls in older version of json-org-java

### ISSUE THREAD

**Issue by faizanahemad** [arturbosch/detekt#596]
While using DetektCli with our build tool, we also pull in kotlin-compiler-embeddable, whose fatjar has older versions of classes like `JSONArray` which are incompatible with versions > 2.0 
The class I am speaking of is in org.json package named `JSONArray`. 

Is it possible to get rid of kotlin-compiler-embeddable dependency and rather depend on Kotlin and Kotlin reflect?

**Comment by arturbosch** [comment]
Unfortunately not. Detekt depends in the kotlin compiler for ast traversal. I'm wondering why the embeddable jar causes you problems .... It shadows everything so there are no conflicts with your code ...

Do you use gradle?
