### ISSUE TITLE
HtmlOutputFormatTest tests assume Unix-style line endings

### ISSUE THREAD

**Issue by 3flex** [arturbosch/detekt#602]
An example: `assertThat(result).startsWith("<!DOCTYPE html>\n<html lang=\"en\">")`

`default-html-report-template.html` is checked out on Windows with Windows-style line endings (per my system default), so the test fails.

Recommend adding either a `.gitattributes` file explicitly specifying Unix-style line endings for these templates so they're checked out with Unix-style line endings on Windows, or changing the tests to remove the Unix-style line endings (I think the first option is best).

**Comment by arturbosch** [comment]
Do you might opening a PR for this :) ?

**Comment by 3flex** [comment]
Adding .gitattributes or changing the test?

**Comment by arturbosch** [comment]
.gitattributes please

**Comment by arturbosch** [comment]
Thanks for the fix !
