### ISSUE TITLE
Configuration file with all possible rules and their values

### ISSUE THREAD

**Issue by vanniktech** [arturbosch/detekt#61]
Right now I'm seeing two configuration files in the project. [#1](https://github.com/arturbosch/detekt/blob/b26f9f2fb02ed4b45a0dc9fced6f7cb550004b64/detekt-api/src/test/resources/detekt.yml) & [#2](https://github.com/arturbosch/detekt/blob/b26f9f2fb02ed4b45a0dc9fced6f7cb550004b64/detekt-cli/src/main/resources/default-detekt-config.yml).

I'm not sure now whether there are any more rules or not that I could make use of. Plus whether some rules might have some more attributes that can be configured or not.

Is something like an aggregated configuration file with proper documentation planned?

**Comment by arturbosch** [comment]
I try to keep the src/main/resources/default-detekt-config.yml up to date. This is also the config file which gets copied when you write `java -jar detekt --generate-config`

**Comment by arturbosch** [comment]
When `rule set configuration` and `formatting` sections combined all possible rules and values should be listed. I close this as with the 1.0 site, I will create a subtask on that issue.
