### ISSUE TITLE
Allow checks on Kotlin script files (.kts)

### ISSUE THREAD

**Issue by 3flex** [arturbosch/detekt#612]
Right now, a check for a `.kt` extension is [hard coded](https://github.com/arturbosch/detekt/blob/33b4ee1d249d0845d75099108caea136a125560f/detekt-core/src/main/kotlin/io/gitlab/arturbosch/detekt/core/KtTreeCompiler.kt#L47) in detekt.

detekt should be able to check Kotlin script files as well (`.kts` extension).

**Comment by vanniktech** [comment]
Is it as easy as `return kotlinEnding == "kt" || kotlinEnding == "kts"`?

**Comment by arturbosch** [comment]
Well yes, unless kotlin scripts need special configuration inside the kotlin compiler
