### ISSUE TITLE
Integrate Kotlin inspections from IntelliJ

### ISSUE THREAD

**Issue by vanniktech** [arturbosch/detekt#62]
Are there any plans to integrate the Kotlin inspections from IntelliJ? There are a few of them which are really helpful. It might be possible to make use of the same code (if it's open source) so that bug fixes in IntelliJ will also propagate to here.

My motivation behind this would be that I can enforce those inspections via this tool in my CI builds and let PRs fail.

**Comment by arturbosch** [comment]
I do not actually know how the intellij inspections work. It looks like they have a specific system with xml configurations. Haven't looked deep into it and do not planning for now. Also haven't found them in kotlin compiler.

I found out yesterday to make use of the intellij formatting, will try to integrate it the next days. If you miss specific rules from intellij you can post them here and I can look if it is easy to integrate them.

**Comment by vanniktech** [comment]
> If you miss specific rules from intellij you can post them here and I can look if it is easy to integrate them.

There are a bunch of useful rules and I don't think copying all of them into this tool is the right choice. It'd be idea if the rules / inspection could be reused.

**Comment by arturbosch** [comment]
True. Lets see what I can do after the idea plugin.

**Comment by arturbosch** [comment]
There is a way to run idea inspections via headless mode. I try to integrate this method in a gradle task which generates output xml files. I won't spend time to properly parse the results into detekt results, but let them as idea gives them. I think they can later be integrated into idea to get locations
