### ISSUE TITLE
Consider adding TooManyFunctions to the test-pattern exclude-rules

### ISSUE THREAD

**Issue by vanniktech** [arturbosch/detekt#622]
To be honest I don't care how many tests I've got for class. You can easily have more than 10 and this won't become too much.

I'd like to have this rule disabled by default for Tests. What are your opinions?

**Comment by schalkms** [comment]
Hmm.. I partially agree. I think the threshold for methods in test classes is in this case to low. However, I don't think **detekt** should completely ignore test classes. Detekt should rather have a separate rule or threshold for it.

**Comment by vanniktech** [comment]
Not completely ignoring test classes, just this rule for test classes.

**Comment by schalkms** [comment]
I only meant this rule, not the complete rule set. ;)

**Comment by Mauin** [comment]
Agree, it should disabled by default in tests.
