### ISSUE TITLE
Update rules/new rules for new Kotlin Coding Conventions

### ISSUE THREAD

**Issue by Mauin** [arturbosch/detekt#652]
JetBrains released new Kotlin Coding Conventions. Let's use this issue to gather rules that should be updated/created to match the conventions similar how #532 tracks the work towards matching the Android guides which are similar to the JetBrains one.

Conventions can be found here: https://kotlinlang.org/docs/reference/coding-conventions.html

Features (please update):
- [x] `MemberNameEqualsClassName` factory functions
- [x] ~Class layout rule~ (refer to https://github.com/shyiko/ktlint/issues/309)

**Comment by Mauin** [comment]
One change to the `MemberNameEqualsClassName` rule: Factory Functions that create an instance of the class can have the same name as the class

https://kotlinlang.org/docs/reference/coding-conventions.html#function-names

**Comment by schalkms** [comment]
I'll change the `MemberNameEqualsClassName` rule.

**Comment by 3flex** [comment]
The class ordering rule may (should?) be implemented in ktlint (https://github.com/shyiko/ktlint/issues/309)

MemberNameEqualsClassName rule has been updated.

Maybe this should be closed and specific rules can be suggested in individual issues as the Kotlin coding conventions develop over time?

**Comment by schalkms** [comment]
> Maybe this should be closed and specific rules can be suggested in individual issues as the Kotlin coding conventions develop over time?

Fully agreed.

**Comment by schalkms** [comment]
> The class ordering rule may (should?) be implemented in ktlint

This makes sense since this only a formatting issue.
I updated the initial post with a reference to the ktlint issue.
I'll close this for the mentioned reasons.
