### ISSUE TITLE
Are there any Rules for inspection a `var` could be `val`?

### ISSUE THREAD

**Issue by ChrisZou** [arturbosch/detekt#657]
Intellij/AndroidStudio has a inspection that inspects if a local variable declared with `var` could be changed to declaring with `val`. I think it's very valuable. I wonder if detekt has any rule for that?

**Comment by Mauin** [comment]
As far as I'm aware there is no such rule in detekt currently. It should be possible to implement one, though.

**Comment by marianosimone** [comment]
This should be done, now that `VarCouldBeVal` is merged
