### ISSUE TITLE
Support any common report file format

### ISSUE THREAD

**Issue by tomasbjerre** [arturbosch/detekt#66]
I'd like to support this in [Violations Lib](https://github.com/tomasbjerre/violations-lib). As requested in https://github.com/tomasbjerre/violations-lib/issues/19 .

I think it is a bit unclear how the output should be parsed. And a better solution might be if this tool could create a report in any common format.

For example ESLint can generate reports in the checkstyle format. Perhaps this tool can support generating report files in the checkstyle format?

**Comment by arturbosch** [comment]
Yep, the current one was just "copy the toString() of smells" to persist the information somehow. Should be useful for 1.0.0. Will check out checkstyles format, thx!
