### ISSUE TITLE
failFast and test-pattern are counterintuitive

### ISSUE THREAD

**Issue by MyDogTom** [arturbosch/detekt#662]
`failFast` description says
>Set `failFast: true` in your `detekt.yml` configuration file. As a result, **every rule will be enabled** and `warningThreshold` and `errorThreshold` will be set to 0

That's not true, because some rules are disabled for tests. Due to the fact that `test-pattern:` is also activated.

I was very surprised to find out, that by enabling `failFast` I actually disabled some checks :(

**Comment by vanniktech** [comment]
That's for my understanding - also the one who wanted this behavior - working as intended since the rules that are disabled by default in tests are carefully chosen. Maybe a simple documentation update could fix this.

**Comment by 3flex** [comment]
I would update the documentation to be clear that the rule doesn't override exclusions in `test-pattern` and how to remove those exclusions if the override shouldn't apply. Could also print an info notice to the console when `failFast` is enabled and `test-pattern` rule exclusions exist.

**Comment by arturbosch** [comment]
Yes, they are counterintuitive. 
Updating the documentation to say that the `test-pattern` could also be disabled is the easiest option.
I'm still not sure if `failFast` should enabl all rules and disable the test-pattern ...

**Comment by vanniktech** [comment]
In my opinion it should not disable the default test patterns.

**Comment by lwasylkowski** [comment]
Wouldn't enabling test-pattern, but clearing default excluded rules and rulesets be exactly what @MyDogTom wants, and @vanniktech you can (and in fact I think in case of `failFast` should) disable only those rules for tests that you want? `failFast` seems to serve exactly for cherry-picking disabled rules, and seems natural that this would also be the case for tests

**Comment by vanniktech** [comment]
I'd just update the documentation - elaborate it a bit more - and let everything stay the same.

My idea of `failFast` was:

- that we can benefit from having a minimal set of configuration (only override the things we don't want or want to be different)
- get all the new rules enabled by default
- benefit from the carefully chosen default properties

By clearing the default excluded we won't get there again. Another pain point that I have is that I can't simply add one rule to the excluded test rules - instead I need to copy pasta the default list and then add my rule that I want to disable.

**Comment by MyDogTom** [comment]
Clear documentation would prevent my initial confusion.

**Comment by schalkms** [comment]
The `failfast` option got moved and the documentation has been updated.
