### ISSUE TITLE
Rule: 'rangeTo' or the '..' call can be replaced with 'until'

### ISSUE THREAD

**Issue by egor-n** [arturbosch/detekt#670]
Kotlin's [`until`](https://kotlinlang.org/api/latest/jvm/stdlib/kotlin.ranges/until.html) should be used instead of the `..` operator where applicable.

**Example:** `0..list.size() - 1` should be replaced with `1 until list.size()`

Warning from the IDE:
<img width="564" alt="screen shot 2018-01-08 at 9 06 37 pm" src="https://user-images.githubusercontent.com/378493/34687692-333ed450-f4b8-11e7-9e57-3543a2bc764e.png">

**Comment by schalkms** [comment]
I would include this rule after v1 is done. 

If you want to implement it, the rule **InvalidLoopCondition** might be a good reference.

**Comment by arturbosch** [comment]
Fixed by #676
