### ISSUE TITLE
generator: anchor tags are lower case; TOC links to CamelCase

### ISSUE THREAD

**Issue by 3flex** [arturbosch/detekt#678]
E.g. in detekt-generator/documentation/comments.md the TOC links to detekt-generator/documentation/comments.md#CommentOverPrivateFunction but the anchor tag is #commentoverprivatefunction.

Need to add `.toLowerCase()` to https://github.com/arturbosch/detekt/blob/master/detekt-generator/src/main/kotlin/io/gitlab/arturbosch/detekt/generator/out/Markdown.kt#L42

Super simple fix, I'm just not at a location where I can make the update at the moment :( (or I should say, I can make the update, but can't create a PR with the updated docs)

**Comment by schalkms** [comment]
Good catch! Thanks! Fix is in the queue.
