### ISSUE TITLE
Gradle plugin cannot create report file

### ISSUE THREAD

**Issue by rock3r** [arturbosch/detekt#68]
If you specify the `output` value in the configuration:

```groovy
detekt {
  // ...
  output = true
}
```

Then the build fails because the plugin is not passing the reports path:

```
$ gw clean detekt

[...]

:app:clean
:clean
:app:detekt
If using --output and/or --baseline the --report path must be given!

[...]


:app:detekt FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:detekt'.
> Process 'command '/Library/Java/JavaVirtualMachines/jdk1.8.0_102.jdk/Contents/Home/bin/java'' finished with non-zero exit value 255

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED
```

This is happening on 1.0.0M10.2 and 1.0.0M10.3.

**Comment by rock3r** [comment]
Oh, actually, my bad; looking at the sources of Detekt itself I can see it can be fixed this way as os M10.3:

```groovy
detekt {
  // ...
  output = true
  report = "$project.projectDir/build/reports"
}
```

**Comment by arturbosch** [comment]
Even the build failure says it: `If using --output and/or --baseline the --report path must be given!` ;)

**Comment by rock3r** [comment]
Yeah my problem was "how do I set that" given the docs aren't mentioning it :) I think the Gradle plugin DSL could use some docs, actually
