### ISSUE TITLE
UtilityClassWithPublicConstructor reports classes with delegates

### ISSUE THREAD

**Issue by lwasylkowski** [arturbosch/detekt#682]
`class NotUtilityClass : SomeInterface by SomeImplementation()` will get reported for being a utility class, while in fact it can't be safely converted to `object` declaration, because of the delegate.

I wonder whether the rule should be changed to not report in this case?

**Comment by schalkms** [comment]
Thanks for the feedback! Yes, this should be changed to ignore classes with delegates.
