### ISSUE TITLE
Default configuration file should be sorted alphabetically

### ISSUE THREAD

**Issue by rock3r** [arturbosch/detekt#688]
I have just spent a _long_ time for something that should be extremely simple, that is, bumping Detekt from RC6 to RC6-2 because merging the rules was a very painful [manual merge](https://github.com/squanchy-dev/squanchy-android/pull/425).

This is because many of the rules had changed place in the default ruleset compared to RC6 (when I also did merge in the changes), and all the sections had changed place.

If the sections, and the rules within the sections, were sorted alphabetically it would be much easier to compare ruleset files and merge in any new and changed rule. I cannot use the default set as-is as some settings I have are different from the defaults.

**Comment by arturbosch** [comment]
Makes sense. Alphabetically seems reasonable :)

**Comment by Mauin** [comment]
Before the rules were sorted in whatever order people added them to the documentation and default config. Now with the generated default config the order of the rules is the same as given in the `RuleSetProvider`s (e.g. https://github.com/arturbosch/detekt/blob/master/detekt-rules/src/main/kotlin/io/gitlab/arturbosch/detekt/rules/providers/StyleGuideProvider.kt).

We could of course do a sort before generating the default config. That makes sense but if we decide do do this change we should do it before v1 as everybody will have to again go through the hard merge of the config.yml as @rock3r described above.

**Comment by arturbosch** [comment]
I can't think of any problems or inconveniences when having an alphabetical order, do you?

**Comment by Mauin** [comment]
Alphabetical order makes sense for sure. It's just a hassle for everyone using detekt having to update/merge their entire `config.yml` again with the next detekt release. I can make the change to sort it.

**Comment by rock3r** [comment]
To be honest I don't mind keeping the current order, as long as it's stable, but if sorted it's also easier to find rules as the lists grow :)

**Comment by Mauin** [comment]
Looking into the future it's probably nicer to have them sorted alphabetically. For the next release it's going to be really annoying for everyone who has to merge the `config.yml` again. 🤷‍♀️

**Comment by arturbosch** [comment]
Should we ship todays PR as RC6-3?
