### ISSUE TITLE
Support for Android? Failed to apply plugin [id 'com.android.application']

### ISSUE THREAD

**Issue by jaredsburrows** [arturbosch/detekt#69]
I am trying to applying to my kotlin supported project here: https://github.com/jaredsburrows/android-gif-example.

## Versions:
- `com.android.tools.build:gradle:2.3.2`
- `org.jetbrains.kotlin:kotlin-gradle-plugin:1.1.2-3`
- `gradle.plugin.io.gitlab.arturbosch.detekt:detekt-gradle-plugin:1.0.0.M10.3`

## Error:
```
* What went wrong:
A problem occurred evaluating root project 'android-gif-example'.
> Failed to apply plugin [id 'com.android.application']
   > Could not create plugin of type 'AppPlugin'.
      > com.google.common.collect.Lists.newArrayListWithCapacity(I)Ljava/util/ArrayList;

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED in 16s
```

I am applying the `apply plugin: "io.gitlab.arturbosch.detekt"` plugin after both android and kotlin plugins.

**Comment by jaredsburrows** [comment]
@scottkennedy has a work around for those that want to use it:

Setup custom configurations:
https://github.com/arturbosch/detekt/issues/24#issuecomment-306070140

Setup custom `JavaExec` tasks:
https://github.com/arturbosch/detekt/issues/24#issuecomment-306069600

**Comment by arturbosch** [comment]
Tested, getting the same error. Hmm maybe it's due to usage of different kotlin compiler versions. Need to investigate this later ...

**Comment by arturbosch** [comment]
I have the feeling that because I'm using the kotlin-compiler which also have guava etc classes, there can be conflicts. Will try to migrate to embeddable compiler.

**Comment by arturbosch** [comment]
Will be fixed in M11 today later.

**Comment by jaredsburrows** [comment]
@arturbosch Thank you!

@scottkennedy We should be able to use the plugin directly soon.

**Comment by arturbosch** [comment]
When using the branch use `gradle detektCheck` for inspection. It's an undocumented change for M11 for now ;).

**Comment by arturbosch** [comment]
Pls reopen the issue if something does not work :)

**Comment by YajJackson** [comment]
Confused about why this issue was closed..

**Comment by Mauin** [comment]
@YajJackson Are you seeing issues when using _Detekt_ in an Android project? In theory there should be no issues and we see many Android projects using Detekt and it's Gradle Plugin

**Comment by Mauin** [comment]
@YajJackson No worries. I'm glad it worked out in the end.
