### ISSUE TITLE
Documentation generator truncates some configuration descriptions

### ISSUE THREAD

**Issue by rock3r** [arturbosch/detekt#691]
If the configuration description contains a `-` character, the description will be truncated in the generated documentation markdown. For example, `ClassNaming`:

```kotlin
/**
 * @configuration classPattern - naming pattern (default: '[A-Z$][a-zA-Z0-9$]*')
 * @active since v1.0.0
 * @author Marvin Ramin
 */
```

Results in this documentation being generated:

![image](https://user-images.githubusercontent.com/153802/34917780-8b608492-f942-11e7-9ba1-556382d80d3e.png)

I suppose this is due to how the description is identified based on the `-` using an hardcoded `split`ting index in `RuleVisitor`:

https://github.com/arturbosch/detekt/blob/1a22cb5bf5e4f9cce7e70f1858d4b070d6bffa75/detekt-generator/src/main/kotlin/io/gitlab/arturbosch/detekt/generator/collection/RuleVisitor.kt#L95-L100

**Comment by rock3r** [comment]
I suppose the configuration name is a single word so we could instead tweak it like this:

```kotlin
val configurationOption = it.trim()
val name = configurationOption.substringBefore(' ').trimEnd()
val defaultValue = configurationDefaultValueRegex.find(configurationOption)
		?.groupValues?.get(1)?.trim() ?: ""
val description = configurationOption.substringAfter("-")
		.replace(configurationDefaultValueRegex, "")
		.trim()
Configuration(name, description, defaultValue) 
```

Which seems to fix the issue and is a bit more robust:

![image](https://user-images.githubusercontent.com/153802/34917943-56302294-f944-11e7-8475-58aafd29f82d.png)

Unfortunately I don't have time to do a proper PR today :( But this needs to be properly tested too.

**Comment by rock3r** [comment]
CC @arturbosch @Mauin

**Comment by schalkms** [comment]
Thanks. I have also updated the corresponding test case.
