### ISSUE TITLE
Settings validation

### ISSUE THREAD

**Issue by lwasylkowski** [arturbosch/detekt#698]
What I see happening right now for our team is that Detekt gets updated pretty often, and with this rules change. Currently there's no easy way to see which parts of configuration file are invalid, e.g. rule is removed, parameters were added/removed. Similarly one can't see easily that a rule has been added, but is disabled by default.

I would like to try and add some sort of report about used-but-deleted configuration keys, or unused-but-disabled ones. This would of course be different for fail-fast approach etc, but I just want to see whether it makes sense.

Right now the simple approach would be to wrap parsed `Config` in a class that would remember all accessed keys, and from this data a report could be made. Could you let me know whether the feature is feasible, how to best tackle it, and most importantly - where would I unit test it? I still find it somewhat difficult to follow all the tests and structure, and would appreciate any pointers

**Comment by arturbosch** [comment]
We had similar feedback stated in #688 . The solution was to sort the config file aphabetically. This allows to do a simple diff on the default-config and your project config to see all the changes between two versions. 
Do you think this will also solve your problems?

**Comment by lwasylkowski** [comment]
Technically you don't need alphabetical order to do a diff in code anyway, since you can just parse default and actual config files. So I'd say we can make these two slightly different issues - #688 about manual merging, mine - while original reason was updating - after some thought I think it'd be nice to be able to see a report of rules that are enabled, disabled, and possibly some parameters. 

The reason is that even if it's easy to merge rules, there's still `fail-fast` and the opposite flags, which don't require all rules enabled, and make it difficult to see which rules are actually working. I find myself just making a specific error and checking if detekt finds it.

I won't insist on this though, since with alphabetical order might help somewhat, and I'm not sure it's worth adding features that'd just clutter the codebase

**Comment by schalkms** [comment]
I think some kind of migration tool might be a good addition to detekt.
However, I think this only makes sense for all major versions of detekt.
To improve usability some kind of overview of the activated rules as @lwasylkowski mentioned would be nice. I just don't think this should have the highest priority now.
What do you think?

**Comment by arturbosch** [comment]
Hm, just had the idea that the `debug`-flag can be used for this.
If `debug=true` we print the whole configuration file to the console which is ok and helped me somehow in the past, but having a wrapper config which tracks rule accesses and reports them formatted could be really useful.
Having this under the `debug`-flag would not clutter much the api code. What do you think?

**Comment by schalkms** [comment]
@arturbosch
I like the debug flag proposal. For the latter I would create a new issue if the community finds it useful.

**Comment by schalkms** [comment]
duplicate #516
