### ISSUE TITLE
Rule: KDoc's first sentence should have a proper end

### ISSUE THREAD

**Issue by egor-n** [arturbosch/detekt#699]
Checkstyle's JavadocStyle for reference – http://checkstyle.sourceforge.net/config_javadoc.html#JavadocStyle.

KDoc's first sentence should have a proper end. The "proper end" can be defined with a regular expression. Looks like checkstyle uses `([.?!][ \t\n\r\f<])\|([.?!]$)`.

Would also be nice to check if the first sentence starts with a capital letter.

**Comment by vanniktech** [comment]
Yes. I like this. I also have this implemented with Lint.
