### ISSUE TITLE
[Question] How to reference to a version of the plugin in the main project before it's even published?

### ISSUE THREAD

**Issue by shehabic-work** [arturbosch/detekt#700]
I have a question here:
https://github.com/arturbosch/detekt/blob/master/build.gradle#L10 you are referring to the `$usedDetektGradleVersion`
Does it mean that for version 0.0.1 (assuming that this is the first version), project wasn't compiling so you had/have to always refer to 1 version behind, until you publish the current version?

**Comment by arturbosch** [comment]
You can see in https://github.com/arturbosch/detekt/blob/master/gradle.properties that we use a different properties for the current version and the used version. So when we started we used one version behind to check code. Nowadays everytime I release a new version I create a new branch, do last changes, let the CI check if everything is alright, updated both versions locally, publish to bintray from a local commit and this last commit gets pushed after to master. That way everything is in sync and no CI breaks happen (hopefully). :) Hope that answers your question.

**Comment by shehabic** [comment]
Yes, thanks, a lot, same thoughts, I'm currently writing a quality plugin that behind the scene applies multiple other plugins including detekt then generates a unified report for different plugins (Checkstyle, PMD, FindBugs, CPD ..... etc) to be easily compared per branch / build / whatever one specifies in his CI. and faced this issue of always have to the have the published version different that the used one until the published version is published to a maven repo.

Thanks a lot for the info. I also believe that I should have contributions here in detekt, I'll give it a deeper look specially for the missing reporting area.

Keep up the great work 👍

**Comment by arturbosch** [comment]
Hey, thanks! I'm looking forward to try out your plugin when its out! :)
I have also a tip for you if your using gradle.
When using `latest.release` as version when resolving dependencies within tasks, you will always get ... well the latest version of a dependency.
