### ISSUE TITLE
Tooling: Accessing the profiles defined by the user

### ISSUE THREAD

**Issue by tasomaniac** [arturbosch/detekt#705]
We are working on a plugin named `static-analysis` to be able to integrate different tools together. 
Not released yet but this PR adds detekt support.

As you can see in the discussion below, we thought that using `.systemOrDefaultProfile()` to access to the output reports may not be the best. Especially when the user has multiple profiles. 

We wanted to access `profiles` field but it seems that it is private. `searchProfileWithName` is public but we cannot use that to access all profiles defines. 

https://github.com/novoda/gradle-static-analysis-plugin/pull/46#discussion_r163277423

What do you think about making `profiles` public? Or is there any other recommended way to access all reports generated by detekt?

**Comment by arturbosch** [comment]
Hey, thanks for suporting detekt in your plugin.
Yes, it would be possible to provide a read-only copy of the profiles for your integration.
This is also somehow liked to https://github.com/arturbosch/detekt/issues/540 as we actually want to rewrite the gradle-plugin.

**Comment by tasomaniac** [comment]
If you're OK with it, I can open a PR having a read-only getter.
Rewrite sounds good but this would be a small modifications.

**Comment by arturbosch** [comment]
Yes, go for it :)
