### ISSUE TITLE
Quickfixes API

### ISSUE THREAD

**Issue by vanniktech** [arturbosch/detekt#710]
The more I'm using ktlint and lint the more I like the pragmatic choice of being able to apply the suggested changes directly.

Obviously since detekt aims at different kind of things than the other tools quickfixes might not be possible for every kind of rule.

One that I could think of right now is the [`NewLineAtEndOfFile`](https://github.com/arturbosch/detekt/blob/master/detekt-rules/src/test/resources/cases/NewLineAtEndOfFile.kt) check or the [`EndOfSentenceFormat`] where we could provide some instant quickfixes that make applying those in large code bases easier.

Let me know what you think!

**Comment by schalkms** [comment]
I think it makes sense for some style rules for now.

**Comment by arturbosch** [comment]
I'm against modifying user code. 
Ofc a module on top of the rules module could be cool, but against introducing refactorings.
The jdeodorant maintainer has a poll where he asks if developers trust a tool, spoiler most of them do not (320 votes total though): http://users.encs.concordia.ca/~nikolaos/jdeodorant/index.php?option=com_poll&id=15:trust-jdeodorant

**Comment by schalkms** [comment]
That's an interesting poll. My experience is kind of mixed since tools can make good proposals how to improve code, but it requires human knowledge to apply it.

**Comment by mkobit** [comment]
That's interesting, tools like http://errorprone.info/docs/refaster (from https://github.com/google/error-prone) are some proof that automated refactoring can work.

**Comment by MyDogTom** [comment]
@arturbosch Poll that you mentioned has the following question

>Would you trust a fully automatic tool to improve **the design quality of your system**?

I think there is a big difference between "improve the design of the system" and "fix small mistakes"

**Comment by vanniktech** [comment]
Also it would still be opt in. You see the warnings and can then choose to get them fixed.

**Comment by arturbosch** [comment]
@MyDogTom your right, but small mistakes are often formatting stuff or something like unused imports. KtLint can do this good enough I think.
Some refactorings like `until instead of size - 1` intellij has inspections and quickfixes for that.
I do not see many rules in detekt which are easy to refactor.

**Comment by vanniktech** [comment]
I do agree that most of the rules won't benefit from this.

It might make sense to move the rules to a tool that can fix them. Especially all of the styling related rules should be living in ktlint - in my opinion. Detekt has a different purpose and then we also would not need this issue.

**Comment by vanniktech** [comment]
Given that this has received almost no positive feedback I'll close this and then use other tools for quickfixes.
