### ISSUE TITLE
External dependency 'detekt-cli' not found when using Gradle plugin in submodule

### ISSUE THREAD

**Issue by benjamin-bader** [arturbosch/detekt#713]
Hi, I'm trying to add detect to my Spring Boot Gradle build.  I'm following the readme steps; `./gradlew detektCheck` now fails with the following error:

```
FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':server:core:detektCheck'.
> Could not resolve all files for configuration ':server:core:detektCheck'.
   > Cannot resolve external dependency io.gitlab.arturbosch.detekt:detekt-cli:1.0.0.RC6-2 because no repositories are defined.
     Required by:
         project :server:core

```

the relevant part of my build.gradle file looks more-or-less like this:

```gradle
buildscript {
  repositories {
    mavenCentral()
    jcenter()
    maven { url "https://plugins.gradle.org/m2" }
  }
  dependencies {
    classpath "gradle.plugin.io.gitlab.arturbosch.detekt:detekt-gradle-plugin:1.0.0.RC6-2"
  }
}

subprojects {
  apply plugin: 'io.gitlab.arturbosch.detekt'

  detekt {
    version = "1.0.0.RC6-2"
    profile("main") {
      input = "$projectDir/src/main/kotlin"
      config = "detekt.yml"
      filters = ".*test.*,.*/resources/.*,.*/tmp/.*"
    }
  }
}
```

I notice that `./gradlew detektCheck` fails in this manner only for nested subprojects, e.g. `:server:core`; modules that are only one level deep still succeed.  I can work around this error by adding a separate buildscript section to each subproject's build.gradle file, which seems less-than-ideal.

Any idea what I may be doing wrong?  Thanks.

**Comment by arturbosch** [comment]
Try to not configure detekt for all subprojects but on top level.
Detekt just wants a root directory to operate on.
After the gradle plugin rewrite is down, for every sub project of your a gradle tasks will be created automatically.
Hope that helps :)

**Comment by emartynov** [comment]
Solved for me

**Comment by benjamin-bader** [comment]
I'll try again shortly - thanks, Artur.

**Comment by benjamin-bader** [comment]
Works for me - thank you!

**Comment by AlexCzar** [comment]
This doesn't work, many of the subprojects do not have "src/main/java" directory and build dies with `Directory 'blabla' specified for property 'input' does not exist.` We need to be able to run detek only for subprojects we have kotlin in.

**Comment by arturbosch** [comment]
Have you tried pointing the input parameter to the directory with only kotlin files?

**Comment by AlexCzar** [comment]
This is a large enterprise project, it does not have such a directory, java and kotlin are mixed in `src/main/java` and `src/test/java`.

**Comment by arturbosch** [comment]
It does not matter if there are java files. You just have to point `input` to any directory containing kotlin files. Make sure the directory is not filtered by `filter`.

You can even write down multiple directories for `input`:
`input = path/to/subproject/src/main/java,path/to/other/subproject`
Maybe with this method you can make detekt run on only the needed directories
