### ISSUE TITLE
EnumNaming should also allow digits

### ISSUE THREAD

**Issue by vanniktech** [arturbosch/detekt#716]
This mirrors the Kotlin inspection from IntelliJ and is then also in sync with class names.

**Comment by schalkms** [comment]
`EnumNaming` should allow enum entries with digits.
Could you please provide more details?

**Comment by vanniktech** [comment]
I'm getting it for instance with `WIFI_LEVEL_1`. I think I know what the problem is. I'm using `failFast: true` and hence I'm getting the default parameters. There's a [typo](https://github.com/arturbosch/detekt/blob/c4c7c7213916b0f5422f0c257e72690c031a5788/detekt-rules/src/main/kotlin/io/gitlab/arturbosch/detekt/rules/naming/EnumNaming.kt#L15) in the documentation but in the [code](https://github.com/arturbosch/detekt/blob/c4c7c7213916b0f5422f0c257e72690c031a5788/detekt-rules/src/main/kotlin/io/gitlab/arturbosch/detekt/rules/naming/EnumNaming.kt#L26) it does accept `0-9`.

**Comment by schalkms** [comment]
That's true. This seems like a copy & paste error in the KDoc.
