### ISSUE TITLE
Exclude comments from MaxLineLength

### ISSUE THREAD

**Issue by benjamin-bader** [arturbosch/detekt#718]
This would be a nice feature!

**Comment by vanniktech** [comment]
How are comments different from code? In my opinion they're just as important.

**Comment by benjamin-bader** [comment]
Sometimes comments contain very long URLs - in my case, links to internal documentation - whose point would be lost if broken up.

**Comment by benjamin-bader** [comment]
I agree with you that comments are quite important - that doesn't mean, IMO, that the same rules can or should apply.  Comments, after all, are free texts included solely for the benefit of humans - they have neither the constraints nor the lexical requirements of code itself, and perhaps shouldn't _necessarily_ get the same linter treatment.

**Comment by vanniktech** [comment]
I can understand your point regarding the URL but for any other type of comment I'd stay within the limit.

**Comment by schalkms** [comment]
I think this is a very very rare case.
One possibility would be a config option which ignores comments.

**Comment by Mauin** [comment]
Also the Android Kotlin style guides mention that KDoc has max line length exceptions:
- Lines where obeying the column limit is not possible (for example, a long URL in KDoc)
- package and import statements
- Command lines in a comment that may be cut-and-pasted into a shell

See: https://android.github.io/kotlin-guides/style.html#line-wrapping

So having these as configuration options would make sense should we at some point want to have a default Android compliant configuration.

**Comment by Mauin** [comment]
As we already have configuration options to exclude package and import statements it would be adding an option to detect URLs and command line statements in KDoc that may violate the `MaxLineLength` rule.

**Comment by rvoortman** [comment]
I will take a shot at implementing this.
