### ISSUE TITLE
OptionalReturnKeyword incorrect behavior

### ISSUE THREAD

**Issue by Mygod** [arturbosch/detekt#722]
```
	OptionalReturnKeyword - [process] at ./mobile/src/main/java/be/mygod/vpnhotspot/Utils.kt:47:9
```

https://github.com/Mygod/VPNHotspot/blob/474018422c2a8f38ed8d21881b3bc613e916ec76/mobile/src/main/java/be/mygod/vpnhotspot/Utils.kt#L47

**Comment by schalkms** [comment]
I think detekt needs to take care of the function return type to determine whether the return keyword is optional or not.

**Comment by Mygod** [comment]
I don't think so. The return keyword can be omitted only if it's the last expression of the ={} structure.

**Comment by schalkms** [comment]
@Mygod 
Of course it also needs to do that. What I meant with my previous post is that if the `return` keyword is in an assignment block it needs to be ignored by the rule.

**Comment by Mygod** [comment]
I don't think you need type inference to do that. You just need to decide whether the function has a return type or not, right?

**Comment by schalkms** [comment]
Detekt does not need type inference for this rule. I updated my first post in this issue to prevent misunderstandings.
