### ISSUE TITLE
EmptyDefaultConstructor incorrect behavior

### ISSUE THREAD

**Issue by Mygod** [arturbosch/detekt#723]
https://github.com/shadowsocks/shadowsocks-android/blob/9a43c78e7b60b00a587d6c2c24e748ec94f50961/mobile/src/main/java/com/github/shadowsocks/database/KeyValuePair.kt#L28

In this example, the parentheses can't be omitted because it defines another constructor that takes no argument.

**Comment by arturbosch** [comment]
I did not know this was even possible thanks :D
