### ISSUE TITLE
The "detektCheck" Gradle task is never UP-TO-DATE

### ISSUE THREAD

**Issue by sschuberth** [arturbosch/detekt#725]
I just realized that running the exact same `./gradlew detektCheck` task two times in a row without changing any source code does not show the `detektCheck` task to be `UP-TO-DATE`, as expected, but runs the task again. Is that by design? If so, I'd vote for changing that for performance reasons, and because tasks can be easily forced to rerun with the `--rerun-tasks` [Gradle command line option](https://docs.gradle.org/current/userguide/command_line_interface.html#sec:rerun_tasks).

**Comment by vanniktech** [comment]
The main drawback is that right now it's not incremental which it should be.

**Comment by arturbosch** [comment]
So how to change that? Any gradle experts here :)

**Comment by vanniktech** [comment]
We need to declare an input. Probably the source files. Gradle will then do the rest of the work.

**Comment by mkobit** [comment]
The tasks should have both inputs and outputs.

**Comment by vanniktech** [comment]
Right as output we could use our output.

**Comment by mkobit** [comment]
I can take a pass at the Gradle stuff sometime next week after https://github.com/arturbosch/detekt/pull/719 is completed
