### ISSUE TITLE
Extend EmptyCatchBlock

### ISSUE THREAD

**Issue by Tolriq** [arturbosch/detekt#734]
First thanks for the tool :)

It would be cool if you could extend the EmptyCatchBlock rule to support regexp on the parameter name to allow easy handling of the normal cases where we want that empty catch due to known possible error that should just be ignored as not important and without possible fix.

PMD for java have the 2 following settings
```
    <rule ref="category/java/errorprone.xml/EmptyCatchBlock">
        <properties>
            <property name="allowExceptionNameRegex" value="^ignore$" />
            <property name="allowCommentedBlocks" value="true" />
        </properties>
    </rule>
```

And most IDE understand ignore as an indicator for that use case.

**Comment by schalkms** [comment]
Closed via 7bba502
