### ISSUE TITLE
Getting EqualsAlwaysReturnsTrueOrFalse incorrectly (I think)

### ISSUE THREAD

**Issue by mverleg** [arturbosch/detekt#738]
I've been using this project for a few days and I like it, thanks for making it!

I'm having a problem with [EqualsAlwaysReturnsTrueOrFalse](https://github.com/arturbosch/detekt/blob/master/detekt-rules/src/main/kotlin/io/gitlab/arturbosch/detekt/rules/bugs/EqualsAlwaysReturnsTrueOrFalse.kt).

I have [this equals method](https://github.com/mangolang/compiler/blob/parse_tests/token/src/main/kotlin/org/mangolang/token/mock/FixedTokenStream.kt):

    override fun equals(other: Any?): Boolean {
        if (other !is FixedTokenStream || this::class != other::class) {
            return false
        }
        if (tokens.size != other.tokens.size) {
            return false
        }
        for (k in 0 until tokens.size) {
            if (tokens[k] != other.tokens[k]) {
                return false
            }
        }
        return true
    }

It can definitely return both true and false:

    val p = FixedTokenStream(listOf())
    val q = FixedTokenStream(listOf(IntegerToken(1)))
    println(q.equals(q)) // true
    println(p.equals(q)) // false

But I get

    Ruleset: potential-bugs
    	EqualsAlwaysReturnsTrueOrFalse - [equals] at kotlin/org/mangolang/token/mock/FixedTokenStream.kt:30:5

Am I misunderstanding this check, or is there a bug?

**Comment by schalkms** [comment]
Thanks for your kind words! That looks like a bug.
