### ISSUE TITLE
Test for missing package line

### ISSUE THREAD

**Issue by mverleg** [arturbosch/detekt#744]
Not sure adding a test is necessary or whether this is the best solution but I'll suggest:

Could there be a test that fails if the file does not have a _'package com.example.package'_ statement?

**Comment by schalkms** [comment]
Do you mean the `SpacingBetweenPackageAndImports` rule?

**Comment by arturbosch** [comment]
I think he just means that there is no package declared (-> default package).
This rule should be easy to implement. @mverleg if want, you can give it a try and add it to the style rule set ^^

**Comment by schalkms** [comment]
I think this should be named `WrongPackageDeclaration`. This rule should also check if a package declaration is not matching the file location.

**Comment by mkobit** [comment]
Another related rule (not sure if it exists already) is _"package should be in same directory space"_

**Comment by schalkms** [comment]
@mkobit I think you mean the same as I have already proposed.

**Comment by mkobit** [comment]
:facepalm: yup, you already said that.

**Comment by marianosimone** [comment]
Package vs dir structure check seems to be the same as the one requested in #646
