### ISSUE TITLE
Space before curly brackets

### ISSUE THREAD

**Issue by aleien** [arturbosch/detekt#753]
Is it possible to check for space before curly brackets? Or should I write my own check for that?
For example:
`if (someCondition){ 
    doSomething(); 
}`
should fail
`if (someCondition) { 
    doSomething(); 
}`
should succeed.

**Comment by schalkms** [comment]
I think **ktlint** here on GitHub already does what you are looking for.
Besides that, you can also write your own rule in detekt.
https://github.com/arturbosch/detekt#extensions

**Comment by arturbosch** [comment]
Hey, what @schalkms said is true, so I will close this one.
Feel free to reopen it if you need help implementing the check yourself.
