### ISSUE TITLE
What do you think about making configuration type safe?

### ISSUE THREAD

**Issue by MyDogTom** [arturbosch/detekt#755]
Probably, it's a duplicate of https://github.com/arturbosch/detekt/issues/19, but I wasn't sure and decided to create a separate issue.

In the past, I had an issue with `yml` configuration, when I had a wrong rule name. That name was just ignored and default setting was used. There was no chance for me to notice that during "configuration" phase.

Personally, I would prefer to configure Detekt completely via Gradle. Like that, wrong configuration would lead to failure during configuration phase. 

For example, it could look like that (just a draft version):
```gradle
detekt {
    config {
        autoCorrect false
        failFast true
        style {
            wildcardImport {
                active true
                excludeImports 'java.util.*'
            }
        }
    }
}
```

What do you think?

**Comment by vanniktech** [comment]
I don't quite like it since I prefer to have one file for the configurations that I can easily copy paste between different projects and use tools like `diff` to see the difference between them easily.

Also this is related to #516

**Comment by MyDogTom** [comment]
>I don't quite like it since I prefer to have one file for the configurations that I can easily copy paste between different projects and use tools like diff to see the difference between them easily.

Would it be possible to achieve same benefits (portability, diff) by extracting Gradle configuration into separate `detekt.gradle`? 
In other words, I propose to replace `detekt_configuration.yml` by `detekt_configuration.gradle`.

**Comment by vanniktech** [comment]
That could work yes. Another benefit - when using gradle DSL - would also be that you get auto completion when configuring Detekt, right?

**Comment by MyDogTom** [comment]
Theoretically yes. For me gradle auto completion doesn't work smooth enough (comparing to Java or Kotlin). That why I don't rely on auto completion.

**Comment by schalkms** [comment]
I just want to add that instead of a yml file detekt could also use a internal/fake DSL for its configuration written in Kotlin.
What do you think?

**Comment by MyDogTom** [comment]
Could you elaborate a bit what "configuration written in Kotlin" means? User writes configuration directly in Kotlin? Configuration needs to be compiled?

**Comment by mkobit** [comment]
Doing it in Gradle is difficult because that means that the Gradle configuration needs to be aware of all possible types and methods. One hiccup there is that additional rulesets not defined in `detekt` may be used in addition to the built in ones. AFAIK with Gradle, there isn't a way to contribute to the runtime DSL generation of `kotlin-dsl` and I don't believe there are similar options for the Groovy DSL.

One option for this would be "compilable configuration" (as mentioned above) through the use of Kotlin scripting - https://github.com/Kotlin/KEEP/issues/75

**Comment by schalkms** [comment]
It means that a DSL is used for the rule configuration.

**Comment by arturbosch** [comment]
Having an additional gradle dsl is just more maintainance in my opinion.
When not using the gradle-plugin, users can still use sonar-kotlin which uses the yaml configuration file.
A kotlin dsl would be type safe and also usable by sonar-kotlin etc. 
Still don't know how much trouble it is to dynamicly compile kotlin files. In groovy its super easy.

**Comment by MyDogTom** [comment]
>One hiccup there is that additional rulesets not defined in detekt itself may be used in addition to the built in ones.

Very good point. As I understand, that creates problem for all kinds of "type safe" configurations.

Nevertheless, I was curios enough to create an example how configuration via Gradle might look like.
I took an approach, when configuration is just serialized to "yaml". There is a repo: https://github.com/MyDogTom/detekt-example
* Inside [`configuration` package](https://github.com/MyDogTom/detekt-example/tree/master/buildSrc/src/main/kotlin/com/github/mydogtom/detekt/configuration) all classes that represent current structure. As I understand, they need to be created for verifying yaml structure anyway. Regardless which approach is selected (just verify provided yaml or DSL for Kotlin or DSL for Gradle)
* Inside  [`detekt` package](https://github.com/MyDogTom/detekt-example/tree/master/buildSrc/src/main/kotlin/com/github/mydogtom/detekt) a simple task, that generates yaml. It also contains custom plugin (I wanted to play with that).
* Configuration is inside [`build.gradle`](https://github.com/MyDogTom/detekt-example/blob/master/build.gradle#L15)

Just to summarize why I think that type safe configuration can be beneficial:
* fail fast and earlier. It's just impossible to have wrong configuration and not notice that
* it's easier to introduce deprecations. For example, you can rename rule, but just deprecate current configuration until next major version.
* when [Kotlin is used for Gradle configuration](https://github.com/gradle/kotlin-dsl), it is even better. Autocompletion should be more reliable, it's possible to use `replaceWith`.

Drawbacks:
* Non gradle-plugin users. (can be handled by having DSL just on top of yaml )
* Configuration for custom rules.

Thank you guys, for your input. Basically, I received answer to my question.  I see now, that such decision is not as straightforward, as I thought initially.

**Comment by arturbosch** [comment]
Hey, thanks for your sample project. If we want to create a new dsl later, we must make sure to generate all dsl classes like we do now with the documentation etc ^^
