### ISSUE TITLE
Rule: Unnecessary brackets

### ISSUE THREAD

**Issue by scottkennedy** [arturbosch/detekt#756]
I don't know if this could be applied to more cases than this, but I've started to see a lot of:

`{ (foo) -> foo == bar }`

The brackets around `foo` are unnecessary.

Alternatively, another configurable option could be to always require them.  Mostly I'd just like to enforce consistency in my codebase, one way or the other.

**Comment by vanniktech** [comment]
There's already a check for this afaik.

**Comment by Mauin** [comment]
As @vanniktech mentioned, shouldn't this be covered by the `UnnecessaryParentheses` rule?

https://github.com/arturbosch/detekt/blob/master/detekt-rules/src/main/kotlin/io/gitlab/arturbosch/detekt/rules/style/UnnecessaryParentheses.kt

**Comment by vanniktech** [comment]
It should. Otherwise the check might need an extension.

**Comment by scottkennedy** [comment]
Ah, looks like I was using it wrong.  Thanks!
