### ISSUE TITLE
Use .editorconfig for MaxLineLength rule

### ISSUE THREAD

**Issue by MariusBoepple** [arturbosch/detekt#757]
I think it would be a good feature to read the max. line length from the `.editorconfig` file. I know that it's possible to add it to the `detekt.yml` config, but then the max. line length is defined in two different config files.

For example *ktlint* is using the `.editorconfig` too for the max. line length. I think there are many projects out there which want to use *ktlint*  and *detekt* in their CI.

**Comment by 3flex** [comment]
Sorry this has been open so long with no reply.

As detekt wraps all of ktlint's rules you could disable detekt's max line length rule then turn on ktlint's wrapped rule.

**Comment by schalkms** [comment]
As @3flex mentioned, using the ktlint rule here is the way to go. It doesn't make much sense to reimplement ktlint's rule. We're sorry for the really late answer.
