### ISSUE TITLE
EmptyCatchBlock.allowedExceptionNameRegex doesn't seem to be useful

### ISSUE THREAD

**Issue by Mygod** [arturbosch/detekt#779]
Running: https://github.com/arturbosch/detekt/commit/f59aa94c2571878e654d085db20d0a851c6f0239 (CLI)
Reported on:
https://github.com/Mygod/VPNHotspot/blob/d2e9ff226c4d7ea453c7dcd3bea5da8c76065894/mobile/src/main/java/be/mygod/vpnhotspot/net/IpNeighbourMonitor.kt#L58

Config:
```
  EmptyCatchBlock:
    active: true
    allowedExceptionNameRegex: "^(ignore|expected).*"
```

**Comment by schalkms** [comment]
I think this regex config is not included in **RC6-3**.
I also can't reproduce it with the latest status from the repo.
Either way, I just included this test-case in a new PR.

**Comment by Mygod** [comment]
I will assume it's working then since I can't run the latest commit. Thanks!

**Comment by Mygod** [comment]
I disabled `UnusedPrivateMember` and indeed it's my bad.
