### ISSUE TITLE
@Suppress("MaxLineLength") at file-level doesn't work

### ISSUE THREAD

**Issue by dafi** [arturbosch/detekt#788]
I have some classes containing variables with SQL queries and I want to disable the `MaxLineLength` check for them, I added the annotation at file level but detekt seems to ignore it.

Example class to use to reproduce the issue

```kotlin
@Suppress("MaxLineLength")
class MaxLineLengthSuppress {
    fun test() {
        val query = "select field1,field2,field3,field4,field5 from a_long_table_name where a_very_very_long_column_name=2 and another_column=5"
    }
}
```
detekt version used: commit # f7b1dd9f

**Comment by arturbosch** [comment]
Hey, you're right, it does now work on CLASS level not file level :)
Please try `@file:Suppress("MaxLineLength")`.
It's correct behaviour because the check does not work on KtElement's but on lines. We can't suppress it on class level (annotation over class) :)

**Comment by dafi** [comment]
Oh oh, this is the first time I use `@file:Suppress("...")` syntax but it works!
Now finally I can use `MaxLineLength` selectively

thanks!
