### ISSUE TITLE
Does detekt include copy/paste detector ?

### ISSUE THREAD

**Issue by contrudar** [arturbosch/detekt#789]
if not, is it on roadmap?

**Comment by vanniktech** [comment]
I'd like to delegate that work to PMD since it already has the cpd plugin.

**Comment by contrudar** [comment]
@vanniktech I found an issue which you created [https://github.com/pmd/pmd/issues/551](url), but as I understood they haven't implemented it yet. Maybe you know thier plans about it. If you do, could you point out the link?

**Comment by vanniktech** [comment]
No don't know their plans :/

**Comment by schalkms** [comment]
I don’t know whether detekt should have such a plugin or not. Detekt could technically do copy detection with the help of the AST (and symbol solving).
I am open for contributed PRs if the community wants this feature.

**Comment by vanniktech** [comment]
Then let's do this with PMD. We get cpd for free and the only thing missing there is the AST mapping afaik.

**Comment by schalkms** [comment]
I’m not familiar with this PMD plugin. I suppose they use the ANTLR AST approach for the currently supported languages. They have already implemented the logic behind copy detection. Subsequently, I don’t think that detekt should reimplement this feature.

**Comment by arturbosch** [comment]
I think you can use the pmd plugin just with cpd ^^ 
If we in the future going to support clones than not just type 1 :P, Closing ;)
