### ISSUE TITLE
No files analysed if path contains test

### ISSUE THREAD

**Issue by davyskiba** [arturbosch/detekt#792]
I get `0 kotlin files were analyzed.` in output after running 

> ./gradlew detektCheck

 if directory path contains 'test'. After renaming root project dir to something else i.e. "banana" kotlin files are properly analysed. I'm using 1.0.0.RC6-3 version

**Comment by arturbosch** [comment]
What is your configuration? Do you use `filter = ".*/test/.*"`?

**Comment by davyskiba** [comment]
Thanks, now I understand it! I'm using slightly modified default config version.
Filter test is present:

> detekt {
>     version = versions.detekt
>     profile("main") {
>         input = "$projectDir/src/"
>         output = "$projectDir/build/reports/detekt"
>         config = "$projectDir/detekt-config.yml"
>         filters = ".*test.*,.*/resources/.*,.*/tmp/.*"
>     }
> }

For some reason I've assumed that it will filter files based on relative path only.

**Comment by arturbosch** [comment]
Cool, so its solved :)?

**Comment by davyskiba** [comment]
Definetly :) Thanks for fast replies

**Comment by kenyee** [comment]
This bit me too because I was following the docs on the web site.  Please update the examples so people don't waste time trying to figure this out :-(

**Comment by kenyee** [comment]
also the generateConfig gradle task generates a yml file that causes this warning:
[Deprecation] - 'warningThreshold' and 'failThreshold' properties are deprecated. Please use the new 'maxIssues' config property.

**Comment by arturbosch** [comment]
@kenyee can you point me to the example you tried? All gradle config examples from the website do not use .*/test/.* in the filters hmmm

**Comment by kenyee** [comment]
@arturbosch:
I used 1.0.0.RC6-4
I ran "gradle detektGenerateConfig"
Look in the yaml file it generates and you'll see this:
"test-pattern: # Configure exclusions for test sources
  active: true
  patterns: # Test file regexes
    - '.*/test/.*'
    - '.*Test.kt'
    - '.*Spec.kt'
"

**Comment by kenyee** [comment]
The deprecation warning also is on the detekt.yml file generated by that gradle command.
