### ISSUE TITLE
Introduce a commit template

### ISSUE THREAD

**Issue by arturbosch** [arturbosch/detekt#797]

**Comment by schalkms** [comment]
+1 for me
I think the link in the **Contributing.md** describes a good template.

**Comment by schalkms** [comment]
Should the build also fail if the commit message doesn’t comply to the template?

**Comment by arturbosch** [comment]
a pre commit git hook for this would be cool :)

**Comment by Mauin** [comment]
Pasting my comments fro #815 here:

> Not really sure this is going to give us much benefit. As @vanniktech already mentioned just using "Squash and Merge" instead of simply merging PRs we will get one well-named commit with the title of the PR (which should have good, descriptive names and we can even rename them if necessary). This commit hook will add another tripwire for people trying to quickly contribute to detekt. 
> I think we shouldn't make it harder than necessary. GitHub can take care of squashing, merging and renaming the appropriate commit for us, let's not put that burden onto people trying to contribute.

**Comment by schalkms** [comment]
I think it's useful. It's just one command to copy this file to `.git/hooks`. This can be packed into the build script for instance.
