### ISSUE TITLE
False negatives for EmptyFunctionBlock with overridden functions

### ISSUE THREAD

**Issue by scottkennedy** [arturbosch/detekt#800]
`override fun foo() {}`

This isn't triggering the `EmptyFunctionBlock` check.

I would accept:
`override fun foo() = TODO("Implement this")`
or
`override fun foo() { /* This is unnecessary in unit tests*/ }`
etc.

But an undocumented block is always going to make me think "why did someone forget to implement this?", and I'd expect Detekt to catch it.

I think this worked before a88a55654ab83e77cd271afba8a323383fed7f17, where it seems like it was explicitly disabled.

**Comment by arturbosch** [comment]
We could make that configurable for EmptyFunctionBlock, thanks for the feedback!

**Comment by schalkms** [comment]
Closed via d545962
