### ISSUE TITLE
deprecation message is printed even when warningThreshold and failThreshold are not used

### ISSUE THREAD

**Issue by MyDogTom** [arturbosch/detekt#811]
Version: 1.0.0.RC6-4

In my config I'm using `failFast: true` and do not specify `build` section at all. Nevertheless, I see the following message in console:

>[Deprecation] - 'warningThreshold' and 'failThreshold' properties are deprecated. Please use the new 'maxIssues' config property.

Is that intended?

**Comment by vanniktech** [comment]
That's probably working as intended since the default configuration is used and there the `warningThreshold` and `failThreshold` are defined.

**Comment by MyDogTom** [comment]
Are there any reason to keep deprecated properties in default configuration?
