### ISSUE TITLE
Change behaviour of version handling in gradle plugin

### ISSUE THREAD

**Issue by Tapchicoma** [arturbosch/detekt#813]
Currently happen following (1.0.0.RC6-3 gradle detekt version):
- No `version` is defined in `detekt {}` configuration block
- New detekt plugin version released `1.0.0.RC6-4`
- CI builds start to fail, because detekt downloaded latest release that has  detekt config handling changes

This breaks the reproducibility of builds at any point in history. Please change the `version` field behaviour to following:
- if version is not set - use current gradle plugin version and don't update to latest release
- if version is set - use provided version

**Comment by Mauin** [comment]
Yeah that makes sense to me. I can also add this to the Gradle plug-in
rework I'm currently working on.

**Comment by rock3r** [comment]
https://github.com/arturbosch/detekt/blob/55d8951142663d9df7cc2882923ff92ac4f85d0b/detekt-gradle-plugin/src/main/kotlin/io/gitlab/arturbosch/detekt/DetektPlugin.kt#L93 Looks like this is done, @Mauin can we consider this done?

**Comment by Mauin** [comment]
Yep I agree. However we should remove the hardcoded version and read the one from `gradle.properties` so that we don't have to manually change it every release.

**Comment by Mauin** [comment]
#1118 for the follow-up
