### ISSUE TITLE
1.0.0.RC6-3 new Issues

### ISSUE THREAD

**Issue by sdoward** [arturbosch/detekt#818]
We have been using 1.0.0.RC6-3 since it was published. Yesterday our CI started failing with new issues from detekt. I saw that 1.0.0.RC6-4 was published yesterday. Did something happen that would affect 1.0.0.RC6-3 as well?

**Comment by sdoward** [comment]
This is a duplicate 
https://github.com/arturbosch/detekt/issues/813
https://github.com/arturbosch/detekt/issues/363

**Comment by Mauin** [comment]
Hi Sam, this looks related to #813. Currently the detekt Gradle Plugin will automatically pick the latest version of detekt. We're looking at changing this. 

This should be resolved by either updating the plugin to `RC6-4` or defining a version in the gradle plugin configuration `version = "1.0.0.RC6-3"`
