### ISSUE TITLE
Threshold changed when updating from RC6-3 to RC6-4

### ISSUE THREAD

**Issue by johncazier** [arturbosch/detekt#822]
With RC6-3 you had to exceed a threshold for an issue to show up, but since updating from RC6-3 to RC6-4 it now adds issues that equal the threshold.  Based on my understanding of the word "threshold" you should need to exceed the threshold, so it seems like a bug was introduced with RC6-4.

**Comment by schalkms** [comment]
You are right. This was changed in 0d45abd for RC6-4
#313 contains the discussion about this rework.

**Comment by johncazier** [comment]
Good to know, thanks. I was confused why I had so many more issues show up after updating. I looked at the release notes and didn't see anything there about it, so it might be nice to add to the release notes too.
