### ISSUE TITLE
Build depends on a full download of IntelliJ

### ISSUE THREAD

**Issue by Mauin** [arturbosch/detekt#827]
When building detekt now that the `detekt-intellij-plugin` is merged Gradle will download a full installation of IntelliJ during the build phase.

## Expected Behavior
- We don't depend on a 350+MB download to build the project.

## Current Behavior
Gradle downloads `ideaIC-2017.3.5.zip`

## Steps to Reproduce (for bugs)
`./gradlew assemble`

**Comment by arturbosch** [comment]
Yes, that's right. It's huge, but what to do about it?
gradle and travis caches the dependency. After the first download it is not a big deal, is it?
Well, ofc we could open a new repository for it.

**Comment by schalkms** [comment]
I agree with @Mauin 
I think there are a number of people out there who don't want to use **detekt** with the IntelliJ plugin. Especially those who use detekt on their CI server.
Adding a new repository is a good approach in my opinion.

**Comment by arturbosch** [comment]
#826 removes the plugin. It has now a new home [here](https://github.com/arturbosch/detekt-intellij-plugin)
