### ISSUE TITLE
Halstead metrics

### ISSUE THREAD

**Issue by schalkms** [arturbosch/detekt#837]
This goes a little bit into the direction of #418 
Wikipedia describes it as a software metric.
https://en.m.wikipedia.org/wiki/Halstead_complexity_measures

Should detekt also include this? What do you think?

**Comment by arturbosch** [comment]
Metrics are something I have in mind after 1.0. 
I would love to have a detekt-metrics module later on :)

**Comment by schalkms** [comment]
Merging this with #418
