### ISSUE TITLE
[Console Output] Change all file paths from relative to absolute

### ISSUE THREAD

**Issue by vanniktech** [arturbosch/detekt#838]
With #801 the report file paths are printed as absolute path - having the entire file path printed which makes it clickable from any place from the Terminal.

We should do the same for the findings so that they're always clickable from the terminal regardless in which directory you execute detekt.

**Comment by ov7a** [comment]
Did anyone test clickable links in IntelliJ IDEA?
I'm using Idea 2018.1.3 (latest), gradle 4.6 and detekt RC7.
I'm launching `detektCheck` from intelliJ's gradle menu (not from terminal) and in Build window file paths are not clickable (sorry for blackboxing project-related info)
![image](https://user-images.githubusercontent.com/4946730/39866641-1d26720c-545a-11e8-8b7c-fe4f50dbb4da.png)

**Comment by vanniktech** [comment]
I think the terminal emulator just doesn't support it.

**Comment by ov7a** [comment]
@vanniktech the issue is with Build window, not the terminal emulator. And paths from, for example, exceptions are clickable there.

**Comment by vanniktech** [comment]
Those are different things. Windows is probably just stupid and does not support clickable links. 

Exceptions are handled by the ide.

**Comment by ov7a** [comment]
Okay. Are there plans to support this? Any related issues on jetbrains issue tracker?
