### ISSUE TITLE
Should ObjectPropertyNaming have a constantPattern?

### ISSUE THREAD

**Issue by scottkennedy** [arturbosch/detekt#844]
`TopLevelPropertyNaming` has `propertyPattern` and `constantPattern`, but `ObjectPropertyNaming` only has `propertyPattern`, even though you can put constants in objects.

Should there be a way to specify a different pattern for constants than properties?

**Comment by schalkms** [comment]
Good idea!

**Comment by schalkms** [comment]
Having looked into this issue I can report that `propertyNaming` already handles this. Please take a look at `TopLevelPropertyNamingSpec.kt`. Anyways, in this source file we mixed up test cases for two separate rules.

**Comment by schalkms** [comment]
I reopen this to wait for verification (@arturbosch @Mauin)

**Comment by arturbosch** [comment]
it makes sense to have a constant and a property pattern on this one - just to be more configurable.
I think why I just used one `propertypattern` for this is because intellij also just uses that regex.

**Comment by schalkms** [comment]
Wouldn't we want to have the same naming patterns as IntelliJ?

**Comment by arturbosch** [comment]
Yes, leaving both configuration options on default being as intellij is enough don't you think?

**Comment by schalkms** [comment]
Ok, so that both patterns have the same defaults.

**Comment by schalkms** [comment]
Closed with c058187
