### ISSUE TITLE
Regex Performance Rule

### ISSUE THREAD

**Issue by schalkms** [arturbosch/detekt#852]
It's a common mistake to initialize a Regex inside a loop or a frequently called function. Internally the compiler creates a nondeterministic finite automaton (NFA) which is then translated into a deterministic finite automaton DFA which consumes time. The compiler must recompile the pattern for each iteration or function call.
Creating a static or member variable solves this problem.

Therefore, this rule should lint uses of
```kotlin
Regex("pattern")
Pattern.compile("pattern")
```
in non-static methods excluding constructors and initializers.
Furthermore, the rule has to check if the pattern is really a constant.

**Comment by schalkms** [comment]
There are other performance issues with regular expressions like intensive backtracking as well, but I think detekt should focus on the ones mentioned in my initial description.

**Comment by arturbosch** [comment]
Finding Regexes inside loops should fairly easy to implement. Regex inside a method which is called often is hard, how do you know it is called often? Is 10 times from other methods often?

How about (after symbol resolving) or through control flow graphs we find methods with loops which call this method where the regex is constructed?

**Comment by schalkms** [comment]
I think this is currently very much out of scope for detekt.
Profiling tools are much better at analyzing stuff like this.
Therefore, I'll close this.
