### ISSUE TITLE
Gradle plugin produces empty directory named '--config-resource'

### ISSUE THREAD

**Issue by nealsanche** [arturbosch/detekt#854]
I have the following configuration:

```
plugins {
    id "io.gitlab.arturbosch.detekt" version "1.0.0.RC6-4"
}
detekt {
    version = "$detektVersion"
    profile("main") {
        input = "$projectDir"
        output = "$projectDir/reports"
        outputName = "varo"
        baseline = "$projectDir/reports/baseline.xml"
        config = "$projectDir/detekt.yml"
        filters = ".*test.*,.*/resources/.*,.*/tmp/.*,.*\\.kts"
    }
}
```
This is in my main configuration, since I am working on an Android application.

## Current Behavior

After running the `detektCheck` gradle task, I find the following directory is most often produced in my source directory:

![screenshot 2018-04-13 15 23 43](https://user-images.githubusercontent.com/5369033/38758566-c707230c-3f2e-11e8-93b1-8f4873e10c87.png)

## Your Environment
* Version used: 1.0.0.RC6-4
* Operating System and version: Mac OS X, 10.13.4 (17E199)
* Android Studio 3.1.1 and Gradle 4.6

**Comment by arturbosch** [comment]
Hey, I also noticed the same problem in my IDE. Will take a look. Thanks for reporting!

**Comment by TWiStErRob** [comment]
That indeed fixes this issue, but the root cause is still there: there's something wrong with argument parsing  or command line building.
