### ISSUE TITLE
Detekt task always runs on the same module

### ISSUE THREAD

**Issue by shadowrider** [arturbosch/detekt#860]
I have setup a multi platform Kotlin project with following structure:
```
/Project
  -- /common
      -- build.gradle
      -- detekt.yml
  -- /common-js
      -- build.gradle
      -- detekt.yml
  -- /common-jvm
      -- build.gradle
      -- detekt.yml
  -- /web
      -- build.gradle
      -- detekt.yml
  -- /android
      -- build.gradle
      -- detekt.yml
  -- build.gradle
  -- settings.gradle
```

Project build.gradle:
```
buildscript {
    repositories {
        jcenter()
        maven { url "http://kotlin.bintray.com/kotlinx" }
        maven { url "https://plugins.gradle.org/m2/" }
        maven { url "https://dl.bintray.com/jetbrains/kotlin-native-dependencies" }
        maven { url "https://dl.bintray.com/kotlin/kotlin-eap" }
        google()
    }
    dependencies {
        classpath "gradle.plugin.io.gitlab.arturbosch.detekt:detekt-gradle-plugin:1.0.0.RC6-4"
    }
}

allprojects {
    repositories {
        jcenter()
        maven { url "http://kotlin.bintray.com/kotlinx" }
        google()
    }

    buildscript {
        repositories {
            jcenter()
            maven { url "https://plugins.gradle.org/m2/" }
        }
    }

    apply plugin: "io.gitlab.arturbosch.detekt"

    detekt {
        version = "1.0.0.RC6-4"
        profile("main") {
            input = "$projectDir/src/main/kotlin"
            config = "$projectDir/detekt.yml"
            filters = ".*test.*,.*/resources/.*,.*/tmp/.*"
        }
    }
}
```
Dependency chains:
web --> common-js --> common
android --> common-jvm --> common

## Expected Behavior
Individual tasks are run on the source files that belong to the module. E.g. `:common:detektCheck` should run only on `project/common/src/kotlin` files, and `:web:detektCheck` should run only `project/web/src/kotlin`.

## Current Behavior
Doesn't matter on which module I call `:detektCheck`, detekt performs checks always on `project/web/src/kotlin` files.

Am I missing something or doing it wrong?

## Your Environment
* Version used: 1.0.0.RC6-4
* Operating System and version: MacOS 10.12, Gradle 4.6, OpenJDK 1.8.0_162, Kotlin 1.2.31

**Comment by arturbosch** [comment]
The gradle plugin was written in such a way that you define the `detekt extension` on the top level of the root  gradle file and configure `profile extensions` to support analyzing selected modules.
So for your case you can write:

```gradle
 detekt {
        version = "1.0.0.RC6-4"
        profile("main") {
            input = "$projectDir/src/main/kotlin"
            config = "$projectDir/detekt.yml"
            filters = ".*test.*,.*/resources/.*,.*/tmp/.*"
        }
        profile("web") {
            input = "$projectDir/web/src/main/kotlin"
        }
    } 
```
A profile always overrides the properties of the main profile.

There is also an ongoing effort to support your expected behaviour at #771

**Comment by shadowrider** [comment]
Makes sense, I was looking for a way to run detekt on all modules in the project. Thank you for the update, I'll wait for #771 to be merged.

**Comment by arturbosch** [comment]
I will close this for now then.
