### ISSUE TITLE
Incorrect "Allowed Maximum" message

### ISSUE THREAD

**Issue by scottkennedy** [arturbosch/detekt#861]
Since the thresholds seem to be the level at which it fails, it's showing an incorrect message.

For example:
`File 'Foo.kt' with '25' functions detected. Allowed maximum amount of functions inside files is set to '25'`

If 25 is the maximum, then it shouldn't error at 25.  With `thresholdInFiles: 25`, it allows 24, so maybe the message on this check (and probably others) could be rephrased, to not suggest that 25 is the allowed maximum (since it's not allowed).

## Your Environment
* Version used: RC6-4

**Comment by arturbosch** [comment]
Jap, your right. The threshold definition changed, but this message was not updated. Thanks for reporting!
