### ISSUE TITLE
Spaces around colon

### ISSUE THREAD

**Issue by vganin** [arturbosch/detekt#870]
I think detekt lacks rules about allowed spaces around colon. 

According to [official coding conventions](https://kotlinlang.org/docs/reference/coding-conventions.html#colon):

> Put a space before `:` in the following cases:
> 
> – when it's used to separate a type and a supertype;
> – when delegating to a superclass constructor or a different constructor of the same class;
> after the `object` keyword.
> – Don't put a space before `:` when it separates a declaration and its type.
> 
> Always put a space after `:`.

**Comment by vanniktech** [comment]
Should be implemented in ktlint.

**Comment by schalkms** [comment]
There is also no reason why you couldn't or shouldn't do this in detekt with custom rules.

**Comment by vanniktech** [comment]
I still don't think this should be included by default. There was a statement somewhere that detekt will not focus on styling and hence this should be implemented in ktlint.

Now that I'm looking at it this rule again it's already implemented with autocorrection which is vastly superior to what Detekt can do.

**Comment by schalkms** [comment]
@vanniktech true
I explicitly stated *with custom rules* in detekt if someone doesn't want to use ktlint for whatever reason.

**Comment by arturbosch** [comment]
Soon we will have the ktlint wrapper ready and will have such rules ^_^
