### ISSUE TITLE
UnsafeCallOnNullableType should not be reported for platform types

### ISSUE THREAD

**Issue by christophsturm** [arturbosch/detekt#880]
## Expected Behavior

detekt should not complain about this code:

    val version = UUID.randomUUID()!!

using !! here is a totally valid way to force kotlin to make version a non null type, and it's less verbose than specifying the type explicitly. It's also an autofix that IDEA suggests

## Current Behavior

    val version = UUID.randomUUID()!!

is reported as UnsafeCallOnNullableType

## Your Environment
I use detekt via codacy.

**Comment by vanniktech** [comment]
You can also use `requireNonNull(UUID.randomUUID())`.

**Comment by christophsturm** [comment]
i could also specify the type. but I think it should not be reported because its a valid pattern.

**Comment by arturbosch** [comment]
We surely need type resolution for platform types :/

**Comment by wenhuanli** [comment]
Also UnsafeCallOnNullableType reports in below case,
```
check(contained != null) { "Value has not been initialized" }
return contained!!
```
Where I have already have a check and expect the clarity.
