### ISSUE TITLE
`./gradlew detektBaseline` fails with "Creating a baseline.xml requires the --baseline parameter to specify a path."

### ISSUE THREAD

**Issue by mcomella** [arturbosch/detekt#886]
## Expected Behavior

`./gradlew detektBaseline` will generate a file like `baseline.xml`

## Current Behavior

That command fails with the error, "Creating a baseline.xml requires the --baseline parameter to specify a path."

## Steps to Reproduce (for bugs)

- `git clone https://github.com/mozilla-mobile/firefox-tv`
- `./gradlew detektBaseline`

## Context

I'm trying to generate a baseline file.

Looking [at the source](https://github.com/arturbosch/detekt/blob/f4eb3269390cd4631e5769ce84a5a0749578d7c2/detekt-gradle-plugin/src/main/kotlin/io/gitlab/arturbosch/detekt/DetektCreateBaselineTask.kt#L34), it uses the `--create-baseline` flag so I'm confused why `--baseline` would fail. I don't think I can use the command line to generate a baseline because I don't know how it would know how to build my project with gradle (so I'm using the gradle plugin).

I don't know how to pass command line arguments to tasks in gradle so I haven't been able to try passing in a `--baseline` to gradle while running this command.

The end result is that I'm struggling to create a baseline file for my project.

## Your Environment

* Version used: 1.0.0-RC6-4
* Operating System and version: macOS high sierra
* Link to your project: See STR

**Comment by arturbosch** [comment]
Heyho,
I could reproduce your issue. You need to use the baseline property pointing to a file
{ baseline = $projectDir/baseline.xmk }`. 
The `--create-baseline` parameter has been removed from detekt long ago and that variable is a relict from the past ;).
You can read more about the baseline [here](https://arturbosch.github.io/detekt/baseline.html)

PS: your using detekt-gradle-plugin in version RC5-6
