### ISSUE TITLE
Link to documentation for new 'maxIssues' config property

### ISSUE THREAD

**Issue by mcomella** [arturbosch/detekt#887]
Running `./gradlew detektCheck` with `warningThreshold` and `failThreshold` in the configuration prints:

> [Deprecation] - 'warningThreshold' and 'failThreshold' properties are deprecated. Please use the new 'maxIssues' config property.

It'd be great if there was a link to the documentation to help make upgrading to the new configuration format trivial.

**Comment by mcomella** [comment]
After a little confusion, I inferred my `*Threshold` lines in my config just needed to be swapped with `maxIssues`, but providing a link to e.g. migration notes could prevent this period of confusion.

**Comment by arturbosch** [comment]
Hey, thanks for the feedback.
You can take a look at the release notes site. Here we generate a list with all fixed issues and have a migration guide (https://arturbosch.github.io/detekt/changelog.html).
The `fail on build` site also mentions the configuration of the new property (https://arturbosch.github.io/detekt/failonbuild.html).
