### ISSUE TITLE
Migrate detekt-formatting/build.gradle to Kotlin DSL

### ISSUE THREAD

**Issue by 3flex** [arturbosch/detekt#893]
## Expected Behavior
All Gradle build configurations should use the Gradle Kotlin DSL.

## Current Behavior
`detekt-formatting/build.gradle` does not use the Gradle Kotlin DSL.

## Context
https://github.com/arturbosch/detekt/issues/611

**Comment by 3flex** [comment]
ICYMI @epeee... I tried doing the conversion but got a bit stuck, but you could probably do it with your eyes closed after the conversions you already did :)

**Comment by epeee** [comment]
@3flex yes, I will do so.
