### ISSUE TITLE
Print link to html report in console on check fail

### ISSUE THREAD

**Issue by Tapchicoma** [arturbosch/detekt#894]
## Expected Behavior
It is a small "nice-to-have" improvement - whenever detekt run fails, because of some problem - print a link in the console to generated html report before sending exit(1), so it can be easily opened in any browser by clicking on it. This behaviour is something similar how Android lint does.

## Current Behavior
Build failed with non-zero exit value and I need to scroll up to find in which module and where violation happens.

## Context
Simplify a little my daily programming routine.

**Comment by vanniktech** [comment]
This has already been implemented. #805

**Comment by Tapchicoma** [comment]
Nice! Haven't checked the PRs :disappointed:
