### ISSUE TITLE
Make website/documentation link more prominent

### ISSUE THREAD

**Issue by madorb** [arturbosch/detekt#896]
this is rather a small issue, but one that i found surprisingly frustrating. 

I saw `[Deprecation] - 'warningThreshold' and 'failThreshold' properties are deprecated. Please use the new 'maxIssues' config property.` in my build logs and wanted to updated my config and needed info on the `maxIssues` config property so I attempted to find the `Detekt` documentation. My search engine failed to locate the desired result via `detekt kotlin documentation` and instead directed me here to the github. 

I scanned the readme multiple times, searched it for the term "documentation" and tried about 4 more googles. Finally i took the time to fully read it line by line and saw: `Visit arturbosch.github.io/detekt for installation guides, rule descriptions and configuration options.`

Could this be made much more prominent? 

Perhaps add a header like: "Documentation" or "Project Website" or at least add in some additional keywords to help grep-fu :-)

thanks for all the hard work, really appreciate it! the tool is great!

**Comment by arturbosch** [comment]
Thanks for the feedback! The website now has an own header :)
