### ISSUE TITLE
MatchingDeclarationName with typealias

### ISSUE THREAD

**Issue by ov7a** [arturbosch/detekt#898]
## Expected Behavior
When a file has a typealias with its name, do not report MatchingDeclarationName.

## Current Behavior
MatchingDeclarationName reported

## Steps to Reproduce (for bugs)

Foo.kt:
    
    typealias Foo = FooImpl<Int>
   
    class FooImpl<T: Any>{
        ...
    }

## Your Environment
* Version used: RC7

**Comment by schalkms** [comment]
I can't reproduce it. The name of the source file which contains your typealias and class is not `FooImpl`.

**Comment by ov7a** [comment]
@schalkms I think that this shoud be treated as false positive (or at least configuration option should exist for that). `FooImpl` is implementation details. I can change it, but from the outside it is still `Foo`.

**Comment by schalkms** [comment]
This is discussable. This could be part of a config option, but I'm not sure if detekt should even include it. I think the community should decide this.
