### ISSUE TITLE
Feature request: Infix functions `and`, `or` and `xor` for booleans

### ISSUE THREAD

**Issue by ov7a** [arturbosch/detekt#899]
It would be nice if `detekt` reported usage of `and`, `or` and `xor` infix functions for booleans. I don't know why they are even exist. The problem with these functions is that a junior coder may think they're just a syntactic sugar for `&&` and `||`. However, unlike `and` and `or`, `&&` and `||` are evaluated lazily.

Example:
    
    //works ok, someArray.first() is not evaluated
    if (someArray.empty || someArray.first().isEmpty()){ ... 

    //would fail on empty array because someArray.first() is evaluated
    if (someArray.empty or someArray.first().isEmpty()){ ... 

Note: this situation can also happen in lambdas, e.g. `filter` argument.

**Comment by 3flex** [comment]
I'm not sure about this - `and` is syntactic sugar for `&` and `or` for `|` (all evaluate eagerly), while `&&` and `||` short-circuit.

Junior coders not using `and` and `or` would face the same trouble if they don't know the difference between `|` and `||`, or `&` and `&&`. I don't think that's any reason to flag usages of these Kotlin functions.

If a rule is implemented it should always be disabled by default in my opinion.

**Comment by ov7a** [comment]
This was a real mistake made by my colleagues.
Suppose that junior coders do have some knowledge about programming.

Consider TOIBE Top10 (please, correct me if I'm wrong)
Java: no `and`
C and C++: `and` is `&&`
Python: `and` is logical and lazy
C#: no `and`
VB.NET: `and` is logical but eager
PHP:  `and` is `&&` with lower precedence.
JavaScript: no `and`
SQL: `and` is logical, laziness depends on optimizing plan.
Ruby: `and` is `&&` with lower precedence

and here is Kotlin, where `and` is bitwise and eager.

And IDE kindly suggests `and` when you write some expression. So if you know some other popular language and it is not VB.NET you might expect that `and` is logical and lazy.

**Comment by schalkms** [comment]
>  I don't think that's any reason to flag usages of these Kotlin functions.

I agree with @3flex here. This shouldn't be a part of detekt.
Furthermore, this can be checked by unit tests in an easy manner.

@ov7a if you really need this rule in your project, you will have to implement a custom rule.
Custom rules are documented [here](https://arturbosch.github.io/detekt/extensions.html#custom-rulesets).
