### ISSUE TITLE
Separate line length setting for comments

### ISSUE THREAD

**Issue by Fleshgrinder** [arturbosch/detekt#902]
There should be an option to define the max. line length for comments; like IDEA has it. Studies show that readability of text is best limited to around 75 characters. <sup>[[refs]](https://duckduckgo.com/?q=optimal+line+length+in+reading)</sup> Since most code has an indent of 4 spaces limiting comments to 80 characters makes sense.

**Comment by schalkms** [comment]
I couldn't find that setting in IntelliJ to differ between code and comment line length.
Should detekt really make a difference between code and comments concerning the line length?
I don't think so.
I did a quick research and found the following [here](https://ux.stackexchange.com/questions/48231/is-there-a-definitive-answer-to-the-line-length-readability-question-in-the-cont?utm_medium=organic&utm_source=google_rich_qa&utm_campaign=google_rich_qa)

> While there's no definitive answer, reading code is still reading just like any other text and some 
> guidelines indicate that 50-75 characters per line is a good number for English.

**Comment by Fleshgrinder** [comment]
Well, you're right, IDEA can actually display an infinite amount of guides. I only ask for comments because that seems rather complicated to implement.

![clipboard01](https://user-images.githubusercontent.com/1059453/40219573-4c65652e-5a76-11e8-9755-878f504341bd.png)

**Comment by schalkms** [comment]
Ok, I didn't know that. 
I'm arguing that there shouldn't be a difference between source code and comments regarding line lenght based on the provided link.

**Comment by schalkms** [comment]
I'm closing this, since there is no guideline for this. Detekt mostly complies with the official Kotlin style guide. However, for me this seems like a good example for a [custom rule](https://arturbosch.github.io/detekt/extensions.html), if you want to have such a setting. The `MaxLineLength` rule is a good starting point for this indent.
