### ISSUE TITLE
StringLiteralDuplication - 3/3 - [toString] unclear error

### ISSUE THREAD

**Issue by vanniktech** [arturbosch/detekt#904]
The following kotlin code gets flagged for me:

```kotlin
override fun toString() = """
    |
    |
    |
    |---
    |Android Version: $RELEASE ($SDK_INT)
    |App Version: ${versionCodeProvider.versionName} (${versionCodeProvider.versionCode})
    |Device: $MODEL ($MANUFACTURER/$BRAND)
    |Locale: ${Locale.getDefault()}
    """.trimMargin()
```

I'm unclear though what is causing the StringLiteralDuplication. Any hints?

**Comment by arturbosch** [comment]
Is there any code in the same file which looks like your toString multiline string :O ?

**Comment by vanniktech** [comment]
No. Only a data class with one parameter. My assumption is that $MODEL will call toString() under the hood and that might be reported?

**Comment by schalkms** [comment]
I was able to reproduce it.
I think you have duplicated parts of the returned string from `toString()` in the same `KtFile`.
I give an example. Here `"|Android Version: "` has 3 usages. It seems like it treats the string before the `$` operator as a separate string.

```Kotlin
data class Data(val i: Int) {

	val str1 = "|Android Version: "
	val str2 = "|Android Version: "

	override fun toString() = """
|---
|Android Version: $RELEASE ($SDK_INT)""".trimMargin()

}
```

**Comment by schalkms** [comment]
I have a fix ready in case the decision is made that this is not the desired behavior.

**Comment by vanniktech** [comment]
This is the entire file:

```kt
package com.vanniktech.common.android

import android.os.Build.BRAND
import android.os.Build.MANUFACTURER
import android.os.Build.MODEL
import android.os.Build.VERSION.RELEASE
import android.os.Build.VERSION.SDK_INT
import java.util.Locale

class ContactEmailBodyTemplate(
  private val versionCodeProvider: VersionCodeProvider
) {
  override fun toString() = """
      |
      |
      |
      |---
      |Android Version: $RELEASE ($SDK_INT)
      |App Version: ${versionCodeProvider.versionName} (${versionCodeProvider.versionCode})
      |Device: $MODEL ($MANUFACTURER/$BRAND)
      |Locale: ${Locale.getDefault()}
      """.trimMargin()
}
```

Still can't see what's triggering this.

**Comment by vanniktech** [comment]
Oh might it be the:

```kt
      |
      |
      |
```

If so we should exclude those.

**Comment by schalkms** [comment]
@vanniktech 
No, I don't think so. I think it would be easier to ignore such multiline strings.
I committed a fix locally which treats such a string as one object.

**Comment by vanniktech** [comment]
That would be much better yeah.
