### ISSUE TITLE
RethrowCaughtException Usage

### ISSUE THREAD

**Issue by scottkennedy** [arturbosch/detekt#906]
I noticed a `RethrowCaughtException` warning in my codebase, and while looking at https://github.com/arturbosch/detekt/blob/dfb6fb615a0a10cc7052dcac285773702115e071/detekt-rules/src/main/kotlin/io/gitlab/arturbosch/detekt/rules/exceptions/RethrowCaughtException.kt#L22, I have a question.

Should this be compliant?

```kotlin
try {
    // ...
} catch (e: IOException) {
    logSomething(e)
    throw e
}
```

It's rethrowing the same exception, but specifically because some special handling is needed there.

I could suppress this usage, but another option could be modifying the rule to only catch cases where the catch block is just `throw e`, with no other exception handling code.

What do you think?

**Comment by schalkms** [comment]
This should be compliant. I'll fix this immediately.

**Comment by arturbosch** [comment]
Should this really be compliant?
I mean whats the point of catching the exception in the first place?

Just logging and doing nothing is bad exception handling imo. Smells like an architectural problem?
Maybe someone can enlighten me :) here please

**Comment by schalkms** [comment]
@arturbosch I quickly did some research. Sonar also treats it that way.
reference (under **exceptions**) https://sbforge.org/sonar/rules/show/squid:S1166?modal=true&layout=false

**Comment by scottkennedy** [comment]
In my case, the exception is handled further up the stack in a more generic case, but we need some special logging in this one specific place.

**Comment by schalkms** [comment]
Closed with 6c57986

**Comment by scottkennedy** [comment]
I'm still seeing this issue with RC8

**Comment by schalkms** [comment]
Okay. Do you mind providing the source code which violates this rule?

**Comment by scottkennedy** [comment]
```kotlin
fun foo() {}
fun bar() {}

fun test() {
    try {
        foo()
    } catch (e: IllegalStateException) {
        bar()
        throw e
    }
}
```

**Comment by schalkms** [comment]
This code should be flagged since you are not doing anything with the caught exception beside rethrowing it.

**Comment by scottkennedy** [comment]
Hmm.  I don't really see how this is any different.  I'm taking specific action here because this exception was thrown, and then I'm re-throwing it to be handled (or not) further up the stack.

The specific case I'm seeing right now is when I encounter an SSL error connecting to a server.  I'm tracking a specific SSL error event, and then rethrowing that exception to be handled the same way as any other network error.

**Comment by marianosimone** [comment]
I agree with @scottkennedy: that's a valid use case for a catch. What can probably be changed in the snippet, though is the naming of the exception:

```
fun test() {
    try {
        foo()
    } catch (_: IllegalStateException) {
        bar()
        throw e
    }
}
```

That why, you'd be signaling that you are not going to use it, but still want to catch it. This rule should be able to be OK with such cases

**Comment by schalkms** [comment]
Okay. It seems like there’s a strong request for change here. I’ll reopen it and put a waiting for feedback label on it.

**Comment by schalkms** [comment]
I had time to tackle this.
@marianosimone @scottkennedy please take a look at PR #1324
