### ISSUE TITLE
Style rule: Prefer to over Pair

### ISSUE THREAD

**Issue by jkaan** [arturbosch/detekt#912]
This is a very stylistic choice so I am sceptical that it is a good idea to add this to Detekt but I very much prefer creating pairs using this syntax:

`1 to 2` instead of `Pair(1, 2)`. 

Do you guys feel this could be added as an optional style rule?

**Comment by arturbosch** [comment]
Sure, I think this is the idiomic way to create pairs in kotlin, so a rule makes sense ^^

**Comment by jkaan** [comment]
I'll get started working on this one. This one is probably super easy. :)

**Comment by schalkms** [comment]
Closed with c9e188b
