### ISSUE TITLE
Support more range expressions in ForEachOnRange rule (downTo, step, until etc.)

### ISSUE THREAD

**Issue by Zayankovsky** [arturbosch/detekt#915]
The following code passes **ForEachOnRange** check:
```kotlin
fun loop() {
    (0 until 10).forEach {
        println(it)
    }
}
```

I doubt it is possible to cover the general case of IntRange, but it would be nice if ranges created using **downTo**, **step** and **until** keywords were supported, as they seem pretty common to me

**Comment by schalkms** [comment]
Closed with cb83b36
