### ISSUE TITLE
Build Gradle plugin using a composite build

### ISSUE THREAD

**Issue by 3flex** [arturbosch/detekt#920]
Looking to see if there's any opposition to this idea before spending more time exploring it.

The Detekt Gradle plugin is tightly coupled to the rest of the project. It creates a chicken and egg problem when making changes like the Gradle plugin rework, nicely illustrated by this example from the Gradle blog post that introduced the composite build feature:
> 1. Change the library
> 2. Publish the library to a local repository
> 3. Add the local repository to your application’s repositories
> 4. Change your application’s dependency to the new library version
> 5. Test your application
> 6. Repeat until the problem is fixed or you lose your mind

A possible solution is shifting to a composite Gradle build. The Gradle plugin would still live in this repository, but instead of having to push updates to a repository before consuming them in this project, the Gradle plugin could be built then consumed as part of the build itself. This should allow for much faster iterations and also allow the build to succeed in CI for the Gradle rework, and may surface the classpath issues faced in Gradle 4.7 during development and not after pushing a new version to the plugin portal.

See here for background: https://blog.gradle.org/introducing-composite-builds

**Comment by 3flex** [comment]
Just to add, I think this can be done with minimal changes and so it shouldn't impact the Gradle plugin rework. If anything rebasing after composite builds are introduced will help move that along more quickly.

**Comment by Mauin** [comment]
That would be great. It would make iterating and testing the Gradle Plugin that much easier 👍

**Comment by mkobit** [comment]
Not supported yet in Gradle itself (some workarounds), see and vote for https://github.com/gradle/gradle/issues/2528

**Comment by 3flex** [comment]
Thanks for chiming in @mkobit! I read through the comments on that issue already and it didn't look like a showstopper. Was going to base work on https://github.com/gradle/multi-project-composite-gradle-plugins-builds, have you seen that example? I didn't see anything in there that suggests this wouldn't work as long as we have the the small workarounds in settings.gradle.

I think the unsupported workaround would be an acceptable tradeoff for now given the pain of developing the Gradle plugin.

OK, I'm going to work on this and test it on Mauin's branch to see if it helps before I submit a PR.

**Comment by mkobit** [comment]
Thanks @3flex , I did not see that before. One thing to consider is how the dependencies work. The Gradle plugin wants to depend on some artifacts (I think it might use the CLI right now?). I don't know if the new PR changes that, but it would be ideal to use that from the local build in most test cases.

One idea might be just to have a TestKit test that just runs against the entire `detekt` repository.

**Comment by 3flex** [comment]
I will be t's simpler to remove the CLI dependency, it's not used for much in the Gradle plugin (at runtime it only uses a wrapper for RuntimeException which is easily copied to the plugin project. It's used in the Gradle plugin tests as well but easily replaced).

I've got this working, just going to test on Mauin's branch (don't see why it wouldn't work there though) and tidy up a bit before submitting a PR.
