### ISSUE TITLE
Splitting up rules in the style package

### ISSUE THREAD

**Issue by schalkms** [arturbosch/detekt#921]
The number of rules in the style ruleset is growing and some of them would fit better in a separate ruleset. Hence, I suggest to think about which new ruleset with which rules detekt should have.
This is a topic for detekt > v1.0

**Comment by arturbosch** [comment]
If someone has ideas for new rulesets and rules which would fit, post them here ^^.

**Comment by schalkms** [comment]
As already mentioned
* Security
* Testing

**Comment by schalkms** [comment]
For splitting up the style package I would say
* Design
* Readability
