### ISSUE TITLE
Extended documentation

### ISSUE THREAD

**Issue by rtfpessoa** [arturbosch/detekt#923]
At Codacy we are using this amazing tool to provide Kotlin static analysis.
We currently scrap the rules for the documentation but some users are trying to improve the docs with more details.

How would something like https://github.com/codacy/codacy-detekt/pull/9/files be possible to add here inside detekt for everybody that uses the tool benefit?

Would https://github.com/arturbosch/detekt/blob/dfb6fb615a0a10cc7052dcac285773702115e071/detekt-rules/src/main/kotlin/io/gitlab/arturbosch/detekt/rules/style/ExpressionBodySyntax.kt#L37 be a good enough place?

**Comment by arturbosch** [comment]
Hey, thanks for the motivating words!
There is no way (yet) to change the issue message outside of the source code.
As you can see beside the reported message the rule itself has KDoc with extended documentation similar what your users want to achieve.
We generate our rule documentation for our [website](https://arturbosch.github.io/detekt/complexity.html) based on this KDoc. 
Our `detekt-generator` module produces this markdown documentation.
You could try to parse them or just link to the detekt website when reporting detekt issues ?

**Comment by rtfpessoa** [comment]
@arturbosch is there any easy way we could get the extended docs while we are generating the docs here https://github.com/codacy/codacy-detekt/blob/master/src/main/scala/codacy/detekt/DocGenerator.scala#L70 ?

**Comment by arturbosch** [comment]
Take a look at the runner class of the `detekt-generator` module. 
basically it is all the code you need to parse detekt's rules and get a `List<RuleSetPage>` with all the documentation and stuff.

**Comment by rtfpessoa** [comment]
Thanks I was a bit confused by the names and did not notice there we two `Rule` classes.

Just did a quick hack here: https://github.com/codacy/codacy-detekt/pull/10

**Comment by arturbosch** [comment]
Cool that it worked out!
