### ISSUE TITLE
[bug] UnsafeCast-@Suppress("UNCHECKED_CAST")

### ISSUE THREAD

**Issue by cyw3** [arturbosch/detekt#939]
![image](https://user-images.githubusercontent.com/11549103/40913967-fb2bd498-6828-11e8-98fb-d3c2d63f40ce.png)

From the image, the code `(request.callback as TransferCallback<Any>)` is annotate with **Suppress**, but detekt still think it is a problem.

**Comment by LanderlYoung** [comment]
It seems like detekt can understand CamelCased `@Suppress("UncheckedCast")` but not SNAKE_CASED one. That's a little bit inconvenient, since IntelliJ auto add and kotlin compiler only understance the SNAKE_CASED one.

Hope it be fixed

**Comment by arturbosch** [comment]
Strange `UNCHECKED_CAST` is already supported through aliases.
Can you try out to move the suppress over the function or class or file and see if it gets supressed?

**Comment by LanderlYoung** [comment]
@arturbosch thanks, We'll try the latest version of Detekt and reply test result latter.

**Comment by arturbosch** [comment]
Thanks!

**Comment by LanderlYoung** [comment]
Tried the latest version `RC7-2`, and problem solved. Thanks so much!
