### ISSUE TITLE
Task Inputs and Outputs are not fully Configured in plugin requiring Daemon restart on change

### ISSUE THREAD

**Issue by JLLeitschuh** [arturbosch/detekt#941]
## Expected Behavior
If I change a parameter in the `profiles` block, for example if I add or change the `filter` block I should be able to re-run the task and be running with these new inputs.

```
detekt {
    version = "1.0.0.RC7"

    subprojects
        .forEach {
            profile(it.name, Action {
                input = "${it.projectDir}/src/main/kotlin"
                config = "${rootProject.projectDir}/config/detekt/detekt.yml"
                outputName = "detekt-report"
                output = "${project.buildDir}/reports/detekt"
            })
    }
}
```

## Current Behavior
If you change configuration without killing the the Gradle daemon (with `./gradew --stop`) your code ends up re-running with the same inputs and you will end up with confusing errors.

## Context
This causes issues during the initial configuration phase of this plugin where you are rapidly changing configuration to be very confusing. Changing some code should result in a behavior change which does not occur.

## Your Environment
```
------------------------------------------------------------
Gradle 4.7
------------------------------------------------------------
Build time:   2018-04-18 09:09:12 UTC
Revision:     b9a962bf70638332300e7f810689cb2febbd4a6c
Groovy:       2.4.12
Ant:          Apache Ant(TM) version 1.9.9 compiled on February 2 2017
JVM:          1.8.0_162 (Oracle Corporation 25.162-b12)
OS:           Mac OS X 10.13.4 x86_64
```

**Comment by arturbosch** [comment]
Thanks for reporting, there is an ongoing effort to rework the gradle plugin and hopefully this will be fixed then too!

**Comment by arturbosch** [comment]
This should be fixed for RC9.2 and higher.
