### ISSUE TITLE
Exclude private functions for TooManyFunctions rule

### ISSUE THREAD

**Issue by jkaan** [arturbosch/detekt#943]
Your issue may already be reported!
Please search in the [issues](https://github.com/arturbosch/detekt/issues) before creating one.

## Expected Behavior

A class that has 6 private functions and 6 public ones, it would be nice if this is not flagged by the TooManyFunctions rule.

## Current Behavior

It will flag because there are 12 functions.

## Steps to Reproduce (for bugs)

A file with 12 private functions will be flagged.

## Context

We have one function which is called `handleIntent` and this calls through to other functions to handle the different intents. We have like 8 of those tiny functions but those are all private.

## Your Environment

* Version used: RC5-3
* Operating System and version: macOS
* Link to your project:

**Comment by arturbosch** [comment]
This was already introduced in #933 and shipped with RC7-2.
Please check out if it works for you. If not, please reopen :)
