### ISSUE TITLE
Allow maxLines option for ExpressionBodySyntax

### ISSUE THREAD

**Issue by gpeal** [arturbosch/detekt#957]
@arturbosch I like the `ExpressionBodySyntax` rule. However, some functions are a single expression but the expression itself has nested lambdas and is several lines itself. We have decided to use expression bodies for simple expressions but not complex ones. It would be nice to be able to use this rule without forcing complex expressions to use the expression body syntax.

**Comment by marianosimone** [comment]
Probably related to #950

**Comment by schalkms** [comment]
This should be done with e35d184. If not please reopen this issue.
