### ISSUE TITLE
TopLevelPropertyNaming description reports wrong regex with private properties

### ISSUE THREAD

**Issue by matejdro** [arturbosch/detekt#960]
Steps to reproduce:

1. Create new empty Android project in Android Studio
2. Create new Kotlin file containing this line:
```kotlin
private var PRIVATE_PROPERTY = ""
```
3. Add `RC7-2` Detekt to the project (just copy paste example gradle snippet, without any additional configuration)
4. Run `detektCheck`
5. Open either xml or html report

Error report will contain `TopLevelPropertyNaming` finding with this description:

> Private top level property names should match the pattern: [A-Za-z][_A-Za-z0-9]*

However, according to this description, my `PRIVATE_PROPERTY` variable should be fine. It matches the displayed regex.

It turns out that description of the warning is wrong. It should display `privatePropertyPattern` regex, since this was used to detect that field, but instead it displays `propertyPattern` regex.

**Comment by arturbosch** [comment]
Thanks @matejdro for reporting and @schalkms for fixing!
