### ISSUE TITLE
Support gradle task caching

### ISSUE THREAD

**Issue by Tapchicoma** [arturbosch/detekt#961]
## Expected Behavior
Detekt Gradle task should pick cached task result and use it for the same inputs.

## Current Behavior
On each run `detektCheck` it executes checking the code for the same input.

## Steps to Reproduce (for bugs)
Run several times `./gradlew detektCheck` on any project with enabled Gradle caching support, observe `X actionable tasks: X executed`

## Context
Will speed up local and CI detekt check.

## Your Environment
* Version used: `1.0.0.RC6-3`
* Operating System and version: Gentoo linux
* Link to your project: private project

**Comment by arturbosch** [comment]
This should also be handled by #771.

**Comment by Mauin** [comment]
Closing this as #1079 was merged
