### ISSUE TITLE
1.0.0-RC7-2 is not published to gradlePluginPortal()

### ISSUE THREAD

**Issue by TWiStErRob** [arturbosch/detekt#967]
## Expected Behavior
```gradle
buildscript {
	repositories {
		jcenter()
		gradlePluginPortal()
	}
	dependencies {
		classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:1.2.50"
                // one of these should work
		classpath "gradle.plugin.io.gitlab.arturbosch.detekt:detekt-gradle-plugin:1.0.0.RC7.2"
		classpath "gradle.plugin.io.gitlab.arturbosch.detekt:detekt-gradle-plugin:1.0.0.RC7-2"
	}
}
```

## Current Behavior
```
Could not find gradle.plugin.io.gitlab.arturbosch.detekt:detekt-gradle-plugin:1.0.0.RC7.2.
Searched in the following locations:
    https://jcenter.bintray.com/gradle/plugin/io/gitlab/arturbosch/detekt/detekt-gradle-plugin/1.0.0.RC7.2/detekt-gradle-plugin-1.0.0.RC7.2.pom
    https://jcenter.bintray.com/gradle/plugin/io/gitlab/arturbosch/detekt/detekt-gradle-plugin/1.0.0.RC7.2/detekt-gradle-plugin-1.0.0.RC7.2.jar
    https://plugins.gradle.org/m2/gradle/plugin/io/gitlab/arturbosch/detekt/detekt-gradle-plugin/1.0.0.RC7.2/detekt-gradle-plugin-1.0.0.RC7.2.pom
    https://plugins.gradle.org/m2/gradle/plugin/io/gitlab/arturbosch/detekt/detekt-gradle-plugin/1.0.0.RC7.2/detekt-gradle-plugin-1.0.0.RC7.2.jar
Required by:
    project :
```

## Steps to Reproduce (for bugs)
1. drop above code into a build.gradle
2. run Gradle

## Context
Take a look at https://plugins.gradle.org/m2/gradle/plugin/io/gitlab/arturbosch/detekt/detekt-gradle-plugin/, it doesn't list the new version.

## Your Environment

* Version used: 1.0.0.RC7-2
* Operating System and version: Windows
* Link to your project: private

**Comment by mrsasha** [comment]
I second that, the release `RC7-2` is not in `jcenter` either.

**Comment by TWiStErRob** [comment]
Same for RC7-3, note that https://plugins.gradle.org/plugin/io.gitlab.arturbosch.detekt is showing the newest version, but it's not usable!

**Comment by arturbosch** [comment]
Thanks for reporting. That's strange, seems like problems with the composite build setup.
There were no gradle-plugin changes for RC7-2 and RC7-3 so just using
```
detekt {
   version = "1.0.0.RC7-3"
}
```
should work.

I uploaded the gradle-plugin to bintray (https://bintray.com/arturbosch/code-analysis/detekt/1.0.0.RC7-3#files/io%2Fgitlab%2Farturbosch%2Fdetekt-gradle-plugin%2F1.0.0.RC7-3)
Can you test again if RC7-3 works for you?

**Comment by arturbosch** [comment]
Seems like the gradle-plugin is now under https://plugins.gradle.org/m2/gradle/plugin/io/gitlab/arturbosch/detekt-gradle-plugin/.

**Comment by arturbosch** [comment]
For RC7-4 I should change the group id and everything should work again as it was I think.

**Comment by ipereziriarte** [comment]
Hi, is there any chance to upload it to Maven Central?

We're experiencing issues every day at 10:00 am CEST. The ci is unable to locate the plugin in jcenter at that time.

**Comment by arturbosch** [comment]
That should be fixed for RC8.
@ipereziriarte uh I'm sorry to hear this. Yes Maven Central publishing is on my list ... already tried it once. Will come to it sooner than later.
