### ISSUE TITLE
Detekt RC 7-3 checks the wrong Gradle module

### ISSUE THREAD

**Issue by rock3r** [arturbosch/detekt#980]
## Expected Behavior
When running `:moduleA:detektCheck`, Detekt checks that module

## Current Behavior
When running `:moduleA:detektCheck`, Detekt checks that module, not `:moduleZ` (the last one alphabetically)

## Steps to Reproduce (for bugs)
Have a Gradle project with several modules, and run `:moduleA:detektCheck`. Verify that it only finds issues, and writes reports to, `moduleZ`, the last in alphabetical order

## Context
Self-explainatory I think

## Your Environment
* Version used: RC7-2, RC7-3
* Operating System and version: macOS 10.13.5
* Link to your project: N/A (private project)\

Not sure if it matters, but the project contains a composite build (references another project located in `../other-project`)

**Comment by marschwar** [comment]
The problem is that the `defaultProfile` is a mutable singleton.

**Workaround:**
Do not use the default profile. Either
```
subprojects {
    apply plugin: "io.gitlab.arturbosch.detekt"
}
```
or
```
subprojects {
    apply plugin: "io.gitlab.arturbosch.detekt"
    profile('myprofile') {
        input = file("src/main/kotlin")
        filters = ".*/resources/.*,.*/build/.*"
    }
}
```
What is the reason for using a singleton in the first place?

**Comment by arturbosch** [comment]
@rock3r can you please test out if the branch changes work for you?

**Comment by rock3r** [comment]
What branch @arturbosch?

**Comment by arturbosch** [comment]
The branch with the stupid name [testy](https://github.com/arturbosch/detekt/compare/testy

**Comment by rock3r** [comment]
Will try tomorrow if I manage to, thanks!
