### ISSUE TITLE
Add idea format setup to README

### ISSUE THREAD

**Issue by andyo729** [arturbosch/detekt#993]
## Expected Behavior
Document `detektIdeaFormat` in README

## Current Behavior
Not sure how to set up `detektIdeaFormat`

**Comment by arturbosch** [comment]
Heyho, please check out [the website](https://arturbosch.github.io/detekt/groovydsl.html#configure-a-local-intellij-instance-for-detekt) and feel free to improve the documentation :).
Hope that helps if not ask more questions here.

Actually I want to keep the README short and let people read the documentation.
